### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-android#1002]
I get this error from Google Play Console's prelaunch report.  It only occurs on Huawei P8 Lite (hwALE-H) - Android 5.0--all other devices function fine.  I don't have a p8 available to me so I can't offer much more insight.

> java.lang.NoClassDefFoundError: aewt
> java.lang.IllegalStateException: Tried to get a plugin before it was configured. Make sure you call Amplify.configure() first.

My code in Application classes onCreate.
```
Amplify.addPlugin(new AWSCognitoAuthPlugin());
Amplify.configure(getApplicationContext());
```

**Comment by jamesonwilliams** [comment]
[This StackOverflow thread](https://stackoverflow.com/a/64839467/695787) suggests this many be a bug with Google Play's Pre-launch Reports. Let us know if you're able to repro this on a real device. Feel free to contribute and follow along with [this Google bug report](https://issuetracker.google.com/issues/160907013#comment25), until then. I do not believe there is any action the AWS team can take at this time.

**Comment by jashparikh** [comment]
This happens to me, on a real device as well. Same issue. 

 java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.

**Comment by richardmcclellan** [comment]
> java.lang.IllegalStateException: Tried to get a plugin before it was configured. Make sure you call Amplify.configure() 

This error occurs when `Amplify.configure()` is not called, or is called, but throws an error.   The most common cause of an error being thrown on `configure()` is missing a `res/raw/amplifyconfiguration.json` file (autogenerated when you run `amplify push`), or it is not formatted correctly.

I would suggest logging any errors thrown by `Amplify.configure()` like this:
```
try {
    Amplify.addPlugin(AWSCognitoAuthPlugin());
    Amplify.configure(getApplicationContext());
    Log.d(TAG, "All set and ready to go!");
} catch (AmplifyException exception) {
    Log.e(TAG, "Configure failed: " + exception.message, exception);
}
```

Given that this is probably not related to the original issue reported (`java.lang.NoClassDefFoundError: aewt`), I would suggest you open a new issue if you are still having trouble after trying the suggestion above.
