### ISSUE TITLE
[Datastore] syncExpression is overriding auth rules

### ISSUE THREAD

**Issue by upachecog** [aws-amplify/amplify-android#1008]
Hello, I implemented syncExpressions a couple of days ago and it seems to work fine, but our QA team noticed that now all information is being shown to all users.

**Description:**

I added this rule:
```
.syncExpression(Location::class.java) {
       Location.DATE.eq(Utils.getCurrentDateString())
}
```
And it seems like now Datastore is fetching all the data in the DB disregarding the **owner** field in the defined auth rules.

```
type Location
@model
@key(name: "byName", fields: ["name", "createdAt"], queryField: "byName")
@auth(rules: [
    { allow: owner, ownerField: "asigned", operations: [read, update] }
    ...
]){
   ...
}
```
 
Even though I think I could work around it using something like the following code, I don't know if it Is the correct behavior.

```
 .syncExpression(Location::class.java) {
       Location.ASIGNED.eq(JWT(AWSMobileClient.getInstance().identityId))
}
```

**Current behavior:**

Datastore syncs all users' data, ignoring auth rules.

**Expected behavior:**

Datastore syncs user-specific data.

**Comment by richardmcclellan** [comment]
Hi @upachecog, what you describe is definitely not expected.  I just setup a similar test app though, and was not able to reproduce what you describe. 

Did you make any other changes that could be causing this behavior?

**Comment by upachecog** [comment]
You're right, it was an issue with my cached data.
