### ISSUE TITLE
DataStore Event "outboxMutationProcessed" is malformed

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-android#1012]
The[ documentation states](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/android#outboxmutationprocessed) that the outboxMutationProcessed DataStore Hub event payload contains the modelName and an element, which in turn contains the model and syncMetadata.

However, the actual payload contains a key for 'model' and a key for 'element'.  The element value contains some model data, but not the model schema - therefore it is not possible to infer the true model name when it is an instance of 'SerializedModel'.

Expected behavior:  as defined [in documentation](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/android#outboxmutationprocessed).

Actual behavior:
<img width="732" alt="Screen Shot 2020-11-30 at 4 04 35 PM" src="https://user-images.githubusercontent.com/10621276/100680129-c7926a00-3325-11eb-97f1-0682d3828bf6.png">

Bug summary: modelName is not present.

**Comment by jamesonwilliams** [comment]
> 7:47 PM
Dustin Noyes hmm - i see the modelName field in the hub payload now... but it is null
> 7:53 PM
Jameson Williams Ugh 🤦‍♂️ damn
