### ISSUE TITLE
Be notified when a new accessToken is generated

### ISSUE THREAD

**Issue by AntoEko** [aws-amplify/amplify-android#1047]
Hi,

Is it possible to be notified when a new "accessToken" is generated from Amplify/Cognito ? 

We are using the "accessToken" for the auth with our backend, but we can't know when a new "accessToken" is generated. So currently we need to implement a process to call everytime the method "fetchAuthSession" to be able to (maybe) get the last "accessToken" available when the backend returns a 401. 

It could be really more convenient to have an event (like token notification) when a new one is available. 

Thank you,

**Comment by richardmcclellan** [comment]
Hi @AntoEko, the accessToken is refreshed automatically, so you shouldn't need to refresh it yourself.  You only need `fetchAuthSession` if you need to access the tokens for use with an API outside of Amplify (See [documentation](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android).)

Can you elaborate on the issue you are trying to solve by refreshing the token?

**Comment by AntoEko** [comment]
I understand, but If I call the `fetchAuthSession` how to be sure I have the "last" accessToken available when I do a call to our backend ? I don't want to call ALWAYS this method before our call, it doesn't seem very "clean". The "accessToken" retrieved the first time through this method may expire few minutes later and I have no idea about that, because I don't receive any event.

So I tried another solution, but it doesn't work : 

We defined the "accessToken" (for testing purpose) to expire every 6 minutes. So everytime I call the backend after 6 minutes, I have a 401 error from the backend, because the "accessToken" sent is expired (the "refreshToken" was set to 1 hour). So when I have an error like this, I'm trying to call the `fetchAuthSession` method. 

The problem is Amplify always returns me (through the fetchAuthSession result) the session is expired and  I need to sign-in again... So I don't understand how to do...

Thank for helping,

**Comment by AntoEko** [comment]
(btw I don't want to refresh manually the token, I just want to receive an event when Amplify has refreshed the "accessToken" actually !)

**Comment by richardmcclellan** [comment]
> I don't want to call ALWAYS this method before our call, it doesn't seem very "clean"

Hi @AntoEko, this is in fact the recommended approach.  You should call `fetchAuthSession` right before each time you want to use it.

**Comment by AntonyARHS** [comment]
Hello,

Any news about this topic? 

When I try to re-use the "fetchAuthSession" when my access token is expired, I still retrieve the "old" token... The access token is not refreshed.
