### ISSUE TITLE
Amplify.Auth.fetchUserAttributes fails if clock sync > 5 minutes

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-android#1069]
Amplify.Auth.fetchUserAttributes fails if the clock is off by more than 5 minutes.  Basically it seems it doesn't take clock skew into account, where other Amplify.Auth calls appear to.  Would love to get this fixed, or have some ability to pass clock skew in, as my app actually keeps track of it.

**Comment by jamesonwilliams** [comment]
Hi Cam, I see that [you asked a similar question on the AWS Forums in December 2019](https://forums.aws.amazon.com/thread.jspa?threadID=314373). What behavior are you observing, when the calls fails? Is there an exception trace that you'd like to share? How did you arrive at a value of 5 minutes?

**Comment by camhart** [comment]
I just assumed its 5 minutes because AWS_IAM auth fails once the aws
signature is 5 minutes off.  I only noticed that it fails if the clock it
out of sync.  Assumed 5 minutes.

**Comment by gpanshu** [comment]
@camhart my apologies for not getting to this sooner. Can you advise if you are still facing this issue using the latest version of the Amplify Android library and I can look into this.

**Comment by gpanshu** [comment]
@camhart if upgrading is an option for you I would invite you to test out our new V2 library and see if you are still experiencing an issue. Thank you.
