### ISSUE TITLE
Amplify API - Authorization Type

### ISSUE THREAD

**Issue by Anikethc** [aws-amplify/amplify-android#1075]
Hello,

I have an Android app with me which I have set up an API for.

1. A **short** description

When I create the API and start the build, some files and folders will get created. Path: `app/src/main/java/package-name` which will store some API information. When I ask someone about it, they say those files are a waste and you can delete it.

When I create the API, I don't get any input for the authorization type. Later, ask someone in the Amplify server and they tell me to change the authorization type in the CLI / Admin UI. 

When I try `amplify update api`, I don't get any authorization type input. When I choose `update path`, I don't get that input.
When I go to the Amplify Admin UI, I go to the `Data` tab and go to the dropdown on Authorization type. When I click on API Keys and then pull the project, there is no change detected. The authorization type gets stuck in Cognito itself and I don't want Cognito.

2. The version of Amplify Android you're using

4.40.1 - Amplify Android Version

3. The **code** you're using to call Amplify Android

I just initialized Amplify with the `AWSAPIPlugin`.

4. Any relevant [logs](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output)

![2020-12-29_LI](https://user-images.githubusercontent.com/50455489/103290975-c5005e80-4a10-11eb-9958-d9cfb1e6a7ef.jpg)

5. Any relevant guides or documentation you're referencing

[AWS Amplify - Android](https://docs.amplify.aws/lib/restapi/existing-resources/q/platform/android)

**Comment by rjuliano** [comment]
Based on the stack trace, it looks like you're using AWSCognitoAuthPlugin. During initialization, are you adding the `AWSCognitoAuthPlugin`? If so, that's probably the reason for the error. If you don't want to use Cognito, you should not add that plugin during initialization.

To use API Key, modify the configuration for the REST API in the amplifyconifguration.json such that authorizationType = API_KEY and be sure to provide the apiKey element as well.
