### ISSUE TITLE
DataStore code has no effect

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-android#1083]
Just something I noticed when debugging #1050 a few weeks ago. Forgot to mention it at the time...

When removing a processed outbox mutation, the following code returns a Completable that isn't subscribed to.
https://github.com/aws-amplify/amplify-android/blob/38999423c4b628a45d52e44d605f736701617344/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PersistentMutationOutbox.java#L160

**Comment by jamesonwilliams** [comment]
Good catch!
