### ISSUE TITLE
Subselection being generated for float fields

### ISSUE THREAD

**Issue by saltonmassally** [aws-amplify/amplify-android#1086]
Appears that the framework's handling for Float fields has been broken by maybe https://github.com/aws-amplify/amplify-cli/commit/fadc14495b21c327069f16f2c8f6bd99397d6059. Now it tries to generate a sub-selection for these. See below

```
amount {\n          BYTES\n          MAX_EXPONENT\n          MAX_VALUE\n          MIN_EXPONENT\n          MIN_NORMAL\n          MIN_VALUE\n          NEGATIVE_INFINITY\n          NaN\n          POSITIVE_INFINITY\n          SIZE\n          TYPE {\n            serialVersionUID\n          }\n          serialVersionUID\n        }\n
```

**Comment by saltonmassally** [comment]
Actually might be my mistake. let me regenerate the java code and report back

**Comment by richardmcclellan** [comment]
Note that if you are generating models with the latest CLI, `Float` fields are now represented as `Double` objects.    Support for `Double` in amplify-android was added in 1.6.7 (https://github.com/aws-amplify/amplify-android/issues/1031), so you'll need that version, or later.

**Comment by saltonmassally** [comment]
Thanks for pointing that out @richardmcclellan ... updating and will report back

**Comment by saltonmassally** [comment]
Updating solves it thanks @richardmcclellan
