### ISSUE TITLE
access control in api gateway with cognito userpool

### ISSUE THREAD

**Issue by sklyang** [aws-amplify/amplify-android#1098]
I use cognito user pool as authorizer in apigateway, i fellowed tutorial and all steps done. but get bad request from server. is there any have some case in mine?
there are problem details.
1. i create a api gateway and lamda function by web console
2. In apigateway, create a cognito uaser autorizer.
3. In apigateway, create a "any" method and combined lambda funtion
4. In apigateway, set "Authorization" as cognito user pool Authorizers. 
5. depoly api gateway 
6. In android app Sign in with Google Hosted UI  and get id token 
7. call apigateway use android amplify sdk Authorization header and token
    
![image](https://user-images.githubusercontent.com/15083023/104093072-85b4f600-52cb-11eb-8319-9f00c761ebf6.png)

8. finally get response message from  server 
    <html>
    <head><title>400 Bad Request</title></head>
    <body>
    <center><h1>400 Bad Request</h1></center>
    </body>
    </html>

![image](https://user-images.githubusercontent.com/15083023/104093090-a8dfa580-52cb-11eb-8634-5ba07351d358.png)

**Comment by raphkim** [comment]
`Authorization` header is added automatically by the API plugin, so you do not need to attach that manually. Would you be able to verify the authorization mode of your API from `amplifyconfiguration.json` (located in `src/main/res/raw`) directory to make sure that you are using OIDC?

**Comment by richardmcclellan** [comment]
Closing due to lack of response.
