### ISSUE TITLE
Subclass AmplifyException for re-configuration error

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-android#1108]
When Amplify configure() is called a subsequent time, we throw an AmplifyException.

iOS provides a tailored exception type, unique to this case.

Android should be updated to throw a unique exception that a customer could catch, e.g.:
```kotlin
try {
    Amplify.configure(...)
} catch (alreadyConfiguredException: AlreadyConfiguredException) {
    // Log it or something....
}
```

Note: we met and decided explicitly *not* to add an `isConfigured()` check as proposed in https://github.com/aws-amplify/amplify-android/pull/1107.

**Comment by royjit** [comment]
iOS error - `ConfigurationError.amplifyAlreadyConfigured` thrown [here](https://github.com/aws-amplify/amplify-ios/blob/f9596f39795d8d59cfc17f4a3b28ea5cde582da1/Amplify/Core/Configuration/AmplifyConfiguration.swift#L95)
