### ISSUE TITLE
API.swift in Android project

### ISSUE THREAD

**Issue by EdwardFinegan** [aws-amplify/amplify-android#1113]
I'm not sure what happen but all the sudden my Android project is generating an API.swift and the models in swift for iOS. Can someone help be figure out what is going on with this? There is both an iOS and Android project pointing to the same backend. At one point it was working and generating the Android models but something got misconfigured and I can't seem to figure out what.

Thanks

**Comment by jamesonwilliams** [comment]
Try running `amplify init .` again. When you see this question:

> Choose the type of app that you're building (Use arrow keys)

Please sure to choose `android`.

**Comment by EdwardFinegan** [comment]
`Amplify init . ` does not display that option. I have copied the text I received from my terminal below. I have seen the option in the past to select Android but not now. However I think I did resolve this. I deleted the amplify folder in the root of my project and did a `amplify pull --appId xxxx --envName dev` At first this failed when it would open Safari. I then changed my default browser to Chrome and the processed worked as expected and allow me to configure the project as Android. It now seems to be doing the correct codegen. I think the project got into the bad state from having safari as my default browser. I believe this all started when Amplify cli tried to load something in Safari and failed. What is the expected behavior when using Safari?  




**Terminal output for amplify init.**
```
[xxx]>amplify init .                                                                                                                                                                                      
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
⠋ Initializing your environment: dev(node:12884) ExperimentalWarning: The fs.promises API is experimental
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything
```

**Comment by richardmcclellan** [comment]
> Note: It is recommended to run this command from the root of your app directory

Based on this, it sounds like you are not running `amplify init` from the root of your app directory.  Try running it from your root directory (the same folder that contains `gradle.properties`, `gradlew`, `settings.gradle`, etc.)

**Comment by EdwardFinegan** [comment]
When this issue was happening it was definitely being executed from the root directory. Here is what I "suspect" happened, and will follow up again if the issue reoccurs. These accounts are from memory....

I'm on and Mac is Safari is my default browser. At one point init was ran and it would open up a deep link into safari. However this would fail for some reason. Safari would load an error page that suggested running `amplify configure` with a string of parameters. This would happen over and over again, and even the configure would not change anything. As soon as I switched my default browser to Chrome and ran `amplify init` again, the deep link would work and things would proceed as expected.

**Comment by jamesonwilliams** [comment]
Hey @EdwardFinegan let us know if you run into this again and we'll re-open/re-investigate with you.
