### ISSUE TITLE
RxAmplify emits Exceptions on disposed (Single)Emitter

### ISSUE THREAD

**Issue by adrian-hidothealth** [aws-amplify/amplify-android#1119]
**Problem:**
If a call to e.g. `signUp()` in case of Auth fails with an Exception but the initial subscription already is disposed (user navigated to different screen  and view model gets cleared e.g.) the app crashes.

```
Fatal Exception: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | UserNotConfirmedException{message=User not confirmed in the system., cause=com.amazonaws.services.cognitoidentityprovider.model.UserNotConfirmedException: User is not confirmed. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotConfirmedException; Request ID: e3a710ce-f1ee-4495-9b21-6f5a17aa0274), recoverySuggestion=Please confirm user first and then retry operation}
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:82)
       at com.amplifyframework.rx.-$$Lambda$MfdYe3QTku1Dvo1tWmxZX_q9rr4.accept(:4)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$5.onError(AWSCognitoAuthPlugin.java:372)
       ...
```

**Reason:**
RxBindings emits the Exception even if a cancellation has happened downstream.

**Possible solution:**
Use `subscriber::tryOnError` instead of  `subscriber::onError`.

If I'm not mistaken, this should happen here:
https://github.com/aws-amplify/amplify-android/blob/23aa2b4cc75c1416373b7e4ce45c54d7c53a9060/rxbindings/src/main/java/com/amplifyframework/rx/RxAdapters.java#L121

_I would prefer this over adding library specific code into the global `RxJavaPlugins.setErrorHandler {  }`_

**Comment by upachecog** [comment]
@richardmcclellan I am facing the exact same issue with the **DataStore** and the **API** in version 1.6.9

What I've noticed is that it happens when I have a "slow" or "intermittent" Internet connection.

**Comment by richardmcclellan** [comment]
@upachecog, could you open a new issue?    While your error logs do include the same `UndeliverableException`, it looks like the root cause is different, so I'd like to address it separately.   It would also be helpful if you have any additional info on how to reproduce, as I tried this morning and have been unable to.

**Comment by upachecog** [comment]
> @upachecog, could you open a new issue? While your error logs do include the same `UndeliverableException`, it looks like the root cause is different, so I'd like to address it separately. It would also be helpful if you have any additional info on how to reproduce, as I tried this morning and have been unable to.

@richardmcclellan thanks for your response, I opened: https://github.com/aws-amplify/amplify-android/issues/1132
