### ISSUE TITLE
Signing in with unverified email as login

### ISSUE THREAD

**Issue by baltekgajda** [aws-amplify/amplify-android#1128]
When user tries to sign in to an unverified account using username `UserNotConfirmedException` is raised.
When user tries to sign in to an unverified account using email address (which is set to be an alias in the user pool), `NotAuthorizedException` is raised.

Is there a way to prioritize `UserNotConfirmedException` over `NotAuthorizedException` when user signs in using an email not username? If user can use aliases, they should be treated the same as the username.

Code to reproduce (the simplest case of sign in scenario, can be taken straigth from the [docs](https://docs.amplify.aws/lib/auth/signin/q/platform/android/#sign-in-a-user)):
```
Amplify.Auth.signIn(
    username,  //username can be an username but also an email
    password, 
    { Log.i("SIGN_IN", "Sign in succeeded") },
    { Log.e("SIGN_IN", "Failed to sign in", it) },
)
```

The problem arises when a user breaks the sign up flow without entering the verification code sent through an email.
Later, he tries to sign in and an exception that the account is not verified should be raised. It works that way if he signs in using his username and password but not when he uses his **email** and password. Because of that error, I am not able to know when to show the  verification screen and send the verification email.

Current Amplify version: 1.6.10

**Comment by baltekgajda** [comment]
@eeatonaws please check out the updated question

**Comment by eeatonaws** [comment]
@baltekgajda thanks for the additional information. Since email is set as an alias in your user pool, users have the option of signing in with a verified email. In your case, the user tries to sign in with an unverified email, which is not a valid way to login, so a `NotAuthorizedException` is thrown. If the user tries to sign in with email, a `NotAuthorizedException` should only occur if the email is unverified, indicating that you can prompt the user to verify their email.

**Comment by baltekgajda** [comment]
@eeatonaws you said that a `NotAuthorizedException` should **only** occur if a user tries to sign in with an unverified email. That is unfortunately not true at the moment. From my previous testing the `NotAuthorizedException` is thrown in several different scenarios. I checked a minute ago and I was able to make the `Amplify.Auth.signIn` throw it when I entered an email and password of an account that doesn't exist at all. 

Therefore, I can't always prompt the user to verify their email because this exception is not unique for this one scenario. `UserNotConfirmedException` would be.

**Comment by eeatonaws** [comment]
Using the code and Amplify version you provided, I'm getting a `UserNotFoundException` when attempting to sign in a user with an unverified email or when trying to sign in with an email and password for an account that doesn't exist. I apologize for any confusion I may have caused by incorrectly stating a `NotAuthorizedException` is thrown.

When using email as an alias for the username, the email alias is only created after the email has been verified. Getting a `UserNotFoundException` when trying to sign in with an unverified email is the intended behavior for Cognito User Pools, as the email alias does not exist at this point.

**Comment by baltekgajda** [comment]
@eeatonaws I checked again, you are right. If this is the intended behaviour, do you have a solution on how to distinguish between the sign in with invalid credentials and the sign in with the unverified email?

There is the `UserNotConfirmedException` so there is  a scenario/behaviour when a user tries to sign in without prior email verification. I see an inconsistency here, because from user's perspective he can sign in using email or username and when he signs in using username there is a special exception but when using email there is not.

And from my perspective I have to somehow tell users that they can sign in using an username or email, BUT they can only can use a verified email. And I don't know which users I should show the verification screen to and resend the verification code because from `UserNotFoundException` I don't know if they did not verify their email or they misspelled the email address.

**Comment by eeatonaws** [comment]
I can understand how it could be a confusing experience for users who signed up but did not verify their account to be told their account doesn't exist when trying to sign in with an unverified email. To determine whether an email is unverified or doesn't exist in the user pool when a user tries to sign in with email, you could keep track of the user information (email) for users who have not verified their email and use a pre authentication lambda trigger on the user pool to check if the email is unverified. The pre authentication lambda trigger would be called when a user tries to sign in. Lambda triggers can be setup by going to user pools in Cognito and then the "Triggers" section under "General settings". More information about the pre authentication lambda trigger can be found [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html).

**Comment by baltekgajda** [comment]
Thank you for the information. This is exactly how I handle this issue currently. Nevertheless, I still think that such a simple use case should not require that amount of effort and it is not an obvious thing to do as I have seen this problem mentioned by developers on many threads. The fact that there is a possibility to choose an email as an alias should make the email sign in use cases behave in the same manner as when using username. Therefore I think that there should be some internal changes or at least some documentation so that people are aware how annoying using aliases can be.

**Comment by eeatonaws** [comment]
Thank you for your feedback. I understand where you're coming from and will bring this up with the team.

**Comment by julien-tamade** [comment]
@baltekgajda I'm experiencing this issue as well. Would you be open to sharing some insights or code from your lambda for how you're handling the check? Are you querying across all of the cognito users for that email or are you keeping a list of unverified emails to speed things up?

**Comment by baltekgajda** [comment]
@julien-tamade let me tell you how I handle it now. Previously I was keeping a list of unverified emails and checking every time a user tries to sign in but I found it annoying that I have to do that every time so I came up with an easier solution which is not perfect but it is kind of working for me. 

Now I do this check "on device". I assume that users are verifying their account on the same device they use for registration so what I do is every time a user registers I save their email and username in shared preferences. And when a user tries to sign in with their email I compare it if this email is in my shared preserences (meaning that this account was not verified yet). And if that is a case, before I send a request to sign in I swap the email with the username. This way I can get the proper exception if the account is not verified. And after verification I remove the particular email and username from the shared preferences.

It is far from perfect because if won't work if a user tries to sign in from a different device but I didn't receive any complaints about it ever since I introduced this change so I think it is kinda working.

Nevertheless, I still think this is a big issue and I don't know why it is not solved internally.

**Comment by imedmar** [comment]
> I can understand how it could be a confusing experience for users who signed up but did not verify their account to be told their account doesn't exist when trying to sign in with an unverified email. To determine whether an email is unverified or doesn't exist in the user pool when a user tries to sign in with email, you could keep track of the user information (email) for users who have not verified their email and use a pre authentication lambda trigger on the user pool to check if the email is unverified. The pre authentication lambda trigger would be called when a user tries to sign in. Lambda triggers can be setup by going to user pools in Cognito and then the "Triggers" section under "General settings". More information about the pre authentication lambda trigger can be found [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html).

I tried the pre-authentication trigger approach, but ran into a problem that I found to be pretty bizarre.
When the user attempts to login with an unverified email, the pre-authentication payload sets the username to a UUID, instead of the clear text email that was entered by the user for login.
The interesting part is that when the user tries to login using the actual username instead of the email, the pre-auth payload contains the username in clear text, i.e. exactly how the user entered. Any idea as to why this happens? Did I misconfigure something?
