### ISSUE TITLE
notContains not available in QueryPredicate

### ISSUE THREAD

**Issue by anandanwar4** [aws-amplify/amplify-android#1142]
The documentation says that there exists a `QueryPredicate` called `notContains`. But `notContains` cannot be resolved as one of the functions of `QueryField`.

**Version Info**:
```gradle
implementation 'com.amplifyframework:core:1.16.11'
implementation 'com.amplifyframework:aws-datastore:1.16.11'
implementation 'androidx.multidex:multidex:2.0.0'
```
**Code** :
```java
Where.matches(SampleTable.SAMPLE_LIST.notContains("sampleId"))
```

**Error** :
> Error: Cannot resolve method 'notContains' in 'QueryField'

**Reference Documentation**:
https://docs.amplify.aws/start/getting-started/integrate/q/integration/android#query-todos

**schema.graphql**:
```graphql
type SampleTable @model @key(fields: ["id"]) {
  id: ID!
  name: String!
  sampleList: [ID!]
}
```

**Comment by raphkim** [comment]
Hi @anandanwar4 ,

Will using `QueryPredicateOperation#not()` method to negate `contains()` operator work for your use-case?
```
Where.matches(not(SampleTable.SAMPLE_LIST.contains("sampleId")))
```

**Comment by anandanwar4** [comment]
Hi @raphkim ,

Yes that should do it. Will use this then. Thanks.

Regards,
Ankit
