### ISSUE TITLE
App cache problem using dynamodb by datastore

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1143]
Hi, I have a problem related to data contained in a DynamoDB table that I am querying with Amplify. I use the `com.amplifyframework:aws-datastore:1.6.11` version, and my code is as follows: 

```java
Amplify.DataStore.query(
    Table.class,
    Where.matches(Table.FIELD1.eq("FIELD1").and(Table.FIELD2.eq("FIELD2"))),
    items -> {
        while (items.hasNext()) {
            Table table = items.next();
        }
    },
    failure -> Log.e("error", "Query failed.", failure)
);
```
So my items contains also deleted data (I have deleted all records with amplify admin UI)

Is it a bug or should I have to reset some caching mechanism?

Thanks

**Comment by jamesonwilliams** [comment]
Hi @marenero1974. Let's ensure that your client is seeing the changes from Admin UI.

Please add this code after your `Amplify.configure(...)` call.
```java
String expectedName =
    DataStoreChannelEventName.SUBSCRIPTION_DATA_PROCESSED.toString();
Amplify.Hub.subscribe(HubChannel.DATASTORE,
    /*filter all*/ event -> expectedName.equals(event.getName()),
    /*only matched*/ event ->  Log.i(TAG, event.toString())
);
```

Repeat the experiment where you delete content through the Admin UI. Do you see logs from your Android device at that same time, in response to the deletions? The Hub subscription above should log them out immediately.

**Comment by marenero1974** [comment]
Yes, now it's logging the only matched records (/*only matched*/ event ->  Log.i(TAG, "Subscription data processed = " + event.toString())), but old records still remains

**Comment by marenero1974** [comment]
My problem is still present, does anyone has any other suggestions?
Thanks

**Comment by jamesonwilliams** [comment]
@marenero1974 Can you verify that you have Conflict Resolution enabled on this AppSync API, and that you are using Auto Merge?

Try running the `query` after you get the Hub event:

```java

private void findMatchingTables() {
    QueryOptions conditions =
        Table.FIELD1.eq("FIELD1").and(Table.FIELD2.eq("FIELD2"));
    Amplify.DataStore.query(Table.class, Where.matches(conditions),
        items -> {
            while (items.hasNext()) {
                Table table = items.next();
            }
        },
        failure -> Log.e("error", "Query failed.", failure)
    );
}

private boolean isIncomingDeletion(HubEvent<?> event) {
        DataStoreChannelEventName eventName =
            DataStoreChannelEventName.SUBSCRIPTION_DATA_PROCESSED;
        if (!eventName.toString().equals(event.getName())) {
            return false;
        }
        ModelWithMetadata<Table> data =
            (ModelWithMetadata<Table>) event.getData();
        return Boolean.TRUE.equals(data.getSyncMetadata().isDeleted());
}

private void listenForSubscriptionEvents() {
    Amplify.Hub.subscribe(HubChannel.DATASTORE,
        event -> isIncomingDeletion(event), event -> findMatchingTables()
    );
}
```

**Comment by marenero1974** [comment]
This is my code:
 
```
private boolean isIncomingDeletion(HubEvent<?> event) {
        Log.i("incoming", "isIncomingDeletion");
        DataStoreChannelEventName eventName =
                DataStoreChannelEventName.SUBSCRIPTION_DATA_PROCESSED;
        if (!eventName.toString().equals(event.getName())) {
            Log.i("incoming", "false");
            return false;
        }
        Log.i("incoming", "true");
        ModelWithMetadata<Table> data =
                (ModelWithMetadata<Table>) event.getData();
        return Boolean.TRUE.equals(data.getSyncMetadata().isDeleted());
}
```

and this is the log:

```
I/incoming: isIncomingDeletion
I/incoming: true
I/matched: HubEvent{name='subscriptionDataProcessed', data=ModelWithMetadata{model=Table {id=d3f2ba82-ea77-40bc-8149-32c41339bdbd, field1=c, field2=x}, syncMetadata=ModelMetadata{id='d3f2ba82-ea77-40bc-8149-32c41339bdbd', _deleted=null, _version=1, _lastChangedAt=Temporal.Timestamp{timestamp=1612396362483}}}, uuid=30e3a539-936f-4b81-9ccc-1d0d2a00d476}
I/incoming: isIncomingDeletion
I/incoming: true
I/amplify:aws-datastore: Orchestrator lock acquired.
I/matched: HubEvent{name='subscriptionDataProcessed', data=ModelWithMetadata{model=Table {id=f6bf647a-cf37-4744-9801-a77c9e5b4d4c, field1=xx, field2=x}, syncMetadata=ModelMetadata{id='f6bf647a-cf37-4744-9801-a77c9e5b4d4c', _deleted=true, _version=2, _lastChangedAt=Temporal.Timestamp{timestamp=1612396296726}}}, uuid=c30939a0-c828-4408-b800-b45915df7748}
I/amplify:aws-datastore: Orchestrator lock released.

```


as you can see isIncomingDeletion logs either record present ( the first one) and the record deleted ( the second one) in the Table object

**Comment by jamesonwilliams** [comment]
@marenero1974 --

That log output looks normal to me, so far.

The first shows you creating a `Table` instance:
> id=d3f2ba82-ea77-40bc-8149-32c41339bdbd, field1=c, field2=x,
> _deleted=null, _version=1

The next one shows you deleting this other `Table` instance:
> id=f6bf647a-cf37-4744-9801-a77c9e5b4d4c, field1=xx, field2=x
> _deleted=true, _version=2

The thing you want to test is the query _after_ that second hub event shows up. Does `f6bf647a-cf37-4744-9801-a77c9e5b4d4c` show up in the query results at that point?

--------------

The next issue that you are encountering is due to where you're initializing Amplify. For simplicity, some of our getting started guides suggest to setup Amplify in an Activity class. However, Amplify is a process-wide singleton. It should really be setup at _application_ scope. For steps to achieve this, please see the [Project Setup documentation](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android#project-setup).

**Comment by marenero1974** [comment]
The first problem was a query problem, and i fixed. For the second i made a class MyAmplifyApp as follow:

```
public class MyAmplifyApp extends android.app.Application {

    @Override
    public void onCreate() {
        super.onCreate();
        try {
            Amplify.addPlugin(new AWSApiPlugin()); // UNCOMMENT this line once backend is deployed
            Amplify.addPlugin(new AWSDataStorePlugin());
            Amplify.configure(getApplicationContext());
            Log.i("Amplify", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("Amplify", "Could not initialize Amplify", error);
        }
    }
}
```

and changed AndroidManifest.xml putting: android:name=".MyAmplifyApp" but MyAmplifyApp onCreate method is never called....

**Comment by jamesonwilliams** [comment]
Hey @marenero1974, glad to hear you got the query issue sorted!

For the next issue, it doesn't seem related to the Amplify framework. I suggest reviewing some of the common responses to [this related StackOverflow question](https://stackoverflow.com/questions/6858158/custom-android-app-application-not-firing-oncreate-event).

I'll close #1143 for now. Please let us know if you need more help. Feel free to join us on Discord to chat in realtime. https://discord.gg/amplify
