### ISSUE TITLE
AWSMobileClient: signalTokensNotAvailable - Android

### ISSUE THREAD

**Issue by ismailseyfi** [aws-amplify/amplify-android#1144]
We have a basic Cognito User Pool and Cognito Identity Pool set up. This was set up outside of amplify. Android plugin was manually configured with CognitoUserPool and CognitoIdentityPool settings.

Our configuration also has a client_id and tokenURI set up. We are trying to use authorization_code grant_type to get id, access and refresh tokens issued to our mobile application.  

In this set up, when we initiate the sign in process and login using the hosted UI for OAUTH2, we are successfully redirected back to the mobile application with our app scheme. 

During this set up we noticed that the following fails `com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity`.

with the following message: 
CustomTabsManagerActivity was created with a null state. This should never happen. Please file an issue with us on GitHub.

We were able to bypass this issue using our MainActivity with the following code. 
```kotlin

    /**
     * On new intent handler for older cognito auth examples
     */
    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        if (intent.data?.scheme == "myapp") {
            Amplify.Auth.handleWebUISignInResponse (intent)
        }
    }
```

When we trace the call stack for handleAuthResponse, we see successful exchange of our authorization_code for OAuth2Tokens. We verified all tokens were issued successfully.  Plugin then tries to use federated identities and generates a temporary credentials and session for the identity that is in the process of login. We can see all of these being successfully generated during debug. 

At the end of this, plugin fails with the following exception. 

```console
W/AWSMobileClient: signalTokensNotAvailable
W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.signalTokensNotAvailable(AWSMobileClient.java:1873)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.getAuthenticationDetails(AWSMobileClient.java:1853)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1834)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1800)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1046)
        at com.amazonaws.mobile.client.AWSMobileClient$24$1$1$1.onResult(AWSMobileClient.java:3160)
        at com.amazonaws.mobile.client.AWSMobileClient$24$1$1$1.onResult(AWSMobileClient.java:3156)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
        at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1722)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:923)
W/AWSMobileClient: signalTokensNotAvailable
```

This is coming from the following code in AWSMobileClient. 

```java
userpool.getCurrentUser().getSession(
                        Collections.<String, String>emptyMap(),
                        new AuthenticationHandler() {
                            @Override
                            public void onSuccess(CognitoUserSession userSession, CognitoDevice newDevice) {
                                try {
                                    mCognitoUserSession = userSession;
                                    callback.onResult(new Tokens(
                                            userSession.getAccessToken().getJWTToken(),
                                            userSession.getIdToken().getJWTToken(),
                                            userSession.getRefreshToken().getToken()
                                    ));
                                } catch (Exception e) {
                                    callback.onError(e);
                                }
                            }
```

`userpool.getCurrentUser()` is returning a new user instead of the logged in user where the USER-ID is end up being null which results in the following exception.

We also tried using amplify init to configure a completely new Pools but we are still running into the same issues. 

We are using the following amplify dependencies in our set up. 
```gradle
    // Amplify core dependency
    implementation 'com.amplifyframework:core:1.6.10'
    implementation 'com.amplifyframework:aws-auth-cognito:1.6.10'
```

We originally did not want to use/configure CIP (Cognito Identity Pool) but it seems its absolutely necessary for amplify library/plugin to work. It seemed almost impossible to turn off CIP federation with CUP. All we are looking to achieve is get OAuth2Tokens issued for our mobile application so we can access some APIs. 

We used the following code to initiate hostedUI login for OAUTH2 flows. 
```kotlin
 /**
   * Amplify.Auth.signInWithWebUI test
   */
  private fun loginHosted() {
    Log.i(TAG, "Initiate Hosted Login Sequence")

    val policy = StrictMode.ThreadPolicy.Builder().permitAll().build()
    StrictMode.setThreadPolicy(policy)

    val options = AWSCognitoAuthWebUISignInOptions.builder()
      .federationProviderName(federationProviderName)
      .build()

    Amplify.Auth.signInWithWebUI(
      this, options,
      { result: AuthSignInResult ->
        Log.i(TAG, result.toString())

        // fetch session details (incl token)
        Amplify.Auth.fetchAuthSession(
          { result -> Log.i(TAG, result.toString()) },
          { error -> Log.i(TAG, error.toString()) }
        )

        // get user details
        val user = Amplify.Auth.currentUser
        Log.i(TAG, user.toString())

      },
      { error: AuthException ->
        Log.e(TAG, error.toString())
        throw error
      }
    )
  }
```

this works as expected. HostedUI opens up in browser and we are able to login. At which time, callback to our application takes place. 

Because of the issue mentioned above with CustomTabsRedirectActivity, we use the following code in our MainActivity to handle callback. 

```kotlin
  /**
   * On new intent handler for older cognito auth examples
   */
  override fun onNewIntent(intent: Intent) {
    Log.i(TAG, "onNewIntent")
    super.onNewIntent(intent)
    if (intent.data?.scheme == "myapp") {
      Log.i(TAG, "handleWebSigninResponse")
      Log.i(TAG, intent.toString())
      Amplify.Auth.handleWebUISignInResponse(intent)
    }
  }
```

Exception is eventually thrown in `handleWebUISignInResponse` call execution.

**Comment by ismailseyfi** [comment]
We originally did not want to use/configure CIP (Cognito Identity Pool) but it seems its absolutely necessary for amplify library/plugin to work. It seemed almost impossible to turn off CIP federation with CUP. All we are looking to achieve is get OAuth2Tokens issued for our mobile application so we can access some APIs. 

We used the following code to initiate hostedUI login for OAUTH2 flows. 
 /**
   * Amplify.Auth.signInWithWebUI test
   */
  private fun loginHosted() {
    Log.i(TAG, "Initiate Hosted Login Sequence")

    val policy = StrictMode.ThreadPolicy.Builder().permitAll().build()
    StrictMode.setThreadPolicy(policy)

    val options = AWSCognitoAuthWebUISignInOptions.builder()
      .federationProviderName(federationProviderName)
      .build()

    Amplify.Auth.signInWithWebUI(
      this, options,
      { result: AuthSignInResult ->
        Log.i(TAG, result.toString())

        // fetch session details (incl token)
        Amplify.Auth.fetchAuthSession(
          { result -> Log.i(TAG, result.toString()) },
          { error -> Log.i(TAG, error.toString()) }
        )

        // get user details
        val user = Amplify.Auth.currentUser
        Log.i(TAG, user.toString())

      },
      { error: AuthException ->
        Log.e(TAG, error.toString())
        throw error
      }
    )
  }

this works as expected. HostedUI opens up in browser and we are able to login. At which time, callback to our application takes place. 

Because of the issue mentioned above with CustomTabsRedirectActivity, we use the following code in our MainActivity to handle callback. 

  /**
   * On new intent handler for older cognito auth examples
   */
  override fun onNewIntent(intent: Intent) {
    Log.i(TAG, "onNewIntent")
    super.onNewIntent(intent)
    if (intent.data?.scheme == "companion") {
      Log.i(TAG, "handleWebSigninResponse")
      Log.i(TAG, intent.toString())
      Amplify.Auth.handleWebUISignInResponse(intent)
    }
  }

Exception is eventually thrown in handleWebUISignInResponse call execution.

**Comment by ismailseyfi** [comment]
We ended up solving this issue ourselves. It turns out having TokenURI in our amplify configuration file forced AWSMobileClient to execute OAuth2UI instead of HostedUI. This caused the issue we were seeing with the CustomTabsRedirectActivity state being null. Us trying to bypass the issue with onNewIntent created the cachedSession issue. Once we removed TokenURI from the the configuration it all worked. 

//AWSMobileClient
if (hostedUIJSON.optString("TokenURI", null) != null) {
    return _showSignInOAuth2UI(callingActivity, signInUIOptions, callback);
} else {
    return _showSignInHostedUI(callingActivity, signInUIOptions, callback);
}

**Comment by upachecog** [comment]
@jamesonwilliams  Our QA team found this same issue today with version 1.6.11

Error logs: https://sentry.io/share/issue/062cd67350634d5181ff2c06ac49cf81/

This is my current implementation:

```
    fun subscribeToAuthEvents() {
        Amplify.Hub.subscribe(HubChannel.AUTH) { hubEvent: HubEvent<*> ->
            when (hubEvent.name) {
                InitializationStatus.SUCCEEDED.toString() -> {
                    Log.i(TAG, "Auth successfully initialized")
                }
                InitializationStatus.FAILED.toString() -> {
                    Log.e(TAG, "Auth failed to succeed")
                }
                else -> {
                    when (AuthChannelEventName.valueOf(hubEvent.name)) {
                        AuthChannelEventName.SIGNED_IN -> {
                            val token = AWSMobileClient.getInstance().tokens.idToken.tokenString **<--- This line crashes.**
                            userSaver.updateCurrentUser(token)
                        }
                        AuthChannelEventName.SIGNED_OUT -> {
                            Log.i(TAG, "Auth just became signed out.")
                        }
                        AuthChannelEventName.SESSION_EXPIRED -> {
                            splashStates.postValue(SplashStates.PRESENT_LOGIN)
                        }
                        else -> Log.w(
                            TAG,
                            "Unhandled Auth Event: " + AuthChannelEventName.valueOf(hubEvent.name)
                        )
                    }
                }
            }
        }
    }
```

Do I need to wait for something else before calling the tokenString or is there a safer way to do it?
