### ISSUE TITLE
How to handle refresh token in android app ?

### ISSUE THREAD

**Issue by JurajBegovac** [aws-amplify/amplify-android#1151]
We use Cognito User Pool for authentication. 
We use phone number + challenge code for authentication. 
The user enters his/her phone number, code is sent via SMS and the user enters the code from SMS and gets idToken, refreshToken and authorizationToken. And then the user is authenticated and the user can use our mobile app.
That works fine.

Here is the problem.
We have set the refresh token to expire after 60 days.

We taught that the refresh token expiration will be extended each time when the access token is refreshed. 
So we taught that the user should re-login only if he/she doesn't use the app for 60 days.
But seems that's not true. Refresh token expired after 60 days no matter if a user is using the app every day.
We don't want active users to re-login after 60 days then we want only inactive users to re-login after 60 days.

How can we achieve this?

Thanks in advance.

**Comment by richardmcclellan** [comment]
Hi @JurajBegovac I don't believe that use case is supported.  Cognito is built around [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-1.5), which doesn't support refreshing a refresh token.

**Comment by JurajBegovac** [comment]
Hi @richardmcclellan 

I taught when I get access token that I'll get new refresh token (if it's expiring soon). But ok.
So you propose just to increase refresh token duration to e.g. 10 years ?

**Comment by richardmcclellan** [comment]
> So you propose just to increase refresh token duration to e.g. 10 years ?

Yes, exactly!

**Comment by JurajBegovac** [comment]
Ok thank you. 
I have another question but I guess it's another topic:

Can we somehow change `AWSMobileClientStore` to not use sharedPrefs then to store tokens inside `AccountManager` because that's the correct place to store tokens (e.g. if we want to have multiple apps that share same account that would be the right place to store it - e.g. google maps, gmail and drive use same account from account manager).

https://developer.android.com/reference/android/accounts/AccountManager#setAuthToken(android.accounts.Account,%20java.lang.String,%20java.lang.String)

Also, what happens is that if user clicks "Clear data" in Android Settings of the app then user will clear sharedPrefs as well. So user will clear tokens as well. But if tokens were saved inside Account Manager user cannot remove them with "Clear data" then just when user removes account (inside Android settings -> Accounts). And that's correct way of doing it.
Or am I missing something ? :)
Thanks in advance

**Comment by richardmcclellan** [comment]
Hi @JurajBegovac, sharing credentials across apps via `AccountManager` is not currently supported, though I do agree it would be valuable for anyone building multiple apps that share a common user pool. 

Since this is different from your initial issue, could you open a new feature request for it?  Then, we will prioritize based on reactions and comments.

**Comment by JurajBegovac** [comment]
Yes sure
