### ISSUE TITLE
Storage.List returns 0 objects even though Bucket Contains objects

### ISSUE THREAD

**Issue by RulerKun** [aws-amplify/amplify-android#1152]
1. A **short** description
Using Storage.List on android doesn't return objects inside the bucket

2. The version of Amplify Android you're using
```
implementation 'com.amplifyframework:aws-auth-cognito:1.6.11'
implementation 'com.amplifyframework:aws-storage-s3:1.16.11'
```
3. The **code** you're using to call Amplify Android
```
Amplify.Storage.list(
    "/",
    { result ->
        result.getItems().forEach { item ->
            Log.i("MyAmplifyApp", "Item: " + item.getKey())
        }
    },
    { error -> Log.e("MyAmplifyApp", "List failure", error) }
)
```
and
```
val options = StorageListOptions.builder()
            .accessLevel(StorageAccessLevel.PROTECTED)
            .targetIdentityId("otherUserID")
            .build()

Amplify.Storage.list(
    "/",
    options,
    { result ->
        result.getItems().forEach { item ->
            Log.i("AmplifyApplication", "Item: " + item)
        }
    },
    { error -> Log.e("MyAmplifyApp", "List failure", error) }
)
```
i tried the 
```
accessLevel(StorageAccessLevel.PROTECTED)
accessLevel(StorageAccessLevel.PRIVATE)
accessLevel(StorageAccessLevel.PUBLIC)
```
but still no returns 0 objects

Bucket got this bucket policy
```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::XXXXXXXXXXXX:role/Cognito_XXXXXXXXXXPoolAuth_Role"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::XXXXXXXXXXXX/*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::XXXXXXXXXXXX:role/Cognito_XXXXXXXXXXPoolAuth_Role"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::xxxxxxxxxxxxx"
        }
    ]
}
```
the CORS
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "HEAD",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
```
while the cognito got this policy
```
{
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::xxxxxxxx/*",
                "arn:aws:s3:::xxxxxxxx"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::xxxxxxxx"
        }
    ]
}
```
this is inside my amplifyconfiguration.json
```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "xxxxxxxxxxxxxxxxxx",
              "Region": "ap-northeast-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "xxxxxxxxxxxxxxxxxx",
            "AppClientId": "xxxxxxxxxxxxxxxxxx",
            "Region": "ap-northeast-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  },
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "xxxxx",
        "region": "ap-northeast-1"
      }
    }
  }
}
```

so far my issue is the same as this too 
`https://stackoverflow.com/questions/63407806/cannot-list-aws-s3-public-folder-items-when-using-android-amplify`

when i tried doing a query to s3 using lambda and boto3. I managed to query fine my objects inside the bucket but the Amplify.storage.list returns 0 even though it is successful

**Comment by jamesonwilliams** [comment]
@RulerKun A couple more ideas for debugging here.

1. What is the full path the objects that _are_ present in the bucket? Are they under the `public`/`protected`/`private` directory in the bucket? Amplify Android only will list items in that directory.

2. Did you upload the items from an Android device? Or by some other means? Unless you uploaded the items through Android, we can't guarantee that the permissions on the objects have been set correctly, since we don't know what they might be.

**Comment by RulerKun** [comment]
> What is the full path the objects that are present in the bucket? Are they under the public/protected/private directory in the bucket? Amplify Android only will list items in that directory.

I got some of the objects on the main path "/" and other objects inside the folder. 

Currently they are on private directory, and users with Cognito and the admin can access to it. I did use a lambda with boto3 and did successfully get the list of items inside of this bucket

> Did you upload the items from an Android device? Or by some other means? 

No I did not upload it with Android Device, I did try to upload via the aws console and a presigned generated url of boto3

> Unless you uploaded the items through Android, we can't guarantee that the permissions on the objects have been set correctly, since we don't know what they might be

I did try to list the permissions that i did added to the bucket in my post above, If possible can you direct me where to look for the other permissions that you want to know of

**Comment by jamesonwilliams** [comment]
> I did try to list the permissions that i did added to the bucket in my post above, If possible can you direct me where to look for the other permissions that you want to know of

Try uploading a small file from the Android device. Check its file path and permissions. Then compare that to the content you've uploaded. You can use the S3 `get-object` command line to see object details, perhaps. https://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html

Hopefully when you A/B them like this it will be clear what's different between the two.
