### ISSUE TITLE
Feature Request: Add AWS Kinesis support in the amplify SDK for Android

### ISSUE THREAD

**Issue by Bogatinovski** [aws-amplify/amplify-android#1162]
I remember in the previous version of the Android Amplify SDK I was able to use the Kinesis API. In the current version this is not available.

**Comment by changxu0306** [comment]
Thanks for your feedback. Our Amplify framework doesn't have AWS Kinesis plugin currently. Please try our [SDK repository](https://github.com/aws-amplify/aws-sdk-android) which contains AWS Kinesis API.
