### ISSUE TITLE
Getting exception - Failed to instantiate AWSMobileClient within 10 seconds and app crashes while trying to execute Amplify.configue() on application class

### ISSUE THREAD

**Issue by prashanthremis** [aws-amplify/amplify-android#1174]
I am using Amplify CLI framework in my Android project to integrate Android with my AWS services( I am using Amazon Pinpoint) I have configured amplify in my machine using the amplify CLI and initated amplify usinsg CLI - amplify init command and have added the necessary plugins in my Android project as per the AWS doc. 
When I launch my app it is crashing at  Amplify.configue() on application class with exception -

The version of Amplify Android you're using - com.amplifyframework:core:1.16.11
The **code** you're using to call Amplify Android - 
** try {
            // Add these lines to add the AWSCognitoAuthPlugin and AWSPinpointAnalyticsPlugin plugins
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSPinpointAnalyticsPlugin(this));
            Amplify.configure(getApplicationContext());

            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
        }**

 Complete exception below -
 E/MyAmplifyApp: Could not initialize Amplify
    AuthException{message=Failed to instantiate AWSMobileClient within 10 seconds, cause=null, recoverySuggestion=Check network connectivity}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:246)
        at com.amplifyframework.core.category.Category.configure(Category.java:88)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:150)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120)
        at com.emishealth.emismobile.framework.application.Application.onCreate(Application.java:50)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1127)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6097)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Any relevant guides or documentation referencing - https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android#n3-provision-the-backend-with-amplify-cli

**Comment by prashanthremis** [comment]
This is due to gradle sync issue closing this as it not a issue.

**Comment by joseAugustoCR** [comment]
@prashanthremis I'm also having this error. Can you elaborate on that?

**Comment by prashanthremis** [comment]
hi @joseAugustoCR - We have various modules split across out app and we have included(inherited) hierarchy modules where I missed to add the below in the correct buid.gradle file,
  implementation 'com.amplifyframework:aws-analytics-pinpoint:1.16.11'
  implementation 'com.amplifyframework:aws-auth-cognito:1.16.11'

This was my issue maybe you can double check if the dependencies are added in the right place.

**Comment by irfanelahidev** [comment]
I am getting this same error on my release build.

1 ) I've implemented the following code base to configure the amplify client :-

JSONObject jsonObject;
        AuthCategoryConfiguration categoryConfiguration;
        try {
            jsonObject = getConfigJson(getAmplifyFile());
            categoryConfiguration = getCategoryConfig(jsonObject);
        } catch (IOException | JSONException e) {
            Logging.logException("Failed to read amplify config data from json", e);
            throw new IllegalStateException("Amplify config JSON parsing failed", e);
            //return;
        }

        try {
            configurePlugin(jsonObject);
            Amplify.Auth.configure(categoryConfiguration, this);
            FirebaseCrashlytics.getInstance().log("Initialized Amplify");
        } catch (AmplifyException e) {
            Logging.logException("Failed to initialize Amplify", e);
            throw new IllegalStateException("Amplify configuration failed " + jsonObject, e);
        }

        //AmplifyException {message=Category auth has already been configured or is currently configuring., cause=null, recoverySuggestion=Ensure that you are only attempting configuration once.}
    }

    private void configurePlugin(@NonNull JSONObject jsonObject) throws AmplifyException {
        AWSCognitoAuthPlugin plugin = new AWSCognitoAuthPlugin();
        plugin.configure(jsonObject, this);
        Amplify.addPlugin(plugin);
    }

    @NonNull
    private static AuthCategoryConfiguration getCategoryConfig(@NonNull JSONObject jsonObject) throws JSONException {
        AuthCategoryConfiguration config = new AuthCategoryConfiguration();
        config.populateFromJSON(jsonObject);
        return config;
    }

    @NonNull
    private JSONObject getConfigJson(@RawRes int amplifyFile) throws IOException, JSONException {
        try (InputStream is = getResources().openRawResource(amplifyFile);
             Writer writer = new StringWriter();
             Reader reader = new BufferedReader(new InputStreamReader(is, "UTF-8"))) {
            char[] buffer = new char[1024];
            int n;

            while ((n = reader.read(buffer)) != -1)
                writer.write(buffer, 0, n);

            return new JSONObject(writer.toString());
        }
    }

2) And I'm getting the following exception :- 

Caused by com.amplifyframework.auth.AuthException
Failed to instantiate AWSMobileClient within 10 seconds
com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure (AWSCognitoAuthPlugin.java:246)
com.paywith.ui.EntApplication.configurePlugin (EntApplication.java:79)
com.paywith.ui.EntApplication.onCreate (EntApplication.java:66)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7184)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7134)
android.app.ActivityThread.access$1500 (ActivityThread.java:274)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2102)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8167)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)

3) Following is my configuration file:- 
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "ap-southeast-2:3h558666-7545-224n-cx06-fb9836nj6yf4",
                "Region": "ap-southeast-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "ap-southeast-2_asdE5jyUt",
            "AppClientId": "4n6fdsfrw22d43r5tbujjkh6jy",
            "Region": "ap-southeast-2"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "buybucks.auth.ap-southeast-2.amazoncognito.com",
                "AppClientId": "7n5b3gsdc9jj43kjioza5f87jn",
                "SignInRedirectURI": "mcards://callback/",
                "SignOutRedirectURI": "mcards://signout/",
                "Scopes": [
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ]
            },
            "authenticationFlowType": "CUSTOM_AUTH"
        }
    }
}

Note:- This issue does not always occur , its being produced like 0.1% of the time
