### ISSUE TITLE
[Auth] Support basic sign in and hosted UI sign in in same app

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-android#1180]
1. A **short** description

When a user signs in using the standard Auth APIs, but the amplify configuration includes OAuth values, the user is briefly presented with a chrome custom tab when attempting to sign out. Signout appears to happen successfully, but the UX is jarring.

2. The version of Amplify Android you're using
1.16.13

3. The **code** you're using to call Amplify Android
```kotlin
 private fun onSignOut (@NonNull flutterResult: Result) {
    try {
      Amplify.Auth.signOut(
              {  -> prepareSignOutResult(flutterResult)},
              { error -> errorHandler.handleAuthError(flutterResult, error)}
      );
    } catch (e: Exception) {
      errorHandler.prepareGenericException(flutterResult, e)
    }
  }
  ```
4. Any relevant [logs](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output)

Note: This is being run within amplify-flutter.

```terminal
W/AWSMobileClient(12847): Failed to parse HostedUI settings from store. Defaulting to awsconfiguration.json
W/AWSMobileClient(12847): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/AWSMobileClient(12847): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/AWSMobileClient(12847): 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/AWSMobileClient(12847): 	at org.json.JSONObject.<init>(JSONObject.java:165)
W/AWSMobileClient(12847): 	at org.json.JSONObject.<init>(JSONObject.java:182)
W/AWSMobileClient(12847): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:682)
W/AWSMobileClient(12847): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:583)
W/AWSMobileClient(12847): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(12847): 	at java.lang.Thread.run(Thread.java:923)
D/AWSMobileClient(12847): initialize: Cognito HostedUI client detected
D/AWSMobileClient(12847): Inspecting user state details
I/amplify:flutter:auth_cognito_hub_evnet_stream_handler(12847): AuthPlugin successfully initialized
D/AWSMobileClient(12847): Inspecting user state details
I/TetheringManager(12847): registerTetheringEventCallback:com.amazonaws.amplify.amplify_auth_cognito_example
D/AWSMobileClient(12847): Inspecting user state details
D/AWSMobileClient(12847): waitForSignIn: userState:SIGNED_OUT
D/IdentityManager(12847): Signing out...
D/AWSMobileClient(12847): Inspecting user state details
```

Please use [syntax highlighting](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) for any code/logs.

**Comment by richardmcclellan** [comment]
> When a user signs in using the standard Auth APIs

Did you use `Amplify.Auth.signIn` or `Amplify.Auth.signInWithWebUi`?

**Comment by haverchuck** [comment]
@richardmcclellan I used `Amplify.Auth.signIn`.  This behavior is NOT observed if I remove the OAuth block from the amplifyconfiguration file.

**Comment by richardmcclellan** [comment]
Got it.  I believe this is a limitation of `AWSMobileClient` - we don't support basic sign in and hosted UI sign in in the same app, you have to choose one or the other.   It will require a non-trivial amount of work to enable it.  Do you know of customers asking for this functionality?

**Comment by kjones** [comment]
We definitely need this and I think many other apps would also. Most apps present, SSO options as well as a sign-up/sign-in with username/password.

**Comment by raphire08** [comment]
Yeah, we would love to have this feature for Flutter library. We are facing the issue on android side only.

**Comment by ekarmazin** [comment]
Supporting this feature request, would be great to use at least hosted UI + socials

**Comment by CamronLDNF** [comment]
Yes prrrrlease, we need this feature! I've spent quite some time moving from a different provider to Amplify Flutter (which I understand is based on Amplify Android) with the belief that basic sign-in + hosted social sign-in simultaneously is supported. And only while researching [this bug](https://github.com/aws-amplify/amplify-android/issues/1212) that I ran in to, I learned that the root cause of the bug is that basic sign-in + hosted UI for social sign-in isn't supported. Gah! So yes, we need this feature.

**Comment by niyonx** [comment]
+1

**Comment by artahc** [comment]
+1

**Comment by rajd90** [comment]
+1
I need this for my flutter app aws-amplify/amplify-flutter#1207

**Comment by MohsinJamadar09** [comment]
> Got it. I believe this is a limitation of `AWSMobileClient` - we don't support basic sign in **and** hosted UI sign in in the same app, you have to choose one or the other. It will require a non-trivial amount of work to enable it (probably a full re-write) Do you know of customers asking for this functionality?

Hi,

I want to use hosted UI signIn, I have also kept OAuth block in amplifyConfiguration.
but still I am  getting this error
`Failed to parse HostedUI settings from store. Defaulting to awsconfiguration.json`

I am using `Amplify.Auth.signInWithWebUI`

could you please help what I am missing?

**Comment by RaviJarwal** [comment]
+1

**Comment by Papashkin** [comment]
+1

**Comment by gpanshu** [comment]
Hello @haverchuck if upgrade is an option for you and your users I would recommend upgrading to our V2 library where you can supply the option that you would like to sign in with even if you have something else in your configuration.

https://docs.amplify.aws/lib/q/platform/android/

`val options =
            AWSCognitoAuthSignInOptions.builder().authFlowType(AuthFlowType.USER_SRP_AUTH).build()`
