### ISSUE TITLE
Events with property (String length greater than 900) is not getting logged in Pinpoint/kinesis and the respective S3 bucket

### ISSUE THREAD

**Issue by prashanthremis** [aws-amplify/amplify-android#1182]
We are using Amplify to send client-side events(from Android) to Pinpoint and Kinesis. 
We build a event where one of the property has length greater than 900 characters is not getting logged in Pinpoint/kinesis and the respective S3 bucket.

**The version of Amplify Android you're using:** com.amplifyframework:core:1.16.11

The code we are using push events with Amplify Android - 

```
val event = AnalyticsEvent.builder()
                                   .name("Exception")
                                   .addProperty("errorDescritionl", errorDescription)
                                   .addProperty("stackTrace", if(error.stackTrace.isNullOrEmpty()) "" else  error.stackTrace.contentToString())
                                   .build()

            Amplify.Analytics.recordEvent(event)
```

**Any relevant guides or documentation you're referencing**: https://docs.amplify.aws/lib/analytics/record/q/platform/android#record-event

Is there any character restriction?

**Comment by richardmcclellan** [comment]
Hi @prashanthremis, it looks like there is a limit of 50 characters for the key name, 200 characaters for the value, and a limit of 40 properties per event.  See [this documentation](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/pinpoint/analytics/AnalyticsEvent.html#addAttribute-java.lang.String-java.lang.String-) for reference.

**Comment by prashanthremis** [comment]
Hi @richardmcclellan Thanks I saw th document now. 
Is there aany chance the 200 characaters limit for the value be extended? We are trying to send stacktrace as part of events to pinpoint which has on an average 900+ character.
Or is there any other way to achieve this?

As well just  aquick note as per the doc  The value will be truncated if it exceeds 200 characters, but for me the events itself is not getting into AWS when the value exceeds 200.

**Comment by richardmcclellan** [comment]
Hi @prashanthremis the 200 character limit is a limitation of the service, not the SDK, so I'm not sure if that can be extended or not.  I'd suggest that you go to the [Pinpoint console](https://console.aws.amazon.com/pinpoint/), and click "Feedback" in the bottom left.  From there, you can submit your question to the Pinpoint service team.

**Comment by prashanthremis** [comment]
ok fine thanks @richardmcclellan

**Comment by ievgen-boink** [comment]
Hey, no updates from Pinpoint team? We have the same issue with 200 characters limit.
