### ISSUE TITLE
Amplify not adding Authorization header automatically 

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [aws-amplify/amplify-android#1186]
So, I'm trying to comunicate to a RESTful API on API Gateway, that is accessible only is authenticated with Cognito.

However, after the login, if I want to make a request, I have to do the following:
``` 
val options: RestOptions = RestOptions.builder()
    .addHeader("Authorization", AWSMobileClient.getInstance().tokens.idToken.tokenString)
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    .addPath("/testapi")
    .build()

Amplify.API.get(options,
    { el ->
        val st = el.data.asJSONObject()
        Log.i("MyAmplifyApp", "GET succeeded: $st.") },
    { Log.e("MyAmplifyApp", "GET failed.", it) }
)
```

otherwise I'll get a `{"message": "Unauthorized"}`.

Now my question is, since Amplify, Cognito, and API Gateway are all AWS services, why do I have to add every time that header?

**Comment by jamesonwilliams** [comment]
Hi Alberto, the `AWSAPIPlugin` _does_ automatically [include the `Authorization` header](https://github.com/aws-amplify/amplify-android/blob/7dc76ee8ee635b217fed015a00fb93bfe6c846ee/aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/AppSyncSigV4SignerInterceptor.java#L208). It does so by calling `getTokens()` on the `AWSMobileClient`, [here](https://github.com/aws-amplify/amplify-android/blob/7dc76ee8ee635b217fed015a00fb93bfe6c846ee/aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/DefaultCognitoUserPoolsAuthProvider.java#L72). When you call `Amplify.configure(...)`, the API plugin loads your configuration values and adds an appropriate request interceptor, [here](https://github.com/aws-amplify/amplify-android/blob/7dc76ee8ee635b217fed015a00fb93bfe6c846ee/aws-api/src/main/java/com/amplifyframework/api/aws/AWSApiPlugin.java#L133).

To help troubleshoot the behavior you're seeing, can you please include:
1. Your `app/src/main/res/raw/amplifyconfiguration.json` file (with any sensitive information replaced with `XXX`)
2. The full code you use to initialize Amplify, and a description of where it is called
3. Device logs showing the initialization of Amplify and the call to `Amplify.API.get`. Please enable [verbose logging as suggested here](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output).

**Comment by AlbertoSinigaglia** [comment]
Sure, (I'll post for the moment only the first 2 since I can't get the third for now):
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "testapi": {
                    "endpointType": "REST",
                    "endpoint": "https://XXXXXXXXXXX.execute-api.us-east-2.amazonaws.com/dev",
                    "region": "us-east-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS",
                    "scope": [
                        "test/read",
                        "test/update",
                        "test/delete"
                    ]
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-XXXXXXXXXXXXXXXX",
                        "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXX",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```
the code: 
```
class MyAmplifyApp : Application() {
    override fun onCreate() {
        super.onCreate()
        try {
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.configure(applicationContext)
            Log.i("MyAmplifyApp", "Initialized Amplify")
        } catch (error: AmplifyException) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
        }
    }
}
```
 (Application that is defined in the manifest as `<application android:name=".MyAmplifyApp" .../>` )

**Comment by AlbertoSinigaglia** [comment]
I've created a new App Client, but once I've changed (manually) the config file, I get: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aerofighter, PID: 12662
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.Exception: You must be signed-in with Cognito Userpools to be able to use getTokens
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1822)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1782)
        at com.aerofighter.MainActivity$onCreate$3.onClick(MainActivity.kt:41)
        at android.view.View.performClick(View.java:6294)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```
This new App Client is a copy of the first one, but it has a Secret key

**Comment by AlbertoSinigaglia** [comment]
Ok the Exception was only a delay in the AWS Service probably since now it's vanished, but now I can tell that even with a AppClient with a AppClientSecret declared in the config, I still need to manually add the token to the requests

**Comment by AlbertoSinigaglia** [comment]
Probably related to : 
 - https://stackoverflow.com/questions/60263497/authenticating-a-rest-api-with-cognito-using-aws-amplify-android/60270118#60270118

**Comment by jamesonwilliams** [comment]
Hey @AlbertoSinigaglia! Are you calling `Amplify.Auth.signIn(...)`? Are you sure this has returned a successful result before your `Amplify.API.get(...)` call?

**Comment by AlbertoSinigaglia** [comment]
Hi @jamesonwilliams  
thank you for your time... yes I'm sure, since the WebHosted UI would have solved a lot of my problem handling the Auth flow, I've now switched to it, and so i now have a function that I call manually clicking on a button: 
```
    private fun login(){
        Amplify.Auth.signInWithWebUI(
                this,
                { result ->
                    toast("Accesso effettuato correttamente")
                    updateUI()
                },
                { error -> Log.e("Error", error.toString()) }
        )

    }
```
this means that both API call and Auth are "activated" through a button click, and so I'm sure that I'm logging in and then making the API call (in fact, i can see in the console the `Amplify.Auth.handleWebUISignInResponse(data)` in the `onActivityResult` printing the token and the "successful login" message)

**Comment by AlbertoSinigaglia** [comment]
@jamesonwilliams  Are there news about this? Do you need other informations?

**Comment by richardmcclellan** [comment]
Hi @AlbertoSinigaglia, per your latest comment, it sounds like your issue is resolved?   If not, please clarify exactly what code you are using and what error you are seeing.    As mentioned by @jamesonwilliams, the Amplify library does automatically include the authorization details on API requests, as long as you make those requests after you have successfully signed in.

**Comment by Muratoter** [comment]
@jamesonwilliams  Thanks for your references. I have done with this code snippet

    private fun initAmplify() {
        try {
            val authProviders = ApiAuthProviders.builder()
                .oidcAuthProvider {
                    val session = runBlocking {
                        com.amplifyframework.kotlin.core.Amplify.Auth.fetchAuthSession()
                    }
                    (session as AWSCognitoAuthSession).userPoolTokens.value?.idToken
                }
                .build()
            Amplify.addPlugin(AWSCognitoAuthPlugin())

            val apiPlugin = AWSApiPlugin.builder()
                .apiAuthProviders(authProviders)
                .configureClient("forApiName") { okHttpBuilder ->
                    okHttpBuilder.addInterceptor(LoggingInterceptor())
                    okHttpBuilder.addInterceptor { chain ->
                        val originalRequest = chain.request()
                        val token = authProviders.oidcAuthProvider.latestAuthToken
                        val updatedRequest = originalRequest.newBuilder()
                            .addHeader("Authorization", token)
                            .build()
                        chain.proceed(updatedRequest)
                    }
                }
                .build()
            Amplify.addPlugin(apiPlugin)

            @RawRes val resourceId =
                if (BuildConfig.DEBUG) R.raw.debugconfig else R.raw.releaseconfig // https://github.com/aws-amplify/amplify-android/issues/1053#issuecomment-747626817
            val config = AmplifyConfiguration.fromConfigFile(applicationContext, resourceId)

            Amplify.configure(config, applicationContext)
        } catch (e: AmplifyException) {
            Timber.e("Could not initialize Amplify " + e.message)
        }
    }
