### ISSUE TITLE
Admin UI does not save and deploy changes

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1188]
Hi,
i have a problem related to amplify admin ui, that doesn't permit me to update a table already created, i want to change the model of a dynamodb table.
In the home of amplify admin ui after saving and deployng my changes it says:

Update API | 20/2/2021, 15:21:44 | FAILED

What should be the problem?

Thanks

**Comment by richardmcclellan** [comment]
Closing as duplicate of https://github.com/aws-amplify/amplify-adminui/issues/128
