### ISSUE TITLE
Usage Question  - Amplify events sent from Android via Analytics is getting obfuscate - is there any proguard rules to avoid this?

### ISSUE THREAD

**Issue by prashanthremis** [aws-amplify/amplify-android#1192]
We are using Amplify to send client-side events from Android to Pinpoint and Kinesis. 

The event properties values like 'stacktrace' are getting obfuscated as we are using ProGuard - are there any ProGuard rules to avoid this?

We're using version 1.16.11.

The code we are using to push events:

```kotlin
val event = AnalyticsEvent.builder()
    .name("Exception")
    .addProperty("errorDescritionl", errorDescription)
    .addProperty("stackTrace", if(error.stackTrace.isNullOrEmpty()) "" else error.stackTrace.contentToString())
    .build()
Amplify.Analytics.recordEvent(event)
```

**Any relevant guides or documentation you're referencing**: https://docs.amplify.aws/lib/analytics/record/q/platform/android#record-event

**Comment by richardmcclellan** [comment]
Hi @prashanthremis, could you share a sample obfuscated stack trace?  The first step would be to identify which classes are getting obfuscated.  Then, you could add rules to `proguard-rules.pro` to prevent the obfuscation.

**Comment by jamesonwilliams** [comment]
Hi @prashanthremis, what's the `error`, above? Can you show us an example value of `error.stackTrace.contentToString()`?

**Comment by prashanthremis** [comment]
Hi @richardmcclellan @jamesonwilliams please find the example value of the stacktrace with obfuscate below,

`com.myproject.submodule.volleymanager.c.l.a(MyHandler.java:5057), com.myproject.submodule.volleymanager.c.aa.a(MyHandler1.java:103), com.myproject.submodule.framework.serviceaccess.a.e$10.a(ServiceManager.java:85), com.android.volley.i.b(Request.java:617), com.android.volley.d$a.run(ExecutorDelivery.java:104), android.os.Handler.handleCallback(Handler.java:790), android.os.Handler.	dispatchMessage(Handler.java:99), android.os.Looper.loop(Looper.java:164), android.app.ActivityThread.main(ActivityThread.java:7000), java.lang.reflect.Method.invoke(Native Method), com.android.intern	al.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)]`


The same  stacktrace without obfuscate,

`com.myproject.submodule.volleymanager.handlers.MyHandler.trackException(MyHandler.java:93), com.myproject.submodule.volleymanager.handlers.MyHandler1.onError(MyHandler1.java:103), com.myproject.submodule.framework.serviceaccess.business.ServiceManager$2.onErrorResponse(ServiceManager.java:85), com.android.volley.Request.deliverError(Request.java:617), com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104), android.os.Handler.handleCallback(Handler.java:790), android.os.Handler.dispatchMessage(Handler.java:99), android.os.Looper.loop(Looper.java:164), android.app.ActivityThread.main(ActivityThread.java:7000), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)]`


The 'error' above are stacktrace from VolleyError / throwable returned from Uncaught exceptions(crashes) in Android

**Comment by richardmcclellan** [comment]
Hi @prashanthremis, adding `-keep class com.amplifyframework.analytics.** { *; }` to your proguard rules probably won't solve the problem in this case, because the classes being obfuscated are not in the Amplify library - they are in your app's code (`com.myproject...`).

Instead, you should add the following to your proguard rules file:
```
-keep class com.myproject.submodule.** { *; }
-keep class com.android.volley.** { *; }
```

**Comment by prashanthremis** [comment]
thanks @richardmcclellan I will give a try on this and get back.
