### ISSUE TITLE
Social Sign In with Facebook and Google not persistent after closing and reopening the app

### ISSUE THREAD

**Issue by arturolc** [aws-amplify/amplify-android#1193]
_1. A **short** description_
Amplify does not save the "Signed In" state when logging in with Google or Facebook Authentication. There is no problem when logging in Google or Facebook at first, but when the app is restarted ```Amplify.Auth.fetchAuthSession``` does not find any user signed in, therefore, the application is prompting for user credentials again. However, this doesn't happen when doing regular Sign In with username and password. 

_2. The version of Amplify Android you're using_
implementation 'com.amplifyframework:core:1.16.13'
implementation "com.amazonaws:aws-android-sdk-core:2.16.4"

_3. The **code** you're using to call Amplify Android_

On a fragment I call the function:
```
Button btnGoogle = view.findViewById(R.id.googleBtn);
        btnGoogle.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Amplify.Auth.signInWithSocialWebUI(
                        AuthProvider.google(),
                        getActivity(),
                        result -> Log.i("AUTHENTICATION", result.toString()),
                        error -> Log.e("AUTHENTICATION", error.toString())
                );
            }
        });
```

On the corresponding activity I call the function:
```
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if (requestCode == AWSCognitoAuthPlugin.WEB_UI_SIGN_IN_ACTIVITY_CODE) {
        Amplify.Auth.handleWebUISignInResponse(data);
    }
}
```

On the other hand, this is how I redirect the User when the app is launched to the Auth and Home activities depending if the AWSCognitoAuthSession isSignedIn state is true or false:
```
 Amplify.Auth.fetchAuthSession(
        result -> {
            Log.d("Auth", result.toString());
            if (result.isSignedIn()) {
                i = new Intent(MainActivity.this,
                        HomeActivity.class);

            } else {
                i = new Intent(MainActivity.this,
                        AuthActivity.class);
            }
        },
        error -> {
            Log.e("Auth", error.toString());
        }
);
```

_4. Any relevant [logs](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output)_

This is what I get after signing in with Google or Facebook and I call
```
 Amplify.Auth.fetchAuthSession(
          result -> {
              Log.d("Auth", result.toString());
          },
          error -> {
              Log.e("Auth", error.toString());
          }
  );
```

> AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}

_5. Any relevant guides or documentation you're referencing_
I have followed the Android guides: https://docs.amplify.aws/lib/auth/getting-started/q/platform/android

**Comment by taranabhangoo** [comment]
I have the same problem. @arturolc Were you able to resolve it somehow?

**Comment by div5yesh** [comment]
I was unable to replicate this on the latest version of Amplify. Try using the latest version: [1.22.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.22.0). Please let us know if you are still facing this issue.
