### ISSUE TITLE
Feedback Request: How would you improve Amplify Library for Android?

### ISSUE THREAD

**Issue by hdworld11** [aws-amplify/amplify-android#1206]
Please comment on this issue to let us know how you would improve Amplify Library for Android.

We are looking forward to hearing from you so we can better address your needs!

**Comment by hellosagar** [comment]
Im unable to update the Data in the Dynamo when the Datastore is enabled?
and while making a project for hashcode Amplify Hackathon Im facing a problem where I cant update two keys at the same time and the documentation needs a lot of work with more sample example for Android

**Comment by milk531** [comment]
give developer more control on datastore sync flow

**Comment by siegerts** [comment]
Thoughts on transferring this to [Discussions](https://github.com/aws-amplify/amplify-android/discussions) and pinning to banner?

- Transfer issue to discussion: https://github.com/github/feedback/discussions/2952
- Example pinned discussions at top of page [here](https://github.com/github/feedback/discussions?discussions_q=pin)

**Comment by KayIlory** [comment]
Sorting data in Amplify query and control return of data set. This is pretty difficult at the moment
