### ISSUE TITLE
Amplify.API should support sorting

### ISSUE THREAD

**Issue by fabiano-alves-dev** [aws-amplify/amplify-android#1208]
Hi. I'm trying to do a custom query to get a list of items and paginate the data.

I can get the items on the response as expected but I can't get the next token. I think the problem is in the deserialization. If I change the return type to String then the `nextToken` is there. But when I use my `PaginatedResult<Property>`, i get only the items but not the `nexToken`. 
Here's my code:

```java
private fun propertiesByPriceRequest(modelType: String): GraphQLRequest<PaginatedResult<Property>> {
        return SimpleGraphQLRequest(
            ("query getPropertiesSorted { "
                    + "propertiesByPrice(modelType: $modelType, price: {gt: 200000},sortDirection: ASC, limit: 2) { " +
                    "items {" +
                    "id " +
                    "imageUrl " +
                    "price " +
                    "type " +
                    "rooms " +
                    "bathrooms " +
                    "parkingSpace " +
                    "lot " +
                    "city " +
                    "}" +
                    "nextToken " +
                    "startedAt " +
                    "}" +
                    "}"),
            mapOf("modelType" to modelType),
            TypeMaker.getParameterizedType(PaginatedResult::class.java, Property::class.java),
            GsonVariablesSerializer(),
        )
    }
```

Below is my response using `PaginatedResult<Property>` as return type

> response: GraphQLResponse{data='PaginatedResult{requestForNextResult=null, items=[Property {id=f45cc017-9cd9-4ecf-b23c-972a788cc654, imageUrl=https://imovelappbucket165022-dev.s3-sa-east-1.amazonaws.com/public/properties_examples/imovel+(2).jpg, sell=null, rent=null, price=250000, type=APARTMENT, rooms=2, bathrooms=2, parkingSpace=1, lot=80, state=null, city=Santo André, neighborhood=null, street=null, number=null, zipCode=null, modelType=null}, Property {id=9b8c6842-8a26-4414-8f38-a76acddb3598, imageUrl=https://imovelappbucket165022-dev.s3-sa-east-1.amazonaws.com/public/properties_examples/imovel+(6).jpg, sell=null, rent=null, price=300000, type=APARTMENT, rooms=2, bathrooms=2, parkingSpace=2, lot=100, state=null, city=São Caetano do Sul, neighborhood=null, street=null, number=null, zipCode=null, modelType=null}]}', errors='[]'}

Could anyone help me on how I could deserialize it as a model and get the `nextToken`? Thanks!

**Comment by richardmcclellan** [comment]
Hi @fabiano-alves-dev,

You should be able to get the nextToken like this:
```
String nextToken = response.getData().getRequestForNextResult().getVariables().get("nextToken")
```

That said, it looks like `requestForNextResult` is null in your response.  This will be the case if AppSync did not return a nextToken.   This simply means there are no more results - you already have all the pages.

**Comment by fabiano-alves-dev** [comment]
@richardmcclellan thank you very much for your answer.

I have seven items in this case, and I used `limit: 2` on the query, so I should have more pages. Take a look on the response when I just change the return type to String. I get the two results and the `nextToken,` so I can´t understand why the `requestForNextResult `  is null when I change the return type back to my model again.

**response: GraphQLResponse{data='{"propertiesByPrice":{"items":[{"id":"f45cc017-9cd9-4ecf-b23c-972a788cc654","imageUrl":"https://imovelappbucket165022-dev.s3-sa-east-1.amazonaws.com/public/properties_examples/imovel+(2).jpg","price":250000,"type":"APARTMENT","rooms":2,"bathrooms":2,"parkingSpace":1,"lot":80,"city":"Santo André"},{"id":"9b8c6842-8a26-4414-8f38-a76acddb3598","imageUrl":"https://imovelappbucket165022-dev.s3-sa-east-1.amazonaws.com/public/properties_examples/imovel+(6).jpg","price":300000,"type":"APARTMENT","rooms":2,"bathrooms":2,"parkingSpace":2,"lot":100,"city":"São Caetano do Sul"}],"nextToken":"eyJ2ZXJzaW9uIjoyLCJ0b2tlbiI6IkFRSUNBSGdzdWsxUmlacC84TlM3dGg2MXltOFI5SEdhbFlCcW5mUlpPbVAraXRYeHVRRUR6MHJEN3hlbXNwMzdVaFB0S284R0FBQURVakNDQTA0R0NTcUdTSWIzRFFFSEJxQ0NBejh3Z2dNN0FnRUFNSUlETkFZSktvWklodmNOQVFjQk1CNEdDV0NHU0FGbEF3UUJMakFSQkF6SWhKZTVwYTZEaEp5WmxWY0NBUkNBZ2dNRk8xczh3T0R2c2NORWVRUG14dG5BL0hqdmpoUmE5V3lFU2dsQ0U2eFBTQ2hvc0swa0RYQkY0b1hEMm5QdTZjREVpdjN3YTNRbmpIRENZSG9XNlRJQko4NElodEs1WTB2VWkvVktPTlRwK3ZmQnBySGFiNzhpZW1wY1dxdFM5Wk9BNjNPZDZSNWhXSHVudmFxUnhwOWRlNFk3anJGREE0VEVHQkFsdEFWYWhOUEZ3Wk9RTGdlMmNhTHc1OGFFL1BxMytDcUF4MzJLckRvWnhNMWpyRmVKallDNFg4UTNzRkJ6bVlBTDVRM1RnN3ppM3pqL09hU2JGbDA2SFFSQXUralJwTDFHVUJYZGsyOU1HQ2RvaWNPdkdVVjBtaUJHSWcyL0dhNEdiWCtDNE51Y1l0dG16QU4rMnZ2N00yWXc1TkNNV3k3d0lqZUwvbUJGMmZpeFk0a2VYbjdwZEJrZ1ZvUlFnWkFGbU1KaEVXWkUvc04wT2NSYzlyNVJ0MTZOblpNUWdWNVE0N0xLS1dCeVFmMlVoTXBOSWN3bHMwMUQ0aFEzbmY0QksvUU04cGVsTmhReExNMmZVT3NEYml6bE1SYWhEbDhzSmNVbjVCd1lqdldlcVJpYWlobm9DdVNRajRaa3MwUTdMS0JuRVduQmR0RUs3OTVSZWVScmhCZnJGOWFBb1UreER3TmRRMWxuVGFlYTlNV0lBU1U3M0xoZ0pYZTlJejVZKytkWHdIcjhKNGVSUUFjQUdCVWZvdDVyT2JXTXduU2t0WkY1NkxmbjJrQkRSQ2RTN0pFSE1wdUpFK3k5RWhCSyt5RjFlRFVaSlArV1EwdHJncEdZMHFlSk5xOU9JK2wvcUtiQUcrME1TOEZLZ2d6RmprK1ZwLzdzSzh1VXgwVEI5b21abnMxeUMwUUM5R29mcmYxbmY0b29FdFhRaWU2UnR5ZXc4ZktGMWxnME9ueklFSkFtZWY4aXpKU3hxK0ZMaHdoa2dNb0hyUEUxNG9Qakc3ak9PV3ZnTk1WeEVHTnFKN0dEVXlvYjQ4WUY0UVIwQ3NsbnpsekNvYlovbmxGNjRJV1gveE96STBPUjNVaEFubUFGMFZ6MTg0ZnhUK3NqQnhmdkFFMDVpVXp1OEk1YTd2Q01tMDQvMnNYV2NWR09PNkUyek5sZnpSNjd2UU01OFBhOCtwN0VHUGQyeU13b25UZFk2bnltdGVYWVBsMzd6YVZDVDVMWVg1SzZGdFV5QVdsa3BhLytHbDdhN01EVWtyUHFCYWlsNkdoVUJRbDVQZzlVN2xaa2FXem5GSzkrN3d5NzBFMGlwV3V2S3VicVlwS29SYzdFa21kU0d6MExycExYcUsrcjBYTFdmMjdMM2w0PSJ9","startedAt":null}}', errors='[]'}**

Here's my model code on schema.graphql, don't know if could be anything wrong here.

```
type Property @model

@key(name: "propertiesByPrice" fields: ["modelType", "price"] queryField: "propertiesByPrice")
@key(name: "propertiesByLot" fields: ["modelType", "lot"] queryField: "propertiesByLot")
{
    imageUrl: String,
    sell: Boolean,
    rent : Boolean,
    price: Int,
    type: PropertyType,
    rooms: Int,
    bathrooms: Int,
    parkingSpace: Int,
    lot: Int,
    state: String,
    city: String,
    neighborhood: String,
    street: String,
    number: String,
    zipCode: String
    modelType: String
}
```

**Comment by fabiano-alves-dev** [comment]
> Hi @fabiano-alves-dev,
> 
> You should be able to get the nextToken like this:
> 
> ```
> String nextToken = response.getData().getRequestForNextResult().getVariables().get("nextToken")
> ```
> 
> That said, it looks like `requestForNextResult` is null in your response. This will be the case if AppSync did not return a nextToken. This simply means there are no more results - you already have all the pages.

@richardmcclellan thank you very much for your answer.

I have seven items in this case, and I used `limit: 2` on the query, so I should have more pages. Take a look on the response when I just change the return type to String. I get the two results and the `nextToken,` so I can´t understand why the `requestForNextResult `  is null when I change the return type back to my model again.

**response: GraphQLResponse{data='{"propertiesByPrice":{"items":[{"id":"f45cc017-9cd9-4ecf-b23c-972a788cc654","imageUrl":"https://imovelappbucket165022-dev.s3-sa-east-1.amazonaws.com/public/properties_examples/imovel+(2).jpg","price":250000,"type":"APARTMENT","rooms":2,"bathrooms":2,"parkingSpace":1,"lot":80,"city":"Santo André"},{"id":"9b8c6842-8a26-4414-8f38-a76acddb3598","imageUrl":"https://imovelappbucket165022-dev.s3-sa-east-1.amazonaws.com/public/properties_examples/imovel+(6).jpg","price":300000,"type":"APARTMENT","rooms":2,"bathrooms":2,"parkingSpace":2,"lot":100,"city":"São Caetano do Sul"}],"nextToken":"eyJ2ZXJzaW9uIjoyLCJ0b2tlbiI6IkFRSUNBSGdzdWsxUmlacC84TlM3dGg2MXltOFI5SEdhbFlCcW5mUlpPbVAraXRYeHVRRUR6MHJEN3hlbXNwMzdVaFB0S284R0FBQURVakNDQTA0R0NTcUdTSWIzRFFFSEJxQ0NBejh3Z2dNN0FnRUFNSUlETkFZSktvWklodmNOQVFjQk1CNEdDV0NHU0FGbEF3UUJMakFSQkF6SWhKZTVwYTZEaEp5WmxWY0NBUkNBZ2dNRk8xczh3T0R2c2NORWVRUG14dG5BL0hqdmpoUmE5V3lFU2dsQ0U2eFBTQ2hvc0swa0RYQkY0b1hEMm5QdTZjREVpdjN3YTNRbmpIRENZSG9XNlRJQko4NElodEs1WTB2VWkvVktPTlRwK3ZmQnBySGFiNzhpZW1wY1dxdFM5Wk9BNjNPZDZSNWhXSHVudmFxUnhwOWRlNFk3anJGREE0VEVHQkFsdEFWYWhOUEZ3Wk9RTGdlMmNhTHc1OGFFL1BxMytDcUF4MzJLckRvWnhNMWpyRmVKallDNFg4UTNzRkJ6bVlBTDVRM1RnN3ppM3pqL09hU2JGbDA2SFFSQXUralJwTDFHVUJYZGsyOU1HQ2RvaWNPdkdVVjBtaUJHSWcyL0dhNEdiWCtDNE51Y1l0dG16QU4rMnZ2N00yWXc1TkNNV3k3d0lqZUwvbUJGMmZpeFk0a2VYbjdwZEJrZ1ZvUlFnWkFGbU1KaEVXWkUvc04wT2NSYzlyNVJ0MTZOblpNUWdWNVE0N0xLS1dCeVFmMlVoTXBOSWN3bHMwMUQ0aFEzbmY0QksvUU04cGVsTmhReExNMmZVT3NEYml6bE1SYWhEbDhzSmNVbjVCd1lqdldlcVJpYWlobm9DdVNRajRaa3MwUTdMS0JuRVduQmR0RUs3OTVSZWVScmhCZnJGOWFBb1UreER3TmRRMWxuVGFlYTlNV0lBU1U3M0xoZ0pYZTlJejVZKytkWHdIcjhKNGVSUUFjQUdCVWZvdDVyT2JXTXduU2t0WkY1NkxmbjJrQkRSQ2RTN0pFSE1wdUpFK3k5RWhCSyt5RjFlRFVaSlArV1EwdHJncEdZMHFlSk5xOU9JK2wvcUtiQUcrME1TOEZLZ2d6RmprK1ZwLzdzSzh1VXgwVEI5b21abnMxeUMwUUM5R29mcmYxbmY0b29FdFhRaWU2UnR5ZXc4ZktGMWxnME9ueklFSkFtZWY4aXpKU3hxK0ZMaHdoa2dNb0hyUEUxNG9Qakc3ak9PV3ZnTk1WeEVHTnFKN0dEVXlvYjQ4WUY0UVIwQ3NsbnpsekNvYlovbmxGNjRJV1gveE96STBPUjNVaEFubUFGMFZ6MTg0ZnhUK3NqQnhmdkFFMDVpVXp1OEk1YTd2Q01tMDQvMnNYV2NWR09PNkUyek5sZnpSNjd2UU01OFBhOCtwN0VHUGQyeU13b25UZFk2bnltdGVYWVBsMzd6YVZDVDVMWVg1SzZGdFV5QVdsa3BhLytHbDdhN01EVWtyUHFCYWlsNkdoVUJRbDVQZzlVN2xaa2FXem5GSzkrN3d5NzBFMGlwV3V2S3VicVlwS29SYzdFa21kU0d6MExycExYcUsrcjBYTFdmMjdMM2w0PSJ9","startedAt":null}}', errors='[]'}**

Here's my model code on schema.graphql, don't know if could be anything wrong here.

```
type Property @model

@key(name: "propertiesByPrice" fields: ["modelType", "price"] queryField: "propertiesByPrice")
@key(name: "propertiesByLot" fields: ["modelType", "lot"] queryField: "propertiesByLot")
{
    imageUrl: String,
    sell: Boolean,
    rent : Boolean,
    price: Int,
    type: PropertyType,
    rooms: Int,
    bathrooms: Int,
    parkingSpace: Int,
    lot: Int,
    state: String,
    city: String,
    neighborhood: String,
    street: String,
    number: String,
    zipCode: String
    modelType: String
}
```

**Comment by richardmcclellan** [comment]
Ahh, I know why.   [This deserialization logic](https://github.com/aws-amplify/amplify-android/blob/a3e26a4b26d1b704eccd2f0a8df4aba7b6e64aaf/aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java#L162-L166) only works when the original request is an `AppSyncGraphQLRequest`, so it won't work for a `SimpleGraphQLRequest`.  So, using `PaginatedResult` is probably not going to work for this use case. 

Instead, I'd suggest creating a similar class, and using that as the deserialization type instead.  Something like this:
```
class QueryList<T> {
     private Iterable<T> items;
     private String nextToken;

     public Iterable<T> getItems() { return items; }
     public String getNextToken() { return nextToken; }
}
```

Then, specify the responseType as:

```
TypeMaker.getParameterizedType(QueryList::class.java, Property::class.java)
```

**Comment by fabiano-alves-dev** [comment]
> Ahh, I know why. [This deserialization logic](https://github.com/aws-amplify/amplify-android/blob/a3e26a4b26d1b704eccd2f0a8df4aba7b6e64aaf/aws-api/src/main/java/com/amplifyframework/api/aws/GsonGraphQLResponseFactory.java#L162-L166) only works when the original request is an `AppSyncGraphQLRequest`, so it won't work for a `SimpleGraphQLRequest`. So, using `PaginatedResult` is probably not going to work for this use case.
> 
> Instead, I'd suggest creating a similar class, and using that as the deserialization type instead. Something like this:
> 
> ```
> class QueryList<T> {
>      private Iterable<T> items;
>      private String nextToken;
> 
>      public Iterable<T> getItems() { return items; }
>      public String getNextToken() { return nextToken; }
> }
> ```
> 
> Then, specify the responseType as:
> 
> ```
> TypeMaker.getParameterizedType(QueryList::class.java, Property::class.java)
> ```

Hi Richard. I've just tried your suggestion. This is my response now:
 
**response: GraphQLResponse{data='br.com.fxmobile.imovelapp.data.model.QueryList@95dd30a', errors='[]'}**

and the response.data is null

Here's my QueryList class;

```
class QueryList<T> {
    val items: Iterable<T>? = null
    val nextToken: String? = null
}
```
And my request:

```
    private fun propertiesByPriceRequest(modelType: String): GraphQLRequest<QueryList<Property>> {
        return SimpleGraphQLRequest(
            ("query getPropertiesSorted { "
                    + "propertiesByPrice(modelType: $modelType, price: {gt: 200000},sortDirection: ASC, limit: 2) { " +
                    "items {" +
                    "id " +
                    "imageUrl " +
                    "price " +
                    "type " +
                    "rooms " +
                    "bathrooms " +
                    "parkingSpace " +
                    "lot " +
                    "city " +
                    "}" +
                    "nextToken " +
                    "startedAt " +
                    "}" +
                    "}"),
            mapOf("modelType" to modelType),
            TypeMaker.getParameterizedType(QueryList::class.java, Property::class.java),
            GsonVariablesSerializer(),
        )
    }
```

Also I'd like to ask, is this the right approach to get a paginated data beign able to filter and sort the items? I don't know if I could have choosen a better / simpler way.

**Comment by richardmcclellan** [comment]
Hi @fabiano-alves-dev, Apologies - I forgot one thing in my previous proposal.   Since the `items` and `nextToken` in the JSON response are contained in a `propertiesByPrice` JSON object, your response type need to represent that appropriately too.

In addition to `QueryList`, you also need a `ResponseData` class:
```
class ResponseData<T> {
      private QueryList<T> propertiesByPrice;

      public QueryList<T> getPropertiesByPrice() { return propertiesByPrice; }
} 

class QueryList<T> {
     private Iterable<T> items;
     private String nextToken;

     public Iterable<T> getItems() { return items; }
     public String getNextToken() { return nextToken; }
}
```

Then, specify the responseType as 
```
TypeMaker.getParameterizedType(ResponseData::class.java, Property::class.java)
```

The easier approach here is to use the `ModelQuery` helper for constructing the GraphQLRequest, but it only supports filtering, not sorting, so your current approach is the only way if you want sorted results.

That said, I will leave this issue open as a feature request to add first-class support for sorting.

**Comment by fabiano-alves-dev** [comment]
Thank you very much for your help @richardmcclellan, it's working now. It would be great adding the sorting support feature.

**Comment by jamesonwilliams** [comment]
Thanks @richardmcclellan, looks like you're enabled for now, @fabiano-alves-dev?

We have an existing issue to track adding sorting to the API category. Please add your 👍 to https://github.com/aws-amplify/amplify-android/issues/837.

Closing for now. If there are further actions from our team, please let us know.
