### ISSUE TITLE
Getting exception - Failed to instantiate AWSMobileClient within 10 seconds and app crashes while trying to execute Amplify.configure() in application class

### ISSUE THREAD

**Issue by irfanelahidev** [aws-amplify/amplify-android#1211]
I am getting an error on my release build.

I've implemented the following code to configure the amplify client:

```java
JSONObject jsonObject;
AuthCategoryConfiguration categoryConfiguration;
try {
    jsonObject = getConfigJson(getAmplifyFile());
    categoryConfiguration = getCategoryConfig(jsonObject);
} catch (IOException | JSONException e) {
    Logging.logException("Failed to read amplify config data from json", e);
    throw new IllegalStateException("Amplify config JSON parsing failed", e);
    //return;
}

    try {
        configurePlugin(jsonObject);
        Amplify.Auth.configure(categoryConfiguration, this);
        FirebaseCrashlytics.getInstance().log("Initialized Amplify");
    } catch (AmplifyException e) {
        Logging.logException("Failed to initialize Amplify", e);
        throw new IllegalStateException("Amplify configuration failed " + jsonObject, e);
    }

    //AmplifyException {message=Category auth has already been configured or is currently configuring., cause=null, recoverySuggestion=Ensure that you are only attempting configuration once.}
}

private void configurePlugin(@NonNull JSONObject jsonObject) throws AmplifyException {
    AWSCognitoAuthPlugin plugin = new AWSCognitoAuthPlugin();
    plugin.configure(jsonObject, this);
    Amplify.addPlugin(plugin);
}

@NonNull
private static AuthCategoryConfiguration getCategoryConfig(@NonNull JSONObject jsonObject) throws JSONException {
    AuthCategoryConfiguration config = new AuthCategoryConfiguration();
    config.populateFromJSON(jsonObject);
    return config;
}

@NonNull
private JSONObject getConfigJson(@RawRes int amplifyFile) throws IOException, JSONException {
    try (InputStream is = getResources().openRawResource(amplifyFile);
         Writer writer = new StringWriter();
         Reader reader = new BufferedReader(new InputStreamReader(is, "UTF-8"))) {
        char[] buffer = new char[1024];
        int n;

        while ((n = reader.read(buffer)) != -1)
            writer.write(buffer, 0, n);

        return new JSONObject(writer.toString());
    }
}
```

And I'm getting the following exception:
```console
Caused by com.amplifyframework.auth.AuthException
Failed to instantiate AWSMobileClient within 10 seconds
com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure (AWSCognitoAuthPlugin.java:246)
com.paywith.ui.EntApplication.configurePlugin (EntApplication.java:79)
com.paywith.ui.EntApplication.onCreate (EntApplication.java:66)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7184)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7134)
android.app.ActivityThread.access$1500 (ActivityThread.java:274)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2102)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8167)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

Following is my configuration file:

```json
{
  "UserAgent":"aws-amplify-cli/0.1.0",
  "Version":"0.1.0",
  "IdentityManager":{
    "Default":{}
  },
  "CredentialsProvider":{
    "CognitoIdentity":{
      "Default":{
        "PoolId":"ap-southeast-2:3h558666-7545-224n-cx06-fb9836nj6yf4",
        "Region":"ap-southeast-2"
      }
    }
  },
  "CognitoUserPool":{
    "Default":{
      "PoolId":"ap-southeast-2_asdE5jyUt",
      "AppClientId":"4n6fdsfrw22d43r5tbujjkh6jy",
      "Region":"ap-southeast-2"
    }
  },
  "Auth":{
    "Default":{
      "OAuth":{
        "WebDomain":"buybucks.auth.ap-southeast-2.amazoncognito.com",
        "AppClientId":"7n5b3gsdc9jj43kjioza5f87jn",
        "SignInRedirectURI":"mcards://callback/",
        "SignOutRedirectURI":"mcards://signout/",
        "Scopes":[
          "phone",
          "email",
          "openid",
          "profile",
          "aws.cognito.signin.user.admin"
        ]
      },
      "authenticationFlowType":"CUSTOM_AUTH"
    }
  }
}
```

Note: this issue does not always occur. It is being produced like 0.1% of the time.

**Comment by richardmcclellan** [comment]
Hi @irfanelahidev, is there a reason you are writing custom logic for configuring the Auth plugin?   I believe you could probably  just replace all of your code with something like this:

```
try {
    Amplify.addPlugin(new AWSCognitoAuthPlugin());
    Amplify.configure(getApplicationContext());
    FirebaseCrashlytics.getInstance().log("Initialized Amplify");
} catch (AmplifyException exception) {
    Logging.logException("Failed to initialize Amplify", exception);
    throw new IllegalStateException("Amplify configuration failed ", exception);
}
```

**Comment by irfanelahidev** [comment]
@richardmcclellan The custom logic is written simply so that we can support different user pools per environment. 
I have different config files that are fetched based on the buildType.

 @RawRes
    private static int getAmplifyFile() {
        String buildType = BuildConfig.BUILD_TYPE;
        switch (buildType) {
            case "uat":
                return R.raw.uat_awsconfiguration;
            case "release":
                return R.raw.release_awsconfiguration;
            default:
                return R.raw.staging_awsconfiguration;
        }
    }

**Comment by rjuliano** [comment]
Looking at your code, it looks like you could be initializing the plugin twice: once by calling it directly (in `configurePlugin()`) and then by calling the category's configure method (`Amplify.Auth.configure(categoryConfiguration, this);`. 

You shouldn't have to call configure for any individual category or plugin. The recommended approach is to call Amplify.configure instead and allow that to do the work of configuring the plugins for you.  You can tell Amplify which config file to use by doing something like this:

```java
try {
    // Read the desired amplifyconfiguration.json file based on your build type via getAmplifyFile()
    AmplifyConfiguration amplifyConfig = AmplifyConfiguration.fromConfigFile(getApplicationContext(), getAmplifyFile());
    // Add the plugin to Amplify
    Amplify.addPlugin(new AWSCognitoAuthPlugin());
    // Amplify.configure will take care of calling the underlying plugin's configure methods for you
    Amplify.configure(amplifyConfig, getApplicationContext());
    FirebaseCrashlytics.getInstance().log("Initialized Amplify");
} catch (AmplifyException exception) {
    Logging.logException("Failed to initialize Amplify", exception);
    throw new IllegalStateException("Amplify configuration failed ", exception);
}

```

**Comment by irfanelahidev** [comment]
@rjuliano  Alright, Thanks for your assistance . I will change my implementation with your suggested way to try it out and get back to you again if the issue persisted

**Comment by irfanelahidev** [comment]
@rjuliano I tried this implementation and started getting this exception 

 Caused by: java.lang.IllegalStateException: Amplify configuration failed
        at com.paywith.ui.EntApplication.onCreate(EntApplication.java:65)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: AuthException{message=Failed to instantiate AWSMobileClient, cause=java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient., recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:240)
        at com.amplifyframework.core.category.Category.configure(Category.java:91)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:150)
        at com.paywith.ui.EntApplication.onCreate(EntApplication.java:61)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202) 
        at android.app.ActivityThread.access$2200(ActivityThread.java:296) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient.
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:601)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:929)

**Comment by rjuliano** [comment]
The configuration file you need to use is the one the CLI generates with the name `amplifyconfiguration.json` as supposed to `awsconfiguration.json` which is for the old SDK. 

So your config retrieval function would be something like:

```
    @RawRes
    private static int getAmplifyFile() {
        String buildType = BuildConfig.BUILD_TYPE;
        switch (buildType) {
            case "uat":
                return R.raw.uat_amplifyconfiguration;
            case "release":
                return R.raw.release_amplifyconfiguration;
            default:
                return R.raw.staging_amplifyconfiguration;
        }
    }
```

The CLI has to generate both to continue supporting users that are still using the SDK. But whenever you use Amplify, you should use `amplifyconfiguration.json`, which has a slightly different format.
