### ISSUE TITLE
getting redirected to external link while signIn and signout while using flutter cognito library in andriod

### ISSUE THREAD

**Issue by raphire08** [aws-amplify/amplify-android#1212]
1. Use the normal signing in android using flutter library with configuration for both cognito login and other auth methods. On signing and signout external Link will be opened in browser. 
2. using library amplify_flutter: '<1.0.0' and  amplify_auth_cognito: '<1.0.0'

Is there a method to use both normal signIn and hosted signIns and not get redirected in android. The same issue is not faced for iOS.

**Comment by richardmcclellan** [comment]
Using both hosted UI and basic authentication is not currently supported in Amplify Android.  Please add a comment / reaction on [this feature request](https://github.com/aws-amplify/amplify-android/issues/1180) if you'd like to see it added.

**Comment by ken-ng-esotec** [comment]
To overcome this issue, do global sign out so that the browser redirect is skipped.

      final SignOutResult res = await Amplify.Auth.signOut(
        options: const SignOutOptions(globalSignOut: true),
      );
