### ISSUE TITLE
Mutation Update not working with automerge  resolution strategy

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [aws-amplify/amplify-android#1222]
I'm retrieving elements from a subscription from AppSync using Amplify, and what i want to do is to update some of them in some cases, so the code looks like this (for example):
```
Amplify.API.subscribe(
        ModelSubscription.onCreate(Player::class.java),
        { Log.i("ApiQuickStart", "Subscription established") },
        { onCreated ->
            Log.i("RESPONSE", onCreated.toString() )
            if (something) {
                val player = onCreated.data
                val playerOnline = player.copyOfBuilder()
                    .name(remote.name)
                    .id(remote.id)
                    .gameroom(remote.gameroom)
                    .positionX(player.positionX.toDouble() / player.context.width.toDouble())
                    .positionY(player.positionY.toDouble() / player.context.height.toDouble())
                    .score((Math.random() * 10000).toInt())
                    .lastinteraction(Temporal.Timestamp.now())
                    .build()
                Amplify.API.mutate(
                    ModelMutation.update(
                        playerOnline,
                        RemotePlayer.ID.eq(remote.id)
                    ),
                    { response ->
                        remote = response.data
                        Log.i(
                                "RESULTS",
                                response.toString()
                        )
                    },
                    { error -> Log.e("MyAmplifyApp", "update position failed", error) }
            )
            } 
        },
        { onFailure -> Log.e("ApiQuickStart", "Subscription failed", onFailure) },
        { Log.i("ApiQuickStart", "Subscription completed") }
)
```
however this is not working, since the Log shows this:
```
I/RESULTS: GraphQLResponse{data='Player {id=659760d0-4d18-4b88-aa20-3d33f42d4032, lastinteraction=Temporal.Timestamp{timestamp=1615500729}, name=Alberto, score=0, positionX=0.5, positionY=0.0, dead=false, gameroom=GameRoom {id=a6a65a87-80fa-44c8-b4bd-bebafd3af4f0, seed=test, gamers=2}}', errors='[]'}
```
(when the `positionX` is `0.25483`, I can set manually a value but it still not works)  

Trying to debugging this problem, I saw this question on StackOverflow (https://stackoverflow.com/questions/65659687/amplify-and-appsync-not-updating-data-on-mutation-from-multiple-sources) that explains that if I want to update a record with automerge, I should pass `_version`, and afaik, there is no `_version` in the `Player` model (autogenerated from Amplify Codegen)

Are there some examples of "update" on Amplify for android? Since in the documentation I can only fine "create", and so I don't even know where to start to "set this `_version`" on the request

Thank you

**Comment by richardmcclellan** [comment]
Hi @AlbertoSinigaglia, `Amplify.API` is not supported when conflict detection is _enabled_, because it does not include the `_version` field on requests, which AppSync requires.

To solve this, you can either:
  - Disable conflict detection (`amplify update api`, choose "Disable DataStore for entire API", `amplify push`)
  - Use `Amplify.DataStore` instead (which requires conflict detection to be enabled).

**Comment by AlbertoSinigaglia** [comment]
@richardmcclellan thank you so much, the first one worked for me
