### ISSUE TITLE
Can't cancel subscription (AppSync)

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [aws-amplify/amplify-android#1231]
Hi, I'm trying to close a subscription inside it's handler:
``` 
var sub : GraphQLOperation<Player>? = null
sub = Amplify.API.subscribe(
        ModelSubscription.onCreate(Model::class.java),
        { Log.i("ApiQuickStart", "Subscription established") },
        { onCreated ->
            if (something) {
                ...
                sub?.cancel()
            } 
        },
        { onFailure -> Log.e("ApiQuickStart", "Subscription failed", onFailure) },
        { Log.i("ApiQuickStart", "Subscription completed") }
)
```
However, no matter what I try, when i get to that line, I receive this exception:
```
E/ApiQuickStart: Subscription failed
    ApiException{message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:376)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(SubscriptionEndpoint.java:258)
        at com.amplifyframework.api.aws.SubscriptionOperation.cancel(SubscriptionOperation.java:105)
        ...
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:392)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifySubscriptionData(SubscriptionEndpoint.java:226)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$700(SubscriptionEndpoint.java:60)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.processJsonMessage(SubscriptionEndpoint.java:573)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onMessage(SubscriptionEndpoint.java:476)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

What am i doing wrong?  
The subscription works fine, I receive everything as supposed, but that line causes that exception

**Comment by jamesonwilliams** [comment]
> Subscription completion not acknowledged

In AppSync's WebSocket subscription protocol, the client sends a `"stop"` message, and the server is supposed to acknowledge it. However, if for _whatever reason_ the client doesn't get an `"stop_ack"` in reply, we probably don't want to throw an error. There's not much the user can do about this.

**Comment by AlbertoSinigaglia** [comment]
> > Subscription completion not acknowledged
> 
> 
> 
> In AppSync's WebSocket subscription protocol, the client sends a `"stop"` message, and the server is supposed to acknowledge it. However, if for _whatever reason_ the client doesn't get an `"stop_ack"` in reply, we probably don't want to throw an error. There's not much the user can do about this.

I've surrounded it with a try-catch... is this the best i can do?...

**Comment by jamesonwilliams** [comment]
> > > Subscription completion not acknowledged
> > 
> > 
> > In AppSync's WebSocket subscription protocol, the client sends a `"stop"` message, and the server is supposed to acknowledge it. However, if for _whatever reason_ the client doesn't get an `"stop_ack"` in reply, we probably don't want to throw an error. There's not much the user can do about this.
> 
> I've surrounded it with a try-catch... is this the best i can do?...

For now, but I think we should fix this inside the library.

**Comment by dishantghai** [comment]
> Hi, I'm trying to close a subscription inside it's handler:
> 
> ```
> var sub : GraphQLOperation<Player>? = null
> sub = Amplify.API.subscribe(
>         ModelSubscription.onCreate(Model::class.java),
>         { Log.i("ApiQuickStart", "Subscription established") },
>         { onCreated ->
>             if (something) {
>                 ...
>                 sub?.cancel()
>             } 
>         },
>         { onFailure -> Log.e("ApiQuickStart", "Subscription failed", onFailure) },
>         { Log.i("ApiQuickStart", "Subscription completed") }
> )
> ```
> 
> However, no matter what I try, when i get to that line, I receive this exception:
> 
> ```
> E/ApiQuickStart: Subscription failed
>     ApiException{message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
>         at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:376)
>         at com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(SubscriptionEndpoint.java:258)
>         at com.amplifyframework.api.aws.SubscriptionOperation.cancel(SubscriptionOperation.java:105)
>         ...
>         at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:392)
>         at com.amplifyframework.api.aws.SubscriptionEndpoint.notifySubscriptionData(SubscriptionEndpoint.java:226)
>         at com.amplifyframework.api.aws.SubscriptionEndpoint.access$700(SubscriptionEndpoint.java:60)
>         at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.processJsonMessage(SubscriptionEndpoint.java:573)
>         at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onMessage(SubscriptionEndpoint.java:476)
>         at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
>         at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
>         at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
>         at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
>         at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)
> ```
> 
> What am i doing wrong?
> The subscription works fine, I receive everything as supposed, but that line causes that exception

+1  Facing the Same issue when I do `subscription.cancel()` ......  waiting for the bug to be resolved. Thanks.

**Comment by dishantghai** [comment]
+1 Facing the Same issue when I do subscription.cancel() ...... waiting for the bug to be resolved. Thanks.
