### ISSUE TITLE
Escape Hatch in version 1.17.0

### ISSUE THREAD

**Issue by vivekathreya1** [aws-amplify/amplify-android#1235]
I want to implement confirm sign in with custom challenge of "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD".

I had previously used escape hatch. But with this new version of **1.17.0**, the "**getPlugin**" method in Auth is not available. 

Do you have a workaround for this?

**Comment by jamesonwilliams** [comment]
Hi @vivekathreya1. There are two versions of `Amplify`, one in the `core` module, and one in the `core-kotlin` module. If you don't have a `Amplify.Auth.getPlugin()`, I suspect you're importing `com.amplifyframework.kotlin.core.Amplify`. That one doesn't have `getPlugin()` right now.

As a workaround, you could add an extension function.

```kotlin
fun <T: Plugin<T>> KotlinAuthFacade.getPlugin(byName: String): Plugin<T> {
    return com.amplifyframework.core.Amplify.Auth.getPlugin(byName)
}
```

Then you can do:
```kotlin
val plugin = Amplify.Auth.getPlugin("awsCognitoAuthPlugin")
val mobileClient = plugin.escapeHatch as AWSMobileClient
```

As an alternate approach, just write a function to get the mobile client, and skip everything above.

```kotlin
fun mobileClient(): AWSMobileClient {
    val plugin = com.amplifyframework.core.Amplify.getPlugin("awsCognitoAuthPlugin")
    return plugin.escapeHatch as AWSMobileClient
}
```

**Comment by vivekathreya1** [comment]
Hello @jamesonwilliams. Thanks for the solution.
I have used the alternate approach you have mentioned above.
