### ISSUE TITLE
Sign out Not clearing the tokens. 

### ISSUE THREAD

**Issue by vivekathreya1** [aws-amplify/amplify-android#1240]
Hi,

The signout does not seem to clear the tokens. I can still see them in the sharedprefs. 

I am using this method  **Amplify.Auth.signOut()** for signing out and this library **com.amplifyframework.kotlin.core** **v1.17.0**

Thanks 
Vivek

**Comment by changxu0306** [comment]
Thanks for reporting this. I'll take a look at it.

**Comment by raphkim** [comment]
Hi @vivekathreya1 , can I get an example of your code snippet to see if we can reproduce this issue? Are you seeing this behavior for global sign-out enabled or disabled (or both)?

**Comment by vivekathreya1** [comment]
Hi @raphkim, I just checked again. The sharedprefs in device explorer still has some cognito specific tokens. But the fetch auth session api gives me a signedout exception, which solves my problem. 
My bad that I created a bug. 

Thanks for the reply
