### ISSUE TITLE
How to reference images stored in an s3 bucket

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1241]
Hi,
i wonder how do i get the whole path of an image stored in an s3 bucket programmatically, from inside my android application.
I don't want to hard code the path for example: 

`https://<bucket-name>.s3.<region>.amazonaws.com/<path-of-image>`

I have a private s3 bucket, if i hard code the whole path it gives exception the reading is forbidden

Thanks

**Comment by raphkim** [comment]
Hi @marenero1974 , please try looking into `Amplify.Storage.getUrl()` API to obtain pre-signed URL for your object.

**Comment by marenero1974** [comment]
@raphkim I saw the Amplify.Storage.getUrl() API, but getUrl returns an AWSS3StorageGetPresignedUrlOperation, but it seems not holding any URL string in it

**Comment by raphkim** [comment]
Amplify operations are asynchronous and works with callbacks to provide operation results. Please try the following snippet:
```
Amplify.Storage.getUrl(
    myKey,
    result -> {
        .... // What to do with result.getUrl()
    },
    error -> {
        ... // What to do if this operation fails
    }
);
```

**Comment by raphkim** [comment]
Hi @marenero1974 ,
I added some documentation on how to use `getUrl()` in the official docs. Please refer to https://github.com/aws-amplify/docs/pull/3074 for more information.

**Comment by marenero1974** [comment]
@raphkim  Ok, this gives me a java.net.URL, that if i use  it with Glide it would give me the same forbidden exception, is there a work around for this? maybe the question is how to use glide in conjunction with amplify in order to load private images from an s3 bucket

**Comment by raphkim** [comment]
Update: docs are now available here:
https://docs.amplify.aws/lib/storage/download/q/platform/android#generate-a-download-url

**Comment by iamAliRaza** [comment]
@raphkim i want to know about URL expiry... Can i save it in database and use it forever ... If it will be expire after some time what's the other approach ??
