### ISSUE TITLE
QueryPredicate objects does not  add another predicate

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1246]
Hi all,
i have an issue regarding my basic predicate not adding another one like this: 

`        QueryPredicate predicate = MyBean.FIELD1.contains("");
        if (true) {
            predicate.and(MyBean.FIELD2.contains("val2"));
        }`

after the if statement my predicate objcets contains only this:

`QueryPredicateOperation { model: MyBean, field: field1, operator: ContainsQueryOperator { type: CONTAINS, value: val1 } }`

why the second predicate was not added?

**Comment by richardmcclellan** [comment]
Hi @marenero1974, the `and` method does not _modify_ your original `predicate` object - it returns a new predicate group containing the two predicates.  So, you just need to actually _assign_ it to your predicate variable, like this:
```
QueryPredicate predicate = MyBean.FIELD1.contains(""); 
if (true) { 
    predicate = predicate.and(MyBean.FIELD2.contains("val2")); 
}
```

**Comment by marenero1974** [comment]
thanks, this solved my question, and works fine
