### ISSUE TITLE
HostedUI webview reloads/disappears when leaving the app to find confirmation code

### ISSUE THREAD

**Issue by changxu0306** [aws-amplify/amplify-android#1251]
### Description
- I'm using `Amplify.Auth.signInWithWebUI()` to perform sign in. After clicking `Sign Up` and filling in the sign up info in the web UI, a confirmation code will be sent to the email address. An EditText view will pop up to let you enter the code you received. If you goes to another app like Gmail to check your email on your phone for a while, then come back to your app, the web UI will disappear. 
When you try to sign up with the same username again, an error message "User already exists" will show. 
![image](https://user-images.githubusercontent.com/42978935/112418195-443ac100-8ce6-11eb-8ed0-a40453824409.png)
- But you can't use this username to sign in because another error message "User is not confirmed" will show.
![image](https://user-images.githubusercontent.com/42978935/112418240-5583cd80-8ce6-11eb-819a-b5fe2c0dc06f.png)
- This is something like a deadlock and the username cannot be used anymore.

The version of Amplify Android you're using: **1.17.1**

### Error message
```2021-03-24 20:57:19.279 16839-16839/com.amplifyframework.sample.photosharing E/AuthService: Signin failed
    UserCancelledException{message=The user cancelled the sign-in attempt, so it did not complete., cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled, recoverySuggestion=To recover: catch this error, and show the sign-in screen again.}```

**Comment by richardmcclellan** [comment]
Sounds like there are 2 separate issues:
1.  If you go to another app like Gmail to find the confirmation code, and then come back, the web UI is gone.   This could be an Android SDK issue that we should investigate further.
2. Unconfirmed users can't finish sign up, or login.  This issue is already tracked here (https://github.com/aws-amplify/amplify-js/issues/3184), and will require changes from the Cognito service team.

**Comment by simonking76** [comment]
this still seems to be an issue, how come its closed?
