### ISSUE TITLE
How to delete all items in a table

### ISSUE THREAD

**Issue by simone40love** [aws-amplify/amplify-android#1272]
Newbie question. How do I delete all the items in a table? 
I am using Java.
This is what I tried:

            Amplify.DataStore.delete(Todo.class, Where.matchesAll(),
                    deleted -> {
                        Log.i(TAG, "Deleted succeeded " );
                    },
                    failure -> {
                        Log.e(TAG, "Delete failed. ");
                    }
            );

Error:
Required type
Provided
object:
T
Class<com.amplifyframework.datastore.generated.model.Todo>
predicate:
QueryPredicate
QueryOptions
reason: QueryOptions is not compatible with QueryPredicate

**Comment by richardmcclellan** [comment]
Hi @simone40love, `Where.matchesAll()` returns a `QueryOptions` object, which is only meant for use with `DataStore.query(...)`  For `DataStore.delete(...)`, try using `QueryPredicates.all()` instead, which returns a `QueryPredicate` object, like this:

```
Amplify.DataStore.delete(Todo.class, QueryPredicates.all(),
        deleted -> {
            Log.i(TAG, "Deleted succeeded " );
        },
        failure -> {
            Log.e(TAG, "Delete failed. ");
        }
);
```
