### ISSUE TITLE
Unable to send user end point info from Android AWS SDK in App to Amazon pinpoint

### ISSUE THREAD

**Issue by Murali-CS** [aws-amplify/amplify-android#1279]
We have setup the amplify project with pinpoint and authorization categories. We are not able to send user end point information to pinpoint from mobile App. Only standard attributes and events from the App are getting sent. We are not able to send the complete end point information. Additionally, we are able to send some custom attributes and global event with attributes for those global events. However, we want to have complete end point information sent with user attributes included. We are not able to do it yet.

We are using mobile Android App to authorize the user using Cognito and then sending the pinpoint events from the mobile App screens. 

We also included code in the App to send some **custom attributes**. We are able to see the custom attributes under the custom attributes section under the Endpoint Attributes drop down of pinpoint console.

We also included code in the App to send some **global event with attributes**. We are able to see the same global event with its attributes under the events and events attributes drop down of pinpoint console.

Regarding the user attributes, we are expecting the **user attributes** to be available from Cognito user pool data sharing operation. For this we have the Cognito user pool data sharing option turned ON. We also have a corresponding identity pool for the user pool. However none of the user attributes are shown under the user attributes section under the Endpoint Attributes drop down of pinpoint console.

Please help

**Comment by poojamat** [comment]
@Murali-CS need some more info to figure out your use case, are you trying to send information that you have specified about the user to Amazon Pinpoint. If so do you make themplify.Analytics.identifyUser(userId, profile) method call as per the documentation below:

https://docs.amplify.aws/lib/analytics/identifyuser/q/platform/android

**Comment by Murali-CS** [comment]
yes we are making the amplify.Analytics.identifyUser(userId, profile) method call as in the documentation
