### ISSUE TITLE
Force token refresh

### ISSUE THREAD

**Issue by mathieuedet** [aws-amplify/amplify-android#1283]
Hello,

I use amplify for an offline/online use-case. I've read in documentation that the refresh process is handled by SDK.
I've set access token to 1 day and refresh to 7 days because I want to be sure that app can be use offline at least 1 day (1 day is maximum value)

I need to force the refresh of token when I have connection and only if token expired in next 12h for example. Currently, behavior seems to be to refresh if token validity is lower than 1h. 

I've read some issues about this subject and some people have indicated that a call to `AWSMobileClient.getInstance().getTokens()` or `Amplify.Auth.fetchAuthSession()` force a refresh but not for me...

I use last version : 1.17.2

Thanks

**Comment by richardmcclellan** [comment]
Hi @mathieuedet, I'm not sure I understand your use case.  Why do you want to refresh the token even if it doesn't expire for 12 hours?  While you are offline, you won't be able to use the token anyway.  Wouldn't it be okay for the token to just get refreshed the next time you come back online?

If you do actually need to manually force a refresh, it is not currently supported, but we have an open feature request here: https://github.com/aws-amplify/aws-sdk-android/issues/696.  Feel free to add your +1 and describe your use case on that issue, to help prioritize it.

**Comment by mathieuedet** [comment]
Hi, thanks for your response. Potentially, my app can be use in offline scenario for many hours and each time phone get a connection, I would like to refresh token (even if no expired yet) if expiration is in 1 hour for example and not waiting for an expiration to make refresh.

I believe it's a crucial feature to make it possible manually for some use-cases and let possibility to users to handle by themselves this part.

Thanks for the link, I'll add +1 on this feature request.

**Comment by richardmcclellan** [comment]
Great!  I'll close this issue now, but feel free to track progress or add any specific use cases for this feature to https://github.com/aws-amplify/aws-sdk-android/issues/696.
