### ISSUE TITLE
Crash at Thread interrupted awaiting subscription acknowledgement

### ISSUE THREAD

**Issue by deepikarenkube** [aws-amplify/amplify-android#1301]
Please search the [existing issues](https://github.com/aws-amplify/amplify-android/search?q=%22your%20search%20query%20goes%20here%22) first.  If your issue is not reported yet, create one with the following information:

1. A **short** description - I am using using Amplify for Android phone and displaying graphs using data pulled from DynamoDB. Every time I want to display the data, I pull the necessary data from DynamoDB to avoid storing it on the phone. So I do an Amplify.Datastore.clear and on success I call Amplify.Datastore.start to force a sync from the DynamoDB and the necessary data is pulled in. Some of the times the app crashes.
2. The version of Amplify Android you're using - 1.17.2
3. The **code** you're using to call Amplify Android -  

```
Amplify.DataStore.clear(new Action() {
    @Override
    public void call() {
        datastorestart();
        return;
    }

    public void datastorestart() {
        token = Amplify.Hub.subscribe(HubChannel.DATASTORE, new HubSubscriber() {
            @Override
            public void onEvent(@NonNull HubEvent<?> hubEvent) {
                String readyeventname = DataStoreChannelEventName.READY.toString();
                if (readyeventname.equals(hubEvent.getName())) {
                    Amplify.Hub.unsubscribe(token);
                    loadsetuppages();
                    Amplify.DataStore.stop(new Action() {
                        @Override
                        public void call() {
                            Log.i("datastore", "Stopped");
                            return;
                        }
                    }, failure -> Log.i("datastore", "Failure to stop"));
                }
            }
        });

        Amplify.DataStore.start(new Action() {
            @Override
            public void call() {
                Log.i("datastore", "Started");
                return;
            }
        }, failure -> Log.i("datastore", "Failure to start"));
    }
```
4. Any relevant [logs](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output) - 
[aws_logs.txt](https://github.com/aws-amplify/amplify-android/files/6404621/aws_logs.txt)

5. Any relevant guides or documentation you're referencing - 
6. For API or DataStore issues, your `schema.graphql` - 
7. For CLI issues, include any relevant logs in `~/.amplify/logs/amplify-cli-<date>.log` - 

Please use [syntax highlighting](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) for any code/logs.

**Comment by rjuliano** [comment]
To clarify, when you say sometimes the app crashes, does that mean you see the stack traces in the log every time you try to run your code but it only causes the app to forcibly closed sometimes?

If you haven't yet, it would also be helpful to [increase the log level](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output) so we can get more verbose output.

**Comment by raphkim** [comment]
Hi @deepikarenkube , I have a few questions regarding your use-case here. 

DataStore is a category that helps with persisting data in local device and keeping it synced with the backend. Trying to keep your data in backend while preventing it from persisting in a local device is, while possible to achieve, not the expected use-case of the category. With each attempt to access the data, you would need to:

1. open up several subscriptions to the backend
1. processing the stream of incoming data
1. store it locally
1. use the data as needed (graphing in your case)
1. delete locally stored items again after using it
1. close the subscriptions

, which can have an unintended impact on the performance of your app.

That said, the code snippet you provided does not appear to be doing the above steps. `DataStore.clear()` will clear local database, but the success callback appears to be calling `DataStore.start()` again to refill your local database, which completely undoes the original attempt to clear it.

Would you be able to let us know why it is necessary to prevent data from being stored locally? If it is storage size issue, then I would recommend using [selective sync expression filter](https://docs.amplify.aws/lib/datastore/sync/q/platform/android#selectively-syncing-a-subset-of-your-data) to sync only the data you need.

**Comment by deepikarenkube** [comment]
Hi Rafael

The app does not close, I only see the stack traces in the log and the app
is no longer able to fetch data from the cloud and gives the message -
"Setting currentState to LOCAL_ONLY". I will change the log level and
attach the logs.

Thanks,
[image: photo]
Deepika Gopal
Co-Founder, Researcher at Renkube
M 96639 63803   <96639+63803>
W www.renkube.com  <http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
[image: www.linkedin.com/in/deepika-gopal-32398319]
<http://www.linkedin.com/in/deepika-gopal-32398319>

**Comment by deepikarenkube** [comment]
Hi Raphael

Thank you for your mail. To give you some background, I have an AWS IOT
device(logger) which is populating the DynamoDB table every minute. What
the app does is to pull the data from the cloud and display it to the user
in the form of a graph. Since the table is getting populated every minute,
if the user refreshes the graph page I would like to pull in the latest
data from the DynamoDB table. From AWS documentation, I understand that the
only way to pull in data eagerly is by stopping/clearing datastore and
again starting it which will bring in the latest data. Please let me know
if there is any other way to eagerly pull in the latest data.

It would not be possible to store all data locally for multiple dates since
there is a very large volume of data for multiple dates stored on the
cloud. We are fine with storing data for a single date. I am already using
the Selective Sync feature to bring in data only for a particular date on
selection by the user. When the user selects a different date I would like
to clear the old data and bring in the new data from the cloud. So for this
purpose as well I am using the datastore clear followed by the start.

Please let me know your thoughts.

[image: photo]
Deepika Gopal
Co-Founder, Researcher at Renkube
M 96639 63803   <96639+63803>
W www.renkube.com  <http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
[image: www.linkedin.com/in/deepika-gopal-32398319]
<http://www.linkedin.com/in/deepika-gopal-32398319>

**Comment by raphkim** [comment]
Thank you for the clarification. I have a better picture of what you are trying to achieve now.

As long as DataStore is in API sync mode, it will continue to pull data from the backend. You do not need to stop and start DataStore to continue receiving newest items in DynamoDB. In fact it will be slower to do so because it will restart the subscriptions that were already listening for changes in the backend. 

On the other hand, you _do_ want to restart DataStore each time the user selects a different date to apply the sync expression. At this time you will want to clear your local database with `DataStore.clear()` so that the data from previous date selection doesn't stay there unnecessarily.

Another thing I notice from your code is that you are attempting to start DataStore before it could stop. I believe the failure to start API sync mode may potentially be a result of a race condition created by attempting to stop and start DataStore at the same time. Moving start operation to inside of the success callback with stop operation will help prevent any concurrency issues.

**Comment by deepikarenkube** [comment]
Hi Raphael,

Approximately how often would the sync happen automatically from the
DynamoDB? I remember initially trying this and I didn't see any sync. Only
when there was a change on the local datastore could I see a sync happening
to the cloud. We would need the sync to come from the cloud at least once
in a couple minutes to have the latest data. Would I need to add anything
else to make this happen automatically?

In my code, I am doing a Hub.subscribe and then calling a
Datastore.start(). Once the ready event is received signalling the data is
downloaded, I do a Hub.unsubscribe. Would this sequence of events lead to a
race condition? Pasting more code below, first clear_datastore is called
which clears the datastore and calls datastorerestart on success. Maybe I
should not unsubscribe as soon as I receive the Ready event?

public void datastorestart() {
    token = Amplify.Hub.subscribe(HubChannel.DATASTORE, new HubSubscriber() {
        @Override
        public void onEvent(@NonNull HubEvent<?> hubEvent) {
            Log.i("datastore", hubEvent.getName());
            String readyeventname = DataStoreChannelEventName.READY.toString();
            Log.i("datastorecheckvalues", hubEvent.getName() + readyeventname);
            if (readyeventname.equals(hubEvent.getName())) {
                Amplify.Hub.unsubscribe(token);
                create_graph();
            }
        }
    });

    Amplify.DataStore.start(new Action() {
        @Override
        public void call() {
            Log.i("datastore", "Started");
            return;
        }
    }, failure -> Log.i("datastore", "Failure to start"));
    //Amplify.DataStore.query(Renkubesetupinfo.class, renkubesetupinfo
-> {},failure -> Log.e("datastore", "Could not query DataStore",
failure));


}

public void clear_datastore() {

    Amplify.DataStore.clear(new Action() {
        @Override
        public void call() {
            datastorestart();
            return;
        }
    }, failure -> Log.i("datastore", "Failure to clear"));

}



[image: photo]
Deepika Gopal
Co-Founder, Researcher at Renkube
M 96639 63803   <96639+63803>
W www.renkube.com  <http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
<http://www.renkube.com/>
[image: www.linkedin.com/in/deepika-gopal-32398319]
<http://www.linkedin.com/in/deepika-gopal-32398319>

**Comment by raphkim** [comment]
Synchronization happens via `start()` operation, which is called before any data manipulation operation such as `query`, `save`, `delete`, or `observe`. You can call `start` to eagerly sync as well but it would likely be unnecessary because you would be calling `query` to access data.

Do note that you may not see the immediate result of synchronization as query does not wait for the sync to complete before showing what is already available locally, which is likely what convinced you that sync is not automated.

**Comment by richardmcclellan** [comment]
@deepikarenkube one other thing to note - DataStore will only get real-time updates if your IoT device is performing AppSync mutations.   If you are instead modifying DynamoDB directly (not recommended), you won't get updates.
