### ISSUE TITLE
Amplify Datastore does not take into account AWS profile change

### ISSUE THREAD

**Issue by meghamittal92** [aws-amplify/amplify-android#1303]
Each Amplify environment is associated with an AWS profile. I mistakenly attached the wrong profile (the prod profile) to the beta env and ran my app which then proceeded to show data from the prod DDB. On changing the profile attached to the environment using amplify configure project, although I was able to push changes to the beta stack (using amplify push), the app still kept downloading from prod DDB.

Detail:

We have 2 different AWS accounts (acting as beta and prod ) and correspondingly 2 amplify stacks.
* agbeta is the env name for beta which is tied to AWS account 1
* agdev is the env name for prod which is tied to AWS account 2

Now, agbeta was added later by a colleague and when I pulled the code, I mistakenly attached it to the prod AWS profile on my system. So, whenever I ran my app, it would download data from prod DDB. 

I corrected this by running an amplify configure project and attaching agbeta to the AWS beta profile. Now, although amplify push started working and allowed me to push changes to beta amplify stack, the app still keeps downloading data from prod DDB!! 
I even deleted the prod credentials and prod aws profile from my system altogether , the app still kept downloading data from prod DDB. This is not only incorrect, but also dangerous.

After running amplify configure project, I checked that my local-aws-info.json looks like this:

```
{
  "agbeta": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "beta"
  },
  "agdev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "prod"
  }
}
```

amplify dependencies used : 

```
    implementation 'com.amplifyframework:core:1.17.3'
    implementation 'com.amplifyframework:aws-api:1.17.3'
    implementation 'com.amplifyframework:aws-datastore:1.17.3'
    implementation 'com.amplifyframework:aws-storage-s3:1.17.3'
   implementation 'com.amplifyframework:aws-auth-cognito:1.17.3'
```

(Not using cognito in the app right now, just the dependency is added)

The following code is used to initialize the local DB from cloud  : 

```
 Amplify.DataStore.clear(
                () -> Amplify.DataStore.start(
                        () -> Log.d("AmplifyDatastoreStart", "DataStore has been started.  Subscribe to `SYNC_QUERIES_READY` to know when sync is complete"),
                        error -> Log.e("AmplifyDatastoreStart", "Failure starting DataStore")
                ),
                failure -> Log.e("MyAmplifyApp", "Failed to start DataStore.")
        );

```

Steps to repro :

1. Make an amplify project and 2 environments attached to 2 different accounts.
2. Change the profile attached to one of the environments
3. Check if using that amplify env still downloads data from the unattached account.

**Comment by rjuliano** [comment]
The AWS profile credentials are not used during app execution. They are used by the Amplify CLI to read environment info from the AWS account and generate the config file for the application. 

At runtime, credential and endpoint information are derived from this config file. Take a look at the config file for the app under `app/src/res/raw` and see if it's pointing to the correct API endpoint. You may just have to delete them and run `amplify pull` under the correct profile. That should regenerate the config files.

**Comment by meghamittal92** [comment]
Hi rjuliano,

Thanks for your response. Deleting the files and doing an amplify pull did work. But, it seems like I have to do it every time. In my colleague's workspace, everytime they do an amplify env checkout, those files change but that's not the case for me. Doing an amplify pull everytime is quite cumbersome. 
Is there a way that I can fix this? Are there any logs the CLI generates when it fails to update those files on an "amplify env checkout"?

**Comment by richardmcclellan** [comment]
Hi @meghamittal92, here's an explanation of the current behavior, and how to think about it: https://github.com/aws-amplify/amplify-cli/issues/960#issuecomment-468503434

If you have further questions/concerns, please [open an issue in the CLI repo](https://github.com/aws-amplify/amplify-cli/issues/new/choose).
