### ISSUE TITLE
Observe table changes, duplicates items

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1310]
Hi @richardmcclellan , i am using amplify version 1.17.3, i have this issue:

i am implementing a chat in my activity, my code is like this:

````
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        ......

        sendMessageButton.setOnClickListener(v -> SendMessage());
        FetchMessages();

        Amplify.DataStore.observe(Messages.class,
                cancelable -> Log.i("MyAmplifyApp", "Observation began."),
                messagesChanged -> {
                    Messages message = messagesChanged.item();
                    messagesList.add(message);
                    messageAdapter.setMessages(messagesList);
                    messageAdapter.notifyDataSetChanged();
                    userMessagesRV.smoothScrollToPosition(messageAdapter.getItemCount());
                    Log.i("MyAmplifyApp", "Messages refreshed: ");
                },
                failure -> Log.e("MyAmplifyApp", "Observation failed.", failure),
                () -> Log.i("MyAmplifyApp", "Observation complete.")
        );
````

FetchMessages method is like this:

````
    private void FetchMessages()
    {

        Amplify.DataStore.query(Messages.class, Where.matches(Messages.RECEIVER.eq(messageReceiverID.trim())
                        .and(Messages.SENDER.eq(messageSenderID.trim()))
                        .or(Messages.SENDER.eq(messageReceiverID.trim())
                                .and(Messages.RECEIVER.eq(messageSenderID.trim())))
                ),
                items -> {
                    while (items.hasNext()) {
                        Messages message = items.next();
                        messagesList.add(message);
                        messageAdapter.setMessages(messagesList);
                        messageAdapter.getItemCount();

                        setIsseen(message);
                    }
                },
                failure -> Log.e("error", "Query failed.", failure)
        );
        messageAdapter.notifyDataSetChanged();
    }

````
The problem resides in the observe, i want to update my recyclerview when a new message is written in the Messages table, but i am getting duplicated messages, what is wrong?

Thanks

**Comment by drochetti** [comment]
Hi @marenero1974, I realize that on every change coming through `Amplify.DataStore.observe` your adding it to your message list using:

```java
Messages message = messagesChanged.item();
messagesList.add(message);
```

Please note that any change is sent to the observer, not only new messages. So if a message was deleted or updated, it will also trigger the observer. So you need to check the type of change (`messagesChanged .getType()`) and update your UI accordingly.

**Comment by marenero1974** [comment]
Thanks @drochetti , i was trying to observe with a predicate and then filtering with:
```
if(messagesChanged.type().equals(DataStoreItemChange.Type.CREATE)) {
.... update UI
}
```
but it gives this exception first:
DataStoreException{message=Not implemented yet, buster!, cause=null, recoverySuggestion=Check back later!}

do you know when it wil be implemented observe with predicates?

**Comment by marenero1974** [comment]
@drochetti i am also facing a bug, with
```
if(messagesChanged.type().equals(DataStoreItemChange.Type.CREATE)) {
...update UI
```
the first time i enter my chat activity ( i put the observe in the onCreate ) the message is added twice on the UI, when i send the first message, but on subsequent sent messages, is added only once

**Comment by drochetti** [comment]
> @drochetti i am also facing a bug, with
> 
> ```
> if(messagesChanged.type().equals(DataStoreItemChange.Type.CREATE)) {
> ...update UI
> ```
> 
> the first time i enter my chat activity ( i put the observe in the onCreate ) the message is added twice on the UI, when i send the first message, but on subsequent sent messages, is added only once

This might be related to your first query. My understanding is that you query first to populate the UI, is that correct? Have you checked if the item coming through `observe` is already in your adapter?

**Comment by drochetti** [comment]
> Thanks @drochetti , i was trying to observe with a predicate and then filtering with:
> 
> ```
> if(messagesChanged.type().equals(DataStoreItemChange.Type.CREATE)) {
> .... update UI
> }
> ```
> 
> but it gives this exception first:
> DataStoreException{message=Not implemented yet, buster!, cause=null, recoverySuggestion=Check back later!}
> 
> do you know when it wil be implemented observe with predicates?

I'm not sure, but I created an issue #1322 to track it and will talk to the team about it.

**Comment by marenero1974** [comment]
Yes @drochetti the observe is put before populating the UI, and the item is not present, so when i do an insert with Amplifiy.Datastore.save .... in the UI it is added twice only on the first access to the table ( query or save...)

**Comment by richardmcclellan** [comment]
Hi @marenero1974, `DataStore.save(...)` does trigger two change events to `DataStore.observe(...)`.  The first is for the local save to the SQLite DB, and the second is when the API response is returned from AppSync indicating that the item is saved on the backend.    If you'd like to only respond to one of these events, you can check the value of itemChange.initiator, which will either be equal to `DataStoreItemChange.Initiator.REMOTE`, or `DataStoreItemChange.Initiator.LOCAL`.  Here is some sample code which does this: https://github.com/richardmcclellan/amplify-android-samples/blob/main/sample-core/sample-core/src/main/java/com/amplifyframework/sample/datastore/ListActivity.kt#L109-L116

**Comment by marenero1974** [comment]
Great @richardmcclellan, i tryied your solution, it works pretty good.
Thank you very much.
