### ISSUE TITLE
Amplify.signInWithWebUI not prompting login page for google sign-in again

### ISSUE THREAD

**Issue by umeshkanhasoft** [aws-amplify/amplify-android#1311]
**Describe the bug**
 
 I just sign in with google SSO using `Amplify.signInWithWebUI` and successfully sign in 
 Now I sign out using `Amplify.Auth.signOut` and again try to login with SSO at that time without any prompting to choose the account I get to sign in with a recent user.
 
 **Steps to reproduce the BUG:**

1.  Login with `Amplify.signInWithWebUI` (GOOGLE), I choose the account 
2. Now I log out with `Amplify.Auth.signOut`
3. Now again choose the SSO Login with GOOGLE, I could not get chooser but I get logged in with a recent user

```
Amplify.Auth.signInWithSocialWebUI(
            AuthProvider.google(), <From activity>, { 
                <Success-Response>
            }, {
                <Failure-Response>
            })
```

```
 Amplify.Auth.signOut({
            <Success-Response>
        }, {
            <Failure-Response>
        })
```

I am using the following dependency 

```
implementation 'com.amplifyframework:core:1.17.5'
implementation 'com.amplifyframework:aws-auth-cognito:1.17.5
```

**Expected behavior**
1.  Login with `Amplify.signInWithWebUI` (GOOGLE), I choose the account 
2. Now I log out with `Amplify.Auth.signOut`
3. Now again choose the SSO Login with GOOGLE, I can get the chooser screen again

This bug only resolved if I choose one of the two options

**CASE 1:** 
This bug occurs only when the mobile chrome browser has only 1 google account linked but If I just logged in 2nd google account in the mobile chrome browser at that time I can see the chooser screen while I try to log in with GOOGLE-SSO 

**CASE 2:** 
If I will clear the browser history and cookies from the mobile chrome browser, at that time also I am getting chooser screen even if I have 1 google account

**Comment by raphkim** [comment]
This issue is now resolved with [v1.17.8](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.17.8). Please follow the [updated documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android#update-androidmanifestxml) to apply this fix :)

**Comment by umeshkanhasoft** [comment]
@raphkim as per the documentation and update the SDK version, the result not getting as expected like could not get option window to choose specific account for google SSO

**Comment by raphkim** [comment]
I apologize for prematurely closing the issue. We had resolved a related, but not identical issue with release v1.17.8, and did not realize that this specific problem has yet to be addressed. Please refer to #1368 for more information. I will close this issue for now in favor of newer issue for the sake of removing duplicate items.
