### ISSUE TITLE
Failed to start datastore

### ISSUE THREAD

**Issue by oras** [aws-amplify/amplify-android#1315]
Hi, I am using the following versions:
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=1400000
Non-Bundled Plugins: com.thoughtworks.gauge, com.intellij.lang.jsgraphql, org.intellij.plugins.markdown, name.kropp.intellij.makefile, BashSupport, org.siprop.android.opencl.OpenCLCLGenerator, PythonCore, aws.toolkit

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'com.amplifyframework:aws-analytics-pinpoint:1.17.5'
    implementation 'com.amplifyframework:aws-api:1.17.5'
    implementation 'com.amplifyframework:aws-auth-cognito:1.17.5'
    implementation 'com.amplifyframework:aws-datastore:1.17.5'
    implementation 'com.amplifyframework:aws-predictions:1.17.5'
    implementation 'com.amplifyframework:aws-storage-s3:1.17.5'
    implementation 'com.amazonaws:aws-android-sdk-apigateway-core:2.15.0'

    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.10'
}

In most of times all the queries was done successfully.
For the last weeks it's the opposite, and today doesn't work at all.
Restarting the device doesn't have any difference.

> E/LoadProgramFromDataStore: Could not query DataStore
>     DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}, recoverySuggestion=Retry.}
>         at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$start$9(AWSDataStorePlugin.java:253)
>         at com.amplifyframework.datastore.-$$Lambda$AWSDataStorePlugin$spoTfTgN3Jp_t82AM9A7010aSAM.accept(Unknown Source:4)
>         at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
>         at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
>         at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout$TimeOutObserver.onComplete(CompletableTimeout.java:87)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:47)
>         at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout.subscribeActual(CompletableTimeout.java:53)
>         at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
>         at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
>         at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
>         at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
>         at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}
>         at com.amplifyframework.datastore.syncengine.Orchestrator.performSynchronized(Orchestrator.java:180)
>         at com.amplifyframework.datastore.syncengine.Orchestrator.start(Orchestrator.java:152)
>         at com.amplifyframework.datastore.AWSDataStorePlugin.start(AWSDataStorePlugin.java:249)
>         at com.amplifyframework.datastore.AWSDataStorePlugin.query(AWSDataStorePlugin.java:397)
>         at com.amplifyframework.datastore.DataStoreCategory.query(DataStoreCategory.java:114)
>         at com.sysmop.dov.ProgramManager.lambda$loadProgramsFromDataStore$15$ProgramManager(ProgramManager.java:419)
>         at com.sysmop.dov.-$$Lambda$ProgramManager$Pjhdlg9d8hCHSZ_vzN0Vtto5jzI.run(Unknown Source:4)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764)_** 

Although I can see the local store using Database Inspector
![image](https://user-images.githubusercontent.com/1174496/117986681-82e21480-b342-11eb-9b9a-e6d8639d06fc.png)

I tried to @richardmcclellan commented from here:
https://github.com/aws-amplify/amplify-android/issues/802#issuecomment-690353087

```Java
Amplify.DataStore.query(Todo.class, result -> { /* ignore this result */ }, error -> { });        
Amplify.Hub.subscribe(HubChannel.DATASTORE, 
    hubEvent -> DataStoreChannelEventName.READY.toString().equals(hubEvent.getName()), 
    hubEvent -> Amplify.DataStore.query(Todo.class, result -> { /* expect the actual results here */ }, error -> { })
);
```

But same result:

> _**Data store connection failed**_

> _**message=Timed out acquiring orchestrator lock**_

Please help

**Comment by richardmcclellan** [comment]
Hi @oras, could you share your code, or at least describe which `Amplify.DataStore` methods you are using, and in what order you are calling them?   Without your code, I'm not able to reproduce this issue.

**Comment by oras** [comment]
Hi @richardmcclellan thanks for your replay,

Amplify.Hub.subscribe(HubChannel.DATASTORE,
                    hubEvent -> handleDataStoreEvents(hubEvent.getName()),
                    hubEvent -> handleDataStoreEvents(hubEvent.getName()));

hubEvent.getName() return  "OutboxStatus"

**Comment by oras** [comment]
?
