### ISSUE TITLE
Handle push notification through Amplify lib 

### ISSUE THREAD

**Issue by AntoEko** [aws-amplify/amplify-android#1327]
It seems there's no way to handle push notification with PinPoint through the Amplify lib directly. We must use the old one, the AWSMobileClient. 

Is there anything plan to use this with Amplify directly?

**Comment by richardmcclellan** [comment]
At some point we would like to add support for this, but we don't have any timelines yet.    For now, please use the SDK ([documentation](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/android#connect-to-your-backend))

**Comment by abdallahshaban557** [comment]
Hi @AntoEko - we are working on enabling push notifications from the Amplify Android library in the near future! What are the use cases you are wanting to use it for?

**Comment by abdallahshaban557** [comment]
Hi @AntoEko  - I wanted to inform you that we now have support for push notifications from the Amplify Android library! Would you be willing to give it a try and let us know what you think? https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/android/
