### ISSUE TITLE
REST API- API Gateway does not exist

### ISSUE THREAD

**Issue by orhna** [aws-amplify/amplify-android#1334]
1. "The current version of the Amplify CLI will create classes intended for use with the AWS SDK for Android in your project. If you see compilation errors relating to com.amazonaws.mobileconnectors.apigateway.annotation, please delete the directory with the name of your API in Android Studio.". My problem is mentioned in the Getting Started page of API(REST). It gives the exact error but as a solution, deleting the directory with the name of my API does not work. The app crashes in VM and there is no relevant log about POST request.

2. 4.51.2 Amplify CLI version

3. ```java 
      try {

            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSApiPlugin());
            Amplify.configure(getApplicationContext());

            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
        }```

4. `C:\Users\calip\Desktop\Todo\app\src\main\java\orhunapi\OrhunapiClient.java:22: error: package com.amazonaws.mobileconnectors.apigateway.annotation does not exist
@com.amazonaws.mobileconnectors.apigateway.annotation.Service(endpoint = "https://a87921ease.execute-api.eu-west-1.amazonaws.com/dev")
                                                     ^
C:\Users\calip\Desktop\Todo\app\src\main\java\orhunapi\OrhunapiClient.java:31: error: package com.amazonaws.mobileconnectors.apigateway does not exist
    com.amazonaws.mobileconnectors.apigateway.ApiResponse execute(com.amazonaws.mobileconnectors.apigateway.ApiRequest request);
                                                                                                           ^
C:\Users\calip\Desktop\Todo\app\src\main\java\orhunapi\OrhunapiClient.java:31: error: package com.amazonaws.mobileconnectors.apigateway does not exist
    com.amazonaws.mobileconnectors.apigateway.ApiResponse execute(com.amazonaws.mobileconnectors.apigateway.ApiRequest request);
                                             ^
C:\Users\calip\Desktop\Todo\app\src\main\java\orhunapi\OrhunapiClient.java:38: error: package com.amazonaws.mobileconnectors.apigateway.annotation does not exist
    @com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/todo", method = "OPTIONS")
                                                         ^
C:\Users\calip\Desktop\Todo\app\src\main\java\orhunapi\OrhunapiClient.java:46: error: package com.amazonaws.mobileconnectors.apigateway.annotation does not exist
    @com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/todo/{proxy+}", method = "OPTIONS")`

5. [guide](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/android#configure-api)

**Comment by poojamat** [comment]
Have tried to invalidate cache and restart?

**Comment by orhna** [comment]
I have tried yes, but it did not help. I gave up using Amplify because I had limited time to implement what I needed so I'm closing the issue.
