### ISSUE TITLE
AmazonS3Exception: The specified key does not exist

### ISSUE THREAD

**Issue by oras** [aws-amplify/amplify-android#1335]
Hi, I am using the following versions:
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=1400000
Non-Bundled Plugins: com.thoughtworks.gauge, com.intellij.lang.jsgraphql, org.intellij.plugins.markdown, name.kropp.intellij.makefile, BashSupport, org.siprop.android.opencl.OpenCLCLGenerator, PythonCore, aws.toolkit

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation 'androidx.appcompat:appcompat:1.2.0'
implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
testImplementation 'junit:junit:4.12'
androidTestImplementation 'androidx.test.ext:junit:1.1.2'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
implementation 'com.google.android.material:material:1.3.0'
implementation 'com.amplifyframework:aws-analytics-pinpoint:1.17.5'
implementation 'com.amplifyframework:aws-api:1.17.5'
implementation 'com.amplifyframework:aws-auth-cognito:1.17.5'
implementation 'com.amplifyframework:aws-datastore:1.17.5'
implementation 'com.amplifyframework:aws-predictions:1.17.5'
implementation 'com.amplifyframework:aws-storage-s3:1.17.5'
implementation 'com.amazonaws:aws-android-sdk-apigateway-core:2.15.0'

// Support for Java 8 features
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.10'
}

Using the following code failed all time
"**AmazonS3Exception: The specified key does not exist**"

```Java
Amplify.Storage.downloadFile(
                "updates/info.txt",
                new File(mActivity.getApplicationContext().getFilesDir() + "/updates/info.txt"),
                result -> Log.i("MyAmplifyApp", "Successfully downloaded: " + result.getFile().getName()),
                error -> Log.e("MyAmplifyApp",  "Download Failure", error)
        );

```
I set access public without restrict, but only using the following direct link working:
https://app91812-dev.s3.eu-central-1.amazonaws.com/updates/info.txt

Although the key is same (Marked in red)
![image](https://user-images.githubusercontent.com/1174496/119366046-3939e800-bcb9-11eb-86aa-0a34f0ae6142.png)

And permissions set to public include internet
![image](https://user-images.githubusercontent.com/1174496/119365600-c2045400-bcb8-11eb-9b5d-2db9f8deedfb.png)
And bucket also public
![image](https://user-images.githubusercontent.com/1174496/119365797-fbd55a80-bcb8-11eb-958e-b36ec98d690c.png)

The bucket has been created locally using the CLI with application,
Also amplifyconfiguration.json include the backet:
```Json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "DOV": {
                    "endpointType": "REST",
                    "endpoint": "https://stpi.eu-central-1.amazonaws.com/dev",
                    "region": "eu-central-1",
                    "authorizationType": "AWS_IAM"
                },
                "dovaws": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://3xy.appsync-api.eu-central-1.amazonaws.com/graphql",
                    "region": "eu-central-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-central-19",
                            "Region": "eu-central-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-central-1_HaJ4Bk62T",
                        "AppClientId": "3cs7",
                        "Region": "eu-central-1",
                        "AppClientSecret": "6asfkl80t6osak"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://3xomny.appsync-api.eu-central-1.amazonaws.com/graphql",
                        "Region": "eu-central-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "dovaws_AMAZON_COGNITO_USER_POOLS"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "app91812-dev",
                        "Region": "eu-central-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "app91812-dev",
                "region": "eu-central-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}
```

Please help thanks

**Comment by raphkim** [comment]
Hi, it seems that you are using trying to access an item that was not uploaded using Amplify. When Amplify Storage uploads an item to the bucket, it uses a specific prefix designed to keep track of the object's permission level (e.g. "public/updates/info.txt" or "private/<id>/updates/info.txt"). 

You can either re-upload these files with desired key (Amplify will prepend the access level automatically), or manually update the objects' keys using valid prefixes.

**Comment by oras** [comment]
Hi sorry what is prefix? and how I can use it?

**Comment by richardmcclellan** [comment]
Hi @oras, currently the Amplify library is only able to access S3 files with the predefined prefixes, as described [here](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/android).    As long as your files are added to S3 via `Amplify.Storage.uploadFile` or `Amplify.Storage.uploadInputStream`, these prefixes are added automatically.  

We are working on making this more customizable, so you can access files with an arbitrary path.  Closing in favor of https://github.com/aws-amplify/amplify-android/issues/910.
