### ISSUE TITLE
Why AWS Cognito & Amplify does not follow OpenID logout?

### ISSUE THREAD

**Issue by sundeepkmallick** [aws-amplify/amplify-android#1344]
1. I want to perform Single Sign In, Single Sign Out & Token Refresh for my mobile application using Cognito. I am using [AppAuth SDK](https://github.com/openid/AppAuth-Android) for it. The Single Sign Out does not work because Cognito does not support [OpenID  Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RedirectionAfterLogout)
2. I am using AppAuth Android SDK and understood AWS Cognito does not implement Open ID and so Amazon Amplify Android SDK.

May I know is there any specific reason/pain point why Amazon does not want to follow Open ID Logout? Is it possible if I integrate Amazon Amplify, it will support other vendors who follows Open ID for Logout?

**Comment by gpanshu** [comment]
Hello, 
AWS Amplify supports openID. Here is a blogpost related to that to help you setup it up https://aws.amazon.com/blogs/mobile/building-an-application-with-aws-amplify-amazon-cognito-and-an-openid-connect-identity-provider/ 

When you do an endSession via openID you can provide a redirectURI that gets called on your application. At that time you can call Amplify signout function.

Feel free to re-open this if this does not solve your problem.
