### ISSUE TITLE
Handle timeout in uploading the file 

### ISSUE THREAD

**Issue by tauqeermajeed0081** [aws-amplify/amplify-android#1348]
How to handle timeout in Amplify
I want to upload a file to AWS using Amplify Android Sdk but due to time out the file can't be uploaded and shows a timeout error in console.
```
Amplify.Storage.uploadInputStream("ExampleKey", stream,
{ LoggerUtils.info(TAG, "Successfully uploaded: ${it.key}") },
{ LoggerUtils.error(TAG, "Upload failed", it) }
)
```
It should be uploaded to the server but the timeout is only 10 secs by default. I want to increase it to upload large files to the server.

**Comment by raphkim** [comment]
Hi @tauqeermajeed0081 , we are currently working on a fix to make uploads more stable. Thank you for your patience!

**Comment by richardmcclellan** [comment]
Automatic retry on timeout was added in the latest release ([Amplify Android 1.20.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.20.0).  Please try it out and let us know if it solves your issue!
