### ISSUE TITLE
PUT, PATCH, POST requests throw error if no body

### ISSUE THREAD

**Issue by ragingsquirrel3** [aws-amplify/amplify-android#1355]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

REST API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
com.amplifyframework:aws-api:1.17.4

```

</details>

### Environment information

<details>

```
# Put output below this line

getting this in flutter so not sure this is applicable 
```

</details>

### Describe the bug

see https://github.com/aws-amplify/amplify-flutter/issues/612

This comes from running through the flutter library, but when calling PATCH with no body (data field in `RestOptions`) I get an error that crashes flutter. I believe the same error exists for PUT and POST, maybe some others that would be expected to have body. Bc HTTP spec does not require this, and ios does not force this, I think this should be allowed.

```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.amazonaws.amplify.amplify_api_example, PID: 813
    java.lang.IllegalArgumentException: method PATCH must have a request body.
        at okhttp3.Request$Builder.method(Request.kt:254)
        at com.amplifyframework.api.aws.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:237)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/Process: Sending signal. PID: 813 SIG: 9
```

### Reproduction steps (if applicable)

see https://github.com/aws-amplify/amplify-flutter/issues/612

### Code Snippet

```java
// Put your code below this line.
Amplify.API.patch( ... request with no body 
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by poojamat** [comment]
The okHttp dispatcher does not take null request body. Please pass in an empty request body. You can refer to the post: 
https://stackoverflow.com/questions/35743516/how-to-make-okhttp-post-request-without-a-request-body

**Comment by ragingsquirrel3** [comment]
Thanks for info. Good to know that's the best option (although kinda bummer bc HTTP spec should allow for no body there).
