### ISSUE TITLE
 s3Client.generatePresignedUrl is slow

### ISSUE THREAD

**Issue by qwaskhaled** [aws-amplify/amplify-android#1362]
Hi there, I am using this SDK for generating signed URLs for my s3 resources. However, it seems to be slow and it takes about 50 ms to generate a signed URL.

Is there any way I can improve that?

**Comment by changxu0306** [comment]
I think this question is not regarding our library, but s3 service.

**Comment by poojamat** [comment]
Please provide the following info:
  - The version of amplify API's
  - The code snippet where you are experiencing the slowness.
Alternatively you can also use the the amplify method which provides this functionality.
```
Amplify.Storage.getUrl(
    "ExampleKey",
    result -> Log.i("MyAmplifyApp", "Successfully generated: " + result.getUrl()),
    error -> Log.e("MyAmplifyApp", "URL generation failure", error)
);
```
Here is the link to the documentation:  https: //docs.amplify.aws/lib/storage/download/q/platform/flutter
