### ISSUE TITLE
Can't continue with reset password after killing the app

### ISSUE THREAD

**Issue by mpaduchh** [aws-amplify/amplify-android#1363]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, RxJava

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```
    private const val amplifyVersion = "1.17.5"
    val amplify = arrayOf(
        "com.amplifyframework:aws-auth-cognito:$amplifyVersion",
        "com.amplifyframework:rxbindings:$amplifyVersion"
    )

```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

Hi,
We are trying to integrate amplify/cognito for user auth and we face an issue when doing reset password.

Our flow is like this:

1. Call `resetPassword()`
2. User gets an email with a deeplink containing the code
3. Click the link, open the app, redirect to page where user can set password
4. Call `confirmResetPassword(code, newPassword)`

Now the issue is - When a user closes the app after step 2 but before 3, we loose the session and get the 
`ava.lang.IllegalStateException: confirmForgotPassword called before initiating forgotPassword`

Is our flow correct?
If yes, what should we do in such scenario? Do you guys expect users not to kill the app? It might happen for many many many reasons.
Is there a way around this right now?

**Comment by changxu0306** [comment]
Hi @mpaduchh ,
Thanks for reporting the issue. Our team gonna take some time to reproduce it, and sync up with iOS team to make the behavior consistent.
