### ISSUE TITLE
Problem handling guest access

### ISSUE THREAD

**Issue by fabiano-alves-dev** [aws-amplify/amplify-android#1391]
Hi everyone. 
In my app I need that unauthenticated users be able to read a type but need to signed in to create or modify it.
To achieve that I did the following:

I configured my auth to allow unauthenticated logins, following the steps in this documentation [https://docs.amplify.aws/lib/auth/guest_access/q/platform/android](url) 

I configured my graphQL Api with Amazon cognito user pool as the default authorization type and IAM as additional authorization.

defined my type in schema.graphql this way
```java
type Property @model\
@auth (
rules: [
        { allow: owner, operations: [create, update, delete, read]}
        { allow: private, operations: [create, read] }
        { allow: public, operations: [read], provider: iam }
    ]
)
@key(name: "propertiesByPrice" fields: ["modelType", "price"] queryField: "propertiesByPrice")
@key(name: "propertiesByLot" fields: ["modelType", "lot"] queryField: "propertiesByLot")
{
    id: ID!,
    imageUrl: String,
    offerType: OfferType,
    price: Int,
    type: PropertyType,
    rooms: Int,
    bathrooms: Int,
    parkingSpace: Int,
    lot: Int,
    state: String,
    city: String,
    neighborhood: String,
    street: String,
    number: String,
    zipCode: String
    modelType: String
}
```

So the guest users will be able to read the type Property but need to be signed in to create one and need to be the owner to modify it.

For test I'm making the following query

```kotlin
Amplify.API.query(ModelQuery.list(Property::class.java),
                { result ->
                    Log.i(TAG, "listProperties: succeeded $result")
                },
                { exception ->
                    Log.e(TAG, "listProperties: failed $exception")
                })
```
I get the right response when I'm signed in but when I try to run it as guest i get the following error

**W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
W/AWSMobileClient: signalTokensNotAvailable**

Looks like it tries to make the query with cognito as authorization mode because it's my default authorization. If I change the default authorization mode to IAM and cognito as additional authorization mode I'm able to make the query as guest but it stops working as signed in user. Is there anything else I need to configure? Thanks in advance

**Comment by fabiano-alves-dev** [comment]
I made some changes in my **amplifyconfiguration.json** and now I'm able to specify which authorization mode I'd like to make the request.

```   "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "imovelapp": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://*****/graphq",
                    "region": "sa-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "imovelapp_IAM": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://*****/graphql",
                    "region": "sa-east-1",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    },
```
I added another awsAPIPlugin and changed the authorizationType to AWS_IAM. Now when I run Amplify.API.query i can specify the api name and choose one or another depending if the user signed in or not, and now it works.
```kotlin
Amplify.API.query(apiName, ModelQuery.list(Property::class.java),
                { result ->
                    Log.i(TAG, "listProperties: succeeded $result")
                },
                { exception ->
                    Log.e(TAG, "listProperties: failed $exception")
                })
```
 I'd like to know if this is really the right approach or if there's a better way to do it. All I could find in the documentation about guest access for Android was this [https://docs.amplify.aws/lib/auth/guest_access/q/platform/android](url)

**Comment by poojamat** [comment]
@fabiano-alves-dev your schema looks correct. The docs suggest that ["iam is specified as the provider which allows you to use an "Unauthenticated Role" from the Cognito identity pool for public access instead of an API Key. When you run amplify add auth, the Amplify CLI generates scoped down IAM policies for the "Unauthenticated role" in Cognito identity pool automatically."](https://docs.amplify.aws/cli/graphql/authorization-rules/#public-data-access) I wonder if you added auth before you added schema so your IAM policies for your unauthenticated user didn't get generated.
