### ISSUE TITLE
[DataStore] Unauthorized errors should be ignored in SyncProcessor

### ISSUE THREAD

**Issue by richardmcclellan** [aws-amplify/amplify-android#1394]
Currently, when a sync request returns an `Unauthorized` error for one of the models, the sync engine is stopped. 
 This is not ideal, because if an `Unauthorized` error occurs with just a subset of types, we shouldn't prevent customers from making being able to sync and query for the other types.   Instead, we should catch the errors and move on to sync the next model.

The JS library already behaves this way (see [this code reference](https://github.com/aws-amplify/amplify-js/blob/dedd5641dfcfce209433088fe9570874cd810997/packages/datastore/src/sync/processors/sync.ts#L135))

**Comment by mattcreaser** [comment]
This was fixed in #2561
