### ISSUE TITLE
Amplify.Auth.currentUser sporadically returns null for guest access

### ISSUE THREAD

**Issue by devShdKhan** [aws-amplify/amplify-android#1402]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication, Analytics

### Gradle script dependencies

<details>

```groovy
// Put output below this line
 
implementation 'com.amplifyframework:core:1.18.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.18.0'
implementation 'com.amplifyframework:aws-analytics-pinpoint:1.18.0'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When I am updating the User Identity it is showing the current user is null. 

### Code Snippet

```java
UserProfile profile = UserProfile.builder()
                .name(loginResponse.Name)
                .email(loginResponse.Email)
                .location(location)
                .build();
        String userId = Amplify.Auth.getCurrentUser().getUserId();
        Amplify.Analytics.identifyUser(userId, profile);

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by div5yesh** [comment]
@devShdKhan Unauthenticated users are not allowed access to the current user. To fetch identity associated with guest access use `fetchAuthSession`. Refer https://docs.amplify.aws/lib/auth/guest_access/q/platform/android for more info.

Let us know if this works for you.
