### ISSUE TITLE
Datastore save success followed by OutputMutationFailed

### ISSUE THREAD

**Issue by PS-MS** [aws-amplify/amplify-android#1405]
**Describe the bug**
Through user error, if the type schema and input schema doesn't match then on calling Amplify.DataStore.save() the save will complete successfully locally but fail on attempting to sync.

This causes some misleading behaviour as the app is unaware that an error has occurred, turning on verbose debugging also shows "I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation" which I think then means the data will never attempt to sync again.

**To Reproduce**
1. Set up a model type and input class as shown under Screenshots (the screenshot shows a type used within a @model type)
2. Call Amplify.DataStore.save(type) and observe a "success" callback
3. DynamoDB won't have updated to match as the input doesn't match, however the local data is stored.

**Expected behavior**
While this is user error, I would expect one or more of the following solutions:
1) The save to fail (to allow instant)
2) A Datastore Event for OutboxMutationFailed (to allow for subscription/reaction)
3) The data to be included in the next sync.

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/86309141/124920311-1bb5a900-dfef-11eb-90c6-9daaae8c45be.png)

**Comment by richardmcclellan** [comment]
Hi @PS-MS, the actual behavior is actually (2).  DataStore publishes an [`outboxMutationFailed` event](https://github.com/aws-amplify/amplify-android/blob/682c9e778adac74c2261bce4de4866c5e255a5eb/core/src/main/java/com/amplifyframework/datastore/DataStoreChannelEventName.java#L74) for this scenario.     The payload contains the original model that failed to be published, so you can retry if desired.

I just realized that this particular event is not documented [here](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/android) though, so I will leave this ticket open until we can add that documentation.
