### ISSUE TITLE
Failed Since user is not authorized Error message on Sign in.

### ISSUE THREAD

**Issue by iamAliRaza** [aws-amplify/amplify-android#1408]
Hi Guyz,

I am building an Android app using amplify..

i configured everything using CLI and pushed my project on Bitbucket.
I am already done with Authentication and i created many user's on cognito everything was working perfectly.

Now i just got new Macbook. I cloned my project on my new machine. 
Installed Amplify CLI.

On project root >> i run this command amplify pull --appId <my-app-id> --envName dev

and i got all the changes that was already in the project >> it just configured my CLI..

The problem i am facing now i build my app with my new machine and trying to login with existing users Its keep showing this error message **Failed Since user is not authorized**

I don't know what's the problem >> users are present on Cognito >> and they are verified users..

_Sign up and Sign in new users working fine >> What's the problem with existing users._

**Comment by div5yesh** [comment]
Please you share the error message/exception and logs.

You can turn on the debug and verbose logs by using the below statement in your app.

```java
Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
```

You also can enable [developer](https://docs.amplify.aws/lib/debugging/dev-menu/q/platform/android) menu to provide more info for us.

**Comment by iamAliRaza** [comment]
It was because of wrong password... Amplify Error messages are quite ambiguous :( Before i tested in case of wrong password it was not giving me this error message .. _**Failed Since user is not authorized**_
