### ISSUE TITLE
DataStore.start() & sync Selective data not working on app startup even after login.

### ISSUE THREAD

**Issue by iamAliRaza** [aws-amplify/amplify-android#1409]
The problem is i need to check if the user data already exist or not in database on app startup In case user uninstalled the app or he changed his device and want to use app on new device. So at that time i need to check his previous data.

But the problem is datastore query is always giving me **_No Data_** because the sync from cloud to local is not happening.
According to documentation Sync would happen when user will call any of datastore method or otherwise he explicitly need to call Datastore.start() method.

One of the biggest **_headache_** is none of the service/method/operation works before **_login_**. Like if i want to sync my database from cloud i must need to login myself. What if i want to query some data right after login so i need to wait for sync then i can query data. 

Besides it. Even i am calling Datastore.start() after login is not working not syncing any data. The only way to start sync is to use Datastore.query() or any other method of datastore. So it would start sync but first time it will also come with empty data because sync is happening in background not completed yet.

So what next i need to listen datastore events when  **_ready_** callback will execute.. Oh now this is the time to run query again and you can get data. That's a long way What user will do meanwhile..

-----------

So i tried another way on app startup in application class where i am setting my all plugins i tried to fetch just user's table but again no luck nothing happening.

```
try {
            Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
            **Amplify.addPlugin(AWSDataStorePlugin.builder().dataStoreConfiguration(
                DataStoreConfiguration.builder().syncExpression(
                User::class.java
            ) {
                QueryPredicates.all()
            }.build()).build())**
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.configure(applicationContext)
            Log.i("MyAmplifyApp", "Initialized Amplify")
        } catch (error: AmplifyException) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
        }
```
So the end solution is drop datastore and call directly Amplify.API.list()... it working fine but again not a good thing.

```
override fun fetchUserData(email: String) {
        Amplify.API.query(ModelQuery.list(User::class.java, User.EMAIL.eq(email)), {
            when {
                it.hasData() -> {
                    it.data.forEach { user ->
                        AppPreference.saveUserData(
                            user.id,
                            user.username,
                            user.userImage,
                            user.email
                        )
                        AppPreference.saveProfileDataStatus(true)
                        _userLiveDataState.postValue(DataState.success(user))
                    }
                }
                it.hasErrors() -> {
                    it.errors.forEach { error ->
                        _userLiveDataState.postValue(DataState.error(error.message))
                    }
                }
                else -> _userLiveDataState.postValue(DataState.error("No Record Found!"))
            }

        }, {
            _userLiveDataState.postValue(DataState.error(it.message ?: it.toString()))
        })
    }
```

**Comment by richardmcclellan** [comment]
> According to documentation Sync would happen when user will call any of datastore method or otherwise he explicitly need to call Datastore.start() method.

This is correct - the sync process is _started_ by calling any DataStore method, but it does not wait until the sync process _completes_.  The success callback returns immediately with whatever is in the SQLite DB at that time, so that you can display cached data on your UI.   I completely understand this is not the best experience and we are actively working on a better solution.  Specifically, you will be able to receive updates as the sync is occurring, and when it is completed, without having to listen for the "ready" event.

> So i tried another way on app startup in application class where i am setting my all plugins i tried to fetch just user's table but again no luck nothing happening.

By default, DataStore syncs all models, so in order to only sync your `User` type, you need to to _disable_ syncing of all of your other types.  There is not a way to prevent a sync request from happening at all, but if you choose a predicate that you know will not match any results (such as id equal to an empty string) , that will prevent that model from syncing:
```
Amplify.addPlugin(AWSDataStorePlugin.builder().dataStoreConfiguration(
    DataStoreConfiguration.builder()
        .syncExpression(OtherModel1::class.java) { OtherModel1.ID.eq("") }
        .syncExpression(OtherModel2::class.java) { OtherModel2.ID.eq("") }
        .syncExpression(OtherModel3::class.java) { OtherModel3.ID.eq("") }
        .build()
    )
    .build()
)
```

**Comment by iamAliRaza** [comment]
ok so according to my understanding by default it sync all the models if i just want to sync selective data i need to do like above you mentioned... But Still would it wait for Datastore.Start() method or any other DataStore method to start syncing??
And if yes then on later stage how i can get whole copy of cloud db ??

**Comment by iamAliRaza** [comment]
@richardmcclellan One more thing that i wanna share i m calling  Datastore.Start() method on a button click for starting synchronization process and i am continuing my work in the ready event callback like checking user stuff in local DB and then proceeding . i realize that after sync had been done second time if i am calling Datastore.Start() method its not triggering **READY** callback ?? Is it default behaviour i mean if the sync is done already so next time we can't use Datastore.start()

**Comment by richardmcclellan** [comment]
> And if yes then on later stage how i can sync whole copy of cloud db ??

To re-sync the entire cloud db, you can force a re-evaluation of sync expressions by calling `DataStore.stop(...)` followed by `DataStore.start(...)`.  See [this documentation](https://docs.amplify.aws/lib/datastore/sync/q/platform/android#reevaluate-expressions-at-runtime) for an example.

> i realize that after sync had been done second time if i am calling Datastore.Start() method its not triggering READY callback ??

If you call `DataStore.start()`, and DataStore is already started, it will not resync, and thus will not fire the `READY` event.  To account for this, when you receive the `READY` event, you should store this.  Then, the next time you want to check user stuff, you can skip calling `DataStore.start(...)` and waiting for `READY`.  Just call `DataStore.query(...)` right away.  I realize this is overly complicated - we are actively working on a better API so this is easier to use.

**Comment by iamAliRaza** [comment]
@richardmcclellan Yup i am exactly doing the same.. Thanks
