### ISSUE TITLE
Data Access Pattern / Data Filtration doesn't work on type Array 

### ISSUE THREAD

**Issue by iamAliRaza** [aws-amplify/amplify-android#1420]
Hy Guyz.. I have a quick question. From last 2 days i am struggling with it. I am not a amplify GraphQL / datastore Expert.. 
But soon will be... 😄 

I created GraphQL model:

```
type EventPost @model @auth(rules: [{ allow: private }]){
    id:ID!
    postImage:String
    caption:String
    startDate:String
    endDate:String
    cost:Int
    paymentLink:String
    location : String
    about : String
    categories : [String]
    danceStyles : [String]
    user : User @connection
}
```

Here you can see i have a list of categories and danceStyles now i want to filter posts according to categories and danceStyles. How i can do ??

Currently i have this data set for the danceStyles example : danceStyles : ["HipHop", "Bollywood Dance", "FreeStyle", "Folk Dance", "Other"]

So while creating post danceStyle is a dropdown menu. Where user can select multiple danceStyles.

Later i want to filter posts according to these danceStyles... Example i need to get all posts that have danceStyle HipHop and FreeStyle How i can do this...  

I tried with @Key directive but data access pattern doesn't work  on <Array type>
Currently i saved all the danceStyles locally in the array. Do i need to create a table for it ????

What's the best Solution Anyone ????

**Comment by richardmcclellan** [comment]
Hi @iamAliRaza!  If you want to make direct calls to your GraphQL API, you can use `Amplify.API` to accomplish what you want like this:
```
Amplify.API.query(
    ModelQuery.list(Queue.class, Queue.QUEUE_SEEDS.contains("HipHop").and(Queue.QUEUE_SEEDS.contains("FreeStyle"))),
    response -> { Log.i(TAG, "Query response: " + response) },
    error -> { Log.e(TAG, "Query failed.", error) }
);
```

If you want your data to be persisted locally, you can use `Amplify.DataStore` and do something like this:

```
Amplify.DataStore.query(EventPost.class,
    EventPost.DANCE_STYLES.contains("HipHop").and(EventPost.DANCE_STYLES.contains("FreeStyle")), 
    response -> { Log.i(TAG, "Query response: " + response) }, 
    error -> { Log.e(TAG, "Query failed.", error) }
);
```

**Comment by iamAliRaza** [comment]
@richardmcclellan Excellent... i am working on a big project and i am heavily using AWS Amplify almost all services inside it.... 

Instead of local danceStyle array i want to save it in database So it will be dynamic... I created a model of it like below....

type DanceStyle @model @auth(rules: [{ allow: private }]){
    id:ID!
    name : String!
}


Now the EventPost Model will be...

type EventPost @model @auth(rules: [{ allow: private }]){
    id:ID!
    postImage:String
    caption:String
    startDate:String
    endDate:String
    cost:Int
    paymentLink:String
    location : String
    about : String
    categories : [String]
    **_danceStyles : [DanceStyle]_**
    user : User @connection
}

Now how we can solve the same problem with this change ?? I mean i need to get all posts that have danceStyle HipHop or FreeStyle How i can do this...

**Comment by richardmcclellan** [comment]
I don't believe there is a good way to perform that query if you put `DanceStyle` in a separate table.   It would be much easier to perform your queries with the first approach you mentioned.  

AWS AppSync (the GraphQL service) is backed by DynamoDB, which does not support table joins by design.  I'd suggest reviewing [Data Access Patterns](https://docs.amplify.aws/cli/graphql-transformer/dataaccess) for some examples of how to design a complex schema.

**Comment by iamAliRaza** [comment]
@richardmcclellan ok i understand.. But according to documentation here ..

https://docs.amplify.aws/cli/graphql-transformer/relational

We can also connect Amazon Aurora MySQL with Amplify API .. So if i will switch my backend from dynamoDB to Amazon Aurora MySQL... So then is it possible to do that??  if yes can you share any example with me.... 

Any link and code snippet?

**Comment by poojamat** [comment]
@iamAliRaza Are you intending to use  Amplify.API or Amplify.Datastore?

**Comment by iamAliRaza** [comment]
@poojamat Amplify Datastore

**Comment by poojamat** [comment]
Unfortunately we don't have a convenient method to support it right now. As a work around to achieve this some users have chained the query predicate dynamically looping through the list of values. I will put in a feature request for it and hopefully we will implement it soon.
