### ISSUE TITLE
Data Loss Issue when Data Update is done using Amplify GraphQL API

### ISSUE THREAD

**Issue by AmitGupta1994** [aws-amplify/amplify-android#1424]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    implementation 'com.google.android.material:material:1.4.0'

    // Amplify core dependency
    implementation 'com.amplifyframework:core:1.22.0'
    implementation 'com.amplifyframework:aws-api:1.22.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.22.0'

    testImplementation 'junit:junit:4.+'

    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_291 (Oracle Corporation 25.291-b10)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

 - https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/android       
 - https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android

### Describe the bug

**Data Loss Issue when Update is done using Amplify API (GraphQL + AppSync)**
When the data for a particular model say “Employee” is updated using Amplify.API.mutate(), then instead of preserving the existing data and updating the new sent data, it is replacing the whole data with the new sent one. For example, if the Employee of id(xyz) already has “name” and “age”, then when I only try to update the “name”, and thus send the “id” and “name”, from the client-side, then instead of only updating the “name” and leaving "age" like it was, the “age” data is being lost/removed and thus the new data is dynamo DB only contains “id” and “name” field, not the “age” field.

Note: DataStore is disabled for the entire API and thus _version is not used. However, using _version and sending the _version from the android client-side solves this data update/loss issues, but adding the _version in the schema.graphQL itself creates issues on the Android side while doing the “amplify push”. (Will explain this in detail if needed, but currently want to focus on updating the data without the need of sending the “_version” from the client.)
 
 Also, Note 
It is working fine while updating the data from the AppSync, console and also working correctly from the Android side when I send all the data(required + non required ) using Amplify.API.mutate(), while updating “Employee”.

 
**Configuration Details**
Amplify CLI Version: 5.0.0

**DataStore is Disabled for Entire API. And transform.conf.json contains the following**
{
   "Version": 5,
   "ElasticsearchWarning": true
}

Use of command “amplify codegen models” to generate the Models.
During “amplify add api” Multiple Level Schema was selected and depth of 2 was used.

### Code Snippet

```java
// Put your code below this line.

```
val employee: Employee = Employee.builder().id("4bf847ab-91b9-4876-a2bd-854e9c18a9ab").name("AmitUpdated").build()

        Amplify.API.mutate(ModelMutation.update(employee),{
            runOnUiThread {
                Toast.makeText(this, "success:" + it.data.name, Toast.LENGTH_SHORT).show()
            }
        },{
            runOnUiThread {
                Toast.makeText(this, "exception:" + it.message, Toast.LENGTH_SHORT).show()
            }
        })

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "testprojectgraphqlapi": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://umxnwlalmbgfdc2wfo5drvs4ny.appsync-api.us-west-2.amazonaws.com/graphql",
                    "region": "us-west-2",
                    "authorizationType": "API_KEY",
                    "apiKey": "********"
                },
                "testProjectRestApi": {
                    "endpointType": "REST",
                    "endpoint": "https://0ai2xjh75a.execute-api.us-west-2.amazonaws.com/testprodev",
                    "region": "us-west-2",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://umxnwlalmbgfdc2wfo5drvs4ny.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "API_KEY",
                        "ApiKey": "****************",
                        "ClientDatabasePrefix": "testprojectgraphqlapi_API_KEY"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "********",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-west-2_CI9dci5uJ",
                        "AppClientId": "*************",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```
### GraphQL Schema

<details>

```graphql
// Put your schema below this line

type Department @model{
    id:ID!
    name:String
    manager:Employee @connection #managerId
}

type Employee @model{
    id:ID!
    name:String
    age:Int
}


```

</details>

### Additional information and screenshots

<img width="1366" alt="after_updating_employee_from_android" src="https://user-images.githubusercontent.com/51045268/126593938-001d5736-2400-4732-b588-420e58a644b1.png">
<img width="1367" alt="before_updating_employee" src="https://user-images.githubusercontent.com/51045268/126593950-76ae8ec8-596e-4745-86c8-e1d8d780965e.png">

**Comment by AmitGupta1994** [comment]
It should not be a datastore issue I guess because 
1. "datastore" dependency is not used in the project.
2. While doing "amplify update api", "disable datastore for entire api" is selected and used.

**Comment by rjuliano** [comment]
We currently don't support these types of partial updates directly via the API plugin. It relies on an [AppSync feature](https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html) which requires the `_version` field being present. 

That scenario requires the DataStore plugin to be used to synchronize data with the backend API.

If using DataStore is not an option, your best bet would be to load the object, modify the fields you want and then perform the mutation.

**Comment by AmitGupta1994** [comment]
@rjuliano So, any idea about when these partial update things will be supported? 

1. While using the _version(Datastore plugin), We need to keep track or simply fetch the _version before sending the Partial data and _version.

2. And if I am not using Datastore, then as you mentioned I need to load the object (by which it means to fetch/read the required data) and then modify and write it to the DB.

So, in both examples it seems to make a write to DB with Partial data, I need to make a Read. So if this is true then it means the database request is going to be increased(in some cases double).  Could you verify what I understand here is true or maybe partially true, because it going to affect the cost of the system/product?

**Comment by rjuliano** [comment]
For option 1, if you're using DataStore, that read can happen against the local data. DataStore keeps track of the version for you via its sync process.

For option 2, your assumption is correct.
