### ISSUE TITLE
Get total record count for certain query criteria

### ISSUE THREAD

**Issue by manbalagan** [aws-amplify/amplify-android#1429]
Is there a way to retrieve the record count for given query criteria using

1. Amplify Datastore/API
2. Appsync Console
3. Dynamo DB console - Instead of live count in every six hours, get count of records for given criteria

**Comment by poojamat** [comment]
Could you please better explain your use case? Do you intend to get count of the result set returned on success callback?

**Comment by manbalagan** [comment]
@poojamat  That's correct. Intention is to get the total count on results for given search criteria.

**Comment by raphkim** [comment]
Amplify DataStore currently does not support a simple scan to obtain total count of query result directly. However, it would be possible to perform a list-query with predicate and getting a count of total items returned.

Another option would be to directly query DynamoDB (there are several ways to do this I imagine, but here is [one example using the aws-cli](https://stackoverflow.com/questions/27316643/how-to-get-item-count-from-dynamodb)).

**Comment by swaroop-at-dockare** [comment]
Is there any way to get count on items in datastore or query result?
