### ISSUE TITLE
Amplify Syncexpression to sort by provided field

### ISSUE THREAD

**Issue by manbalagan** [aws-amplify/amplify-android#1430]
Problem : For chat application - for example, has 2 contacts with 5,000 messages each. If the sync expression syncMaxRecords is set to 5000, then messages from first contact gets synced and not for the second contact. 

Expectation : Messages should be synced based on creation data (SortKey), so that latest 5000 messages gets synced irrespective of contacts.

**Comment by raphkim** [comment]
Can I get code sample of what your graphQL schema and the sync expression looks like? I am under the impression that it _is_ supposed to sync based on a filter irrespective of which contact a message belongs in.

**Comment by raphkim** [comment]
Hi @manbalagan ,

I noticed that this issue has become stale now. 
If you still experiencing this issue, please feel free to re-open the issue with requested information.
