### ISSUE TITLE
 Token didn't get refresh after expiry when Amplify.FetchAuthSession is called

### ISSUE THREAD

**Issue by vishalmishra** [aws-amplify/amplify-android#1431]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Describe the bug

**Describe the bug**
Hi Team
We need to send Bearer Token to our rest API so that we can authenticate the requests in backend. So we wrote an interceptor which we attach to all retrofit calls of the API. Once this went live for most of the users it's working fine but for few users we are receiving expired token at the backend even if they have just signed in on the app.
Here is the intercept logic to get token

please help me to identify what could be the possible course of this?

**Environment Information (please complete the following information):**
 - com.amplifyframework:aws-auth-cognito:1.18.0

### Code Snippet

```java
// Put your code below this line.

@kotlin.jvm.Throws(IOException::class)
    override fun intercept(chain: Interceptor.Chain): Response {
        val request: Request = chain.request()
        return try {
            Amplify.Auth.fetchAuthSession(
                { Log.i("AmplifyQuickstart", "Auth session = $it") },
                { Log.e("AmplifyQuickstart", "Failed to fetch auth session") }
            )
            val user = Amplify.Auth.currentUser
            if (user == null) {
                throw Exception("User is not logged in.")
            } else {
                val cognitoAuthPlugin = Amplify.Auth.getPlugin("awsCognitoAuthPlugin")
                val mobileClient = cognitoAuthPlugin.escapeHatch as AWSMobileClient
                var idToken = mobileClient.tokens.idToken.tokenString
                if (idToken.isNullOrEmpty()) {
                    throw Exception("idToken is null")
                } else {
                    val modifiedRequest = request.newBuilder()
                        .addHeader(X_AWS_ID_TOKEN, "Bearer $idToken")
                        .build()
                    chain.proceed(modifiedRequest)
                }
            }
        } catch (e: Exception) {
            throw IOException(e.message)
        }
    }
    
```

**Comment by rjuliano** [comment]
You may be running into a race condition here. The call to `Amplify.Auth.fetchAuthSession` is asynchronous and may not have finished (or it fails) by the time you retrieve the tokens via the mobile client. One thing you can try to do is move the code that depends on the result of `fetchAuthSession` to run inside the `onResponse` callback of that method.

That being said, you may not need to roll your own interceptor. Have you tried using `AMAZON_COGNITO_USER_POOLS` setting as an authorization type [1]? 

[1] https://docs.amplify.aws/lib/restapi/authz/q/platform/android#cognito-user-pool-authorization

**Comment by vishalmishra** [comment]
@rjuliano I have to use my own interceptor as i need some more customisations. Also I am not able to use chain interceptor inside the onResponse of Amplify.Auth.fetchAuthSession as I need to return the modified request. I can use suspend function anyway. 

Also the main problem is some users are getting repetitive issue of token expire. Even if it have send the expired token one time, the token should get refresh next time when the user is calling new api but some user are getting expired token repeatedly.

**Comment by rjuliano** [comment]
Understood. Do you have access to application logs? Just wondering if there is any output in there that may help us troubleshoot this issue.

**Comment by vishalmishra** [comment]
@rjuliano There are no app logs. I am getting the following response after an API call from the retrofit.

**Response:**
{
    "detail": "Incorrect authentication credentials."
}
Response code: 401 Unauthorized

**At the backend:**

        try:
            jwt_data = jwt.decode(
                token,
                public_key,
                audience=self.audience,
                issuer=self.pool_url,
                algorithms=["RS256"],
            )
        except (jwt.InvalidTokenError, jwt.ExpiredSignatureError, jwt.DecodeError) as exc:
            raise TokenError(str(exc))
            
  We are getting jwt.ExpiredSignatureError exception.

**Comment by vishalmishra** [comment]
@rjuliano Any update on this. We are still facing this issue.

**Comment by changxu0306** [comment]
Hello @vishalmishra ,
According to the code snippet you give, in this line of code: `var idToken = mobileClient.tokens.idToken.tokenString`, when you call `.tokens` of mobileClient, you are actually calling `getTokens()` which is an asynchronous call. There could be a race condition that the tokens has not been returned, and it is null, but you just threw the exception that the id token is null. So your backend got a TokenError.
