### ISSUE TITLE
Getting error "AADSTS50070:Signout failed" at the time of Android app logout using Amplify library version: 1.21.0

### ISSUE THREAD

**Issue by sarika2019** [aws-amplify/amplify-android#1432]
I have integrated Cognito with a mobile application and using Amplify library, version 1.21.0. But at the time of logout, it is giving Error: "AADSTS50070:Signout failed"

Below are the cases with code snippet used:

**Case 1 :**

- Sign in invoked in SignInActivity, hosted web UI launched.
- After successful sign in, hosted web UI redirects back to our application (SignInActivity) and then starts MainActivity
- SignOut is called, hosted web UI launches and it shows error : AADSTS50070 SignOut failed. The sign out request specified a name identifier that didn't match the existing session(s). Then the error code block of Auth.signOut gets called.
- Close the app and when we try to sign in again, no credentials will be asked and it goes to success sign in callback.

**Case 2 :**

- Sign in invoked in SignInActivity, hosted web UI launched.
- After successful sign in, hosted web UI redirects back to our application (SignInActivity) and then starts MainActivity
- SignOut is called, hosted web UI launches and it successfully signs out but it doesn't redirect back to app. It stays in HostedWebUi but the error code block of Auth.signOut function gets called which is Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: Timed out while waiting for sign-out redirect response.
- Try signing in again, no credentials being asked and it goes to success sign in callback.
Amplify version : 1.21.0
Identity provider using SAML : Azure AD

**Code for sign in in SignInActivity**

```java
Amplify.Auth.signInWithWebUI(this,
    {
        runOnUiThread {
            startActivity(Intent(this, MainActivity::class.java))
        }
    },
    {
        LOG.error("Sign in failed: ${it.message}", it)
        runOnUiThread {
            Snackbar.make(
                findViewById(R.id.constraint_layout),
                "Sign in failed: ${it.message}",
                Snackbar.LENGTH_SHORT
            ).show()
        }
    }
)
```

**Code for sign out in MainActivity :**

```java
Amplify.Auth.signOut(
    {
        showToast("Signout success")
        LOG.info("sign out succeeded")
        finish()
    }
) { showToast(it.message.toString())
    LOG.error("sign out failed", it) }
```

**Android Manifest File:**
```xml
<activity
    android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="myapp" />
    </intent-filter>
</activity>
```

**amplifyconfiguration.json**

```json
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxxxxxx",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxxx",
                        "AppClientId": "xxxxx",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxx",
                            "AppClientId": "xxxxx",
                            "SignInRedirectURI": "myapp://callback",
                            "SignOutRedirectURI": "myapp://signout",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

![Error](https://user-images.githubusercontent.com/52123910/127155579-4f7d6da8-5963-43cc-a565-dc00993c4150.jpg)

**Comment by rjuliano** [comment]
I have reached out to the service team to help troubleshoot this issue.

**Comment by rjuliano** [comment]
Does your manifest file also have:

```xml
snippet from https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android#update-androidmanifestxml
<queries>
  <intent>
      <action android:name=
          "android.support.customtabs.action.CustomTabsService" />
  </intent>
</queries>
```

**Comment by akshayshankarek** [comment]
Yes , we tried adding this but the issue persist. We tried it in the latest version 1.24.0

**Comment by div5yesh** [comment]
Hope this helps.

1. To sign out of MS account when you sign out of Cognito, you need select the checkbox `Enable IdP sign out flow` in your SAML config under "Identity Provider" settings in Cognito. This will allow show the MS accounts prompt where you can sign in using a different account or reenter the password for already signed in account.
2. In my testing with web hostedUI, I found out that I always get the error `AADSTS50070` when I hit Microsoft's `/saml2` endpoint with previous `SAMLRequest` value without calling Cognito's hostedUI `logout`. It must be that Cognito is caching SMALRequest value from previous request. Although, this error occurred rarely in Android App's normal signout flow but it does happen sometimes if you call sign out immediately after signin in the App too. 
3. Regarding not redirecting to App after sign out the first time but a successful redirect on second logout could be a Cognito issue since all we do is call hostedUI's '/lougout' endpoint in Amplify. Any unsuccessful App redirect will result in `AuthServiceException: Timed out`.

**Comment by akshayshankarek** [comment]
We have enabled the IdP sign out flow but still the signout doesn't work at times. This issue occurs almost every alternate attempt of signout flow.

**Comment by div5yesh** [comment]
Below is the configuration and code that works for my sample app for successful sign in and sign out flows. Please try this out and let us know if it works.

**Note: values that require substitutions are mentioned in [ ]**

## Code Snippet

```java
try {
    Amplify.Auth.signInWithWebUI(
        this,
        result -> Log.i("AuthQuickStart", result.toString()),
        error -> Log.e("AuthQuickStart", error.toString())
    );
} catch (Exception error) {
    Log.e(TAG, error.toString());
    setText(error.toString());
}
```

## Azure Config

Identifier (Entity ID): urn:amazon:cognito:sp:[userpoolId]

Reply URL (Assertion Consumer Service URL): https://[domain].auth.us-east-2.amazoncognito.com/saml2/idpresponse

Sign on URL: -

Relay State: -

Logout Url: https://[domain].auth.us-east-2.amazoncognito.com/logout?client_id=[clientId]&logout_uri=myapp://signout/

App Federation Metadata Url: https://login.microsoftonline.com/[directoyId]/federationmetadata/2007-06/federationmetadata.xml?appid=[appId]

Login URL: https://login.microsoftonline.com/[directoyId]/saml2

Azure AD Identifier: https://sts.windows.net/[directoyId]/

Logout URL: https://login.microsoftonline.com/[directoyId]/saml2

## Cognito Config

Identity providers: Azure-AD

OAuth grant types: Authorization code grant

OpenID Connect scopes: aws.cognito.signin.user.admin email openid phone profile

Allowed callback URLs: myapp://callback/

Allowed sign-out URLs: myapp://signout/

Metadata document endpoint URL: https://login.microsoftonline.com/[directoryId]/federationmetadata/2007-06/federationmetadata.xml?appid=[appId]

Attribute Mapping: email -> http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress

Sign-out flow: Enabled

Device Tracking: Don't remember

## Request/Response Logs

| Request | Response |
|-|-|
|https://[domain].auth.us-east-2.amazoncognito.com/oauth2/authorize?client_id=[client_id]&redirect_uri=myapp%3A%2F%2Fcallback%2F&response_type=code&code_challenge=[challenge]&code_challenge_method=S256&state=[state]&userContextData=null <br> referer: android-app://com.example.sampleamplifyandroid/ |302 <br> https://login.microsoftonline.com/[directoryId]/saml2?SAMLRequest=[request]&RelayState=[state]|
|https://login.microsoftonline.com/[directoryId]/saml2?SAMLRequest=[request]&RelayState=[state]|html|
|https://login.microsoftonline.com/common/GetCredentialType |json |
|https://login.microsoftonline.com/[directoryId]/login |html |
| https://login.microsoftonline.com/kmsi |html `<form method="POST" name="hiddenform" action="https://[domain].auth.us-east-2.amazoncognito.com/saml2/idpresponse">`  |
|https://[domain].auth.us-east-2.amazoncognito.com/saml2/idpresponse | 302 <br> myapp://callback/?code=[code]&state=[state]|
|||
