### ISSUE TITLE
Cannot parse the List of Data when using Own custom GraphQL requests

### ISSUE THREAD

**Issue by AmitGupta1994** [aws-amplify/amplify-android#1438]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    // Amplify core dependency
    implementation 'com.amplifyframework:core:1.22.0'

    // Amplify plugins
    implementation 'com.amplifyframework:aws-api:1.22.0'
    implementation 'com.amplifyframework:aws-datastore:1.22.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.22.0'
    implementation 'com.amplifyframework:aws-analytics-pinpoint:1.22.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_291 (Oracle Corporation 25.291-b10)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/android#subset-of-data         https://github.com/aws-amplify/amplify-android/issues/1361

### Describe the bug

I am trying to get a List of Movie (Model) using the own custom GraphQL requests mentioned at  (I tried Fetching a single Item using the documentation and that worked fine)

https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/android

But, the issue is the documentation only shows fetching a single Item, no example is given for fetching a List of Item.
https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/android#subset-of-data

However, when searching we found the following as an Android-Amplify issue.

https://github.com/aws-amplify/amplify-android/issues/1361

It shows that using the following we can get a List of Items.

private GraphQLRequest<Todo> getListTodosRequest() {
    String document = "query listTodos { "
        + "listTodos { "
            + "items {
                + "id "
                + "name "
            + "}"
        + "}"
    + "}";
    return new SimpleGraphQLRequest<>(
            document, 
            Collections.emptyMap(),
            TypeMaker.getParameterizedType(QueryResponse.class, Todo.class) 
            new GsonVariablesSerializer());
}

class QueryResponse<T> {
      private QueryList<T> listTodos;

      public QueryList<T> getTodos() { return listTodos; }
}

class QueryList<T> {
     private Iterable<T> items;
     private String nextToken;

     public Iterable<T> getItems() { return items; }
     public String getNextToken() { return nextToken; }
}

But this also did not work for me, My code is below:
 

### Code Snippet

```java
// Put your code below this line.

 //MovieList function Defination
 private fun getMovieList(): GraphQLRequest<MovieDBFinal2> {
        val document = ("query getMovieList { "
                + "listMovieDBFinal2s(limit: 1000, filter: {Genre1: {eq: \"Animation\"}}) { "
                + "nextToken "
                + "items { "
                + "IMDB_title "
                + "} "
                + "} "
                + "} ")

        return SimpleGraphQLRequest(
            document,
            Collections.emptyMap(),
            TypeMaker.getParameterizedType(QueryResponse::class.java, MovieDBFinal2::class.java),
            GsonVariablesSerializer())
    }

    internal class QueryResponse<T> {
        private val listMovieDBFinal2s: QueryList<T>? = null

        val moviesList: QueryList<T>?
            get() = listMovieDBFinal2s
    }

    internal class QueryList<T> {
        val items: Iterable<T>? = null
        val nextToken: String? = null
    }
    
    
 //MovieList function call
        Amplify.API.query(
            getMovieList(),
            { response ->
                if (response.hasData()) {
                    Log.e("MovieList", "$response")
                }

            },
            { failure ->
                Log.e("MovieList", "Query failed.", failure)
            }
        )


```

### Log output

<details>

```
// Put your logs below this line

```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "78ffd48dd2334a9685159948354bad13",
                    "region": "us-west-2"
                },
                "pinpointTargeting": {
                    "region": "us-west-2"
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://hynz3rxvvzg2vdi7aq7kznh2ce.appsync-api.us-west-2.amazonaws.com/graphql",
                    "region": "us-west-2",
                    "authorizationType": "API_KEY",
                    "apiKey": "*****"
                },
                "machinevillageapi": {
                    "endpointType": "REST",
                    "endpoint": "https://7qbl31zi2m.execute-api.us-west-2.amazonaws.com/mvdevnew",
                    "region": "us-west-2",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://hynz3rxvvzg2vdi7aq7kznh2ce.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "API_KEY",
                        "ApiKey": "**********",
                        "ClientDatabasePrefix": "amplifyDatasource_API_KEY"
                    },
                    "amplifyDatasource_AWS_IAM": {
                        "ApiUrl": "https://hynz3rxvvzg2vdi7aq7kznh2ce.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "amplifyDatasource_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-west-2:e949fb32-897b-46dd-ab6a-60ffffde1d40",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-west-2_XYXOARXIN",
                        "AppClientId": "*******",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "machinevillagebcba4bbb-bcba4bbb-mvdevnew.auth.us-west-2.amazoncognito.com",
                            "AppClientId": "35qbgd391i0nqfvns2j202rnul",
                            "SignInRedirectURI": "https://sign.com/",
                            "SignOutRedirectURI": "https://signout.com/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "78ffd48dd2334a9685159948354bad13",
                        "Region": "us-west-2"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "us-west-2"
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line

type MovieDBFinal2 @model
@key(name: "ByImdbVotes2", fields: [ "type", "IMDB_votes" ], queryField: "getMovieDBFinal2ByImdbVotes")
@key(name: "ByImdbID", fields: [ "IMDB_id" ], queryField: "getMovieDBFinal2ByImdbID")
@key(name: "BySearchTitle", fields: [ "searchTitle" ], queryField: "getMovieDBFinal2BySearchTitle")
@key(name: "ByImdbRating", fields: [ "type", "IMDB_rating_int" ], queryField: "getMovieDBFinal2ByImdbRating")
@key(name: "ByMetaCriticRating", fields: [ "type", "RatingMetacritic_int" ], queryField: "getMovieDBFinal2ByMetaCriticRating")
@key(name: "ByRatingRottenTomatoes", fields: [ "type", "RatingRottenTomatoes_int" ], queryField: "getMovieDBFinal2ByRatingRottenTomatoes")
@key(name: "ByReleaseYear", fields: [ "type", "release_year_ms" ], queryField: "getMovieDBFinal2ByReleaseYear")
@key(name: "ByAvgRating", fields: [ "type", "avg_rating" ], queryField: "getMovieDBFinal2ByAvgRating")
{
    id:ID!
    Actors:String
    Genre1:String
    Genre2:String
    Genre3:String
    Genre4:String
    Genre5:String
    Genre6:String
    Genre7:String
    Genre8:String
    Genre9:String
    IMDB_id:String!
    IMDB_keywords:String
    IMDB_rating:String
    IMDB_title:String
    IMDB_votes:Int
    Plot:String
    RatingMetacritic:String
    RatingRottenTomatoes:String
    rating:String
    Seed:String
    Writer:String
    all_languages:String
    custom_keywords_many:String
    custom_keywords_sall:String
    poster:String
    release_year:String
    runtime:String
    searchTitle:String
    similar_ids:String
    similar_titles:String
    type:String
    userBucket:UserBucket @connection(fields: ["id"])
    watchLaterMovie:WatchLaterMovie2 @connection(fields: ["id"])
    userLikedMovie:UserLikedMovie @connection(fields: ["id"])
    userDisLikedMovie:UserDisLikedMovie @connection(fields: ["id"])
    userDeletedMovie:UserDeletedMovie @connection(fields: ["id"])
    avg_rating:Int
    IMDB_rating_int:Int
    RatingMetacritic_int:Int
    RatingRottenTomatoes_int:Int
    release_year_ms:Int
    release_year_int:Int
    is_disney: Boolean
    is_hbo: Boolean
    is_hulu: Boolean
    is_netflix: Boolean
    is_paramount: Boolean
    is_peacock: Boolean
    is_prime: Boolean
    is_showtime: Boolean
    is_starz: Boolean
}

```

</details>

**Comment by raphkim** [comment]
Hi @AmitGupta1994 ,

Please do not use a custom result type as it will confuse the serializer.
Here is a sample code that works:
```
val document = ("query ListTodos {\n" +
        "listTodos(limit: 10) {\n" +
        "items {\n" +
        "id\n" +
        "}\n" +
        "nextToken\n" +
        "}\n" +
        "}")
val queryRequest = SimpleGraphQLRequest<PaginatedResult<Todo>>(
    document,
    TypeMaker.getParameterizedType(PaginatedResult::class.java, Todo::class.java),
    GsonVariablesSerializer()
)
Amplify.API.query(
    queryRequest,
    {
        Log.i(TAG, "Successfully queried todos.")
        it.data?.items?.let { todos ->
            for (todo in todos) {
                Log.i(TAG, todo.toString())
            }
        }
    },
    { Log.e(TAG, "Failed to list todos.", it) }
)
```

**Comment by AmitGupta1994** [comment]
Thank you, now the parsing works.

But I cannot get the "nextToken" now, and also "requestForNextResult" is null.

**Comment by raphkim** [comment]
It seems that `requestForNextResult` field will be correctly generated only if the initial request was properly formatted using `AppSyncGraphQLRequest`. I opened a PR #1440 to expose the selection set setter in `AppSyncGraphQLRequest.Builder` class, which will allow you to generate a proper request object with subset functionality.

**Comment by harishanth** [comment]
Still doesn't work for me also., requestForNextResult is always null even though there are items still available. I am using `2.13.2`
