### ISSUE TITLE
Amplify Datastore Error deleting parent object from java

### ISSUE THREAD

**Issue by oleemonster** [aws-amplify/amplify-android#1449]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:core:1.24.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
6.7.1

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/datastore/data-access/q/platform/android#delete

### Describe the bug

When deleting an object that is a parent to another object the delete fails. The error does not occur when deleting an item without a child or when deleting the object through admin UI.

### Code Snippet

```java
// Put your code below this line.
Amplify.DataStore.delete(model,
                success -> {         
                    Log.i("AmplifyLog", "Deleted item: "+model);
                },
                e -> Log.e("AmplifyLog","Error delete: ",e));

```

### Log output

<details>

```
// Put your logs below this line
2021-08-16 10:08:29.263 E/AmplifyLog: Error delete: DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
type User @model @auth(rules: [{allow: public}, {allow: private}]) {
  id: ID!
  name: String!
  pass: String
  Cars: [Car] @connection(keyName: "byUser", fields: ["id"])
}

type Car @model @key(name: "byUser", fields: ["userID"]) @auth(rules: [{allow: public}, {allow: private}]) {
  id: ID!
  name: String!
  userID: ID
  Months: [Month] @connection(keyName: "byCar", fields: ["id"])
}

type Month @model @key(name: "byCar", fields: ["carID"]) @auth(rules: [{allow: public}, {allow: private}]) {
  id: ID!
  month: String!
  year: Int!
  carID: ID
  Notes: [Note] @connection(keyName: "byMonth", fields: ["id"])
}

type Note @model @key(name: "byMonth", fields: ["monthID"]) @auth(rules: [{allow: public}, {allow: private}]) {
  id: ID!
  title: String!
  mileage: Int
  location: String
  cost: Float
  date: Int
  other: String
  monthID: ID
}

```

</details>

**Comment by poojamat** [comment]
The child models are missing @connection to the parent model. Here is how your model class should look:
type User @model {
  id: ID!
  name: String!
  pass: String
  Cars: [Car] @connection(keyName: "byUser", fields: ["id"])
}

type Car @model @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  name: String!
  userID: ID
  user: User @connection(fields: ["userID"])
  Months: [Month] @connection(keyName: "byCar", fields: ["id"])
}

type Month @model @key(name: "byCar", fields: ["carID"]){
  id: ID!
  month: String!
  year: Int!
  carID: ID
  car: Car @connection(fields: ["carID"])
  Notes: [Note] @connection(keyName: "byMonth", fields: ["id"])
}

type Note @model @key(name: "byMonth", fields: ["monthID"]) {
  id: ID!
  title: String!
  mileage: Int
  location: String
  cost: Float
  date: Int
  other: String
  monthID: ID
  month: Month @connection(fields: ["monthID"])
}

Please update your model class and rerun the "amplify codegen models" command. It should fix the issue.

**Comment by HuiSF** [comment]
This issue seems still happening after made suggestion from above comment looking at the issue reported in https://github.com/aws-amplify/amplify-flutter/issues/972 .

Test schema:

```graphql
type Contact
  @model
  @key(
    fields: ["email"]
    name: "contactByEmail"
    queryField: "contactByEmail"
  ) {
  id: ID!
  name: String!
  email: String!
  relationship: String
  groups: [ContactGroup] @connection(name: "byContact", fields: ["id"])
}

type Group
  @model
  @key(fields: ["name"], name: "groupByName", queryField: "groupByName") {
  id: ID!
  name: String!
  contact: [ContactGroup]! @connection(name: "byGroup", fields: ["id"])
}

type ContactGroup
  @model
  @key(
    name: "byContact"
    fields: ["contactId", "groupId"]
    queryField: "groupByContact"
  )
  @key(
    name: "byGroup"
    fields: ["groupId", "contactId"]
    queryField: "contactByGroup"
  ) {
  id: ID!
  contactId: ID!
  groupId: ID!
  contact: Contact! @connection(fields: ["contactId"])
  group: Group! @connection(fields: ["groupId"])
}
```

Note that `ContactGroup` model has reference to its parent models `Contact` and `Group` similar to what above comment suggested.

When delete any `Contact` model, below exception thrown.

```
E/MyAmplifyApp: Query failed.
    DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:542)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Issue happened here:

https://github.com/aws-amplify/amplify-android/blob/2592ef46d865ee6fd98faa5b1e454297214a62c5/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteModelTree.java#L123-L125

In the root model, `association.getAssociatedName()` returns `"id"`.

<img width="671" alt="02" src="https://user-images.githubusercontent.com/10602282/137227012-1e2f1d37-a1bc-4b9f-9898-c6b63e263441.png">

And next it tries to use `id` as the key to get the association from child model. Which resolves `null` as in the child model the associations are identified by `group` and `contact`,  therefore the subsequent `null.getTargetName()` causes the exception. 

<img width="710" alt="associations in root model" src="https://user-images.githubusercontent.com/10602282/137227044-6a125b94-2365-40d0-a6c1-9573450cf0bb.png">

Could the amplify-android owners please look into this issue?
