### ISSUE TITLE
[Question/Feature Request] How to change Amplify configuration at runtime?

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-android#1460]
amplifyconfiguration.json files appear to support multiple configurations--the default is "Default".  However I want to be able to switch to a custom configuration at runtime.  AWSConfiguration supports this by passing in the configName in a constructor (see https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobile/config/AWSConfiguration.html#AWSConfiguration-android.content.Context-int-java.lang.String-) and through the setConfiguration method (https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobile/config/AWSConfiguration.html#setConfiguration-java.lang.String-).

How can I accomplish the same with Amplify?

Edit:  It looks like Amplify's configuration can't be changed once it's set?  See https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/core/Amplify.java#L137.  Why...?  How can you then use different configurations?  There needs to be a way to clear this out--it's unreasonable for end users to be expected to close/reopen the app since it's all set statically.  Or for developers to use separate processes...

**Comment by rjuliano** [comment]
Related to #560

**Comment by gpanshu** [comment]
Closed as this will be handled when #560 is done.
