### ISSUE TITLE
[DataStore] When enable API sync a release build may crash on App start

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-android#1465]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation "com.amplifyframework:aws-datastore:1.23.0"
    implementation "com.amplifyframework:aws-api-appsync:1.23.0"

```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_292 (AdoptOpenJDK 25.292-b10)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Describe the bug

This issue was raised by an amplify-flutter customer, that he's release build App crashes on App start. This happened only when amplify_api plugin is added.

Similar to #1441 but the exception for this crash was thrown from `SubscriptionProcessor` in the datastore plugin.

Myself have tried to generate release build testing with Android emulator. This crash wasn't reproducible.
Tested the same release build in an Android device, same crash occurred.

However, this crash seems inconsistent as we tried different app (with exactly the same plugin configuration) the crash didn't happen.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
E/AndroidRuntime(31841): FATAL EXCEPTION: RxCachedThreadScheduler-4
E/AndroidRuntime(31841): Process: com.app.myapp, PID: 31841
E/AndroidRuntime(31841): z9: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava
/wiki/What's-different-in-2.0#error-handling | java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'Ka$a' (declaration of 'com.amplifyframework.dat
astore.syncengine.SubscriptionProcessor' appears in /data/app/com.app.myapp-x3nLa4_rfpjjcJ4Lg_N67g==/base.apk)
E/AndroidRuntime(31841):        at Lb.f(:2)
E/AndroidRuntime(31841):        at k9$a.run(Unknown Source:19)
E/AndroidRuntime(31841):        at ob.run(Unknown Source:21)
E/AndroidRuntime(31841):        at ob.call(Unknown Source:0)
E/AndroidRuntime(31841):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(31841):        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime(31841):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(31841):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(31841):        at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(31841): Caused by: java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'Ka$a' (declaration of 'com.amplifyframework.datastore.sync
engine.SubscriptionProcessor' appears in /data/app/com.app.myapp-x3nLa4_rfpjjcJ4Lg_N67g==/base.apk)
E/AndroidRuntime(31841):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.l(Unknown Source:41)
E/AndroidRuntime(31841):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.m(Unknown Source:0)
E/AndroidRuntime(31841):        at com.amplifyframework.datastore.syncengine.S0.a(Unknown Source:11)
E/AndroidRuntime(31841):        at Ka.p(Unknown Source:10)
E/AndroidRuntime(31841):        at f9.e(Unknown Source:5)
E/AndroidRuntime(31841):        at La.p(Unknown Source:17)
E/AndroidRuntime(31841):        at f9.e(Unknown Source:5)
E/AndroidRuntime(31841):        at Xa$b.run(Unknown Source:6)
E/AndroidRuntime(31841):        at k9$a.run(Unknown Source:9)
E/AndroidRuntime(31841):        ... 7 more

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by HuiSF** [comment]
Looking at the original error log, it seems that RxJava caught a `java.lang.IllegalAccessError` exception, but wasn't able to deliver it, which caused the crash (sort of expected behavior by RxJava's design).

The exception `java.lang.IllegalAccessError` though was due to some logic in SubscriptionProcessor was trying to invoke method that was invisible to it (this might be the root cause). And this happens only when setting Android `minifyEnabled: true`.

**Comment by sktimalsina** [comment]
@HuiSF Is the issue still present? with the new comments, it seems that `minifyEnabled` set to true was fine. But `shrinkResources` needed to be set to false. It is likely that the minify's marked resources such as amplify config to be removed by shrink resources?

**Comment by HuiSF** [comment]
Hi @sktimalsina thanks for following up, amplify-flutter has merged another fix which allows minify. 
This should be an issue related with lower version of Gradle. 
I think we can close this issue now. Thanks!
