### ISSUE TITLE
DataStore query predicate operator ne doesn't return expected results

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-android#1468]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.amplifyframework:aws-api:1.24.1'
    implementation 'com.amplifyframework:aws-datastore:1.24.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_292 (AdoptOpenJDK 25.292-b10)
OS:           Mac OS X 10.16 x86_64
```

</details>

### Please include any relevant guides or documentation you're referencing

Original amplify-flutter issue: https://github.com/aws-amplify/amplify-flutter/issues/823

### Describe the bug

Let's say I have table
```
| id    | str         |
| 1     | "name1"     |
| 2     | "name2"     |
| 3     | null        |
```
When I run this query 
```java
Amplify.DataStore.query(
        Person.class,
        Where.matches(Person.STR.ne("name2")),
        people -> {},
        failure -> Log.e("MyAmplifyApp", "Query failed.", failure)
);
```
I'm expecting the query returns results:
``` json
[
  {
    "id": "1",
    "str": "name1"
  },
  {
    "id": "3",
    "str": null
  }
]
```
But it returned only
```json
[
  {
    "id": "1",
    "str": "name1"
  }
]
```
Row with `null` somehow got excluded.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by rjuliano** [comment]
Is the behavior different in iOS? That's the behavior of the != operator in SQLite (and any other SQL database I think). That operator is used to compare two values, which NULL is not. You may need to do something like:

```
Amplify.DataStore.query(
        Person.class,
        Where.matches(Person.STR.ne("name2").or(Person.STR.eq(null)),
        people -> {},
        failure -> Log.e("MyAmplifyApp", "Query failed.", failure)
);


```

**Comment by HuiSF** [comment]
It's the same behavior in iOS. I understood it's an expected behavior working with SQLite. Currently iOS, Android and Flutter libraries API behave the same, but JS API returns `null` values on `Person.STR.ne("name2")`. I'm wondering it's worth to unify API behavior cross platform.

**Comment by palpatim** [comment]
As we think about this, also consider the behavior of the backing GraphQL API: the predicates there are evaluated differently from how the native platforms are evaluating them. 

- Android & iOS native: By default, `str != 'value'` DOES NOT return records where `str` is `null`
- GraphQL, `list` query with a filter like `{str: {ne: "name2"}}` DOES return records where `str` is `null`

Native implementations of DataStore being backed by SQLite is an implementation detail, and it's not something we should assume for our API behavior definitions. (NULL handling is somewhat ambiguous for some cases even [across SQL-based systems](https://www.sqlite.org/nulls.html)).

The right thing to do in this case probably would have been to standardize the behavior with JS & AppSync (I'm assuming that AppSync's behavior conforms to GraphQL's spec in this case) during initial implementation. However at this point, changing the behavior on native clients would be a breaking change, and unifying this behavior is not something I would see us doing until the next major version.

**Comment by HuiSF** [comment]
Thanks for pointing out the behavior of AppSync @palpatim.
