### ISSUE TITLE
Handle expiry token in Amplify.Auth.fetchAuthSession

### ISSUE THREAD

**Issue by arjun-ibm** [aws-amplify/amplify-android#1478]
What is the best way to handle an expired token in Amplify.Auth.fetchAuthSession. 

**Positive flow:**
As per documentation, when a user has a valid session token can be retrieved from `Amplify.Auth.fetchAuthSession(Consumer<AuthSession> onSuccess, ...)`. Casting `AuthSession` to `AWSCognitoAuthSession` and when `AWSCognitoAuthSession.AuthSessionResult.Type` is `Type.SUCCESS`, token can be obtained from `AWSCognitoAuthSession.AuthSessionResult.getToken()`, `AWSCognitoUserPoolTokens`.

**Session expiry flow:**
When the user session/token has expired, `AWSCognitoAuthSession.AuthSessionResult.Type` is expected to be `Type.FAILURE` and A`WSCognitoAuthSession.AuthSessionResult.AuthException` to be be `SessionExpiredException`. Is this valid? And there are no other flows that indicate the session expiry.

**Testing:**
Is there a way to artificially introduce this expiry for testing purposes? 

Amplify SDK version: 1.21.0

**Comment by changxu0306** [comment]
Hello @arjun-ibm ,
The **session expiry flow** you describe is correct. After session expired, the `AuthSessionResult` is like this: 
```
Auth session = AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}
```
To introduce a expiry manually, you could set the refresh token expiration to 60 minutes in your AWS Cognito console as below: 
![image](https://user-images.githubusercontent.com/42978935/134481191-dd4d7bcc-cee0-4db2-9df4-4e01251b4d28.png)

After you sign in the auth user, wait 60 minutes until the session expired.
