### ISSUE TITLE
Always getting nullPointerException while accessing Array in Has-many relationship Datastore

### ISSUE THREAD

**Issue by iamAliRaza** [aws-amplify/amplify-android#1483]
I am not sure how this relationship is working.

Schema:

```
type MessageThread @model @auth (rules : [{allow:private}]){
    id:ID!
    senderId : ID!
    receiverId : ID!
    otherUser : User @connection
    messages : [Message] @connection(keyName: "byThread", fields: ["id"])
}

type Message @model @auth (rules : [{allow:private}])
    @key(name: "byThread", fields: ["threadId", "date"]){
    id:ID!
    threadId: ID!
    messageThread: MessageThread! @connection(fields: ["threadId"])
    message: String!
    date:AWSDate!
    createdTime: AWSTime!
}
```

You can see in the **_MessageThread_** model there is a connection on array of messages.. When i am adding new message will it be automatically add in the array ?? 

How its working ?

Do i need to manually add message object inside this array of messages????
If yes Is it static array i mean when i will close the app and reopen again will this array will be again null???

I want to fetch all the messages that is associated with thread ?? How i can do this .. 
According to my understanding all messages should be inside that array of messages .. So i do not need to add any filter. Each thread saving its own list of messages. But that array is always giving me **nullPointerException**...

**Comment by sdhuka** [comment]
@iamAliRaza So while creating Message object you have to set corresponding MessageThread object and datastore will add to the messages array. Please refer to this [documentation for more details](https://docs.amplify.aws/lib/datastore/relational/q/platform/android/)

**Comment by iamAliRaza** [comment]
@sdhuka Yes i am doing exactly same when i am creating a new message i am passing MessageThread object inside it. But when i accessed array of messages its giving me **nullPointerException**.

**Comment by sdhuka** [comment]
@iamAliRaza We currently don't support lazy querying for relational properties. For your case you have to query Messages separately using MessageThreadID and set the result in the Message object.

**Comment by iamAliRaza** [comment]
👍🏻  ok got your point >> So its means everytime in need to query again and again for getting all latest messages in the array. am i right ??

**Comment by raphkim** [comment]
@iamAliRaza I agree with you 100%! 
This is a feature gap on the Android platform at the moment (lazy loading model children is currently supported on iOS only) and we are actively working on it to close that gap as soon as possible. Thank you for your patience and continuing to use Datastore.
