### ISSUE TITLE
The SESSION_EXPIRED event is not generated

### ISSUE THREAD

**Issue by abogatov** [aws-amplify/amplify-android#1484]
I'm trying to sort out when the AuthChannelEventName.SESSION_EXPIRED event of HubChannel.AUTH will be raised.
In the AWS Cognito I defined the minimum refresh token expiration (1 hour):
![image](https://user-images.githubusercontent.com/70779398/132128543-d7ff9378-4ca1-46cc-95d8-a2f1b6cc86d1.png)

In my code, I subscribed to the HubChannel.AUTH events:
```
authSubscriptionToken = Amplify.Hub.subscribe(HubChannel.AUTH) { hubEvent: HubEvent<*> ->
            when (hubEvent.name) {
                InitializationStatus.SUCCEEDED.toString() -> {
                    Log.i("MyApp", "Auth successfully initialized")
                }
                InitializationStatus.FAILED.toString() -> {
                    Log.i("MyApp", "Auth failed to succeed")
                }
                else -> {
                    when (AuthChannelEventName.valueOf(hubEvent.name)) {
                        AuthChannelEventName.SIGNED_IN -> {
                            Log.i("MyApp", "Auth just became signed in.")
                            changeUserLogInStatus(true)
                        }
                        AuthChannelEventName.SIGNED_OUT -> {
                            Log.i("MyApp", "Auth just became signed out.")
                            changeUserLogInStatus(false)
                        }
                        AuthChannelEventName.SESSION_EXPIRED -> {
                            Log.i("MyApp", "Auth session just expired.")
                            changeUserLogInStatus(false)
                        }
                        else -> {
                            Log.i("Sensodix", "Auth event: ${hubEvent.name}.")
                        }
                    }
                }
            }
        }
```
As well I call the "Amplify.Auth.fetchAuthSession" method every time when my app is activated.

After 1 hour I expected to see that the "AuthChannelEventName.SESSION_EXPIRED" event will be generated but this does not happen.
I found some info in the ticket of amplify-ios project (https://github.com/aws-amplify/amplify-ios/issues/1028) where there is some info that the event should be generated after the session expires and the "fetchAuthSession " method is called.

How about amplify-android, when and after calling which methods should I observe the SESSION_EXPIRED event?

Amplify SDK version: 1.25.1

**Comment by gpanshu** [comment]
Hello, as you can see in the [code](https://github.com/aws-amplify/amplify-android/blob/main/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java#L230) we call the HUB event when the user pool tokens are invalid and that check is called upon fetchauthsession. Hence if you call fetchauthsession AFTER the token has been expired you *should* see the session_expired event. Please reopen this ticket if that is not the case and you have updated to the latest version of the sdk.

**Comment by abogatov** [comment]
Hi @gpanshu,
>  Hence if you call fetchauthsession AFTER the token has been expired you should see the session_expired event
The problem that I need to know the session (refresh token) was expired or not before calling API (to prevent error) and if it was expired the app should open login screen.
Should I call fetchauthsession always when the app is activated?

**Comment by div5yesh** [comment]
API call internally calls `getTokens` and getTokens checks if session is valid before doing a refresh. If session is expired, `SESSION_EXPIRED` event will be generated and app can show login screen at this point. It is not required to call fetchAuthSession before API calls but if you do `SESSION_EXPIRED` event will be generated if refresh token is expired.

**Comment by abogatov** [comment]
>It is not required to call fetchAuthSession before API calls 

I call it when my app is activated, not before API call

If I will not call the fetchAuthSession and the refresh token was expired (without SESSION_EXPIRED ) then after an attempt to call something of amplify API I will have an error.
Therefore, I have to call fetchAuthSession when my app is activated to prevent it. But I expected to SESSION_EXPIRED will be geterated without having to call the fetchAuthSession method.

**Comment by div5yesh** [comment]
Please make sure that you are subscribe to Hub events when app starts. When an API call will fail due to expired session, the Hub will receive SESSION_EXPIRED event.
