### ISSUE TITLE
Adding okHttpClientBuilder.addInterceptor Plugin after Amplify.configure

### ISSUE THREAD

**Issue by markfraserr** [aws-amplify/amplify-android#1487]
My team is using `AmazonCognitoIdentityProviderClient.respondToAuthChallenge` to authenticate users when an `Amplify.API.post` call is met with a Re-Authentication step_up challenge. Once the user successfully authenticates themselves, we use the `accessToken` and the `idToken` from the `respondToAuthChallenge` response as headers and re-execute the same request that triggered the challenge.

In our iOS implementation we are using the `URLRequestInterceptor` to add these headers to any subsequent calls to the matching API that triggered the challenge. This allows the user to be "authenticated" for the rest of their session.

When trying to achieve the same functionality in Android I followed the resulting implementation from this issue:
https://github.com/aws-amplify/amplify-android/issues/1178
https://docs.amplify.aws/lib/restapi/authz/q/platform/android/#none
However, when trying to add the interceptor I am met with the following error:
`Amplify has already been configured., cause=null, recoverySuggestion=Do not add plugins after calling `Amplify.configure()``

Intended implementation:
```
val response: RespondToAuthChallengeResult? = provider.respondToAuthChallenge(respondToAuthChallengeRequest)
Amplify.API.addPlugin(AWSApiPlugin.builder().configureClient(apiName)
                                { okHttpBuilder ->
                                    okHttpBuilder.addInterceptor {
                                        it.proceed(it.request()
                                                .newBuilder()
                                                .addHeader(AUTH_HEADER, response?.authenticationResult?.accessToken)
                                                .addHeader(ID_HEADER, response?.authenticationResult?.idToken)
                                                .build())
                                    }
                                }.build())
```

Is there any way to achieve this implementation in Android?

**Comment by rjuliano** [comment]
Plugins can only be added before the call to `Amplify.configure()`. Once that method is called, plugin configuration cannot be changed. Was `Amplify.configure()` invoked somewhere before the snippet you provided?

PS: Also, instead of using `Amplify.API.addPlugin`, use `Amplify.addPlugin`.

**Comment by markfraserr** [comment]
> Plugins can only be added before the call to `Amplify.configure()`. Once that method is called, plugin configuration cannot be changed. Was `Amplify.configure()` invoked somewhere before the snippet you provided?
> 
> PS: Also, instead of using `Amplify.API.addPlugin`, use `Amplify.addPlugin`.

Yes Amplify.configure() has already been called - that is the issue. It seems that the only way to add an interceptor is to add a Plugin that must be added during configuration, whereas iOS can add interceptors dynamically using `URLRequestInterceptor`. We won't know which values need to be added to the interceptor when Amplify is configured.

**Comment by ekmwilson** [comment]
Is there a way to add a interceptor not as part of a Plugin so that it can be added later in the flow, similar to what's available on iOS, described in the [issue](https://github.com/aws-amplify/amplify-android/issues/1178) @markfraserr  references

**Comment by changxu0306** [comment]
Hi @markfraserr @ekmwilson ,
Adding an interceptor to a plugin during configuration is the only way we currently support. The use case you provide makes sense. It's also necessary for us to align with iOS to support the same functionality. I'll mark it as feature request and put it on our team's backlog. Please stay tuned on this issue.

**Comment by gpanshu** [comment]
This can be accomplished now using the confirmSignIn with the new challenge or directly using the [kotlin sdk underneath](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android/). Hence this feature request can now be closed as invalid.
