### ISSUE TITLE
With same iOS project's amplifyconfiguration and awsconfiguration, Android is failing to get cognito identity token

### ISSUE THREAD

**Issue by hiteshdave347** [aws-amplify/amplify-android#1491]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

implementation 'com.amplifyframework:core:1.25.1'
    implementation 'com.amplifyframework:aws-api:1.25.1'
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.30.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.25.1'

    implementation 'com.amplifyframework:aws-analytics-pinpoint:1.25.1'
    implementation 'com.amplifyframework:aws-datastore:1.25.1'
    implementation 'com.amplifyframework:aws-predictions:1.25.1'
    implementation 'com.amplifyframework:aws-storage-s3:1.25.1'

</details>

### Environment information

<details>

```
# Put output below this line


7.0.2
```
</details>

### Describe the bug

We are using a Cognito User Pool, without a Cognito Identity Pool, so we omit the CredentialsProvider section in the configuration. And with same awsconfiguration.json amplifyconfiguration.json, we are able to get congnito token. But we are not getting token from android project. 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots
```
{
    "IdentityManager": {
        "Default": {}
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "xx-xxxx-x_xxxxxxxxx",
            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Region": "xx-xxxx-x"
        }
    }
}
```

**Comment by raphkim** [comment]
Looks like a bug or potentially a missing feature in Android. We will prioritize it in our backlog.

Meanwhile, what is your use-case for specifically omitting Cognito Identity Pool from your application? 
Would it be possible to reconfigure your app with identity pools as a workaround while we investigate?

**Comment by raphkim** [comment]
It seems that Auth is actually behaving as expected. Are you trying to call `AWSCognitoAuthSession#getUserPoolTokens()` method and still getting this error? `AWSCognitoAuthSession#getIdentityId()` will only work if your identity pool is configured. 

If you aren't able to fetch the user pool tokens after being successfully signed in, please let us know in this ticket and provide us with code snippet to help us investigate.
