### ISSUE TITLE
amplify-android crashes with android navigation version 2.4.0_alpha08

### ISSUE THREAD

**Issue by casontek** [aws-amplify/amplify-android#1493]
I upgraded my project navigation components from 2.3.5 to 2.4.0_alpha08 and since then i have not been able to compile my project. 
I noticed that when i remove amplify dependencies, it works fine but once i put it back the error shows up again.

    //navigation
    implementation 'androidx.navigation:navigation-fragment:2.4.0-alpha08'
    implementation 'androidx.navigation:navigation-ui:2.4.0-alpha08'

    //aws auth and storage library
    implementation 'com.amplifyframework:core:1.24.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.24.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.24.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.24.0'

**Error** 

Duplicate class androidx.navigation.ActivityKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.ActivityNavArgsLazyKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.ActivityNavArgsLazyKt$navArgs$1 found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.ActivityNavigatorDestinationBuilder found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.ActivityNavigatorDestinationBuilderKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.ActivityNavigatorExtrasKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.AnimBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavActionBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavArgsLazy found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavArgsLazyKt found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavArgumentBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavControllerKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.NavDeepLinkDsl found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavDeepLinkDslBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavDeepLinkDslBuilderKt found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavDestinationBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavDestinationDsl found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphBuilderKt found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphKt found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphViewModelLazyKt found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphViewModelLazyKt$navGraphViewModels$1 found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphViewModelLazyKt$navGraphViewModels$backStackEntry$2 found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.NavGraphViewModelLazyKt$navGraphViewModels$storeProducer$1 found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.NavHostKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.NavOptionsBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavOptionsBuilderKt found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavOptionsDsl found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.NavigatorProviderKt found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.PopUpToBuilder found in modules navigation-common-2.4.0-alpha08-runtime (androidx.navigation:navigation-common:2.4.0-alpha08) and navigation-common-ktx-2.3.0-runtime (androidx.navigation:navigation-common-ktx:2.3.4)
Duplicate class androidx.navigation.ViewKt found in modules navigation-runtime-2.4.0-alpha08-runtime (androidx.navigation:navigation-runtime:2.4.0-alpha08) and navigation-runtime-ktx-2.3.0-runtime (androidx.navigation:navigation-runtime-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.DialogFragmentNavigatorDestinationBuilder found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.DialogFragmentNavigatorDestinationBuilderKt found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.FragmentKt found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.FragmentNavArgsLazyKt found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.FragmentNavArgsLazyKt$navArgs$1 found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.FragmentNavigatorDestinationBuilder found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.FragmentNavigatorDestinationBuilderKt found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.fragment.FragmentNavigatorExtrasKt found in modules navigation-fragment-2.4.0-alpha08-runtime (androidx.navigation:navigation-fragment:2.4.0-alpha08) and navigation-fragment-ktx-2.3.0-runtime (androidx.navigation:navigation-fragment-ktx:2.3.4)
Duplicate class androidx.navigation.ui.ActivityKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.AppBarConfigurationKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.AppBarConfigurationKt$AppBarConfiguration$1 found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.AppBarConfigurationKt$AppBarConfiguration$2 found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.AppBarConfigurationKt$AppBarConfiguration$3 found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.AppBarConfigurationKt$sam$i$androidx_navigation_ui_AppBarConfiguration_OnNavigateUpListener$0 found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.BottomNavigationViewKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.CollapsingToolbarLayoutKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.MenuItemKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.NavControllerKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.NavigationViewKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)
Duplicate class androidx.navigation.ui.ToolbarKt found in modules navigation-ui-2.4.0-alpha08-runtime (androidx.navigation:navigation-ui:2.4.0-alpha08) and navigation-ui-ktx-2.3.0-runtime (androidx.navigation:navigation-ui-ktx:2.3.4)

Go to the documentation to learn how to Fix dependency resolution errors.

**Comment by SomnathS09** [comment]
It doesn't seem to be related to Amplify 
Just clean and rebuild project : https://stackoverflow.com/questions/16636848/equivalent-of-clean-build-in-android-studio

**Comment by changxu0306** [comment]
By looking through your log, the error messages doesn't related to Amplify Android. 
As you mentioned, your project works fine before you changing the version to alpha. Currently there's little thing our team could do with your issue since the version you use is an alpha version.

**Comment by casontek** [comment]
Well it's compatibility issue.
The only way I followed to get through it was by downloading .AAR of
awsamplifyframework core, to avoid it's compile navigation dependency
