### ISSUE TITLE
NullPointerException while fetching list items 

### ISSUE THREAD

**Issue by a-taeyeon** [aws-amplify/amplify-android#1494]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'com.amplifyframework:core:1.24.0'
    implementation 'com.amplifyframework:aws-api:1.24.0'
    implementation 'com.amplifyframework:aws-datastore:1.24.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
gradle-6.5-bin.zip

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/android/#query-item

### Describe the bug

I want to fetch list items using the centerId column.
It works well in other tables, but it doesn't work only in that table (Box).
It is possible to fetch a query item (ModelQuery.get(Box.class, id), ... ), but the error occurs when I fetch list items.

### Code Snippet

```java
Amplify.API.query(
                ModelQuery.list(Box.class, Box.CENTER_ID.contains(userId)),
                response -> {
                    for (Box box: response.getData()) {
                        Log.i(TAG, box.getWeight().toString());
                    }
                },
                error -> Log.e(TAG, "Query failure", error)
        );
```

### Log output

<details>

```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: {packagename}, PID: 4278
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator com.amplifyframework.api.graphql.PaginatedResult.iterator()' on a null object reference
        at {packageName}.{activityName}.lambda$getBoxList$2({activityName}.java:106)
        at {packageName}.-$$Lambda${activityName}$rgk9ygsRkFB-FK8Uxv-v5sisk6Y.accept(Unknown Source:2)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

</details>

### amplifyconfiguration.json

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.ap-northeast-2.amazonaws.com/graphql",
                    "region": "ap-northeast-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
 
}

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
type Box @model {
  id: ID!
  address: String!
  centerId: String!
  weight: Float!
}


```

</details>

**Comment by changxu0306** [comment]
Hello @a-taeyeon ,
Based on your description of the problem, list items works well in other tables except `Box` table. Is that correct?
If so, I would assume this is not a library bug. 
Your code snippet doesn't include a `ModelPagination`, but the error log shows the NPE was due to invoking `PaginatedResult.iterator()`. Can you elaborate on the code and the error?
