### ISSUE TITLE
Not signed-in following sign up

### ISSUE THREAD

**Issue by davidattias** [aws-amplify/amplify-android#1503]
Current framework version: 1.26.0

I'm using sign-up flow with confirmation code using custom native UI.

Sign-up and confirm sign-up steps are successfully completed.

Right after sign-up, I perform an API call `Amplify.Auth.fetchAuthSession` which returns the following session:

`AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}`

It looks like I'm not logged-in right after sign-up despite being the expected behaviour, isn't it ?

**Comment by changxu0306** [comment]
Hi @davidattias ,
Yes, this is the expected behavior. Please make sure that you configure Amplify Auth with Cognito User Pool. After sign up, you need to call `signIn()` explicitly. The `isSignedIn` status will only be set to true if you called `signIn()`.

**Comment by davidattias** [comment]
Thanks @changxu0306 , implemented that way!
