### ISSUE TITLE
How to delete user from UserPool which signup with Amplify.Auth.signUp() ?

### ISSUE THREAD

**Issue by maheshordex** [aws-amplify/amplify-android#1511]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

Authentication, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'com.amplifyframework:core:1.26.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.26.0'
    implementation 'com.amplifyframework:aws-datastore:1.26.0'
    implementation 'com.amplifyframework:aws-api:1.26.0'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I want to delete the user from the Cognito user pool but I can see any method in AWS amplify for it ?

![User-Pools-Amazon-Cognito](https://user-images.githubusercontent.com/13220264/135083383-2b5d2068-fe68-4a15-b74d-a9ce3104dae2.png)

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

![User-Pools-Amazon-Cognito](https://user-images.githubusercontent.com/13220264/135083420-61a1625c-7eb8-4f1e-89f3-b34afc08898c.png)

**Comment by maheshordex** [comment]
@ericclemmons  @jpignata  @jpeddicord @palpatim  @brennanMKE 
Can anyone from your team help here?

**Comment by maheshordex** [comment]
@eeatonaws 
any comment on this?

**Comment by ericclemmons** [comment]
@maheshordex For deleting, you can do so manually within Cognito by clicking the user, disabling them, then deleting:

1. <img width="447" alt="Screen Shot 2021-10-01 at 9 34 09 AM" src="https://user-images.githubusercontent.com/15182/135638142-226c0630-c7f0-47c3-bad6-879f5a1b81b7.png">
2. <img width="583" alt="Screen Shot 2021-10-01 at 9 34 04 AM" src="https://user-images.githubusercontent.com/15182/135638236-84b95a9f-29a4-4995-828c-619e0a5509ee.png">

Amplify CLI does support [Admin Queries](https://docs.amplify.aws/cli/auth/admin/) with a `disableUser` path that can be called via `Amplify.API`.

Can you share why you were needing to delete some of these users?
