### ISSUE TITLE
Amplify.Auth.signOut() doesn't work as expected on Firefox

### ISSUE THREAD

**Issue by taranabhangoo** [aws-amplify/amplify-android#1518]
Amplify version - 1.27.0

I want to add the functionality to use any browser that supports Custom Tabs instead of just Chrome Tabs to sign in through Facebook. I'm using Amplify.Auth.signInWithWebUI() for that. And call Amplify.Auth.signOut() for logging out.

I have followed this thread - https://github.com/aws-amplify/amplify-android/issues/678

Problem with Firefox:
When I call Amplify.Auth.signOut(), I receive the redirect uri for sign in but the Firefox browser doesn't close on its own.

=========== CHROME  ===========
Amplify.Auth.signInWithWebUI() - custom tab  is closed automatically after the sign in is complete
Amplify.Auth.signOut - custom tab automatically closes 

=========== FIREFOX  ===========
Amplify.Auth.signInWithWebUI() - custom tab  is closed automatically after the sign in is complete
Amplify.Auth.signOut - custom tab DOES NOT automatically close and has to be closed manually

**Comment by eeatonaws** [comment]
Hi @taranabhangoo. We are investigating the issue and will keep you updated here.

**Comment by eeatonaws** [comment]
The issue of Firefox not redirecting back to the app when using custom tabs appears to be a bug in Firefox, based on [this issue](https://github.com/mozilla-mobile/fenix/issues/15202) in the Mozilla Mobile GitHub repo. At this time, the issue has not been resolved by Firefox, but there is a [proposed workaround](https://github.com/mozilla-mobile/fenix/issues/15202#issuecomment-924661965) mentioned in the GitHub issue, which disallows Firefox. Would it be possible for you to try this workaround?

**Comment by taranabhangoo** [comment]
@eeatonaws Yes, it seems it is a bug in Firefox. But I don't understand how I can use this workaround? Are you suggesting that I add extra data in AWSCognitoAuthSignOutOptions? Right now, I think the only options that can be added in AWSCognitoAuthSignOutOptions is - isGlobalSignOut and browserPackage. How do I add this extra data?

Do you think this is something that needs to be handled on Amplify sdk side?

**Comment by eeatonaws** [comment]
Hi @taranabhangoo, you could use [this code](https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#how-can-i-check-whether-the-android-device-has-a-browser-that-supports-custom-tab) from the Android documentation to check what applications on the device support custom tabs, then select a package from the list of packages returned, using the workaround I previously mentioned to avoid selecting a Firefox package. Once you select one of these packages, you can then set it as the `browserPackage` with `AWSCognitoAuthSignOutOptions`.

**Comment by taranabhangoo** [comment]
Thank you @eeatonaws
