### ISSUE TITLE
Datastore observer queryPredicate evaluated incorrectly.

### ISSUE THREAD

**Issue by PS-MS** [aws-amplify/amplify-android#1525]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    def amplify_version = "1.28.0"

    implementation 'com.amplifyframework:core-kotlin:0.12.0'
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-datastore:$amplify_version"

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Please include any relevant guides or documentation you're referencing

AWSDataStorePlugin.java

### Describe the bug

I have noticed an issue with AWSDataStorePlugin::observe when using a QueryPredicate where the changed item is not being returned to the observer due to the changed item being evaluated incorrectly

### Code Snippet

when using a predicate such as Inspection.ORG_ID.eq(organization) the observer is not returning the result of any changes that do match the predicate, I have had a look into the observe method and believe the reason is the evaluate parameter
```
selectionCriteria.evaluate(itemChange)
```
Removing the query predicate does return the result and I have used the evaluate method to see what the evaluation result should be:
```
changedInspection -> 
DataStoreItemChange evaluation: Inspection.ORG_ID.eq(organization).evaluate(changedInspection) // returns false
Item evaluation: Inspection.ORG_ID.eq(organization).evaluate(changedInspection.item()) // return true
```

This is the AWSDataStorePlugin method being used:
```
    @Override
    public <T extends Model> void observe(
            @NonNull Class<T> itemClass,
            @NonNull QueryPredicate selectionCriteria,
            @NonNull Consumer<Cancelable> onObservationStarted,
            @NonNull Consumer<DataStoreItemChange<T>> onDataStoreItemChange,
            @NonNull Consumer<DataStoreException> onObservationFailure,
            @NonNull Action onObservationCompleted) {
        start(() -> onObservationStarted.accept(sqliteStorageAdapter.observe(
            itemChange -> {
                try {
                    if (itemChange.modelSchema().getName().equals(itemClass.getSimpleName()) &&
                            selectionCriteria.evaluate(itemChange)) {
                        @SuppressWarnings("unchecked") // itemClass() was just inspected above. This is safe.
                        StorageItemChange<T> typedChange = (StorageItemChange<T>) itemChange;
                        onDataStoreItemChange.accept(ItemChangeMapper.map(typedChange));
                    }
                } catch (DataStoreException dataStoreException) {
                    onObservationFailure.accept(dataStoreException);
                }
            },
            onObservationFailure,
            onObservationCompleted
        )), onObservationFailure);
    }
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by eeatonaws** [comment]
A fix for this issue has been released as part of Amplify Android 1.28.2.
