### ISSUE TITLE
Handle Timeout in Amplify Android SDK

### ISSUE THREAD

**Issue by tauqeermajeed0081** [aws-amplify/amplify-android#1530]
How to handle timeout in Amplify 
I want to upload a file to AWS using Amplify Android Sdk but due to time out the file can't be uploaded and shows a timeout error in console.

 Amplify.Storage.uploadInputStream("ExampleKey", stream,
                { LoggerUtils.info(TAG, "Successfully uploaded: ${it.key}") },
                { LoggerUtils.error(TAG, "Upload failed", it) }
            )

It should be uploaded to the server but the timeout is only 10 secs by default. I want to increase it to upload large files to the server.

**Comment by sdhuka** [comment]
@tauqeermajeed0081 Could you please provide details on the size of the file, exception stacktrace and version you are using?
