### ISSUE TITLE
Can refresh token generate new access token without network connectivity? Ampify.currentUser returns random results after expiration of access token time, 

### ISSUE THREAD

**Issue by SomnathS09** [aws-amplify/amplify-android#1531]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
// Amplify core dependency
    implementation 'com.amplifyframework:core:1.18.0'

    implementation 'com.amplifyframework:aws-auth-cognito:1.18.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.18.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html


------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_242-release (JetBrains s.r.o 25.242-b01)
OS:           Windows 10 10.0 amd64


```

</details>

### Describe the bug

I'm using Amplify.currentUser to check if user is logged in or not and then taking him/her to Home Screen

But, after expiration of access token time & unavailability of Internet, Amplify.currentUser returns random results:
sometimes, it returns user other times it returns nothing

I think the problem is : Refresh token cannot generate new access token without Internet so allow an option to get currentUser with time equals to expiration of refresh token (not access token maybe) or solve it otherwise

### Code Snippet

```java
// Put your code below this line.
val user = Amplify.currentUser?

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Have you tried this recently?

`Auth.currentAuthenticatedUser({
    bypassCache: false  // Optional, By default is false. If set to true, this call will send a request to Cognito to get the latest user data
}).then(user => console.log(user))
.catch(err => console.log(err));`

It appears that if you do not bypass cache it would do what you are asking for.
