### ISSUE TITLE
Amplify graphQL API update is not working.

### ISSUE THREAD

**Issue by amneeshsoftobiz** [aws-amplify/amplify-android#1532]
here is my screenshot from AWS app sync, same mutation i am using in my code, both are not updating, you can see i am trying to update "time" in store 

![image](https://user-images.githubusercontent.com/46473769/136949073-4dafbd8c-a0b4-4c27-913f-38c7ffc3eec1.png)

**Comment by eeatonaws** [comment]
@amneeshsoftobiz could you share your GraphQL schema, the code you are using to update the data, and the error you are observing?

**Comment by eeatonaws** [comment]
Closing the issue due to lack of response, please reopen if this is still an issue.
