### ISSUE TITLE
How to Hard Delete multipe record with from DyanmoDB with aws amplify ?

### ISSUE THREAD

**Issue by maheshordex** [aws-amplify/amplify-android#1533]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I want to Hard delete multiple records in dynamo DB with different tables for that I tried the below method for delete but it just updates the flag in a table rather than hard delete from dynamo DB.
 
```
Amplify.DataStore.delete(data,
                            {
        // success
                            },
                            {
                               // errors
                            }
                        )
```

After deleting the record my table looks like the below IMAGE.

![Screenshot from 2021-10-12 21-02-01](https://user-images.githubusercontent.com/13220264/136986129-345ca708-ebcd-47b3-8b3d-5ae4cd723def.png)

### Code Snippet

```java
// Put your code below this line.
Amplify.DataStore.delete(data,
                            {
        // success
                            },
                            {
                               // errors
                            }
                        )
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by maheshordex** [comment]
Can anyone help here?

**Comment by changxu0306** [comment]
Amplify Datastore doesn't support hard delete from DynamoDB. If you do want to remove all the data deleted, you can go to your AWS DynamoDB console, filter the deleted items as follows, then choose Action - delete items. 

<img width="954" alt="Screen Shot 2021-11-02 at 10 47 49 PM" src="https://user-images.githubusercontent.com/42978935/140014835-4688f4c4-ecb3-4de4-a3b3-daf0ee7e1749.png">
