### ISSUE TITLE
HostedUIRedirectActivity does not raise UserCancelledException

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-android#1536]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
com.amplifyframework:aws-auth-cognito:1.26.0

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_265 (AdoptOpenJDK 25.265-b01)
OS:           Mac OS X 10.15.7 x86_64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/

### Describe the bug

When using the showSignIn API, the library displays a custom tab with the Cognito Hosted UI interface, which the end user is able to close.

The documentation for amplify-android gives two seperate sets of version-dependent instructions for updating the AndroidManifest file. 

When using the older instructions utilizing `com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity`,  the closure of the CustomTab results in a UserCancelledException being raised from the showSignIn onError handler. 

When using the newer instructions utilizing `com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity`, no such exception is raised.

**Desired behavior:**
A UserCancelledException should be thrown when the user closes the CustomTab. 

### Reproduction steps (if applicable)

1. Follow the HostedUI instructions for 1.17.7 and below.
2. Close the Customtab
3. Note the UserCancelledException
4. Follow the HostedUI instructions for 1.17.8 and up.
5. Close the Customtab
6. Note the absence of a UserCancelledException.

### Code Snippet

```kotlin
// Put your code below this line.
mainActivity.let {
            Amplify.Auth.signInWithWebUI(
                    it,
                    { result ->
                      if (!resultSubmitted) {
                        resultSubmitted = true;
                        prepareSignInResult(flutterResult, result)
                      }
                    },
                    { error -> errorHandler.handleAuthError(flutterResult, error) }
            )
          }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

amplify-android is being used via amplify-flutter.

**Comment by AndreasBoehm** [comment]
The same happens when using `amplify-android` directly in Android.

**Comment by jbb1003** [comment]
A problem for me too, using SDK version 1.30.1

As a workaround, in the activity that launches signin, I use 


```
    /* Although onActivityResult is deprecated in favour of result launchers, it's the only way to catch the activity result
       without modifying the AWS library. AWS does not issue a URL callback if the user cancels, so there is no
       other way to determine that the UI has been cancelled.
     */
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        
        // Successful signin is adequately handled by HostedUIRedirectActivity. Here, we want to 
        // handle just a user-cancelled login. It appears to work fine without the if-statement, 
       // in which case Amplify.Auth.handleWebUISignInResponse would be called twice  - but I'd 
       // rather avoid that, so I have retained the if. 
        if (data == null) {
            Amplify.Auth.handleWebUISignInResponse(data);
        }
       
```

**Comment by kyleliao321** [comment]
I've been experiencing the same issue before. It seems like the redirect intent won't be received by HostedUIRedirectActivity when use cancelled the login flow. As a result, we have to collect this type of event manually as @jbb1003 's workaround. 

Part of the reason that I came across this issue is because I followed what document had been written. It stated that
```
If you are using a version of Amplify 1.17.8 or above and have already declared HostedUIRedirectActivity in your manifest file, then you may skip this step.
```
I've opened an [issue](https://github.com/aws-amplify/docs/issues/3644) with `amplify/doc` for fixing this document statement. If this issue can not be solved by HostedUIRedirectActivity, I think the document should be modified instead.

**Comment by gpanshu** [comment]
Looking at the code it has been implemented : 
CustomTabsManagerActivity.handleAuthorizationCanceled
```
private void handleAuthorizationCanceled() {
        Log.d(TAG, "Authorization flow canceled by user");
        setResult(RESULT_CANCELED);
    }
```
If this does not solve your issue please recreate but I highly recommend you update your libraries to the latest and try again. 
Thank you

**Comment by eeatonaws** [comment]
Reopening this issue, as it still exists on the latest version of Amplify Android.

**Comment by tylerjroach** [comment]
Documentation has been updated on how to receive cancellation event that occurs early in the sign in process.
