### ISSUE TITLE
AWS existing resources keep getting removed from `awsconfiguration.json` 

### ISSUE THREAD

**Issue by pcanas** [aws-amplify/amplify-android#1556]
Our team is working on an Android app based on Amplify and existing AWS resources. Following the guidelines to add existing resources to the project, we have added them in the `awsconfiguration.json` file. However, every time someone makes a pull operation, this file gets overridden, so we find ourselves manually modifying it all the time.

Is there any other way that I could get around this? If not, are there any plans of making this use case less painful? I would imagine it to be quite common.

**Comment by changxu0306** [comment]
Hi @pcanas ,
`awsconfiguration.json` wouldn't change unless someone pull the backend and modify the configuration. Do you mean that you have to modify the file when there's only a pull operation?

**Comment by pcanas** [comment]
Hi @changxu0306,
This is what I mean.

So let's say that we have a configuration with existing AWS resources and I make a change to the backend. If my teammate wants this change to be reflected, they should pull the new configuration, hence losing this existing AWS resource configuration and having to add it manually.

**Comment by changxu0306** [comment]
In your case, you and your teammate share the same AWS account and the same Amplify project. The configuration file will always get overriden once someone make a change to the backend resources via `amplify push`. This is the expected behavior. 
I'll put your question on our team's discussion to see whether this any future plan to deal with this scenario. Thanks.

**Comment by pcanas** [comment]
Thanks. I think that the use case of having a shared Amplify project and adding existing AWS resources is not well satisfied, and the experience could be improved.
