### ISSUE TITLE
AWS Amplify.Auth - AWSMobileClient.getInstance().federatedSignIn

### ISSUE THREAD

**Issue by RoustamManookian** [aws-amplify/amplify-android#1557]
Hi
I create an android app with AWS.Amplify.Auth federated Login Option.
Everything is working good but I don't know how to continue after successfully logging in with Google credentials.
When I use Hosted WebUI of Cognito User Pool AppClient it automatically adds a user to User Pool.
I didn't find no examples and no documentations about.

I attach my code screenshots.
Any suggestion, please  

![howIGetThisUser](https://user-images.githubusercontent.com/75514218/139475432-4986ec82-8770-4626-aad1-30a2e7c0b106.png)
![fragmentOnCreate](https://user-images.githubusercontent.com/75514218/139474973-b025e50e-fd18-4fd0-8261-343796f57b67.png)
![BtngoogleClick](https://user-images.githubusercontent.com/75514218/139475488-41ec8e03-1f40-4126-9888-808a829660bb.png)
![GoogleSignIn](https://user-images.githubusercontent.com/75514218/139475099-6472d62a-7b8c-44f8-9151-67cc801288b8.png)

**Comment by changxu0306** [comment]
Hello, did you follow the [Amplify Social Sign In with Web UI documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#launch-social-web-ui-sign-in)? You don't need to get the user, instead, just call `Amplify.Auth.signInWithSocialWebUI()` and it will redirect to the URL specified in the Auth configuration.

**Comment by taouichaimaa** [comment]
Hi, having the same issue but I would Like to get the data of google user into my datastore. however auth.fetchattributes() gives the 'user is not authorized 400 ' error. I opened my own issue but it's been ' days now with no answer or update.

**Comment by taouichaimaa** [comment]
Still no update on this one?

**Comment by FlorinAsavoaie** [comment]
Modern apps are using native social login as they are provided (like Facebook, Apple, Google). Exposing the federatedSignIn method is really important. 

Also, it would keep things consistent with the iOS SDK which already does this.

@taouichaimaa I think for now you can call that method using the escapeHatch?

**Comment by poojamat** [comment]
@FlorinAsavoaie  as mentioned by @div5yesh you can achieve it with below code:
Amplify.Auth.signInWithSocialWebUI(AuthProvider.facebook(), this,
    { Log.i("AuthQuickstart", "Sign in OK: $it") },
    { Log.e("AuthQuickstart", "Sign in failed", it) }
)
Please follow the [Amplify Social Sign In with Web UI documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#add-response-handler)

**Comment by FlorinAsavoaie** [comment]
Yeah, meanwhile we decided to drop  Amplify altogether. It seems like it was build to dumb down all kinds of AWS integrations.

- Lack of native authentication (not through web views/browsers/etc) but through Native SDKs, leveraging all the power it brings.
- Limited and weird support for S3. Not supporting multiple buckets, forcing prefixes, etc.
- In Flutter there's just layers on top of the native implementation rather than having an actual SDK.

All in all it seems like a solution only for small apps with minimal integrations.

**Comment by poojamat** [comment]
@FlorinAsavoaie sorry to hear that. Thanks for your feedback. I will bring it to the team and would try to alleviate the pain points.
