### ISSUE TITLE
DataStore items are out of sync between consecutive updates

### ISSUE THREAD

**Issue by zhopon** [aws-amplify/amplify-android#1559]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
    amplifyFramework_version = '1.28.2'
    amplifyKotlinFramework_version = '0.12.2'

    // Amplify core dependency
    implementation "com.amplifyframework:core:$amplifyFramework_version"
    implementation "com.amplifyframework:core-kotlin:$amplifyKotlinFramework_version"

    // Amplify auth
    implementation "com.amplifyframework:aws-auth-cognito:$amplifyFramework_version"

    // Amplify data store
    implementation "com.amplifyframework:aws-datastore:$amplifyFramework_version"
    implementation "com.amplifyframework:aws-api:$amplifyFramework_version"

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Note: Relates to [#8038](https://github.com/aws-amplify/amplify-js/pull/8038) in amplify-js.

When performing consecutive mutations to a DataStore model, the model becomes out of sync until all the subscription events are merged back in the local storage.

### Reproduction steps (if applicable)

1. Observe model changes.
2. Update a model.
3. Update model again.
4. A subscription event (triggered by the first update), updates the model and reverts it to previous version of the model.
5. A subscription event (triggered by the second update), updates the model and it's in sync with the latest version of the model.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by poojamat** [comment]
Is this still an issue with latest version?

**Comment by zhopon** [comment]
I don't know. We have migrated away from DataStore.
