### ISSUE TITLE
com.amplifyframework.auth.AuthException is thrown at at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure

### ISSUE THREAD

**Issue by wangjunyan** [aws-amplify/amplify-android#1563]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication, Analytics, Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:aws-analytics-pinpoint:1.28.1'
implementation 'com.amplifyframework:aws-storage-s3:1.28.1'
implementation 'com.amplifyframework:aws-auth-cognito:1.28.1'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/start/getting-started/setup/q/integration/android/#create-a-new-android-application

### Describe the bug

Find crash log in firebase console as follows,

Fatal Exception: java.lang.RuntimeException: Unable to create application com.squarevalley.i8birdies.MyApplication: AuthException{message=Failed to instantiate AWSMobileClient within 10 seconds, cause=null, recoverySuggestion=Check network connectivity}
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6678)
       at android.app.ActivityThread.access$1400(ActivityThread.java:233)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

Caused by com.amplifyframework.auth.AuthException: Failed to instantiate AWSMobileClient within 10 seconds
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:263)
       at com.amplifyframework.core.category.Category.configure(Category.java:91)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:156)
       at com.squarevalley.i8birdies.AppExtensionsKt.initAmplify(AppExtensionsKt.java:442)
       at com.squarevalley.i8birdies.MyApplication.onCreate(MyApplication.java:90)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6673)
       at android.app.ActivityThread.access$1400(ActivityThread.java:233)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

### Reproduction steps (if applicable)

I can't reproduce this bug by myself. But in firebase console, hundreds of crash logs every day.

### Code Snippet

```java
// Put your code below this line.
in onCreate() of Application,

LogFactory.setLevel(LogFactory.Level.ALL)
  Amplify.addPlugin(AWSCognitoAuthPlugin())
  Amplify.addPlugin(AWSPinpointAnalyticsPlugin(this))
  val confResId = if (AppConstants.IS_PROD) R.raw.amplifyconfiguration_prod else R.raw.amplifyconfiguration
  Amplify.configure(AmplifyConfiguration.fromConfigFile(applicationContext, confResId), applicationContext)
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "analytics": {
    "plugins": {
      "awsPinpointAnalyticsPlugin": {
        "pinpointAnalytics": {
          "appId": "3cc7c249995f4e4688a572ad67bc9c07",
          "region": "us-east-1"
        },
        "pinpointTargeting": {
          "region": "us-east-1"
        }
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "us-west-2:582ad88e-cbe9-43ef-898b-a86fa44e9064",
              "Region": "us-west-2"
            }
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        },
        "PinpointAnalytics": {
          "Default": {
            "AppId": "3cc7c249995f4e4688a572ad67bc9c07",
            "Region": "us-east-1"
          }
        },
        "PinpointTargeting": {
          "Default": {
            "Region": "us-east-1"
          }
        },
        "S3TransferUtility": {
          "Default": {
            "Bucket": "18birdies-upload-medias",
            "Region": "us-west-2"
          }
        },
        "UserFileManager": {
          "Default": {
            "Bucket": "18birdies-upload-medias",
            "Region": "us-west-2"
          }
        }
      }
    }
  }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by changxu0306** [comment]
From the error log, the production app crashes due to Amplify.configure threw an exception. If Amplify configuration is not finish within 10 seconds, the exception will be thrown. I suggest the customer add a try-catch block in `onCreate()` of Application class, just like what our [documentation](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#4-initialize-amplify-in-the-application) suggests, and handle the error in the catch block:
```
try {
      Amplify.addPlugin(new AWSCognitoAuthPlugin());
      Amplify.configure(getApplicationContext());
      Log.i("MyAmplifyApp", "Initialized Amplify");
} catch (AmplifyException error) {
      // handle the error here
      Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
}
```

**Comment by wangjunyan** [comment]
1. If we add "try catch" clause, App may not crash when Amplify initializing failed. But we can't use APIs provided by SDK, such as S3 download and upload. How do handle this issue?
2. We can't reproduce this issue in our own devices, even when we start App without network, App won't crash after 10 seconds.

**Comment by eeatonaws** [comment]
We are not able to reproduce this issue on our end as well and don't expect this error to occur in production. What kind of devices is the issue occurring on?

**Comment by wangjunyan** [comment]
![image](https://user-images.githubusercontent.com/6811893/145327882-ec22bb8e-1a32-4b6a-b7a1-d625bf0d231e.png)
![image](https://user-images.githubusercontent.com/6811893/145328028-c127a4c7-db07-4fe5-a660-59569bf22635.png)

Not able to reproduce doesn't mean no issue.  App crashes 777 time in the last 30 days.

**Comment by poojamat** [comment]
Does the app have services running when it's in background? From the screenshot it appears that crashes are happening when the app is in the background. Could you please provide us the details on why the app is trying to configure amplify while it's in background? The amplify categories should be configured on the onCreate of the application.
