### ISSUE TITLE
Temporal classes contain unsupported APIs for Android <26

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-android#1584]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
implementation "com.amplifyframework:aws-datastore:1.28.3-rc"
implementation "com.amplifyframework:aws-api-appsync:1.28.3-rc"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.13 (Amazon.com Inc. 11.0.13+8-LTS)
OS:           Mac OS X 11.6.1 x86_64
```

</details>

### Describe the bug

The class `java.time.format.DateTimeParseException` is not included in Android SDKs below API 26. This class is used [throughout](https://github.com/aws-amplify/amplify-android/blob/main/aws-api-appsync/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java#L92) the Temporal library. When a parse exception occurs on a device running API level 25, for example, the following output is displayed:

```
W/art     ( 6658): Unresolved exception class when finding catch block: java.time.format.DateTimeParseException
```

The API level 25 sources can be seen below, showing omission of the `java.time` package entirely.

<img width="1032" alt="Screen Shot 2021-11-22 at 9 52 46 AM" src="https://user-images.githubusercontent.com/24740863/142902521-fd347c24-5ac6-4960-bc03-c666fbd06161.png">

### Reproduction steps (if applicable)

1. Create a schema using a date/time type with version control enabled
2. Create some models
3. Perform initial sync
4. Restart app

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
W/art     ( 6658): Unresolved exception class when finding catch block: java.time.format.DateTimeParseException
```

</details>

### GraphQL Schema

<details>

```graphql
type Event @model {
    id: ID!
    date: AWSDate
    time: AWSTime
    ts: AWSTimestamp
    dt: AWSDateTime
}
```

</details>

**Comment by jamesonwilliams** [comment]
The java 8 time APIs are meant to be resolved at compile time by the Android build tools.

But you have to enable it explicitly in your project. Have you done so?

Please see the configuration options for "core library desugaring" here:

https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by HuiSF** [comment]
This issue still reproducible, please indicate proper `minSdkVersion` if API 26+ is required to consume this package.
