### ISSUE TITLE
DataStore waits too long before it's ready

### ISSUE THREAD

**Issue by haitv2910** [aws-amplify/amplify-android#1588]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

The DataStore query doesn't do anything on the first load of the app, so I tried to listen for the DataStoreChannelEventName.READY event, but it took 1 minute from opening the app to when it got into Event Ready.
Is there a way to sync data faster
### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line  
"version": "3.1",
</details>


### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.11 (Oracle Corporation 11.0.11+9-LTS-194)

```

</details>


### Please include any relevant guides or documentation you're referencing

_No response_

### Describe the bug

The DataStore query doesn't do anything on the first load of the app, so I tried to listen for the DataStoreChannelEventName.READY event, but it took 1 minute from opening the app to when it got into Event Ready.
Is there a way to sync data faster

### Reproduction steps (if applicable)

_No response_

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by poojamat** [comment]
When you start datastore sync starts in the background. You can use the [observe query API](https://docs.amplify.aws/lib/datastore/real-time/q/platform/android/#observe-query-results-in-real-time) to get the realtime sync results and you will be notified when sync is complete as well.

**Comment by nazarcybulskij** [comment]
> The DataStore query doesn't do anything on the first load of the app, so I tried to listen for the DataStoreChannelEventName.READY event, but it took 1 minute from opening the app to when it got into Event Ready.
> Is there a way to sync data faster

The solution is not working :(.   When we use observe query API we got data only after  DataStoreChannelEventName.READY event .  We got an empty array (initial data)    and full array after DataStoreChannelEventName.READY event . Problem is longing time  on  DataStoreChannelEventName.READY event  on the first load of the app.

**Comment by poojamat** [comment]
Is there any data saved locally when the app is started?

**Comment by nazarcybulskij** [comment]
@poojamat I don't save any data when the app is started. It is the first starting app

**Comment by taouichaimaa** [comment]
having the same issue, I resorted to loading static data from a json file. Any solutions?

**Comment by eeatonaws** [comment]
A large dataset can cause DataStore sync to take more time to sync all the records and send the READY event. You can limit the number of records being synced using [selective syncing](https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#selectively-syncing-a-subset-of-your-data).

**Comment by maheshordex** [comment]
@nazarcybulskij 
Have you got any solution for faster sync ?
I have only around 100 data but it takes more than 60 seconds.

**Comment by maheshordex** [comment]
@nazarcybulskij 
In ios with same user takes only 7 seconds it is big diff for sync between android and ios.
