### ISSUE TITLE
How to get list of items with IDs in a list  by graphQL Query 

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/amplify-android#1602]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

How can I get all Todos where ID exists in an arraylist? I couldn't find a working example in the Doc or here.
This is what I tried thus far but I get the error on the 'type.OR'  in the Query.list() constructor.

        `Amplify.API.query( ModelQuery.list(InterviewDB::class.java,InterviewDB.ID.eq(QueryPredicateGroup.Type.OR,listOfIds), 
              ModelPagination.limit(1000)),{
        //do stuff
                    },{
        //handle exception
                    })

I was inspired by this snippet of code from a similar issue in aws-IOS:

        let arrayOfUserIds = ["UserId1", "UserId2", "UserId3", "UserId4", "UserId5" ]

        Amplify.API.query(
            request: .paginatedList(
            User.keys,
            where: QueryPredicateGroup(type: .or, predicates: arrayOfUserIds),
        limit: 1_000
        )
        ) { queryResult in
            ...
        }`

Thank you

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by poojamat** [comment]
Please refer to issue: https://github.com/aws-amplify/amplify-android/issues/1420

**Comment by taouichaimaa** [comment]
Hi, the answer doesn't really satisfy my question. I'm looking for a way to easily perform something like `query(citiesRef, where('country', 'in', ['USA', 'Japan']));` in firebase . The answer only gives the possibility for two values.

**Comment by poojamat** [comment]
I @taouichaimaa I beleive this should work:
Amplify.API.query(
    ModelQuery.list(InterviewDB.class, InterviewDB.country.contains("USA").or(InterviewDB.country.contains("Japan")), 
    response -> { Log.i(TAG, "Query response: " + response) },
    error -> { Log.e(TAG, "Query failed.", error) }
);

**Comment by taouichaimaa** [comment]
Thing is I don't necessarily know the arraysize of the values I want to compare. that's why this approach is not working. Isn't there a containsAny( arrayListOfValues) option?

**Comment by poojamat** [comment]
@taouichaimaa unfortunately we don't have a convenient method to support it right now. As a work around to achieve this some users have chained the query predicate dynamically looping through the list of values. I will put in a feature request for it and hopefully we will implement it soon.

**Comment by taouichaimaa** [comment]
I have done the same but I wanted something much more efficient and simpler. Thank you @poojamat , hope you guys work on the android SDK more, it's very much lackluster.
