### ISSUE TITLE
Social sign in with web UI does not work

### ISSUE THREAD

**Issue by chirag-ss** [aws-amplify/amplify-android#1604]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:core:1.30.1'
implementation 'com.amplifyframework:aws-auth-cognito:1.30.1'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          12.0.2 (Oracle Corporation 12.0.2+10)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#setup-your-auth-provider

### Describe the bug

I am using Facebook, Google & Apple social signing using **Social sign in with web UI (HostedUIRedirectActivity)**. I have followed all the steps mentioned in the below doc:
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/

It works fine with the devices above Android API 28 but it doesn't work with the device below Android API 28. However, It succeeds social sign in the web browser of the device(for all the devices) but when it sends callback, SDK does not handle that callback in the devices below Android API 28.

Callbacks that I am getting from the social logins are as below:
**Google:**
shearshare:\/\/callback\/?code=0cf52b0c-fa38-4744-8cc4-f649b0b3a933&state=XCQAS2MXFrTiO_9rLnHv0lI61q8kKoat43U3ZemaHRg",

**Facebook:**
\/\/callback\/?error_description=attributes+required%3A+%5Bemail%5D&state=CWr_-QOzkAaVQuKvvma8QwzDfrHMis5CF1DPxwrNFJ0&error=invalid_request#_=_

**Apple:**
 shearshare:\/\/callback\/?code=63ce31a8-01ba-4356-8b7e-bd58db6f9bf6&state=iC2TAlRJ6uToH_5ds9ChzKtfCm7XBBT_L81r2d9i93s
 
 **I am using the below method for the social SignIn:**
```
 Amplify.Auth.signInWithSocialWebUI(
            provider,
            activity, {
                getProfileInfo(socialLoginListener, it)
            }, {
                socialLoginListener.onAuthException(it)
            }
        )
```

 **As per the document:**
 https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#add-response-handler
 I don't need to put the below code in the app when using **HostedUIRedirectActivity** but I am using it to handle the user cancel event.
in `onActivityResult` function,
```
        super.onActivityResult(requestCode, resultCode, data)
        try {
            if (requestCode == AWSCognitoAuthPlugin.WEB_UI_SIGN_IN_ACTIVITY_CODE) {
                try {
                    Amplify.Auth.handleWebUISignInResponse(data)
                } catch (e: AuthNavigationException) {
                    e.printStackTrace()
                }
                if (resultCode == Activity.RESULT_CANCELED) {
                    dismissProgressDialog()
                }
            }
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
 ```

Executing `Amplify.Auth.signInWithSocialWebUI(....)` opens a web browser for the social login & once it succeeds & returns to the app, it opens a popup to choose the app for redirection. 
It has two app intents with the same package name of the app (the second is due to the deep-link implemented using Branch.io) (attached is a screenshot for this). If I choose the **first intent** (Branch deep link intent) from the popup then it just closes the application. 
If I choose the **second intent** (main app intent) then it returns the below error logs:
```
D/AWSMobileClient: onSuccess: HostedUI signed-in
D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
 E/AWSMobileClient: onError: Federation from the Hosted UI failed
    java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1801)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.us-west-2.amazonaws.com/us-west-2_TvPGHxxxx
```

However, In the devices above Android API 28, it works fine with both the app intents. I have also tried to upgrade & downgrade the Amplify lib version but it doesn't work. I am using the "1.30.1" version right now. Let me know what am I missing here.

### Code Snippet

```kotlin
// Put your code below this line.
 Amplify.Auth.signInWithSocialWebUI(
            provider,
            activity, {
                getProfileInfo(socialLoginListener, it)  // API call to set user data on server
            }, {
                socialLoginListener.onAuthException(it)  // In app listener
            }
        )

//In Activity
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        try {
            if (requestCode == AWSCognitoAuthPlugin.WEB_UI_SIGN_IN_ACTIVITY_CODE) {
                try {
                    Amplify.Auth.handleWebUISignInResponse(data)
                } catch (e: AuthNavigationException) {
                    e.printStackTrace()
                }
                if (resultCode == Activity.RESULT_CANCELED) {
                    dismissProgressDialog()
                }
            }
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
    }
```

### Log output

<details>

```
// Put your logs below this line
D/AWSMobileClient: onSuccess: HostedUI signed-in
D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
 E/AWSMobileClient: onError: Federation from the Hosted UI failed
    java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1801)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.us-west-2.amazonaws.com/us-west-2_TvPGHfzG6

```

</details>

### amplifyconfiguration.json

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-west-2_TvPGHxxxx",
                        "AppClientId": "addhh5kgf4i5rogkjxxxxxxxx",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "ss-v2-stg.auth.us-west-2.amazoncognito.com",
                            "AppClientId": "addhh5kgf4i5rogkjxxxxxxxx",
                            "SignInRedirectURI": "shearshare://callback/",
                            "SignOutRedirectURI": "shearshare://signout/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

![Screenshot_1639375444](https://user-images.githubusercontent.com/47347241/145771099-9c2944b7-b9e7-4f1b-9d0f-0dab31b0fb5b.png)

**Comment by raphkim** [comment]
Hi @chirag-ss ,

Thank you for reporting the issue. I am noticing that you are calling `handleWebUISignInResponse()` in your `onActivityResult()`. I believe this is what's causing the 2nd popup (for redirection). At this point, the redirect should already have happened since you are using the latest `HostedUIRedirectActivity`, which may be causing some unexpected behavior. Would you be able to try again with the following instead?

```kotlin
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        try {
            if (requestCode == AWSCognitoAuthPlugin.WEB_UI_SIGN_IN_ACTIVITY_CODE) {
                // Handling user-canceled still needs to be called in here
                if (resultCode == Activity.RESULT_CANCELED) {
                    dismissProgressDialog()
                }
            }
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
    }
```
