### ISSUE TITLE
#TooManyRequestsException. Having enough service quota/limit, but unable to fetch tokens during peak hours. 

### ISSUE THREAD

**Issue by harryz2016** [aws-amplify/amplify-android#1609]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'com.amplifyframework:aws-auth-cognito:1.31.0'
    implementation 'com.amplifyframework:core-kotlin:0.15.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
Welcome to Gradle 7.0.2!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0.2/release-notes.html


------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.5 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/

### Describe the bug

Can't fetch auth tokens during peak hours with error listed below. (Everything works when traffic is low)

### Code Snippet

```java
// Put your code below this line.
Used the exact same code from amplify documentation.
```

### Log output

<details>

```
// Put your logs below this line
AWSMobileClient: Failed to federate tokens during sign-in
java.lang.RuntimeException: Error in federating the token.
at ...
Caused by: com.amazonaws.services.cognitoidentity.model.TooManyRequestsException: Rate exceeded (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: TooManyRequestsException; Request ID: fa2f7b9c-686c-4846-96d9-c28a5da1e101)

```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxxxxxxxxxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_x xxxxxxxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxx",
                        "AppClientSecret": "xxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by harryz2016** [comment]
Checked another app of ours in production using AWS SDK, the older version. (https://github.com/aws-amplify/aws-sdk-android)) Never found this problem, even through it uses the same user pool under the same account.

Also, checked AWS console. Fetching token is related to a service quota called "Rate of UserAuthentication requests", but we are only using 5% of the quota during peak hours...

Can someone help please?

**Comment by div5yesh** [comment]
Can you provide the code snippet you are using to signin?

**Comment by div5yesh** [comment]
Closing. Let us know if you are still facing this issue.
