### ISSUE TITLE
DataStore Observe and ObserveQuery do not include the fields of nested models for belongsTo relationships [Flutter Support]

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-android#1610]
### Description

I opened a previous issue (https://github.com/aws-amplify/amplify-android/issues/1566) to support the nested models for belongsTo relationships for observe and observeQuery. The issue was addressed for native Android apps. However, Amplify-Android has some duplicated methods in DataStore specifically to support Amplify-Flutter. There is now an inconsistency between the support for native Android apps and Flutter apps that are implicitly depending on Amplify Android.

Original Issue: https://github.com/aws-amplify/amplify-android/issues/1566

PR to Address it: https://github.com/aws-amplify/amplify-android/pull/1585

`getModelFields` (used in native apps and has been fixed): https://github.com/aws-amplify/amplify-android/blob/7e9cfdf5ea3000a0e72adc41876f652b02feed86/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java#L244-L304

`getModelFields` (added for flutter support, issue still present): https://github.com/aws-amplify/amplify-android/blob/7e9cfdf5ea3000a0e72adc41876f652b02feed86/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/SelectionSet.java#L358-L407

**Comment by Jordan-Nelson** [comment]
Note: I can test out that if the same changes are made in the duplicate `getModelFields`, that it resolves this issue.

**Comment by changxu0306** [comment]
Hi Jordan, the fix PR has been approved. Thanks for pointing out and fixing the issue!
