### ISSUE TITLE
Disable persistence on CognitoıdentityProvider cache

### ISSUE THREAD

**Issue by kubilayaydin** [aws-amplify/amplify-android#1612]
I want to disable amplify to write cache into shared presences because it contains user phone numbers. I tried to set persistence disabled by 

```
IdentityManager.getDefaultIdentityManager().setPersistenceEnabled(false)
```
and setting Persistance false in config as 
```
"Auth": {
          "Default": {
            "OAuth": {
              "WebDomain": "**.auth.eu-central-1.amazoncognito.com",
              "AppClientId": "***",
              "AppClientSecret": "***",
              "SignInRedirectURI": "**://",
              "SignOutRedirectURI": "**://",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ],
              "Persistence": false
            },
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        },
```

but still, after user login, "CognitoIdentityProviderCache.xml" file is created and stored in shared preferences. 

Is there any way that I could disable that file written into shared preferences?

if not possible how can I mask the user's phone number in that file? Currently, Cognito holds values like:
```
<string name="CognitoIdentityProvider.276dt8eeub4a9cmn9hlhs35u1d.{#phonenumber}.idToken.encrypted.keyvaluestoreversion">1</string>
```
is there any way to mask or change this number into something that is not directly related to users?

**Comment by eeatonaws** [comment]
Hi @kubilayaydin. Amplify doesn't currently provide a way to remove or encrypt user information stored in shared preferences. I have created a feature request [here](https://github.com/aws-amplify/amplify-android/issues/1618) for encrypting that information. Any updates on this issue will be posted in that feature request.
