### ISSUE TITLE
Update/Save freeze up LOCK ACQUIRED / RELEASED

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/amplify-android#1616]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Authentication, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

hey, I'm trying to update an existing item in the datastore, however the logs give 
```
 I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
```
   and stop. No error , no exception .  This is my update function : 

```
 fun addToFave(idOfInterview : String){
        Log.i("SavingFaves","inside!")
        Amplify.DataStore.query( UserSettings::class.java,
            Where.id(Amplify.Auth.currentUser.userId), { matches ->
                run {
                    Log.i("SavingFaves","inside!2")
                    matches.forEach { Log.i("SavingFavesOne",it.toString())
                        val original= it
                        val edited=original.copyOfBuilder()
                            .userFavorites(original.userFavorites.toString().plus("@@@@").plus("16F11584-E4CE-4232-8DAF-4F65E3AAC6C0"))
                            .build()
                            Log.i("SavingFaves",edited.toString())
                            Amplify.DataStore.save(edited, {  Log.i("SavingFaves","Saved!") },
                                {  Log.e("MyAmplifyApp", "Error saving post", it) })
                            Log.i("SavingFaves","Saved!")
                          }

                }
            },{
                Log.e("MyAmplifyApp", "Query failed", it)
            })

    }
```
I already have the Hub subscriptionon my MainActivity and the state is READY . fetching data works perfectly fine ,it's the update /save that's not working. 
 As for the logs, I only get 'inside!' and 'inside2'. Any help is appreciated. 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by taouichaimaa** [comment]
Any one has any idea why this happens?

**Comment by raphkim** [comment]
You are currently querying for `UserSettings` models where its `id` is equal to your currently signed user's ID. Is that the intended query? Model's `id` field is randomly generated by us to serve as unique primary key, perhaps you meant to query by matching user ID with another field in the model?  Would you be able to share your GraphQL schema and explain the exactly what you are trying to query?

**Comment by taouichaimaa** [comment]
Hi @raphkim , I changed from ID based querying to EMAIL based, the problem isn't there.
here's my graphql schema :
```
type UserSettings @model @aws_cognito_user_pools @auth(rules: [{allow: private}]) {
  id: ID!
  user_subId: String
  user_name: String
  user_Email: String
  user_Favorites: String
}
```
` user_favorites `is a string made from concatenated object IDs by `'@@@@'.` My approach was to get the `userSetting` object and then update the `user_favorites` field before saving the `usersetting `object.

**Comment by taouichaimaa** [comment]
@raphkim any updates on this issue please?

**Comment by eeatonaws** [comment]
Hi @taouichaimaa. Based on the code you provided and the logs you're seeing, it looks like the query of UserSettings is completing successfully, but there are no items that match the query since the log "SavingFavesOne" inside `matches.forEach` isn't being logged. Could you please verify that there is an existing entry in your UserSettings table where the email matches the one you are querying for?

**Comment by taouichaimaa** [comment]
hi @eeatonaws , yes, there is a UserSettings with the email that I'm giving the function. I can display user favorites that I get from the same query but I can't update.

**Comment by eeatonaws** [comment]
Hi @taouichaimaa. Using the latest version of Amplify, I am able to query and update the user settings using the code you provided and am not able to reproduce the issue. What version of Amplify are you using? Could you also please provide additional logs?

**Comment by taouichaimaa** [comment]
Hi, I'm using amplify 7.5.1 and the logs stop at the " Log.i("SavingFaves","inside!")". How can I give you more information?

**Comment by eeatonaws** [comment]
@taouichaimaa Amplify Android does not have a version 7.5.1. Could you share your `build.gradle` file with the Amplify dependencies? Also, could you try running the same code you shared, but comment out the call to `Amplify.DataStore.save`, and share what logs you see (e.g., does the log for "SavingFavesOne" show up?)?

**Comment by taouichaimaa** [comment]
Hi, Thank you for the help , turns out I was using a different service than the one I was using. I'll close this now.
