### ISSUE TITLE
How to get details of current authenticated user via google?

### ISSUE THREAD

**Issue by pierluigisupino** [aws-amplify/amplify-android#1625]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:aws-auth-cognito:1.30.0'
implementation 'com.amplifyframework:aws-api:1.30.0'
implementation 'com.amplifyframework:aws-predictions:1.31.0'


```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17.0.1 (Oracle Corporation 17.0.1+12-LTS-39)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

When Login thru Amplify using:

``` Amplify.Auth.signUp(email, password, options, ...); ```

i'm able to retrive current authenticated user details using:

``` Amplify.Auth.getCurrentUser().getUserId() //example``` 

but if the Login is made with:

``` Amplify.Auth.signInWithSocialWebUI(AuthProvider.google(), activity, ...); ```

when i try to retrive the user using ``` Amplify.Auth.getCurrentUser() ``` i get a
 ``` null object ```

What is the correct way to get the user authenticated via google?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Hello @pierluigisupino 

Can you post the response for 

`Amplify.Auth.signInWithSocialWebUI(AuthProvider.facebook(), this,
    result -> Log.i("AuthQuickstart", result.toString()),
    error -> Log.e("AuthQuickstart", error.toString())
);`
Whats the result or error ?

**Comment by pierluigisupino** [comment]
Yes i have done all thees steps, here is the screenshot
![Screenshot (217)](https://user-images.githubusercontent.com/58226371/149397332-98cb9cec-66fd-48ea-af09-12488f6ba42d.png)
t

**Comment by pierluigisupino** [comment]
@gpanshu also the redirect uris works correctly, in fact after the login you are redirected to the "mainAcrivity"

**Comment by div5yesh** [comment]
Correct way to fetch credentials is use `fetchAuthSession`. Refer: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android/

**Comment by div5yesh** [comment]
Although, `Amplify.Auth.getCurrentUser()` should work if you want to fetch user details.

**Comment by pierluigisupino** [comment]
@div5yesh no I get no response from both success end error callback

**Comment by pierluigisupino** [comment]
I was missing to add the activity to catch the rusult in the Manifest  ```com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity```
