### ISSUE TITLE
DataStore errorHandler cannot capture asynchronous mutation errors 

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-android#1637]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
dependencies {
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    implementation 'com.amplifyframework:aws-api:1.31.2'
    implementation 'com.amplifyframework:aws-datastore:1.31.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_292 (AdoptOpenJDK 25.292-b10)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Describe the bug

DataStore allows developer to provide a custom `errorHandler` function.
According to the [library document](https://docs.amplify.aws/lib/datastore/conflict/q/platform/android/#custom-configuration-fields), the `errorHandler` function is invoked for unrecoverable model synchronization errors. However, it never been invoked on any GraphQL error triggered my model mutation, and the library only prints an error log, but not providing an API to allow developers to catch this type off error.

Related amplify-ios issue: https://github.com/aws-amplify/amplify-ios/issues/1555

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by applyinnovations** [comment]
Hey @poojamat  I have also logged the same issue on the amplify-js repository which is still open https://github.com/aws-amplify/amplify-js/issues/8891
