### ISSUE TITLE
How can I properly share my amplify backend with my native SwiftUI iOS project and native Kotlin Android Project?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-android#1647]
I have an existing iOS app using the amplify backend with GraphQL API, Cognito User Pools Auth and S3 Storage.  I have been using this app and all is well.

Now I am developing an Android version of the same app with Kotlin in Android Studio.  I would like to use the same Backend (Auth/API/Storage).  

The multiple frontends documentation is insufficient and only tells me how to get the config files into my Android project.  I need to be able to use all of my services and for that I need the Auth, need to Codegen my models etc...

The only command I can see on your documentation is Amplify Pull in the root directory of the Android project which is only bringing in my config files.  

How can I properly share my amplify backend with my native SwiftUI iOS project and native Kotlin Android Project?

**Comment by eeatonaws** [comment]
Hi @alionthego, you can run `amplify pull` from the root directory of your Android project and select the Amplify project whose backend you would like to import when prompted. When asked "Do you plan on modifying this backend?", answering yes will add the `backend` folder in addition to the `.config` folder in the `amplify` directory in your project. After running `amplify pull`, `amplifyconfiguration.json` (with your backend) will be created, and the code generated models for your GraphQL API will be located in `app/src/main/java/com/amplifyframework.datastore.generated.model/`.

**Comment by alionthego** [comment]
Thanks @eeatonaws . That seems to work well.  Hope the documentation will be more robust going forward.
