### ISSUE TITLE
ResendConfirmation method doesn't work

### ISSUE THREAD

**Issue by reberthkss** [aws-amplify/amplify-android#1669]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

apply plugin: "com.android.application"
apply plugin: "kotlin-android"
apply plugin: "kotlin-android-extensions"
apply plugin: "kotlin-kapt"
apply plugin: "androidx.navigation.safeargs.kotlin"

android {
    compileSdkVersion rootProject.ext.compile_sdk_version
    buildToolsVersion rootProject.ext.build_tools_version

    defaultConfig {
        applicationId "com.example.shoplist"
        minSdkVersion rootProject.ext.min_sdk_version
        targetSdkVersion rootProject.ext.target_sdk_version
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

        javaCompileOptions {
            annotationProcessorOptions {
                arguments << [
                        "room.schemaLocation": "$projectDir/schemas".toString(),
                        "room.incremental": "true",
                        "room.expandProjection": "true"
                ]
            }
        }
        
        repositories {
            google()
            mavenCentral()

        }

        compileOptions {
            coreLibraryDesugaringEnabled true
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }

        kotlinOptions {
            jvmTarget = '1.8'
        }

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

}

dependencies {
    implementation project(":core")
    implementation project(":core:viewmodel")
    implementation project(":core:di")
    implementation project(":authentication")
    implementation project(":authentication:authenticated")
    implementation project(":authentication:unauthenticated")
    implementation project(":main")
    implementation project(":main:dashboard")
    implementation project(':main:categorylist')
    implementation project(':main:userlist')
    implementation project(":createlist")
    implementation project(":providers")
    implementation project(":productdetail")
    implementation project(":listdetail")
    implementation project(":mutations")
    // android core
    implementation androidx_core_deps.values()
    implementation android_fragment.values()
    implementation android_navigation.values()
    implementation android_lifecycle.values()
    implementation android_material_design.values()
    implementation room_db.values()
    implementation dagger.values()
    implementation rx_deps.values()
    implementation glide_deps.values()

    annotationProcessor annotation_processor_glide.values()
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
    // Amplify SDK
    implementation amplify.values()
    // kapt
    kapt kapt_lifecycle.values()
    kapt kapt_dagger.values()
    kapt kapt_room_db.values()
    // annotation processor
    kapt annotation_processor_dagger.values()
    // tests
    testImplementation tests.values()
    // android tests
    androidTestImplementation android_test.values()
}
</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

i'm trying to resend the confirmation sign up as follow below.

```
fun reSendSMS(username: String): Single<AuthSignUpResult> {
        return Single.create { emitter ->
            Amplify.Auth
                .resendSignUpCode(
                    username,
                    AuthResendSignUpCodeOptions.defaults(),
                    {
                        emitter.onSuccess(it)
                    },
                    {
                        emitter.onError(it)
                    }
                )
        }
    }
```

and stucking at the error

<details>

<summary>Click to expand </summary>

```
NotAuthorizedException{message=Failed since user is not authorized., cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Cannot resend codes. Auto verification not turned on. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 1b34d101-e931-479f-aa1d-f8b4d5bfd9f4), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
```

</details>

### Reproduction steps (if applicable)

try to use the ` Amplify.Auth.resendSignUpCode()` method.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by eeatonaws** [comment]
Hi @reberthkss. The error you are observing can be thrown if the user pool is set to not verify any attributes. You can change this setting by going to your user pool in the AWS console, then "MFA and verifications" under "General settings" on the left, and under "Which attributes do you want to verify?", choosing email, phone, or both (depending on your use case).

**Comment by reberthkss** [comment]
@eeatonaws thank you for reply. I fixed this issue changing the verification method from e-mail to sms.
