### ISSUE TITLE
AWS Cognito Android 12 Login failed on Samsung S22

### ISSUE THREAD

**Issue by CeccoCQ** [aws-amplify/amplify-android#1673]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:core:1.32.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.32.0'


```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

I'm working with this code to sign the user:

```
        List<AuthUserAttribute> authUserAttributeList = new ArrayList<>();
        authUserAttributeList.add(new AuthUserAttribute(AuthUserAttributeKey.familyName(), userDTO.getFamilyName()));
        authUserAttributeList.add(new AuthUserAttribute(AuthUserAttributeKey.givenName(), userDTO.getGivenName()));
        authUserAttributeList.add(new AuthUserAttribute(AuthUserAttributeKey.email(), userDTO.getEmail()));

        AuthSignUpOptions options = AuthSignUpOptions.builder()
                .userAttributes(authUserAttributeList)
                .build();

        String username = SecureUtils.SHA1.makeHash(userDTO.getEmail().trim()).trim();

        TaskCompletionSource<Object> source = new TaskCompletionSource<>();
        Amplify.Auth.signUp(username, userDTO.getPassword(), options, source::setResult, source::setException);
```

and if I try to login with this user with this code:
```
Amplify.Auth.signIn(email, password, result -> {
                source.setResult(result);
            }, e -> {
                source.setException(e);
            });
```

All works fine with Android 11 (I've a OnePlus 6) but not works with Android 12 (Samsung S22 Ultra).
I've this error:

`InvalidParameterException{message=One or more parameters are incorrect., cause=com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: 2 validation errors detected: Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+; Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+ (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: 7d4a10f9-f2de-45e4-a808-bff0ec0d9c47), recoverySuggestion=Enter correct parameters.}`

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "MobileApi": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxxx.execute-api.eu-central-1.amazonaws.com/dev",
                    "region": "eu-central-1",
                    "authorizationType": "AWS_IAM"
                },
                "AdminQueries": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxxx.execute-api.eu-central-1.amazonaws.com/dev",
                    "region": "eu-central-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-central-1:01c96203-603b-4b9d-a406-adfc5d540403",
                            "Region": "eu-central-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-central-1_dG4hDnAsS",
                        "AppClientId": "7hml7632vulfls7gn5buq4pk94",
                        "Region": "eu-central-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxxxx.eu-central-1.amazoncognito.com",
                            "AppClientId": "7hml7632vulfls7gn5buq4pk94",
                            "SignInRedirectURI": "xxxxx://callback/",
                            "SignOutRedirectURI": "xxxxx://logout/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "loginMechanisms": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL",
                            "FAMILY_NAME",
                            "GIVEN_NAME"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ]
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
@CeccoCQ can you give me an example username that fails on Android 12 please?

**Comment by gpanshu** [comment]
I have tested it with the following user : abcTestUser+123@gmail.com SHA1: CAD4BF2E870A81C73EAF9E21E0DE7BBF1FC5FF03

Sign up succeeded with user _____: AuthSignUpResult{isSignUpComplete=true, nextStep=AuthNextSignUpStep{signUpStep=CONFIRM_SIGN_UP_STEP, additionalInfo={}, codeDeliveryDetails=AuthCodeDeliveryDetails{destination='a***@g***', deliveryMedium=EMAIL, attributeName='email'}}, user=AuthUser{userId='f8aa48fe-d7e8-49f9-a046-d8a824a968fa', username='CAD4BF2E870A81C73EAF9E21E0DE7BBF1FC5FF03'}}

I have tested this on both Samsung S21 (Android 12) and Pixel 5 and the result were the same. 

You can also check your SHA1 against the Regex that you got from the exception to see if there is something that might be wrong there.

Feel free to reopen if you have done the above and still get the exception on Android 12 and we can dive deeper.
