### ISSUE TITLE
How to use AuthConfirmSignInOptions while resetting a password (Amplify Android v1.25.0)

### ISSUE THREAD

**Issue by malik082009** [aws-amplify/amplify-android#1679]
### Discussed in https://github.com/aws-amplify/amplify-android/discussions/1469

<div type='discussions-op-text'>

<sup>Originally posted by **vijayendra-tripathi** August 29, 2021</sup>
Following is the issue (Amplify Android v1.25.0) - 

1. Create a new account directly in user pool on AWS console and ask user to login (email invite).
2. When user logs in, then he/she gets "**CONFIRM_SIGN_IN_WITH_NEW_PASSWORD**" as next step.
3. To provide a new password API available is "**Amplify.Auth.confirmSignIn**" which asks for a confirmation code and "**AuthConfirmSignInOptions**". **AuthConfirmSignInOptions** class says "_This is currently empty but exists here to support common sign in options in the future._" So there is no way I can use it to provide user information like name, email etc. Thus the API "**Amplify.Auth.confirmSignIn**" fails due to lack of information provided. The error says "name" is missing.

Please suggest. Thanks!</div>

**Comment by malik082009** [comment]
```
AWSMobileClient.getInstance().confirmSignIn(newPassword, new Callback<SignInResult>() {
                                @Override
                                public void onResult(SignInResult signInResult) {
                                    runOnUiThread(new Runnable() {
                                        @Override
                                        public void run() {
                                            Log.d(TAG, "Sign-in callback state: " + signInResult.getSignInState());
                                            switch (signInResult.getSignInState()) {
                                                case DONE:
                                                    makeToast("Sign-in done.");
                                                    break;
                                                case SMS_MFA:
                                                    makeToast("Please confirm sign-in with SMS.");
                                                    break;
                                                default:
                                                    makeToast("Unsupported sign-in confirmation: " + signInResult.getSignInState());
                                                    break;
                                            }
                                        }
                                    });
                                }

                                @Override
                                public void onError(Exception e) {
                                    Log.e(TAG, "Sign-in error", e);
                                }
                            });
```

https://docs.amplify.aws/sdk/auth/working-with-api/q/platform/android/#force-change-password

**Comment by sdhuka** [comment]
@malik082009 I verified that calling `Amplify.Auth.confirmSignIn("NEW_PASSWORD", {}, {})` completes the signIn and results in nextSignInStep as done. Code snippet you pasted should work and passing AuthConfirmSignInOptions is not required. Could you please post the error stacktrace if this is not working for you?

**Comment by malik082009** [comment]
@sdhuka I can't find this method `Amplify.Auth.confirmSignIn("NEW_PASSWORD", {}, {})`. I ended up calling ```
AWSMobileClient.getInstance().confirmSignIn(newPassword, new Callback<SignInResult>() {
                                @Override
                                public void onResult(SignInResult signInResult) {
                                    runOnUiThread(new Runnable() {
                                        @Override
                                        public void run() {
                                            Log.d(TAG, "Sign-in callback state: " + signInResult.getSignInState());
                                            switch (signInResult.getSignInState()) {
                                                case DONE:
                                                    makeToast("Sign-in done.");
                                                    break;
                                                case SMS_MFA:
                                                    makeToast("Please confirm sign-in with SMS.");
                                                    break;
                                                default:
                                                    makeToast("Unsupported sign-in confirmation: " + signInResult.getSignInState());
                                                    break;
                                            }
                                        }
                                    });
                                }

                                @Override
                                public void onError(Exception e) {
                                    Log.e(TAG, "Sign-in error", e);
                                }
                            });
```. Thanks for your time.
