### ISSUE TITLE
S3 storage access denied

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/amplify-android#1680]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication, Storage

### Gradle script dependencies

<details>

```groovy
 "com.amazonaws:aws-android-sdk-core:2.38.0"


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I'm trying to get and upload files into my s3 bucket from android .  But I can't get anything except for this error:

> 
    com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 2FP0606VVWZCV4T4), S3 Extended Request ID: U4ymXbCBZWNXKnDtHXVPjrcLHgrzJA47ZGV2RMrp/37PtfOaXp32NKcbrYBKpPOoLnMT3gsax+8=

I've checked the identitypoolId, but I have no idea which one to use since I have 4 . Do I use the one in my amplifyconfiguration ?

My admin was also contacted and they said that my iam user has the S3 role to access and get objects.
This is my code:
`
           s3 = AmazonS3Client(credentialsProvider, Region.getRegion(Regions.US_EAST_1))

           s3.putObject("bucketname", audioFileRecorded.name, audioFileRecorded)//breaks here
var fileObject = s3.getObject("bucketname","content4.mp3")// and here
       
` 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sdhuka** [comment]
@taouichaimaa You could refer to this [guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-walkthroughs-managing-access-example1.html) for granting IAM user permission to s3 bucket.
