### ISSUE TITLE
idToken and AuthSession are not refreshed automatically + help for custom lambda approach

### ISSUE THREAD

**Issue by shri-onecup** [aws-amplify/amplify-android#1685]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    def amplifyframework_version = "1.32.2"

    // Amplify
    implementation 'com.amplifyframework:core-kotlin:0.16.2'
    implementation "com.amplifyframework:aws-api:$amplifyframework_version"
    // Datastore
    implementation "com.amplifyframework:aws-datastore:$amplifyframework_version"
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    // Cognito
    implementation "com.amplifyframework:aws-auth-cognito:$amplifyframework_version"

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17.0.1 (Oracle Corporation 17.0.1+12-39)
OS:           Mac OS X 12.3 aarch64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://github.com/aws-amplify/amplify-android/issues/919

### Describe the bug

When the user is signed in but their session has expired, AuthSession is not refreshed automatically because of which I am unable to get a valid idToken. I get an error of "session expired error" followed by an app crash because idToken is being used to fetch smart cookies from CloudFront for media streaming. The authSession is not refreshed unless I sign out and sign back in (for which I am having to uninstall the app and reinstall it because the sign out button is part of the next activity which never gets launched because of app crash).

I had a chat with Pooja Mathur from the android team and she linked me this issue: https://github.com/aws-amplify/amplify-android/issues/919 . Accordingly, I tried to implement a custom lambda but I can't get it to work right.

Kindly help me with either giving a way to make authSession refresh automatically or telling me the exact lambda implementation to get a new session on each app launch using RespondToAuthChallengeRequest(). I am attaching the lambda and code implementation that I have so far based on what I could find on AWS docs. With the current lambda implementation i get error:
<details>
```
com.amazonaws.services.cognitoidentityprovider.model.CodeMismatchException: Invalid code/session provided (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: CodeMismatchException; Request ID: 51b15af7-ac67-4620-b7ce-c1d9783f72ac)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
```
</details>

Also, please guide me with what the "authCode" is supposed to be and how to implement it on lambda side as well.

### Reproduction steps (if applicable)

1. Implement login flow such that you are not automatically logged out on app quit.
2. Sign in user using Amplify.Auth.signIn(username, password)
3. Wait for idToken to expire.
4. Launch the app again while staying signed in.
5. Notice that Amplify.Auth.fetchAuthSession() says something along the lines of "AWSCognitoAuthSession{isSignedIn=true, awsCredentials=null, error=cognito session expired.....}"
6. Session does not refresh automatically as opposed to what AWS docs state [here](https://docs.amplify.aws/lib/auth/overview/q/platform/android/#:~:text=Sumerian%2C%20and%20others.-,Sign%2Dup%20and%20sign%2Din,-For%20many%20apps)

### Lambda
```javascript
exports.handler = (event, context) => {
  if (event.request.session.length === 1 && 
    event.request.session[0].challengeName === 'SRP_A') {
    event.response.issueTokens = false;
    event.response.failAuthentication = false;
    event.response.challengeName = 'CUSTOM_CHALLENGE';
  } else if (
    event.request.session.length === 2 &&
    event.request.session[1].challengeName === 'CUSTOM_CHALLENGE' &&
    event.request.session[1].challengeResult === true
  ) {
    event.response.issueTokens = true;
    event.response.failAuthentication = false;
  } else {
    event.response.issueTokens = false;
    event.response.failAuthentication = true;
  }
  context.done(null, event);
};
```

### Code for refreshing AuthSession using CUSTOM_CHALLENGE lambda

```kotlin
// Put your code below this line.
    suspend fun refreshUsingLambda() {
        val client = AmazonCognitoIdentityProviderClient(AWSMobileClient.getInstance())
        val sessionToken = (Amplify.Auth.fetchAuthSession() as AWSCognitoAuthSession).userPoolTokens.value?.idToken
        val userPool = CognitoUserPool(context, AWSMobileClient.getInstance().configuration)
        val providerKey = "cognito-idp.us-west-2.amazonaws.com/${userPool.userPoolId}"
        val user = userPool.getUser(Amplify.Auth.getCurrentUser()?.username)
        val authChallengeRequest = RespondToAuthChallengeRequest()

        val map = HashMap<String, String>()
        
        val authCode = "testCode"
        map[CognitoServiceConstants.CHLG_RESP_ANSWER] = authCode
        map[CognitoServiceConstants.AUTH_PARAM_USERNAME] = Amplify.Auth.getCurrentUser()!!.username
        // idToken
        authChallengeRequest.session = sessionToken
        // challenge name for Lambda; don't know if it can be changed to other value
        authChallengeRequest.challengeName = "CUSTOM_CHALLENGE"
        authChallengeRequest.clientId = userPool.clientId
        // respond to challenge question with authCode + username
        authChallengeRequest.challengeResponses = map

        user.respondToChallenge(authChallengeRequest, object: AuthenticationHandler {
            override fun onSuccess(
                userSession: CognitoUserSession?,
                newDevice: CognitoDevice?
            ) {
                AWSMobileClient.getInstance().federatedSignIn(providerKey, userSession?.idToken?.jwtToken)
                Log.d(
                    "AmplifyService", 
                    "Successful federated signIn: idToken = " + userSession?.idToken?.jwtToken
                )
            }

            override fun onFailure(exception: java.lang.Exception?) {
                if (exception != null) {
                    Log.e("AmplifyService", "Failed to get session in background: ", exception)
                }
            }

            override fun getAuthenticationDetails(
                authenticationContinuation: AuthenticationContinuation?,
                userId: String?
            ) {
                val authDetails = AuthenticationDetails(
                    userId!!, 
                    prefs.getString(CONSTANTS.PASSWORD, null)!!, 
                    null)
                authenticationContinuation?.setAuthenticationDetails(authDetails)
                authenticationContinuation?.continueTask()
            }

            override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {}

            override fun authenticationChallenge(continuation: ChallengeContinuation?) {}

        }, true).run()
    }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "portal": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
                    "region": "us-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-west-2:xxxxxxxxxxxxx,
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxx",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://xxxxxxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "portal_AMAZON_COGNITO_USER_POOLS"
                    },
                    "portal_AWS_IAM": {
                        "ApiUrl": "https://xxxxxxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "portal_AWS_IAM"
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by shri-onecup** [comment]
This could be a **bug** in Amplify android library. I switched to AWS Mobile SDK and switched my entire login process to AWSMobileClient and everything works. Session and tokens are refreshed automatically.

On Amplify, the session and tokens never refreshed automatically after getting expired. Seems to be a bug. The only solution in the Amplify case was to EITHER force refresh the token (using reflection or customAuthChallenge Lambda) OR Force logout a user and log them back in.

**Comment by div5yesh** [comment]
@shri-onecup I have verified that automatic token refresh works in Amplify. Could it be that refresh token expiration was same as other tokens causing the failure?

Regarding force refresh, please use this workaround: https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-1101894554 and let us know if it fits your use case.
