### ISSUE TITLE
Deleted user

### ISSUE THREAD

**Issue by Muratoter** [aws-amplify/amplify-android#1703]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
"com.amplifyframework:aws-auth-cognito:1.32.1"


```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (AdoptOpenJDK 15.0.2+7)
OS:           Mac OS X 10.16 x86_64



```

</details>

### Describe the bug

How to we can handle deleted cognito user from client side? There is https://docs.amplify.aws/lib/auth/auth-events/q/platform/android/ this event but it's only triggers when delete user using Amplify like; Amplify.Auth.deleteUser(). This events not called delete user manuelly or delete using backend services. 
Is there a any method listen user state like DELETED_USER ?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sdhuka** [comment]
@Muratoter Unfortunately, there is no way to immediately detect user deletion from the backend via some event. The logged-in user will continue to have access until the access token expires (default one hour). One thing you could do is set a shorter expiration on the access token (which can be a minimum of 5 minutes), which would allow them to detect the deletion and handle it sooner. Or send a push notification to the device for a user deletion event and handle it in the app.

**Comment by Muratoter** [comment]
@sdhuka  Thanks a lot, I liked send push notification method.
