### ISSUE TITLE
Android Studio - Navigation Editor not showing previews after using amplify sdk

### ISSUE THREAD

**Issue by rchampa** [aws-amplify/amplify-android#1726]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
api('com.amplifyframework:aws-auth-cognito:1.33.0')

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (JetBrains s.r.o. 11.0.11+0-b60-7590822)
OS:           Mac OS X 11.6.1 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://github.com/rchampa/NavigationXMLBug

### Describe the bug

Suddenly the preview of the navigation graph just dissapear. After a deep research I figure out this problem was triggered right after adding the amplify dependency.

To reproduce this bug, follow the following steps:

1. Clone the repository https://github.com/rchampa/NavigationXMLBug
2. Go to :sharedlibrary build.gradle file and change from:
    `implementation('com.amplifyframework:aws-auth-cognito:1.33.0')`
to
    `api('com.amplifyframework:aws-auth-cognito:1.33.0')`
3. Open the the nav_grap.xml file located in app/anyfeature/res/navigation
4. If you don't see the result as is described in the picture bellow then restart android studio. 
5. The bug is about I cannot see the preview of the nav_graph.xml however I still can use the code section but is anoying see nothing in the preview.

![Screen Shot 2022-05-01 at 15 01 16](https://user-images.githubusercontent.com/3956444/166161068-d56ffb9e-e111-434b-a72e-590ee7981dc2.png)

### Reproduction steps (if applicable)

1. Clone the repository https://github.com/rchampa/NavigationXMLBug
2. Go to :sharedlibrary build.gradle file and change from:
    `implementation('com.amplifyframework:aws-auth-cognito:1.33.0')`
to
    `api('com.amplifyframework:aws-auth-cognito:1.33.0')`
3. Open the the nav_grap.xml file located in app/anyfeature/res/navigation
4. If you don't see the result as is described in the picture bellow then restart android studio. 
5. The bug is about I cannot see the preview of the nav_graph.xml however I still can use the code section but is anoying see nothing in the preview.

### Code Snippet

```java
// Put your code below this line.
There is a repository to replicate this bug. https://github.com/rchampa/NavigationXMLBug
```

### Log output

<details>

```
// Put your logs below this line
This is an android studio problem in compilation time.

```

</details>

### amplifyconfiguration.json

No needed

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
I haven't these details

```

</details>

**Comment by wesam1999** [comment]
may  all the thing is related to handler

**Comment by banji180** [comment]
Hi there, thank you for reporting this issue. Just curious, is there a reason you have decided to use **api** instead of **implementation** prefix to import the cognito library?

**Comment by rchampa** [comment]
Hello @banji180 .
The main reason is because I want to have a shared library(as a gradle module) to be shared across different repositories as a Git sub module.

**Comment by banji180** [comment]
ok got it and apologies for late response. 
Is the com.amplifyframework:aws-auth-cognito:1.33.0 only going to be used by the shared library? If yes, I'd still recommend using implementation so that only sharedlibrary project is able to have access to it.

**Comment by sdhuka** [comment]
@rchampa Please re-open if the above suggestion didn't address the issue.

**Comment by ngolegiahung** [comment]
Hi guys,
I still using "implementation 'com.amplifyframework..." but navigation editor not showing.
Please help me to check it.
