### ISSUE TITLE
Get cached device key

### ISSUE THREAD

**Issue by joe-netcenter** [aws-amplify/amplify-android#1734]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:aws-auth-cognito:1.33.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.15 (Debian 11.0.15+10-post-Debian-1deb10u1)
OS:           Linux 5.10.101-14962-gede4ccb2bf53 amd64

```

</details>

### Describe the feature request

I'm looking for a feature similar to the javascript getCachedDeviceKeyAndPassword() in Android (and iOS!) so that I can access the device id before the user is authenticated; we send this information during sign in to determine if the user's device is remembered. Is it possible to gather this information on mobile? Using Amplify or AWSMobileClient.

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by eeatonaws** [comment]
On Android, after the user has signed in at least once on the device, the following code can be used to retrieve the cached device key stored in shared preferences, even if the user has signed out:
```
val sharedPreferences = applicationContext.getSharedPreferences("AWS.Cognito.ContextData", Context.MODE_PRIVATE)
val deviceKey = sharedPreferences?.getString("CognitoDeviceId", null)
```

**Comment by joe-netcenter** [comment]
Thank you for the response!

So, I was expecting to get a device key of the form {region}-{guid} that matches the device key reported in the Cognito console or list-devices api. However, the CognitoDeviceId in storage is of the form {guid}:{timestamp}, and the guid does not match any device key. Is there any relationship between the two?

**Comment by joe-netcenter** [comment]
We decided to store the deviceKey in sharedPrefs when the signed-in user chooses to remember device. Roughly:

```
        // Remember device
        AWSMobileClient.getInstance().deviceOperations.updateStatus(true, object : Callback<Void?> {
            override fun onResult(result: Void?) {
                Log.d("CustomAuth", "device remember successful")
                AWSMobileClient.getInstance().deviceOperations.get(object : Callback<Device> {
                    override fun onResult(result: Device?) {
                        Log.i("CustomAuth", "got device")

                        val sharedPref = activity?.getSharedPreferences("app_settings", Context.MODE_PRIVATE) ?: return
                        with (sharedPref.edit()) {
                            putString("deviceKey", result?.deviceKey)
                            apply()
                        }
                    }

                    override fun onError(e: java.lang.Exception?) {
                        Log.e("CustomAuth", "could not retrieve device id")
                    }
                })
            }

            override fun onError(e: java.lang.Exception) {
                Log.e("CustomAuth", "device remember error: ", e)
            }
        })
```

Then we retrieve that during custom auth flow sign in.

Thanks much!
