### ISSUE TITLE
DataStore SQLiteModelFieldTypeConverter DateTime and Time value format logics breaks amplify-flutter

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-android#1736]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Since amplify-android version [1.34.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.34.0), a [new change](https://github.com/aws-amplify/amplify-android/pull/1670) has been introduced to `SQLiteModelFieldTypeConverter.java` to ensure unified DateTime, and Time string formats to ensure correct sorting when query sorting by these values.

We've identified this new changes breaks query by AWSTime field functionality in amplify-flutter.

1. Originally amplify-android directly writes amplify-flutter passed Time values in `String` type into SQLite
2. Now amplify-android reformats the values in `String` type as well
3. The new format of the Time value in amplify-android is different from amplify-flutter

Under this condition, when query data using amplify-flutter, it returns empty result, e.g.

Query model with `awsTimeField` values as `00:00:00`
```dart
Amplify.DataStore.query(
  ModelWithAWSTimeField.class,
  where: ModelWithAWSTimeField.AWSTIMEFIELD.eq(
    TemporalTime(DateTime.fromMillisecondsSinceEpoch(0)),
  ),
);
```

With the new format, `00:00:00` is written in SQLite as `00:00:000000000Z`. The format of the value of the query predicate, however, is handled by `Temporal.Time#format`, which doesn't format value into the format as what in the DB tables. therefore DB query returns empty result. 

Summary
* The newly add formatting logic is standalone and `Temporal.Time#format` has a different formatter
* amplify-android should probably not reformat amplify-flutter passed string value

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by poojamat** [comment]
Fixed with the commit:https://github.com/aws-amplify/amplify-android/commit/57a48ed37eaed445188beb2ab6717ee54801c3f9
