### ISSUE TITLE
Dependency conflict with Android "In App Review"

### ISSUE THREAD

**Issue by UrielFrankel** [aws-amplify/amplify-android#1758]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
1.35


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Please update your
     navigationVersion = '2.3.4'
to 
    navigationVersion = '2.4.2'

### Reproduction steps (if applicable)

try to add in app review to an existing project

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

Please dear fellow dev. We are in this together.

**Comment by sdhuka** [comment]
@UrielFrankel Could you please provide details on the issue like stacktrace, repro steps?
