### ISSUE TITLE
Amplify.Storage.** does nothing

### ISSUE THREAD

**Issue by MmedaraJ** [aws-amplify/amplify-android#1790]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy

    // Amplify core dependency
    implementation 'com.amplifyframework:core:1.35.4'
    implementation 'com.amplifyframework:aws-api:1.24.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.24.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.4.0'
    implementation 'com.amazonaws:aws-android-sdk-apigateway-core:2.3.2'

```

</details>

### Environment information

<details>

```

Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html


------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17 (Oracle Corporation 17+35-2724)
OS:           Mac OS X 12.3.1 x86_64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://aws.amazon.com/getting-started/hands-on/build-android-app-amplify/module-four/

### Describe the bug

Amplify.Storage.** does nothing. There is no error message. Just radio silence. 

### Reproduction steps (if applicable)

To reproduce, follow the steps in this tutorial:

https://aws.amazon.com/getting-started/hands-on/build-android-app-amplify/ 

I followed the tutorial to the tee but I am still having the same result. 

### Code Snippet

```kotlin

//This is my storeImage() function:

fun storeImage(filePath: String, key: String) {
        val file = File(filePath)
        val options = StorageUploadFileOptions.builder()
            .accessLevel(StorageAccessLevel.PRIVATE)
            .build()

        Amplify.Storage.uploadFile(
            key,
            file,
            options,
            { progress -> Log.i(TAG, "Fraction completed: ${progress.fractionCompleted}") },
            { result -> Log.i(TAG, "Successfully uploaded: " + result.key) },
            { error -> Log.e(TAG, "Upload failed", error) }
        )
    }

//This is where I call the storeImage() function:

addNote.setOnClickListener {

            // create a note object
            val note = UserData.Note(
                UUID.randomUUID().toString(),
                name?.text.toString(),
                description?.text.toString()
            )

            if (this.noteImagePath != null) {
                note.imageName = UUID.randomUUID().toString()
                //note.setImage(this.noteImage)
                note.image = this.noteImage

                // asynchronously store the image (and assume it will work)
                Backend.storeImage(this.noteImagePath!!, note.imageName!!)
            }

          // ...
}

```

### Log output

<details>

```

I wish I had an error message to show, but no. There is no message concerning amplify.storage on my logcat. Its as if the code does not even run at all.

```

</details>

### amplifyconfiguration.json
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "AdminQueries": {
                    "endpointType": "REST",
                    "endpoint": "xxxxx",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "teststorage": {
                    "endpointType": "GraphQL",
                    "endpoint": "xxxx",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxxx,
                        "AppClientId": "xxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxx",
                            "AppClientId": "xxxxxx",
                            "SignInRedirectURI": "teststorage://",
                            "SignOutRedirectURI": "teststorage://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "xxxxxx",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "teststorage_AMAZON_COGNITO_USER_POOLS"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "xxxxx",
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "xxxxxx",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}
```
### GraphQL Schema

<details>

```graphql

type NoteData
@model
@auth (rules: [ { allow: owner } ]) {
    id: ID!
    name: String!
    description: String
    image: String
}

```

</details>

### Additional information and screenshots

My best guess is my s3 permissions or IAM policy but I have all the permissions and policies I can think of. Still ... nothing. Please help me figure this out.

**Comment by MmedaraJ** [comment]
I am configuring amplify correctly:

fun initialize(applicationContext: Context) : Backend {
        try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSDataStorePlugin())
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            Amplify.addPlugin(JavaLoggingPlugin(LogLevel.VERBOSE))

            Amplify.configure(applicationContext)
            Log.i(TAG, "Initialized Amplify")
        } catch (e: AmplifyException) {
            Log.e(TAG, "Could not initialize Amplify", e)
        }

        Log.i(TAG, "registering hub event")
        .....
}

**Logs:**
...
...
...
D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
D/AWSMobileClient: initialize: Cognito HostedUI client detected
D/AWSMobileClient: Inspecting user state details
I/TetheringManager: registerTetheringEventCallback:com.example.teststorage
I/Backend: Initialized Amplify
I/Backend: registering hub event
I/Backend: retrieving session status
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.us-east-1.amazonaws.com/us-east-1_62xN08DAw
D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.us-east-1.amazonaws.com/us-east-1_62xN08DAw
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor rawQuery in 0 ms inTransaction: false SQL: SELECT `PersistentModelVersion`.`id` AS `PersistentModelVersion_id`, `PersistentModelVersion`.`version` AS `PersistentModelVersion_version` FROM `PersistentModelVersion`;
I/System.out: DEBUG/amplify:aws-datastore: Querying item for: PersistentModelVersion
I/System.out: VERBOSE/amplify:aws-datastore: Attempt to convert value "1ae1b4d0-7894-4f23-831e-ccf6c8439e1c" from field id of type ID in model PersistentModelVersion
I/System.out: VERBOSE/amplify:aws-datastore: Attempt to convert value "2697e529-05a1-3520-9986-b96d0221e61c" from field version of type String in model PersistentModelVersion
I/System.out: DEBUG/amplify:aws-datastore: No ModelMetadata migration needed.
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor.bindValueToStatement(..., value = 1ae1b4d0-7894-4f23-831e-ccf6c8439e1c
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor executeExists in 1 ms inTransaction: false SQL: SELECT EXISTS(SELECT 1 FROM `PersistentModelVersion` WHERE `PersistentModelVersion`.`id` = ?);
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor.bindValueToStatement(..., value = 1ae1b4d0-7894-4f23-831e-ccf6c8439e1c
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor.bindValueToStatement(..., value = 2697e529-05a1-3520-9986-b96d0221e61c
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor.bindValueToStatement(..., value = 1ae1b4d0-7894-4f23-831e-ccf6c8439e1c
I/System.out: VERBOSE/amplify:aws-datastore: SQLCommandProcessor execute in 19 ms inTransaction: false SQL: UPDATE `PersistentModelVersion` SET `id` = ?, `version` = ? WHERE `PersistentModelVersion`.`id` = ?;
W/System: A resource failed to call close. 
W/ple.teststorag: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ple.teststorag: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/MainActivity: Note observer received 0 notes
I/MainActivity: isSignedIn changed : false
D/MainActivity: Hiding fabADD
D/HostConnection: HostConnection::get() New Host Connection established 0xe7b1ebd0, tid 2151
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xe7b20300: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe7b20300: ver 3 0 (tinfo 0xe7e7b110) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xe7b207d0, tid 2151
D/goldfish-address-space: allocate: Ask for block of size 0x100
D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3c7ffe000 size 0x2000
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: hasFederatedToken: true provider: cognito-idp.us-east-1.amazonaws.com/us-east-1_62xN08DAw
D/AWSMobileClient: waitForSignIn: userState:SIGNED_IN
D/AWSMobileClient: getCredentials: Validated user is signed-in
I/Backend: AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=com.amazonaws.auth.BasicSessionCredentials@ecc4934, error=null, type=SUCCESS}, userSub='AuthSessionResult{value=162bace1-009e-4582-9521-b59c120d382e, error=null, type=SUCCESS}', identityId='AuthSessionResult{value=us-east-1:e9207c81-7f69-4f88-a4e2-12dd481cf9c9, error=null, type=SUCCESS}', userPoolTokens='AuthSessionResult{value=AWSCognitoUserPoolTokens{accessToken=eyJraWQiOiJETnNDcW9GUFgyVmpXZVRMY0dXQm5HQUgyRnNob0Vkb2dMV01TNjlnb2ZVPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxNjJiYWNlMS0wMDllLTQ1ODItOTUyMS1iNTljMTIwZDM4MmUiLCJjb2duaXRvOmdyb3VwcyI6WyJBbGxBZG1pbnMiXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfNjJ4TjA4REF3IiwidmVyc2lvbiI6MiwiY2xpZW50X2lkIjoicGJzNTE1a2FnbzViOWo1djhpaDM5NGRsaiIsIm9yaWdpbl9qdGkiOiIwMDM5MGRmNC1hZDE5LTQzM2UtOTBkOS03YTA0YTVhOWViMWMiLCJldmVudF9pZCI6ImE4NTY4Mzc5LTZlOTgtNDI2Zi1hNzQzLTM5Y2RjNDUxMzFlZSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4gcGhvbmUgb3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhdXRoX3RpbWUiOjE2NTU3ODk0OTcsImV4cCI6MTY1NjA5NDk5MCwiaWF0IjoxNjU2MDkxMzkwLCJqdGkiOiI0MzZlMzdmZS04MDZjLTRkODYtYWI4MS0zN2M3OGI3OTY2ZWYiLCJ1c2VybmFtZSI6Im1tZWRhcmFqIn0.gAbBiyo9dKpACDk1xced832VbtP8L3AcwZxAY8PYOdCVL-Pgo8-ZWuyAn9ACYnro6UWvRDfs63jwnjaCe02DqJxUklHDLMPN9ORUZtTfOy51z4VV0kjethotsL1yzU7UfEhwsLTITRqUOyRDoIk2oh7Uqg5uMf7qZSXpT-WICN763CJbvyUBiTbgO1uEDzn7YoauI1_x80VcUYWK48oQZZF7d--SuoT_bkrwsfeFU0V1GC0Ya_pia7pkKlc_XBhpKPIOohCMC83AAQC1dzqp9cSM_AiDzs_dpX8jka9S3ZccQs8X03_spNJvk6UYH12fSTXwJPhYwJqWH0DfUsIWrQ, idToken=eyJraWQiOiJUdUtPa1hhRDlQVVk4dUx1SGV5NmxaOFJGM05rNDlHemVQSE9MTzBuM0p3PSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoidHhjRVhNdWV1VEwzckRjOFgyWGJWZyIsInN1YiI6IjE2MmJhY2UxLTAwOWUtNDU4Mi05NTIxLWI1OWMxMjBkMzgyZSIsImNvZ25pdG86Z3JvdXBzIjpbIkFsbEFkbWlucyJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY29nbml0bzpwcmVmZXJyZWRfcm9sZSI6ImFybjphd3M6aWFtOjo3ODk1MzQ0NzA5MDU6cm9sZVwvdXMtZWFzdC0xXzYyeE4wOERBdy1BbGxBZG1pbnNHcm91cFJvbGUiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV82MnhOMDhEQXciLCJjb2duaXRvOnVzZXJuYW1lIjoibW1lZGFyYWoiLCJvcmlnaW5fanRpIjoiMDAzOTBkZjQtYWQxOS00MzNlLTkwZDktN2EwNGE1YTllYjFjIiwiY29nbml0bzpyb2xlcyI6WyJhcm46YXdzOmlhbTo6Nzg5NTM0NDcwOTA1OnJvbGVcL3VzLWVhc3QtMV82MnhOMDhEQXctQWxsQWRtaW5zR3JvdXBSb2xlIl0sImF1ZCI6InBiczUxNWthZ281YjlqNXY4aWgzOTRkbGoiLCJldmVudF9pZCI6ImE4NTY4Mzc5LTZlOTgtNDI2Zi1hNzQzLTM5Y2RjNDUxMzFlZSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjU1Nzg5NDk3LCJleHAiOjE2NTYwOTQ5OTAsImlhdCI6MTY1NjA5MTM5MCwianRpIjoiNjFhMzU2MzUtMzZkOC00ODY2LTk1MDUtNDI4ODAwZjY5YThkIiwiZW1haWwiOiJtbWVkYXJham9zaWFoQGdtYWlsLmNvbSJ9.DlJZY-qset9QJTMwuUsPI_6GKuzVndpNe4BPOnjE53jITf4_7wclAfotvwaDfMzDvo69Xu8kbqueoG4JYoQ9Ht-yigjxkHI4Rx8YWx9U63QofLwe9V03aL8nOIkhFr5m9yX9LELsG5su7B-7sDaY0EjeH58Y6TilXJFPzig9RVyT1G2BKKefzLzKQ4misGSUgC1qqxxiSck3sLNnDvh70yMRFn9yfZfT2P-eYVKuZ5LX0NXf4H3wA3ZUzkcgJ4aFW1PnKQ5z1gomfWDjCZioD5NUQ1SPlaAZrDN2qBhBPGZgSnGtM3l4A40Bk2TTkIAwpufLvHkM3YqwSYggTJNm0A, refreshToken=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.ZaeOALGwxnu8kiLmeuetIwa3kfyCzMEmuRUqWZwRUsCrdlawlEGzMtREh8R4ohZbeEqucG635hIgsm_fjb6HGLkjWDOdZWrPBOXnJ0dWbY51BBuG1Zzsvk-P6GdDsLgy8Vc3UVksoRfNRvR270BA6BFhyNC-eKETiIEDyg6QRhMiMijdPRzyTdgZ7MeqpNZNc9GGruhSEL-uF9u30r8xT9ieZwPqu1_bsYi4iGAOUczGyMhoF3FDH5S3ySc9dLoQhp_oYxUsQleyk2KFENi4phBcWA2k7BafRuh_kyhIXww0nqqT50xt__p3vhed_wATZKMxE2v9ZHYa2ZwQc6kVmA.GN6y1Lb9pXNr6JMa.z_FDEmipelG4_me4OQl_DRWAzcF5TEmJyrgj2BGLEDGizVIRo4chopSr12w9Dojrfq5azwvSbmKxghj8lrB7tMkVejqOL5WGNZwfql14aC-Wqircgj3kG-yMErdX7LRKmquXXGDEst0LP5aiJIJ1JwFzaifWAC-KF4MiYLkIVGzTRSPtJYndch1_d6HfOWRzRX6Xgkelp_-F_xubIPg7-sEDQSWNkwHj3jiSBIaGdb2zofVasLduKQJ0KjiOvDuSNyNMaz6ka5UeDmkTpjtk_DZIs7Db0X_C6wPzU6znKPLza0SJsA3lUdz1JRIPy2tN4b0jWVQL6d9FCPs05kza5sHC9IWiMoaAwHIxrlpywG9j1T4CTy1lOuXMyjf_eExihjaNjuNy8pZ5VaaAZgUwu-A7UXoBMrzRRboBnrkm2Fc6vr3ysl-pRG2_xTLQUpBEORCNVLol7ALve4CVxzrOo-PkXj-208VUdvpPDCF1kr_IviHnktf8u0Gk3wkc2nYsmsPbizE8UOasCFObVmFIeHOQqrEn_Iaq6WHRN-3X5oGWnovurm1sAIBUH4QSpwTf1tCexv3hb8XPlfwt56YS1yFCdCfF2f_9yZqzTF1nR8t4cSUCeZEMl-N0fbkY3RqUUTdNYtV2
I/Backend: Querying notes
I/MainActivity: isSignedIn changed : true
D/MainActivity: Showing fabADD
I/System.out: DEBUG/amplify:aws-api: Request: {"query": "query ListNoteDatas($limit: Int) {\n  listNoteDatas(limit: $limit) {\n    items {\n      createdAt\n      description\n      id\n      image\n      name\n      owner\n      updatedAt\n    }\n    nextToken\n  }\n}\n", "variables": {"limit":1000}}
I/Backend: IdentityId: us-east-1:e9207c81-7f69-4f88-a4e2-12dd481cf9c9
I/Backend: Queried
I/Backend: Response has no data GraphQLResponse{data='null', errors='[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'listNoteDatas' in type 'Query' is undefined @ 'listNoteDatas'', locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}]'}
I/AssistStructure: Flattened final assist data: 1728 bytes, containing 1 windows, 9 views
D/AddNoteActivity: Select photo activity result : Intent { dat=content://com.google.android.apps.docs.storage/document/acc=1;doc=encoded=XnWCelPNN/fX63LxjYbMReKJtN67Bq8FSQULyPItQy863IYNIxcJyklz4Q== flg=0x1 }
D/AddNoteActivity: Selected image : /data/user/0/com.example.teststorage/cache/image4028340951396296326.image
I/Backend: About to start storing image in S3...
I/Backend: Creating notes
I/System.out: DEBUG/amplify:aws-api: Request: {"query": "mutation CreateNoteData($input: CreateNoteDataInput!) {\n  createNoteData(input: $input) {\n    createdAt\n    description\n    id\n    image\n    name\n    owner\n    updatedAt\n  }\n}\n", "variables": {"input":{"image":"8bd33edd-2cda-490b-aac1-1de1d7edc3f4","name":"Note Title","description":"Note Description","id":"16256d06-cdb2-42d9-8a7c-fc67eb992d93"}}}
D/MainActivity: Note observer received 1 notes
I/Backend: Created
I/Backend: Created Note with id: 16256d06-cdb2-42d9-8a7c-fc67eb992d93

Notice that after "About to start storing image in S3..." prints, nothing related to storing prints.
Even Amplify.API.query() has an error.

**Comment by tylerjroach** [comment]
@MmedaraJ Can you update each of the Amplify library versions to the latest (`1.36.0`). The storage version listed is especially old. I was able to build the sample app as given by the instructions, and am seeing successful uploads.

Try again after updating and see if you are still having the issue. If you are still having an issue, you can click "App Inspection" in Android Studio and check the awss3transfertable to see if the transfer queue is empty, or if it has data. It may also be helpful to set debug breakpoints inside the storage sdk to investigate what is happening.

The query error is a separate one that I'll take a look at.

**Comment by MmedaraJ** [comment]
Thank you for looking into the issue. After talking to AWS Technical Support, I was able to resolve both issue. 

1. Amplify.Storage.** issue: 
    Just like you suggested, I simply had to update each of my Amplify library versions to the latest (1.36.0).

2. Amplify.API.query() issue:
    I had to change my schema from:

```
type NoteData
@model
@auth (rules: [ { allow: owner } ]) {
    id: ID!
    name: String!
    description: String
    image: String
}
```

to:

```
type NoteData
@model(queries: { get: "getNoteData", list: "listNoteDatas" })
@auth (rules: [ { allow: owner } ]) {
    id: ID!
    name: String!
    description: String
    image: String
}
```

After the above schema is pushed, the query "listNoteDatas" is generated in AppSync console. This solves the problem.
