### ISSUE TITLE
Refresh token with authenticationFlowType USER_PASSWORD_AUTH

### ISSUE THREAD

**Issue by aguigon** [aws-amplify/amplify-android#1798]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Environment information

<details>

```
Device : Google Pixel 6 Pro
Android version : 12 et 13
Not tested on simulator
Amplify version: 1.35.7
```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android/

### Describe the bug

Hi,

We need support regarding a bug/strange behavior when we use the authenticationFlowType: USER_PASSWORD_AUTH (required for users migration on a new userpool for our customer).

User is well signed in but we are logged out when amplify try to refresh the sessions tokens when using the refresh_token. Using the documentation with:

```
Amplify.Auth.fetchAuthSession(
    { result: AuthSession -> Log.i("LauncherActivity", result.toString()) },
    { error: AuthException -> Log.e("LauncherActivity", error.toString()) }
)
```

we have the following AWSCognitoAuthSession error: 

```
AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}
```

After a tests on the applications we found the issue by changing the authenticationFlowType from USER_PASSWORD_AUTH to USER_SRP_AUTH (but not possible for our users migration schedule...).

We don't have this behavior with the Javascript implementation of Amplify. We didn't test it on iOS yet.

I found closed issues with the same kind of issue regarding refresh_token but the authenticationFlowType is never mentionned.

For tests purposes we changed the sessions (id & access) tokens duration to 20 minutes (60 days for refresh_token), to be sure of the behavior.

### Reproduction steps (if applicable)

Be sure to allow App Client to use Authentication flows ALLOW_REFRESH_TOKEN_AUTH, ALLOW_USER_PASSWORD_AUTH, ALLOW_USER_SRP_AUTH

signIn user using login / password with authenticationFlowType: USER_PASSWORD_AUTH

Wait until sessions tokens expires

refresh/make a call to Amplify.Auth.fetchAuthSession

### amplifyconfiguration.json

```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-west-1:xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
              "Region": "eu-west-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-west-1_XXXXXXXXXX",
            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
              "OAuth": {
                  "WebDomain": "xxxxxxxxxxxxxxxxxxxxxxxxxx.auth.eu-west-1.amazoncognito.com",
                  "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  "SignInRedirectURI": "xxxxxxxxxx://login/",
                  "SignOutRedirectURI": "xxxxxxxxxx://login/",
                  "Scopes": [
                      "phone",
                      "email",
                      "openid",
                      "profile",
                      "aws.cognito.signin.user.admin"
                  ]
              },
              "authenticationFlowType": "USER_PASSWORD_AUTH"
          }
        }
      }
    }
  }
}
```

### Additional information and screenshots

I'm not the Android developper but only the Solutions Architect on the project, I don't have more informations about the implementation but I'll do my best to answer / ask the developper if you have more questions.

**Comment by sdhuka** [comment]
We tried to repro the issue by setting access token expiry = 5mins, refresh token expiry = 60mins & authFlowType = "USER_AUTH_PASSWORD" and noticed that fetchAuthSession return valid token for 60mins (until refresh token expires ) and then return Session expired error, which is the expected behavior.

Could you please answer following questions

What is the token expiry setting in the cognito console? (General settings -> App client -> show details)
How much time after initial sign-in user is seeing this error?
What do you mean by that "you are not seeing same issue with USER_SRP_AUTH"? fetchAuthSession behavior is same for both the flows.
Could you please share the repro steps?
