### ISSUE TITLE
E/amplify:aws-datastore: Failure encountered while attempting to start API sync

### ISSUE THREAD

**Issue by liyang15515** [aws-amplify/amplify-android#1822]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

  api 'com.amplifyframework:aws-datastore:1.36.1'
    api 'com.amplifyframework:core:1.36.5-dev-preview.0'
    api 'com.amplifyframework:aws-api:1.36.1'

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

 Amplify.DataStore.save(post,
                    update -> Log.i("MyAmplifyApp", "Post updated successfully!"),
                    failure -> Log.e("MyAmplifyApp", "Could not update post, maybe the title has been changed?", failure)
            );
when execute above these code, the model 'post' will save in local Sqlite and sync to remote database DynamoDB.
But sync failed and report the exception log tell us 
E/amplify:aws-datastore: Failure encountered while attempting to start API sync.

### Code Snippet

```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            Amplify.addPlugin(new AWSDataStorePlugin());
            Amplify.addPlugin(new AWSApiPlugin());
            Amplify.configure(getApplicationContext());
            Post post = Post.builder()
                    .title("My First Post888")
                    .status(PostStatus.PUBLISHED)
                    .rating(10)
                    .id("111")
                    .build();

            Amplify.DataStore.save(post,
                    update -> Log.i("MyAmplifyApp", "Post updated successfully!"),
                    failure -> Log.e("MyAmplifyApp", "Could not update post, maybe the title has been changed?", failure)
            );
 } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
        }
        setContentView(R.layout.activity_main);
        main ma=new main();
    }
}
```

### Log output

<details>

```
E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
    DataStoreException{message=DataStore subscriptionProcessor failed to start., cause=GraphQLResponseException{message=Subscription error for Post: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onCreatePost/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onCreatePost/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onCreatePost/_version'', locations='null', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onCreatePost/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onCreatePost/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onCreatePost/_version'', locations='null', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}, recoverySuggestion=Check your internet.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:303)
        at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda5.subscribe(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/amplify:aws-datastore: Caused by: GraphQLResponseException{message=Subscription error for Post: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onCreatePost/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onCreatePost/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onCreatePost/_version'', locations='null', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onCreatePost/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onCreatePost/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onCreatePost/_version'', locations='null', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2(AppSyncClient.java:324)
        at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda5.accept(Unknown Source:8)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:425)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifySubscriptionData(SubscriptionEndpoint.java:248)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$700(SubscriptionEndpoint.java:61)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.processJsonMessage(SubscriptionEndpoint.java:603)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onMessage(SubscriptionEndpoint.java:509)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        	... 3 more
W/amplify:aws-datastore: API sync failed - transitioning to LOCAL_ONLY.

```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "offlinesdk": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://lynz4ahfkfgurmql5pybubpo74.appsync-api.us-west-2.amazonaws.com/graphql",
                    "region": "us-west-2",
                    "authorizationType": "API_KEY",
                    "apiKey": "da2-4ozacwnhqbf75a6jcffpglisyu"
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Todo @model {
  id: ID!
  name: String!
  description: String
}
type Post @model {
  id: ID!
  title: String!
  status: PostStatus!
  rating: Int
  content: String
}

enum PostStatus {
  DRAFT
  PUBLISHED
}

```

</details>

**Comment by liyang15515** [comment]
I am stuck with this error. can some please help me here? I have tried with multiple fresh new project to fix this but getting same error every time.

**Comment by cmllamosas** [comment]
I am seeing the same error.

We are using these dependencies with 1.36.2 version

    implementation "com.amplifyframework:core:$rootProject.amplifyVersion"
    implementation "com.amplifyframework:aws-analytics-pinpoint:$rootProject.amplifyVersion"
    implementation "com.amplifyframework:aws-datastore:$rootProject.amplifyVersion"
    implementation "com.amplifyframework:aws-api:$rootProject.amplifyVersion"
    implementation "com.amplifyframework:aws-predictions:$rootProject.amplifyVersion"
    implementation "com.amplifyframework:aws-storage-s3:$rootProject.amplifyVersion"
    implementation "com.amplifyframework:aws-auth-cognito:$rootProject.amplifyVersion"

**Comment by liyang15515** [comment]
> I am seeing the same error.
> 
> We are using these dependencies with 1.36.2 version
> 
> ```
> implementation "com.amplifyframework:core:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-analytics-pinpoint:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-datastore:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-api:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-predictions:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-storage-s3:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-auth-cognito:$rootProject.amplifyVersion"
> ```



> I am seeing the same error.
> 
> We are using these dependencies with 1.36.2 version
> 
> ```
> implementation "com.amplifyframework:core:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-analytics-pinpoint:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-datastore:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-api:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-predictions:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-storage-s3:$rootProject.amplifyVersion"
> implementation "com.amplifyframework:aws-auth-cognito:$rootProject.amplifyVersion"
> ```

hello boss,Have you resolved your errors?Could you share with me?

**Comment by poojamat** [comment]
@liyang15515 could you please retry the save without supplying the id to the post builder. Let ID be autogenerated.

**Comment by liyang15515** [comment]
> @liyang15515 could you please retry the save without supplying the id to the post builder? Let ID be autogenerated.

yes I had done without the id,also it was not work and reported same error.

**Comment by liyang15515** [comment]
> @liyang15515 could you please retry the save without supplying the id to the post builder? Let ID be autogenerated.

hello sir, this following is my whatsapp +8613926407056,we can communicate on whatsapp or telegram

**Comment by lighthuangfu** [comment]
seems ModelMetadata not auto fill in the custom object, then the server report this error ??

**Comment by chrisbonifacio** [comment]
Hi @liyang15515 👋 if you are still experiencing this issue please make sure that DataStore is enabled on your AppSync API by configuring Conflict Resolution via the Amplify CLI command `amplify update api`. If you already had existing data before enabling DataStore, it will not be synced unless they have a value for `_lastChangedAt` and `_version` as they are required and non-nullable.

**Comment by mengshuaishuai** [comment]
> Hi @liyang15515 👋 if you are still experiencing this issue please make sure that DataStore is enabled on your AppSync API by configuring Conflict Resolution via the Amplify CLI command `amplify update api`. If you already had existing data before enabling DataStore, it will not be synced unless they have a value for `_lastChangedAt` and `_version` as they are required and non-nullable.

We have fix this problem, but we got another serious problem within sync data, the exception message like below--

2022-09-15 20:28:12.051 32663-1141/com.retech.offline_retech W/amplify:aws-api: Websocket connection failed.

2022-09-15 20:28:12.055 32663-1141/com.retech.offline_retech W/amplify:aws-datastore: API sync failed - transitioning to LOCAL_ONLY.
    DataStoreException{message=Error during subscription., cause=ApiException{message=Subscription failed., cause=com.google.gson.JsonParseException: Got JSON from an API call which was supposed to go with a List but is in the form of an object rather than an array. It also is not in the standard format of having an items property with the actual array of data so we do not know how to deserialize it., recoverySuggestion=Check your Internet connection. Is your device online?}, recoverySuggestion=Evaluate details.}

**Comment by eeatonaws** [comment]
Closing this issue since the original issue is resolved. @mengshuaishuai if you are still experiencing the sync issue with the latest version of Amplify Android, please open a new issue including the logs you shared above and describing the issue you're observing.
