### ISSUE TITLE
IllegalArgumentException thrown when performing POST request with zero length (but not null) body

### ISSUE THREAD

**Issue by AALLx** [aws-amplify/amplify-android#1831]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

REST API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
com.amplifyframework:aws-api:1.36.1
```

</details>

### Environment information

<details>

```
# Put output below this line
# Put output below this line

Welcome to Gradle 7.5!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5/release-notes.html


------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0-25 (Microsoft 25.71-b00)
OS:           Windows 10 10.0 amd64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://github.com/aws-amplify/amplify-android/blob/main/aws-api/src/main/java/com/amplifyframework/api/aws/auth/IamRequestDecorator.java

### Describe the bug

On previous versions, it was possible to call the POST API with an empty body by providing a zero-length byte[] to the data parameter. Using amplify-flutter, it was possible to construct a POST RestOptions like below:
`    final options = RestOptions(
      path: 'path/of/the/api',
      body: Uint8List(0),
      headers: {
        'X-WebSocket-Connection-Id': '1234567890',
      },
    );`

Doing the above now throws an error:
`E/AndroidRuntime( 7582): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 7582): Process: com.accenture.emobility, PID: 7582
E/AndroidRuntime( 7582): java.lang.IllegalArgumentException: method POST must have a request body.
E/AndroidRuntime( 7582): 	at okhttp3.Request$Builder.method(Request.kt:254)
E/AndroidRuntime( 7582): 	at com.amplifyframework.api.aws.auth.IamRequestDecorator.decorate(IamRequestDecorator.java:124)
E/AndroidRuntime( 7582): 	at com.amplifyframework.api.aws.AWSApiPlugin.lambda$configure$0(AWSApiPlugin.java:161)
E/AndroidRuntime( 7582): 	at com.amplifyframework.api.aws.AWSApiPlugin$$ExternalSyntheticLambda1.intercept(Unknown Source:4)
E/AndroidRuntime( 7582): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/AndroidRuntime( 7582): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/AndroidRuntime( 7582): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/AndroidRuntime( 7582): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 7582): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 7582): 	at java.lang.Thread.run(Thread.java:920)
I/Process ( 7582): Sending signal. PID: 7582 SIG: 9`

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

The issue seems to be caused by the fix to this item https://github.com/aws-amplify/amplify-android/pull/1684

By excluding zero length body from the code change below:
`            if (body != null && body.contentLength() > 0) {
                //write the body to a byte array.
                final Buffer buffer = new Buffer();
                body.writeTo(buffer);
                bodyBytes = IOUtils.toByteArray(buffer.inputStream());
            } else {
                isEmptyRequestBody = true;
                bodyBytes = "".getBytes();
            }`

It caused zero length body to be assigned as null:
`        if (!isEmptyRequestBody) {
            requestBody = RequestBody.create(bodyBytes, JSON_MEDIA_TYPE);
        } else {
            requestBody = null;
        }`

**Comment by eeatonaws** [comment]
Thank you for reporting this issue. A fix for the issue has been released as part of Amplify Android 1.37.0.
