### ISSUE TITLE
[API] Subscribe fails for API auth types other than API key

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/amplify-android#185]
Other API operations support auth types other than API key but Subscription breaks if the Customer selected one of those because it was hard coded to only support API key:

https://github.com/aws-amplify/amplify-android/blob/master/aws-api/src/main/java/com/amplifyframework/api/aws/SubscriptionAuthorizationHeader.java#L34

**Comment by NirpE** [comment]
Is there any estimate when other authentication methods will be available with subscription? E.g. Cognito user pool which is pretty much the standard way when using AWS stack. 

If this is not in near road map, can you point me to mobile client docs or example where Amplify is used with apiKey method and cloud database data is owner protected, in other words how I can achieve auth rule to allow owner only when using apiKey auth method?

**Comment by jpignata** [comment]
Thanks, @NirpE! This is on our near-term roadmap. I expect it to be out in our end-of-April preview release.

**Comment by jamesonwilliams** [comment]
@raphkim Was this issue #185 resolved by your PR https://github.com/aws-amplify/amplify-android/pull/502 ? If so, can we close this #185?

**Comment by raphkim** [comment]
> @raphkim Was this issue #185 resolved by your PR #502? If so, can we close this #185?

Yessir! Closing the issue
