### ISSUE TITLE
[API] Subscribe fails if model has owner authorization

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/amplify-android#186]
If a model has @auth(rules: [{allow: owner}]) AppSync requires an owner parameter be passed to the subscribe function but we currently are not generating this when we build the GraphQL Request for subscribe on these models. 

Furthermore, the CLI model gen does not indicate which models have this type of auth so we would not be able to know when to generate it.

**Comment by jamesonwilliams** [comment]
Some work has been started on this in https://github.com/aws-amplify/amplify-android/pull/559.

**Comment by a-melnyk** [comment]
Hi all,

is there a workaround for this issue (besides disabling authentication)? if my app doesn't use `DataStore.observe` would it be possible to skip the subscription request?

Another more general question: Could someone please give an estimate when the framework will be production-ready? in terms of stability (offline mode compatibility, not crash the app) and support for all Amplify features (like this one and AppSync Scalar types).
Background: my team builds an android application which has to be production-ready in 2 months and we have to decide if we can count on Amplify Framework or if we have to re-evaluate other options (apollo-android+AppSync & aws-android-sdk-cognitoidentityprovider+Cognito vs Firebase)

Thanks!

**Comment by richardmcclellan** [comment]
Support for owner based auth has been added for `AWSApiPlugin` and `AWSDataStorePlugin`, in version `1.1.0`, released today.   Full end to end functionality also requires an update to the CLI though, so that codegen will add `@AuthRule` annotations to each generated model.    This work is in progress here: https://github.com/aws-amplify/amplify-cli/pull/4717
