### ISSUE TITLE
Pinpoint analytics escape hatch is not configured correctly.

### ISSUE THREAD

**Issue by naveenthontepu** [aws-amplify/amplify-android#1867]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Analytics

### Gradle script dependencies

<details>

```groovy

implementation 'com.amplifyframework:aws-analytics-pinpoint:1.36.5'

```

</details>

### Environment information

<details>

```
Welcome to Gradle 7.4!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4/release-notes.html


------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Azul Systems, Inc. 17.0.2+8-LTS)
OS:           Mac OS X 12.2.1 aarch64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/analytics/escapehatch/q/platform/android/

### Describe the bug

The escape hatch provided for Pinpoint analytics is returning the [AnalyticsClient](https://github.com/aws-amplify/amplify-android/blob/main/aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java#L430-L433) instead of the `PinpointManager`. This behaviour is inconsistent with the iOS package's [escape hatch](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter.swift#L46-L48). 

The escape hatch is required to `PinpointManager`  as I want to use the `NotificationClient` provided by the `PinpointManager` to register my FCM token to endpoint being created by amplify. 

Due to this I am having to manual create a different instance of `PinpointManager` and then register the FCM token to the endpoint.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by naveenthontepu** [comment]
Any update on when this will be releases?

**Comment by tjleing** [comment]
Hello @naveenthontepu, we launched the new Push Notifications category for Android earlier this year. You can find the documentation [here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/android/). You should be able to implement Push Notifications for your app using this new category. Please reach out to us if you are looking for additional use cases. Thank you!
