### ISSUE TITLE
Use Amplify in a library (.aar)

### ISSUE THREAD

**Issue by suchiz** [aws-amplify/amplify-android#1870]
Hello everyone,

I am making an android SDK and I am using AWS s3 to store and load some data.
I used amplify on my test app (which is implementing my SDK), and it is working well and was really easy to setup.

The thing is that the commands  `amplify init/add storage/push` is setting up the current app, and not the SDK.
I've chosen the `res/raw` folder of my SDK but it looks like the awsconfiguration.json and amplifyconfiguration.json aren't embedded with the library.

It only works for my app, not for others who only integrates my SDK.
I couldn't find any documentation on this. Do you guys have any suggestions ?

**Comment by banji180** [comment]
Were you in the SDK folder when you ran the amplify init/add storage/push commands? Also, when you added the AWS libraries in your gradle, did you use api or implementation commands to add them?

**Comment by suchiz** [comment]
Hi @banji180 

Thanks for you quick reply.
`amplify init/add storage/push` were done on the root project, not in the SDK indeed. But while filling the amplify init prompt I've chosen to put amplify resources in the SDK one.

I added AWS librairies using the implementation commands:
```
    // Amplify core dependency
    def amplify_version = "1.36.4"
    implementation "com.amplifyframework:core:$amplify_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
```

**Comment by sdhuka** [comment]
Adding the amplify configuration to the app res is the correct behavior here. If you are integrating aws-sdk into your sdk, then your sdk should read the amplify configuration from the app res/raw folder and then use it to initiliaze aws-sdk([AmazonS3Client](https://github.com/aws-amplify/amplify-android/blob/main/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java)) from your sdk.

Please let us know if you have any questions.

**Comment by suchiz** [comment]
Can't I use for the SDK ?
```
        try {
            // Add these lines to add the AWSCognitoAuthPlugin and AWSS3StoragePlugin plugins
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());

            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
        }
    }
 ```
 The upload method from Amplify is way more intuitive and easy to read/maintain than TransferUtility from AmazonS3Client.
 
 >  then your sdk should read the amplify configuration from the app res/raw folder
 
 The thing is that I can't force people who integrate my SDK to get an amplify configuration in their app. That is why I wanted to put them in my SDK res/raw.
 
 I will try the workaround, as it is blocking for the app, and I will let you know.
 Thanks for the support !

**Comment by suchiz** [comment]
Hello everyone,

Moving the ` amplify init/add storage/push`  and choosing the SDK `res/raw` did the job
Thank for your support !
