### ISSUE TITLE
getType breaks schemas with "Type"

### ISSUE THREAD

**Issue by joekiller** [aws-amplify/amplify-android#1878]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

1.37.0
```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Short report via mobile but important. The getType method breaks any schemas with a field of "Type".

This'll affect anyone merging into 1.37.0. I suggest using an underscore or adopting a reserve world prefix for the future to avoid snafu. A reserve word could be amplify. So amplifyType would make the method getAmplifyType.

This'll really hose us if this is the future.

https://github.com/aws-amplify/amplify-android/blame/bf50967cc789a526d860415da3d5b63792c48ce2/aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelMetadata.java#L73

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
type TemperatureRecord  @model @auth(rules: [{ allow: owner }]) {
reading: Float!
type: TemperatureType
}

enum TemperatureType {
  FAHRENHEIT
  CELSIUS
}

type BloodRecord @model @auth(rules: [{ allow: owner }])  {
type: BloodType
whiteBloodCount: Float!
cholesterol: Float!
}

enum BloodType {
 A_PLUS
 A_MINUS
 B_PLUS
 B_MINUS
 O_PLUS
 O_MINUS
 AB_PLUS
 AB_MINUS
}

type AlertEvent @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  eventId: String!
  type: String!
  state: String!
  actionTime: String!
  recordedTimeStamp: Int!
}

```

</details>

**Comment by poojamat** [comment]
Fixed with release: https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.37.2

**Comment by joekiller** [comment]
Thanks for addressing this @poojamat
