### ISSUE TITLE
Delete user account from AWS Cognito using the Amplify Android SDK

### ISSUE THREAD

**Issue by mregnauld** [aws-amplify/amplify-android#1910]
**Which AWS Services is the feature request for?**
Cognito

**Is your feature request related to a problem? Please describe.**
Using `AWSMobileClient` in an Android app allows to do pretty much anything, except deleting a user. A user cannot delete his account by himself from AWS Cognito only using `AWSMobileClient`.

**Describe the solution you'd like**
Is it possible to get a function that allows users to delete their accounts from AWS Cognito, using a command like `AWSMobileClient.getInstance().deleteUser(...)`?

**Environment**
AWS SDK for Android 2.14.1

**Comment by div5yesh** [comment]
Yes, delete user API is available in Amplify starting v[1.33.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.33.0) and Android SDK starting v[2.40.0](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.40.0). Refer docs: https://docs.amplify.aws/lib/auth/delete_user/q/platform/android/
