### ISSUE TITLE
uploadInputStream idle after restoring internet access

### ISSUE THREAD

**Issue by pcanas** [aws-amplify/amplify-android#1926]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:core:1.28.1'
implementation 'com.amplifyframework:aws-api:1.28.1'
implementation 'com.amplifyframework:aws-auth-cognito:1.28.1'
implementation 'com.amplifyframework:aws-datastore:1.28.1'
implementation 'com.amplifyframework:aws-storage-s3:1.28.1'

```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_331 (Oracle Corporation 25.331-b09)
OS:           Mac OS X 12.3.1 x86_64
```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/storage/upload/q/platform/android/#upload-files

### Describe the bug

I would like to run the function `uploadInputStream` with no internet access so that it starts the upload as soon as internet connectivity is restored.

Most of the times this works fine, and the upload starts right when reconnecting, but sometimes the upload does not happen, and no value is returned either as a success or error.

Is there anyway I can handle these scenarios?

### Reproduction steps (if applicable)

1. Disconnect from WiFi and data (no internet access).
2. Run `uploadInputStream`
3. Re-connect. Most of the times it will commence the upload right away, but sometimes the function stays idle (neither success nor error is returned).

### Code Snippet

```kotlin
// This way of setting a socket timeout is deprecated, we need to find another alternative
val awsS3StoragePlugin = Amplify.Storage.getPlugin("awsS3StoragePlugin") as AWSS3StoragePlugin
val client = awsS3StoragePlugin.escapeHatch
client.setConfiguration(ClientConfiguration().apply {
    socketTimeout = 0
})

...

Amplify.Storage.uploadInputStream(key, stream,
    { onSuccess() },
    {
      Log.e("MyAmplifyApp", it.toString())
    }
)
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by pcanas** [comment]
@banji180 any updates on this?

**Comment by pcanas** [comment]
Hey @banji180 sorry to bug you again but I was wondering if you've had the time to check this issue. Thanks!

**Comment by pcanas** [comment]
@sdhuka any updates? thanks!

**Comment by sdhuka** [comment]
@pcanas I will try to repro this on my end, but it would be helpful if you could share the logs after the device goes online to investigate why the upload is not resumed.

**Comment by sdhuka** [comment]
We tried to repro and could not repro on our end. It would be helpful if you could share the logs for us to investigate further.
