### ISSUE TITLE
Compound Filters in ModelQuery Predicate OR/AND/NOT in android

### ISSUE THREAD

**Issue by AsitDixit** [aws-amplify/amplify-android#1945]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
    implementation 'com.amplifyframework:core:1.35.4'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'com.amplifyframework:aws-auth-cognito:1.35.4'
    implementation 'com.amplifyframework:aws-api:1.35.4'
    implementation 'com.amplifyframework:aws-datastore:1.35.4'

```

</details>

### Environment information

<details>

```


android studio 
```

</details>

### Link

[Documentation  for Javascript](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js/#compound-filters)

### Describe the bug

```query(ModelQuery.list(Todo.class,Todo.TITLE.eq("5") || Todo.DESCRIPTION.between("s","a"), ModelPagination.limit(10)));```
In the above code I'm getting an error ```Operator '||' cannot be applied to 'com.amplifyframework.core.model.query.predicate.QueryPredicateOperation<java.lang.Object>', 'com.amplifyframework.core.model.query.predicate.QueryPredicateOperation<java.lang.String>```.

My question is how to add or/and/not operator in android using java. I saw documentation this is only described for Javascript as:
```
let filter = {
      or: [{ priority: {eq:1} },
           { priority: {eq:2} }]
  };
await API.graphql({ query: listProducts, variables: { filter: filter}}));
```

Can we do the same in android java??

**Comment by AnilMaktala** [comment]
Hi @AsitDixit 👋 , Yes it is possible. Please use "And" or "or" instead of || symbol. 
ex:  ModelQuery.list(Todo.class,Todo.NAME.eq("5").and(Todo.PRIORITY.between("NORMAL","HIGH"))).

**Comment by AnilMaktala** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
