### ISSUE TITLE
Persistence of Storage uploadInputStream when no internet access

### ISSUE THREAD

**Issue by pcanas** [aws-amplify/amplify-android#1947]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the feature request

I would like to use the Storage's function `uploadInputStream` when the internet connection is not guaranteed. I know that the service would enqueue the event until the internet access is restored, but I had a couple of questions regarding the persistence of this queue.
* Does the upload start even after the variable is destroyed?
* Does the upload start after the activity gets destroyed?
* Does the upload start after the application is closed?
* Is there a timeout after which the events would get dequeued?

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sdhuka** [comment]
Once a transfer is queued using the Amplify api, a record is created in the local sqlite database and the transfer will be started once the network is available and enqueued again if for some reason the network is interrupted in between the transfers.

To answer your question, upload will start irrespective of the variable or activity lifecycle. If the application is stopped for whatever reason, transfer will resume when the application is opened again.

There is no time limit after which the transfer will be dequeued. To cancel the transfer, you have to use the cancel API on the operation object returned by the API.

**Comment by pcanas** [comment]
@sdhuka Thanks for your prompt and complete answer! And by the way, this is an amazing feature :)
