### ISSUE TITLE
When we will have unity SDK ?

### ISSUE THREAD

**Issue by Thaina** [aws-amplify/amplify-android#195]
I want to to use datastore sync with unity

**Comment by desokroshan** [comment]
@Thaina Thanks for your interest in Amplify framework. We currently do not have a timeline for Amplify datastore category support in Unity SDK. I have taken this as a feature request and will update this thread with details after discussion with the team.

**Comment by jpignata** [comment]
Thanks for your feature request. We've logged this feature request with our product team.

**Comment by alionthego** [comment]
I have just begun developing with Unity.  Previously I have used the amplify iOS SDK.  What would be the equivalent if I wanted to add an amplify backend to a unity app?  Is that achievable at the moment?

**Comment by smhk** [comment]
Please hurry up guys!  The most natural thing in the world is unity + amplify.  50% of the world's apps would be unity + amplify.

**Comment by ilmarioranen** [comment]
> Please hurry up guys! The most natural thing in the world is unity + amplify. 50% of the world's apps would be unity + amplify.

Couldn't have said it better. Incredibly weird that something so natural and needed by the industry seems to still be ignored.

**Comment by JulesThuillier** [comment]
Still nothing ?
