### ISSUE TITLE
Enabling soft deletion: `_deleted` value does not exist in my DynamoDB entries

### ISSUE THREAD

**Issue by pcanas** [aws-amplify/amplify-android#1982]
I was following the [How it works section video](https://www.youtube.com/watch?v=KcYl6_We0EU) on Datastore, and I realized that in the demo they were using the field  `_deleted` which allowed for soft deletion. After a standard setup of my Datastore API, I cannot find this field, and I was wondering how I could enable soft deletion within my application.

Other default fields like `__typename`, `_version`, and `_lastChangedAt` exist in my DDB table.

This is an example of an item in my schema:
```
type Institution @model {
  id: ID!
  name: String!
  address: String!
  country: String!
  users: [User] @connection(name: "UserInstitution")
}
```

And the following is the `transform.conf.json` file (in case it is useful).
```
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        }
    }
}
```

Thanks for the help!

**Comment by AnilMaktala** [comment]
Hey @pcanas 👋, Thank you for raising the issue. You need to delete at least one record to see the _deleted field in the dynamoDB table. Please verify after deleting the record and let us know if you still need more information.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/3206171/196729366-6466a193-b168-48c4-aadb-8f8daee21c6d.png">
