### ISSUE TITLE
Offline device data overrides BE server data 

### ISSUE THREAD

**Issue by anas-najjar** [aws-amplify/amplify-android#1997]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy

implementation "com.amplifyframework:core:1.37.4"
implementation "com.amplifyframework:aws-auth-cognito:1.37.4"
implementation 'com.amplifyframework:aws-api:1.37.4'
implementation "com.amplifyframework:aws-datastore:1.37.4"
```

</details>

### Environment information

<details>

```
Welcome to Gradle 6.7.1!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7.1/release-notes.html


------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_321 (Oracle Corporation 25.321-b07)
OS:           Mac OS X 12.5.1 x86_64
```

</details>

### Describe the bug

While we are using the app offline or are storing some actions and data on the Datastore and another actions form another online devices affect the data and changes the metadata version on the server.
when the offline device back to online state and start syncing the data the metadata version changed to the latest server version and then the offline data overrides the server data since the app send the old data with the latest metadata version.

The Expected behaviour is to send the old data with the old version and a conflict should occur.
Conflict resolution strategy: Custom Lambda

### Reproduction steps (if applicable)

1. Go offline and do some changes on the Datastore.
2. Go to another client and do some other changes and sync it to the server to create a newer version on the remote.
3. Go back to the offline app and return it to online state and sync the changes.
4. Offline data override server data

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by AnilMaktala** [comment]
Hi @anas-najjar :wave thank you for raising this issue, can you please share your schema and custom lamda logic you used for conflict resolution.

**Comment by ala-harri** [comment]
This case is happening in our side and it doesn't allow us to have a conflict history in our system.

After digging into the code, The change made here breaks the flow
https://github.com/aws-amplify/amplify-android/pull/1319/files#r633739437

> The item in the outbox wins over any model coming from the API. However, we do still need to update the metadata, so that when the item in the outbox does get processed, it doesn't get rejected because the _version is too old.

Simply we need the item in the outbox to be detected as a Conflict if the `_version` is old, so our Conflict Resolution Handler gets triggered and determine which item to keep.

**Comment by AnilMaktala** [comment]
Hey @ala-harri 👋 , are you using the custom lamba as conflict resolution strategy?

**Comment by ala-harri** [comment]
> Hey @ala-harri 👋 , are you using the custom lamba for conflict resolution?

 @AnilMaktala Yes custom lamba.

**Comment by AnilMaktala** [comment]
@ala-harri will you be able to share the graphql schema and custom lamda logic?

**Comment by AnilMaktala** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
