### ISSUE TITLE
GraphQL query processing slowly and showing "Long monitor contention"

### ISSUE THREAD

**Issue by kingmarleycoffee** [aws-amplify/amplify-android#2017]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API, DataStore

### Amplify Categories

api, flutter

### Environment information

I got Long monitor contention with owner pool-4-thread-87 (4997) at void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String)(SubscriptionEndpoint.java:-1) waiters=24 in void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String) repeated 85 times when i am trying to get data from amplify using GraphQL 

### Describe the bug

Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=0 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 2.732s

### Expected behavior

get a data without taking all this time, it takes more than 1 minute to get the data.

### Reproduction steps

-

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=76 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 28.951s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=77 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 29.275s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=78 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 29.659s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=79 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 30.069s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=80 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 30.396s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=81 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 30.680s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=82 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 31.096s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=83 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 31.501s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=84 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 31.910s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=85 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 32.320s
I/amplify:aws-datastore( 4656): Started subscription processor for models: [29 models] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
I/System.out( 4656): [socket]:check permission begin!
2
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background young concurrent copying GC freed 66102(4853KB) AllocSpace objects, 20(412KB) LOS objects, 53% free, 4724KB/10146KB, paused 1.226ms total 107.410ms
3
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background concurrent copying GC freed 53277(4787KB) AllocSpace objects, 26(696KB) LOS objects, 49% free, 4515KB/9030KB, paused 568us total 142.228ms
2
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background concurrent copying GC freed 38826(3958KB) AllocSpace objects, 2(32KB) LOS objects, 49% free, 4816KB/9633KB, paused 693us total 166.281ms
5
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background young concurrent copying GC freed 51056(4199KB) AllocSpace objects, 5(108KB) LOS objects, 43% free, 5432KB/9633KB, paused 1.515ms total 121.137ms
W/amplify:aws-datastore( 4656): Initial cloud sync failed for Users.
W/amplify:aws-datastore( 4656): DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Cannot return null for non-nullable type: 'EmployersAds' within parent 'Users' (/syncUsers/items[27]/employersAds)', locations='null', path='[GraphQLPathSegment{value='syncUsers'}, GraphQLPathSegment{value='items'}, GraphQLPathSegment{value='27'}, GraphQLPathSegment{value='employersAds'}]', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
W/amplify:aws-datastore( 4656): 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:116)
W/amplify:aws-datastore( 4656): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
W/amplify:aws-datastore( 4656): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:151)
W/amplify:aws-datastore( 4656): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
W/amplify:aws-datastore( 4656): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore( 4656): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore( 4656): 	at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:datastore( 4656): DataStoreException{message=Initial cloud sync failed for Users., cause=DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Cannot return null for non-nullable type: 'EmployersAds' within parent 'Users' (/syncUsers/items[27]/employersAds)', locations='null', path='[GraphQLPathSegment{value='syncUsers'}, GraphQLPathSegment{value='items'}, GraphQLPathSegment{value='27'}, GraphQLPathSegment{value='employersAds'}]', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}

**Comment by kingmarleycoffee** [comment]
Hi @chrisbonifacio can you please mention the Android repo that issue transferred to

**Comment by HuiSF** [comment]
Hi @kingmarleycoffee how many models have created in your Amplify App?

When the sync engine starts, it creates subscriptions to App Sync for each model that you have in the App, and each model creates 3 subscription (create, update and delete). 

Looking at the logs you provided, the subscription seemed working correctly, the issue actually happened on syncing the `Users` model. 

```
Cannot return null for non-nullable type: 'EmployersAds' within parent 'Users
```

 I believe you set `EmployersAds` as required in the `Users` model? Can you check if you have any `Users` record that doesn't have associated `EmployersAds` in your Dynamo DB table.

**Comment by AnilMaktala** [comment]
Hi @kingmarleycoffee 👋, Will you be able to share your graphql schema?

**Comment by RamaTechnology** [comment]
Hi @HuiSF  , actually I have 37 models in my App.

I tried to test my app with empty tables, I just insert only one record in non-related table and tried to retrieve this data and these duplicate and slow issue appear.

**Comment by chrisbonifacio** [comment]
> Hi @HuiSF , thanks for your response actually I have 37 models in my App.
> 
> I tried to test my app with empty tables, I just insert only one record in non-related table and tried to retrieve this data and these duplicate and slow issue appear.

Just out of curiosity, how many records might you be syncing down per model/table?

Also, we noticed you have 37 models. You would be hitting a subscription limit of 100 set by AppSync because DataStore subscribes to create, update, and delete mutations on all models. At 33 models, that is 99 subscriptions already. To increase this limit, you have to open a support ticket for a service limit increase with AppSync.

**Comment by RamaTechnology** [comment]
Hi @chrisbonifacio, thanks for response, the records might be more than 1000, but I got same sync time when I am retrieving one record. 
Where I should open the ticket that you mentioned. and what exactly the process and procedure that I should go forward.

**Comment by AnilMaktala** [comment]
Hey @RamaTechnology, You can request AppSync quota increase here:[link](https://us-east-1.console.aws.amazon.com/servicequotas/home/services/appsync/quotas/L-AA33EB36)

for more information on AppSync limits please refer this page:[link](https://docs.aws.amazon.com/general/latest/gr/appsync.html)

**Comment by AnilMaktala** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
