### ISSUE TITLE
CI/CD Infrastructure

### ISSUE THREAD

**Issue by kvasukib** [aws-amplify/amplify-android#21]
1. Currently we rely on the developer running `./gradlew build` locally before pushing any code. We want to introduce a CircleCI process for this.

2. We are using the following spec:

Android Platform 29
Java 1.8 Source compatibility

We need to install these tools as part of the build script.

**Comment by jamesonwilliams** [comment]
I believe this was duplicated in #27. Regardless, a basic CircleCI configuration has now been on-boarded.
