### ISSUE TITLE
[API] GraphQL - Support for different Id fields and range keys

### ISSUE THREAD

**Issue by asyschikov** [aws-amplify/amplify-android#210]
Amplify Android imposes an unreasonable requirement that every model must have an ID field called exactly `id`. I see no reason why this particular name is hardcoded everywhere, and it is a significant limitation when dealing with schema created before. Also there is no support for range (sort) keys.

From [the source](https://github.com/aws-amplify/amplify-android/blob/4df9cd4fbd95d3ed8e4caa0bd5568de38fa79629/aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java#L76-L86):

```
doc.append("query ")
    .append("Get")
    .append(StringUtils.capitalizeFirst(graphQlTypeName))
    .append("(")
    .append("$id: ID!) { get")
    .append(StringUtils.capitalizeFirst(graphQlTypeName))
    .append("(id: $id) { ")
    .append(getModelFields(modelClass, DEFAULT_LEVEL_DEPTH))
    .append("}}");

variables.put("id", objectId);
```

**Comment by richardmcclellan** [comment]
Custom primary keys is something we may add in the future.  Closing in favor of this open feature request: https://github.com/aws-amplify/amplify-android/issues/869
