### ISSUE TITLE
Lambdafication of Android Category Behaviors

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-android#212]
The current syntax required when using our category behaviors is pretty verbose. For example, a user passes an anonymous instance of `ResultListener` or `StreamListener` when invoking an API behavior:

```
Amplify.API.query(Person.class, new ResultListener<Iterable<Person>> {
    @Override
    public void onResult(Iterable<Person> people) {
        Log.i(TAG, "Found people via remote API: " + people);
    }
    
    @Override
    public void onError(Throwable error) {
        Log.e(TAG, "Error querying the API.", error);
    }
});
```

The `ResultListener` above is one of two widely-used callback interfaces defined in our Core library. The `ResultListener` and its sibling `StreamListener` are used extensively throughout the category contracts. These two callback interfaces had been modeled after Rx’s [`Observer`](http://reactivex.io/RxJava/javadoc/io/reactivex/Observer.html)  and [`SingleObserver`](http://reactivex.io/RxJava/javadoc/io/reactivex/SingleObserver.html):

```
// A poor man's io.reactivex.SingleObserver
interface ResultListener<T> {
    void onResult(T result);
    void onError(Throwable error);
}
```
```
// A poor man's io.reactivex.Observer
interface StreamListener<T> {
    void onNext(T item);
    void onComplete();
    void onError(Throwable error);
}
```

However, consumers of Rx rarely use these, directly. Rx provides a family of convenience methods to subscribe to an `Observable` or to a `Single`, by providing lambdas. For example, instead of specifying an `Observer` instance during the call to `subscribe(..)`, an Rx user instead does:

```
someObservable.subscribe(
    /* onNext */ item -> Log.i(TAG, "Got an item: " + item),
    /* onError */ error -> Log.e(TAG, "An error occurred.", error)
);
```

That’s 4 lines of code, instead of 11 like we have with the `ResultListener` in our API behavior.

*The core problem is that `ResultListener` cannot be expressed as a lambda, since it is not a simple functional interface as defined in the Java Language Specification (JLS).*

## A Proposal

Rx addresses this problem by using a [`Consumer`](http://reactivex.io/RxJava/javadoc/io/reactivex/functions/Consumer.html), which accepts an argument in its callback, and an [`Action`](http://reactivex.io/RxJava/javadoc/io/reactivex/functions/Action.html), which does not.

A solution is to remove `ResultListener` and `StreamListener` from the public contracts. Instead, we replace them with decomposed functional interfaces, which are able to be expressed as lambdas:

```
@FunctionalInterface interface Consumer<T> {
    void accept(T item);
}
```
```
@FunctionalInterface interface Action {
    void call();
}
```

With these, a `StreamListener` would become a three-tuple of:

1. `Consumer<T>` (for an `onNext(T item)` callback);
2. `Consumer<E>` (with `E extends AmplifyException`, for an `onError(E error)` callback);
3. `Action` (for an `onComplete()` callback.)

And the `ResultListener` would become a two-tuple of:

1. `Consumer<T>` (to replace the `onResult(T item)` callback);
2. `Consumer<E>` (with `E extends AmplifyException`, to supply an `onError(E error)` callback.)

As a worked example, the API `query(...)` method would become:

```
void <T extends Model> query(
        Class<T> clazz,
        Consumer<Iterable<T>> onItems,
        Consumer<ApiException> onError);
```

And a customer would invoke it as:

```
Amplify.API.query(Person.class,
    items -> Log.i(TAG, "Items: " + items), 
    error -> Log.w(TAG, "Error during query.", error)
);
```

Internally, we may keep the `ResultListener` and `StreamListener `as “function bundles,” to group together the individually specified callbacks:

```
// A bundle for customer-provided callbacks.
// This keeps a the callbacks for a single API call "together",
// in a single piece of state.
final class ResultListener<T, E extends AmplifyException> {
    private final Consumer<T> onResult;
    private final Consumer<E> onError;
    
    ResultListener(Consumer<T> onResult, Consumer<E> onError) {
        this.onResult = onResult;
        this.onError = onError;
    }

    void onResult(T result) {
        onResult.accept(result);
    }

    void onError(E error) {
        onError.accept(error);
    }
}   
```

**Comment by jamesonwilliams** [comment]
Source code has been fully updated. Still need to prepare changes to public docs.

**Comment by jpignata** [comment]
Changes to public docs in flight and this change will go out in 0.10.
