### ISSUE TITLE
Core Kotlin - Transfer ID

### ISSUE THREAD

**Issue by cyodrew** [aws-amplify/amplify-android#2126]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    def amplify_version = '2.0.0'
    implementation "com.amplifyframework:core:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:core-kotlin:$amplify_version"

```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Mac OS X 10.16 x86_64



```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/storage/querytransfers/q/platform/android/

### Describe the bug

The new Amplify 2.0.0 library just released has a method to query transfers by ID via `Amplify.Storage.getTransfer("TRANSFER_ID")`. Through the Kotlin facade, an upload/download can be performed with coroutine support via `Amplify.Storage.uploadFile()` and `Amplify.Storage.downloadFile()`. This method gives back an `InProgressStorageOperation` instance, but it is does not contain a way to get the `transferId`, only the progress, result, and ability to cancel are available.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Thank you for opening this issue! We will take a look internally and discuss the best way to enable better Kotlin Coroutine support.

**Comment by sdhuka** [comment]
This fix will be available in the next release.
