### ISSUE TITLE
Vulnerability in the res/raw/ folder's files.

### ISSUE THREAD

**Issue by santaclawn** [aws-amplify/amplify-android#2138]
Im concerned about the files amplifyconfiguration.json and awsconfiguration.json in the "raw" folder. Since those files are in the "res" folder, they are easily reversed engineered and accessed. Anyone can download my apk, decompile it, and then get full access to those files, containng all the sensitive information of my backend, inclusive my API Key and endpoints. There is something I'm not doing here? How do I hide/obfuscate this files?

**Comment by tylerjroach** [comment]
Hi @santaclawn, please see https://docs.amplify.aws/cli/reference/files/#amplifyconfigurationjson

>  This file (amplifyconfiguration.json/awsconfiguration.json) contains information which is non-sensitive and only required for external, unauthenticated actions from clients (such as user registration or sign-in flows in the case of Auth) or for constructing appropriate endpoint URLs after authorization has taken place.

**Comment by santaclawn** [comment]
Thanks for your answer.answer.

How it is "non-sensitive", it literally has my API Key on it?

**Comment by tylerjroach** [comment]
@santaclawn What specific variable are you concerned about in the configuration files. As referenced in the statement above (which contains other links to details on the topic in the [aws-exports](https://docs.amplify.aws/cli/reference/files/#aws-exportsjs) section (js version of amplifyconfiguration.json), values stored in this configuration file are considered to be non-sensitive.

**Comment by santaclawn** [comment]
ApiUrl, ApiKey, Cognito's PoolIds

**Comment by div5yesh** [comment]
Please see https://docs.amplify.aws/cli/graphql/authorization-rules/#how-it-works for best practices for using API key based authorization.

> API Keys are best used for public APIs (or parts of your schema which you wish to be public) or prototyping, and you must specify the expiration time before deploying.

**Comment by santaclawn** [comment]
closing

**Comment by tjleing** [comment]
I'm assuming this means you would like to close the issue -- please respond if you wish it to remain open, or I'll close it later this week.
