### ISSUE TITLE
Amplify S3 for Android doesn't upload metadata on V2.0.0

### ISSUE THREAD

**Issue by looksbo** [aws-amplify/amplify-android#2150]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.5.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

none

### Describe the bug

When trying to upload an image using sdk V2.0.0 on the following code, the metadata is not uploaded, but when using sdk v1.37.9 it is uploaded.

`val TAG = "Upload image"

fun uploadImage(image: ItemImage) {
    image.inputStream?.let {
        Amplify.Storage.uploadInputStream(image.id,
            it,
            createStorageUploadOptions(image),
            { success ->
                Log.i(TAG, "Successfully uploaded: ${success.key}") },
            { error ->
                Log.e(TAG, "Upload failed", error) })
    }
}

private fun createStorageUploadOptions(image: ItemImage): StorageUploadInputStreamOptions {
    var metaData = HashMap<String, String>()
    metaData["width"] = image.width.toString()
    metaData["height"] = image.height.toString()
    metaData["type"] = "webp"
    var options = StorageUploadInputStreamOptions.builder().metadata(metaData).build()
    return options
}
`

### Expected behavior

The metadata is uploaded for the newest sdk

### Reproduction steps

`val TAG = "Upload image"

fun uploadImage(image: ItemImage) {
    image.inputStream?.let {
        Amplify.Storage.uploadInputStream(image.id,
            it,
            createStorageUploadOptions(image),
            { success ->
                Log.i(TAG, "Successfully uploaded: ${success.key}") },
            { error ->
                Log.e(TAG, "Upload failed", error) })
    }
}

private fun createStorageUploadOptions(image: ItemImage): StorageUploadInputStreamOptions {
    var metaData = HashMap<String, String>()
    metaData["width"] = image.width.toString()
    metaData["height"] = image.height.toString()
    metaData["type"] = "webp"
    var options = StorageUploadInputStreamOptions.builder().metadata(metaData).build()
    return options
}
`

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by banji180** [comment]
Thanks! We are looking into this.

**Comment by sdhuka** [comment]
This fix will be available in the next release.
