### ISSUE TITLE
CUSTOM_AUTH is working partially on v2.0.0 (working on 1.37.7 version)

### ISSUE THREAD

**Issue by JurajBegovac** [aws-amplify/amplify-android#2173]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line

aws-amplify = "1.37.7"
aws-kotlin = "0.21.7"

aws-amplifyframework-core = { module = "com.amplifyframework:core", version.ref = "aws-amplify" }
aws-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "aws-amplify" }
aws-amplifyframework-core-kotlin = { module = "com.amplifyframework:core-kotlin", version.ref = "aws-kotlin" }
```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.16.1 (Homebrew 11.0.16.1+0)
OS:           Mac OS X 12.6.1 aarch64


```

</details>

### Describe the bug

Confirming SMS code is not working when using CUSTOM_AUTH as authenticationFlowType.

Not working on 2.0.0 - working on 1.37.7

Basically, I manage to confirm the SMS code but then after the access token expires Cognito session treats user as signedOut ?!
 
 This is our use case:

1. Call signup (in case of success go to signIn, or in case user exists go to signIn)
```
Amplify.Auth.signUp(username, password, options)
```
2. Call signIn:
```
Amplify.Auth.signIn(username, password)
```
3.Call confirm
```
Amplify.Auth.confirmSignIn(smsCode)
```

And everything works - I get the token - but once the accessToken expires I don't get any new accessToken (like in older version) - then I'm getting some signout exception

AWS configuration:
```
{
    "auth":
    {
        "plugins":
        {
            "awsCognitoAuthPlugin":
            {
                "CognitoUserPool":
                {
                    "Default":
                    {
                        "PoolId": "",
                        "AppClientId": "",
                        "AppClientSecret": "",
                        "Region": ""
                    }
                },
                "Auth":
                {
                    "Default":
                    {
                        "authenticationFlowType": "CUSTOM_AUTH"
                    }
                }
            }
        }
    }
}
```

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

I'm working on KMM project where I have interface/protocol inside shared module and implementations on iOS and Android side.
I also opened swift issue because on iOS I cannot even pass the third step https://github.com/aws-amplify/amplify-swift/issues/2608

**Comment by tylerjroach** [comment]
Thank you for your report. Someone on our team will take a look.

**Comment by banji180** [comment]
Hi there,
For the Cognito setup, did you select CUSTOM_AUTH_WITH_SRP or CUSTOM_AUTH_WITHOUT_SRP?

**Comment by JurajBegovac** [comment]
We use "CUSTOM_AUTH_FLOW_ONLY" so I guess it's "CUSTOM_AUTH_WITHOUT_SRP"

**Comment by banji180** [comment]
Hi @JurajBegovac 

Can you change your authentication flow type to CUSTOM_AUTH_WITHOUT_SRP or use the `signIn(username, password, options)` as mentioned [here](https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/android/#sign-in-a-user))

And please make sure you call fetchAuthSession or any other api before your token expires. Please reply here if this helps and if it doesn't, we will investigate further.

**Comment by JurajBegovac** [comment]
@banji180 Hi, in the meantime we changed auth flow so I guess this is now oboslete
