### ISSUE TITLE
Amplify is not triggering delete event for a subscribed model 

### ISSUE THREAD

**Issue by ZubairAkber** [aws-amplify/amplify-android#2182]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'com.amplifyframework:core:1.30.0'
    implementation 'com.amplifyframework:aws-api:1.30.0'
    implementation 'com.amplifyframework:aws-datastore:1.30.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.30.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.30.0'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am observing models in my app, one of model is not getting event on deletion, all other events are fired for that model but event is not firing in case of delete. I can see in logs that we have _delete as true but it is removing from sqlite and event is not firing at all for delete

If i catch the event on hub and delete the value using Amplify delete method i am getting this exception

DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}

DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
11:36:22.601 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:534)
11:36:22.607 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
11:36:22.609 System.err               W  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
11:36:22.610 System.err               W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:36:22.612 System.err               W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11:36:22.613 System.err               W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11:36:22.614 System.err               W  	at java.lang.Thread.run(Thread.java:923)
11:36:22.620 System.err               W  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference
11:36:22.623 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.recurseTree(SQLiteModelTree.java:125)
11:36:22.625 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.descendantsOf(SQLiteModelTree.java:87)
11:36:22.629 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:502)
11:36:22.630 System.err               W  	... 6 more

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

If i catch the event on hub and delete the value using Amplify delete method i am getting this exception

DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}

// Put your logs below this line

DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
11:36:22.601 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:534)
11:36:22.607 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
11:36:22.609 System.err               W  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
11:36:22.610 System.err               W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:36:22.612 System.err               W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11:36:22.613 System.err               W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11:36:22.614 System.err               W  	at java.lang.Thread.run(Thread.java:923)
11:36:22.620 System.err               W  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference
11:36:22.623 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.recurseTree(SQLiteModelTree.java:125)
11:36:22.625 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.descendantsOf(SQLiteModelTree.java:87)
11:36:22.629 System.err               W  	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:502)
11:36:22.630 System.err               W  	... 6 more

```

</details>


### amplifyconfiguration.json

_No response_

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by AnilMaktala** [comment]
Hey @ZubairAkber 👋 , thank you raising the issue. can you please run "amplify diagnose --send-report" command and add the project identifier to the ticket?

**Comment by ZubairAkber** [comment]
@AnilMaktala i have executed the command kindly verify. Thanks

**Comment by AnilMaktala** [comment]
Hey @ZubairAkber, can you please update the project identifier to the ticket?

**Comment by ZubairAkber** [comment]
I have added the identifier @AnilMaktala, what i have observed that it start working fine now but issue still exist as some times it doesn't delete record from sqlite and doesn't sync properly with cloud.

**Comment by eeatonaws** [comment]
@ZubairAkber are you still observing the issue?
