### ISSUE TITLE
[DataStore] Issue with Syncing to Cloud

### ISSUE THREAD

**Issue by lotchay** [aws-amplify/amplify-android#219]
Hi there, we have an issue with DataStore syncing to cloud. Below is a snippet of the error:
```Java
2020-01-06 12:15:57.814 21346-21493/com.wdpr.ee.ra.android.amplify.demo W/amplify:aws-datastore: Error ended journal subscription: 
    java.lang.RuntimeException: Failed to publish item to network.
        at com.amplifyframework.datastore.network.SyncEngine$2.onResult(SyncEngine.java:219)
        at com.amplifyframework.datastore.network.SyncEngine$2.onResult(SyncEngine.java:215)
        at com.amplifyframework.datastore.network.MutationAdapter.onResult(MutationAdapter.java:39)
        at com.amplifyframework.datastore.network.MutationAdapter.onResult(MutationAdapter.java:22)
        at com.amplifyframework.api.aws.SingleItemResultOperation$OkHttpCallback.onResponse(SingleItemResultOperation.java:146)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ekmwilson** [comment]
Any update on this? I am seeing this in my logs as well and am unable to sync with the cloud. Initially it looked like the SyncMode was set to LOCAL_ONLY so I changed my initialization code to look like:
```
AWSDataStorePlugin dataStorePlugin = AWSDataStorePlugin.forModels(AmplifyModelProvider.getInstance());
        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("syncMode","api");
        } catch (JSONException e) {
            e.printStackTrace();
        }
        new Thread(() -> {
            try {
                dataStorePlugin.configure(jsonObject,this);
                Amplify.addPlugin(dataStorePlugin);
                Amplify.addPlugin(new AWSApiPlugin());
                Amplify.configure(this);
            } catch (AmplifyException e) {
                e.printStackTrace();
            }
        }).start();
```

And then began to see this error in the logs.

**Comment by jamesonwilliams** [comment]
Hey @ekmwilson, thanks for following up. The 0.9 "preview" release of DataStore had some bugs and missing functionalities. The DataStore category is a strategic business priority for us and is a current focus of my development. An upcoming release of Amplify Android will see expanded functionality and fixes. Cloud synchronization is a critical part of the product definition for the 1.0 release.

In 0.9, there was basic support for synchronizing local content _up_ to the cloud. This is demonstrated in [one of the instrumentation tests](https://github.com/aws-amplify/amplify-android/blob/6ea11e0a06ecdd2a2971bc59113f36735ba24af5/aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java#L80-L99). However, the reverse case -- synchronizing data _down_ from cloud -- was not working in 0.9. (See [this `@Ignore`d instrumentation test](https://github.com/aws-amplify/amplify-android/blob/6ea11e0a06ecdd2a2971bc59113f36735ba24af5/aws-datastore/src/androidTest/java/com/amplifyframework/datastore/AWSDataStorePluginInstrumentedTest.java#L102-L132).)

By default in 0.9, cloud sync is disabled. You can still experiment with cloud synchronization in 0.9 by doing:
1. Turn on sync mode via your `amplifyconfiguration.json`. Validate that the `"dataStore"` section of the config looks like:
```
  "dataStore": {
    "plugins": {
      "awsDataStorePlugin": {
        "syncMode": "api"
      }
    }
  }
```
2. Initialize Amplify in an asynchronous way, to work-around #209:
```
Completable.fromAction(() -> {
    Amplify.addPlugin(new AWSApiPlugin());
    Amplify.addPlugin(AWSDataStorePlugin.forModels(AmplifyModelProvider.getInstance()));
    Amplify.configure(context);
})
.observeOn(Schedulers.io())
.subscribeOn(Schedulers.io())
.subscribe();
```

**Comment by jamesonwilliams** [comment]
The [0.10.0 release](https://github.com/aws-amplify/amplify-android/releases/tag/release_v0.10.0) saw numerous improvements in the sync engine, and I believe this has been fixed. Please re-open if you see it again.

**Comment by sunithapremjee** [comment]
Hello, 
 I have  added data to AWS app sync. My android app code is giving exception while Querying data from AWS cloud as follows.

amplify:aws-datastore: Initial cloud sync failed.
    AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type FieldUndefined:
locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}

**Comment by jamesonwilliams** [comment]
Hi @sunithapremjee Please create a new issue
