### ISSUE TITLE
Perform different operations on specific model in Amplify

### ISSUE THREAD

**Issue by Frankat1578** [aws-amplify/amplify-android#2191]
Hi,
I have 3 models(model A,B,C) in my application(kotlin) and would like to implement Datastore and Api in different ways.
Case 1 : Model A
This should be saved locally by user and should not sync to cloud.
Case 2 : Model B
This should be saved both locally and cloud. This is easy to achieve with amplify.
Case 3 : Model C
This should only be in the cloud. It has list of categories. User will fetch this with "Amplify.Api" call but dont have to be stored locally. Am yet to try 2.1 of https://github.com/aws-amplify/amplify-flutter/issues/1553#issuecomment-1110252210 which should work in this case. If there is any other workaround i will appreciate that also. Also if there is a way to clear Datastore ,ie. using DataStore.clear(), on specific model(Model C) I will appreciate that also so that I can load Model C locally and clear it when user navigates. I dont want to clear the whole DataStore.

Question
How can I perform these operations of the different models. To perform only local operations for Model A , Both Cloud and local operations for Model B and only Cloud operations for Model C at the same time in one application(kotlin)

Thank you.

**Comment by AnilMaktala** [comment]
Hey @Frankat1578 👋 , Case 1 we do not support in Android. we support Case 2 or Case 3 but not both.
