### ISSUE TITLE
Support Android SDK 23 Marshmallow 

### ISSUE THREAD

**Issue by 4brunu** [aws-amplify/amplify-android#2192]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

Not applicable

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:aws-auth-cognito:2.0.0'
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Azul Systems, Inc. 17.0.5+8-LTS)
OS:           Mac OS X 13.1 aarch64

```

</details>

### Describe the feature request

Hi,
I just saw the release 2.0.0 and I noticed that it only supports Android SDK API 24: Android 7.0 (Nougat) and higher.
Why does Amplify needs a minimum Android support version has high as 24?
What specific functionality does it needs?
Jump from a minimum Android support version of 16 to 24 seems a bit "aggressive".
In my company we still support Android 23 marshmallow, so I cannot upgrade to amplify 2.0.0.
Is it possible to support Android 23 as a minimum?
Thanks

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Thank you so much for your question. We are discussing this internally and with the holidays our responses can be delayed. Once we have a resolution we will post it here. Thank you.

**Comment by gpanshu** [comment]
Amplify SDK for Android depends on AWS SDK for Kotlin which currently has a minimum SDK version of 24. Due to this dependency we are unable to go lower. We will take in your requirement into consideration and discuss it further internally. In the meantime, you can continue to use Amplify for Android V1. We will update this thread as we make progress on this.

**Comment by gpanshu** [comment]
Due to having dependencies that require higher Android version and having a fallback (V1) for customers that require minsdk < 23 we are unable to lower the minsdk version in V2. I hope this answers your question. Please feel free to create a new issue if you are still facing problems.
