### ISSUE TITLE
[StorageEngine] Support storing lists and querying with predicates on them

### ISSUE THREAD

**Issue by raphkim** [aws-amplify/amplify-android#220]
Predicates such as `beginsWith` and `contains` currently applies only to `String`s and would not parse correctly when being converted to WHERE statement in SQLite. In fact, SQLite currently does not store any collection, which makes it impossible to query on them to begin with. 

Action item: 
* Implement logic to serialize lists and store them in DB
* Implement SQL parsing logic for predicate on lists
* Implement evaluation logic for predicate on lists

**Comment by jpignata** [comment]
Resolved in the predicate work. Please re-open if you are having an issue.
