### ISSUE TITLE
Google sign in does not return token for user and returns white screen 

### ISSUE THREAD

**Issue by EkaterinaT89** [aws-amplify/amplify-android#2205]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When i launch this:

        Amplify.Auth.signInWithSocialWebUI(
            AuthProvider.google(),
            activity, { result: AuthSignInResult ->
                Log.i(
                    "AuthQuickstart",
                    result.toString()
                )
            }
        ) { error: AuthException ->
            Log.e(
                "AuthQuickstart",
                error.toString()
            )
        }

**I have this result - I/AuthQuickstart RESULT: AuthSignInResult{isSignedIn=true, nextStep=AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}}
without tokens or smething else** 

My manifest:

        <activity
            android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
            </intent-filter>
        </activity>

My json:

             "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "amplifyinitad8f4193-ad8f4193-dev.auth.us-west-2.amazoncognito.com",
                            "AppClientId": "2c4qqje5d0bjslcpvn57oqg7u8",
                            "SignInRedirectURI": "myapp://callback/",
                            "SignOutRedirectURI": "myapp://signout/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },

What am i doing wrong? I do not have any arror messages got this into logs:

I/AuthQuickstart RESULT: AuthSignInResult{isSignedIn=true, nextStep=AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}}

What should I do to make this work? 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

I found issue and checked info from that about callbacks - it is correct.

**Comment by gpanshu** [comment]
You are not doing anything wrong and the library is working as expected. You get a success callback and at that point you can continue to do whatever you want to do when you are signed in.
