### ISSUE TITLE
Allow clientMetaData for signInWithSocialWebUI

### ISSUE THREAD

**Issue by iyobo** [aws-amplify/amplify-android#2259]
Similar to this issue which has been closed,
https://github.com/aws-amplify/amplify-android/issues/2013

We cannot add clientMetaData to any of the hostedAuth logins i.e
- Amplify.Auth.signInWithSocialWebUI(...)
- Amplify.Auth.signInWithWebUI(...)

**Comment by div5yesh** [comment]
The #2013 mentions the need for clientMetaData in the signIn API. `signInWithSocialWebUI` uses Cognito's [HostedUI](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html) which does not need clientMetaData. What is your case for needing the clientMetaData for hosted UI?
