### ISSUE TITLE
Handling Errors During an Upload/Download

### ISSUE THREAD

**Issue by cyodrew** [aws-amplify/amplify-android#2276]
### Discussed in https://github.com/aws-amplify/amplify-android/discussions/2260

<div type='discussions-op-text'>

<sup>Originally posted by **cyodrew** January 27, 2023</sup>
Question regarding usage of the 2.0.0 SDK. For a file upload, an error will be thrown from the `InProgressStorageOperation` once `result()` is called based on the example provided in the docs.

```kotlin
val upload = Amplify.Storage.uploadFile("ExampleKey", exampleFile)
    try {
        val result = upload.result()
        Log.i("MyAmplifyApp", "Successfully uploaded: ${result.key}")
    } catch (error: StorageException) {
        Log.e("MyAmplifyApp", "Upload failed", error)
    }
```

The demo only provides a log here, which means the suspend call is done and the calling function would return. However, in the background, it appears the underlying code to perform the upload (multipart) via `PartUploadTransferWorker` will attempt to retry up to three times or more depending on the type of error from a function called `isRetryableError`.

```kotlin
private fun isRetryableError(e: Throwable?): Boolean {
        return isStopped ||
            !isNetworkAvailable(applicationContext) ||
            runAttemptCount < maxRetryCount ||
            e is CancellationException ||
            // SocketException is thrown when download is terminated due to network disconnection.
            e is SocketException
    }
```

What's the best way to know if the worker has truly failed vs an error during upload but the worker is still in a retry state? Is it best to pause and resume using the transfer Id here?</div>

**Comment by sdhuka** [comment]
@cyodrew result() will only throw the error if the error is not retry-able further. Meaning in case of retry-able error worker will be completed with the RETRY result and enqueued to be re-ran in the future, error is not passed to the caller in this case.

Let us know if you are observing a different behavior?

**Comment by cyodrew** [comment]
@sdhuka That makes sense, I assumed that was the expected behavior. In the case of a retryable error, the `result` call will still be suspended until success or non-retryable error, correct? I don't believe I hit a case like that, I just wanted to verify.

**Comment by sdhuka** [comment]
> In the case of a retryable error, the result call will still be suspended until success or non-retryable error, correct?

@cyodrew that's correct.
