### ISSUE TITLE
Unable full logout (after signInWithSocialWebUI). Unable change account with signInWithSocialWebUI

### ISSUE THREAD

**Issue by Tin-moon** [aws-amplify/amplify-android#2287]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
def amplify_version = '2.2.1'
implementation "com.amplifyframework:aws-api:$amplify_version"
implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
implementation "com.amplifyframework:rxbindings:$amplify_version"
```
</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)
OS:           Windows 10 10.0 amd64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/social/q/platform/android/#configure-auth-category

### Describe the bug

Hi, maybe it's not really a bug, probably more of a question, I'll try to explain what's going on, maybe someone can tell me.
So:
**Issue 1**: 
a. I call **Auth.signInWithSocialWebUI(AuthProvider.google(), )**, after that open brouser (chrome for my case), I put login data, and press login. All fine.
b. After I wont change account. Call **Auth.signOut**. Logout (check **issue 2**)
c. Again call **Auth.signInWithSocialWebUI(AuthProvider.google(), )**.
Browser opens and automatically login me back into the same account I was already in before (step a). I am not given the option to choose between or enter a new one. 
Can you tell me what needs to be done to make such an opportunity appear or is it still a bug?

**Issue 2**: 
After call **Auth.signOut**. I get error
```
Failed to revoke token
See attached exception for more details. RevokeToken can be retried using the CognitoIdentityProviderClient accessible from the escape hatch.
Access Token does not contain origin_jti claim. Skip revoking tokens.
```
Is this a problem with some my settings?
https://docs.amplify.aws/lib/auth/signOut/q/platform/android/#partialsignout
Can you provide sample how to use Escape hatch for fix this?

Thanks.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Hi @Tin-moon have you tried signout with globalSignOut as `true` ?

**Comment by gpanshu** [comment]
Actually looking at the error again it seems like your local cache has been cleared even when there was a revoke token error. As far as using the escape hatch you can use this page as your resource : https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android/

**Comment by Tin-moon** [comment]
> Hi @Tin-moon have you tried signout with globalSignOut as `true` ?

Yes, the result is the same

**Comment by Tin-moon** [comment]
> Actually looking at the error again it seems like your local cache has been cleared even when there was a revoke token error. 
Didn't quite understand what it was about? How can this be corrected?

As far as using the escape hatch you can use this page as your resource : https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android/
Yes, I watched it, I didn't quite understand how to use it, can you give an example?

**Comment by tylerjroach** [comment]
I had also missed reading that your logs show

```
Failed to revoke token
See attached exception for more details. RevokeToken can be retried using the CognitoIdentityProviderClient accessible from the escape hatch.
Access Token does not contain origin_jti claim. Skip revoking tokens.
```

While this still doesn't allow you to switch social sign in users due to the web browser cookie issue described above, it appears you may not have token revocation enabled, which is an additional security feature that revokes the refresh token that was stored on the device. Token revocation is enabled automatically on new Amazon Cognito User Pools, however existing User Pools must enable this feature, [using the Cognito Console or AWS CLI](https://docs.aws.amazon.com/cognito/latest/developerguide/token-revocation.html).

**Comment by tuancuong009** [comment]
@Tin-moon Did you resolve the issue? I have the same issue with my app (Java) now. Could you please help?
