### ISSUE TITLE
SessionExpiredException not thrown in `fetchAuthSession` when refresh token expired

### ISSUE THREAD

**Issue by fanwgwg** [aws-amplify/amplify-android#2289]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'com.amplifyframework:core:2.2.1'
    implementation 'com.amplifyframework:aws-auth-cognito:2.1.0'
    implementation 'com.amplifyframework:aws-storage-s3:2.1.0'
```

</details>

### Environment information

<details>

```
# Put output below this line
Welcome to Gradle 7.5!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5/release-notes.html


------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_361 (Oracle Corporation 25.361-b09)
OS:           Mac OS X 13.2.1 x86_64

```

</details>

### Describe the bug

I'm trying to integrate with amplify for authentication purpose in my android app. Right now I'm testing the refresh token expiry behaviour, therefore I've set the following on  the AWS Cognito console:
* id token expiry to 5 mins
* access token expiry to 5 mins
* refresh token expiry to 60 mins

In my code, I'm calling ` Amplify.Auth.fetchAuthSession` and see if any exception is thrown. After 60 mins and calling this method again, I'm getting a valid response of `AWSCognitoAuthSession`. No error is present in any values, i.e., `cognitoAuthSession.getAwsCredentialsResult().getError() = null`, similarly for `identityIdResult`, `userPoolTokensResult` and `userSubResult`.

However, when I try to fetch user attributes, this `NotAuthorizedException` for access token is thrown
```
NotAuthorizedException{message=Failed since user is not authorized., cause=NotAuthorizedException(message=Access Token has expired), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
```

May I know what's the proper way to handle refresh token expiry?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
HI @fanwgwg apologies for not responding sooner. We are going to try to reproduce this and get back to you.

**Comment by tjleing** [comment]
Hey @fanwgwg, thanks for reporting!  I was able to reproduce this issue; still looking into root causes.

**Comment by gpanshu** [comment]
@fanwgwg since your access token is expired and not the refresh token you can call fetchAuthSession with the forceRefresh option. If that succeeds you are good to go, if that fails you can sign out and sign the user back in again. https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android/

**Comment by gpanshu** [comment]
We should be seeing the refresh token is expired exception as well along with access token is expired. What is the response you are getting when you do a fetchAuthSession and what happens when you do a getCurrentUser()

**Comment by gpanshu** [comment]
@fanwgwg when the refresh token expires you will have to sign in again and all API calls will fail. Cognito does not support refresh token rotation. You can accomplish what you are doing by enforcing a max age for refresh token and within that time the access token can be refreshed but once the refresh token expires your users will have to sign out and sign back in. I hope this helps.
