### ISSUE TITLE
Set a session with AccessToken and RefreshToken

### ISSUE THREAD

**Issue by victorOwnID** [aws-amplify/amplify-android#2291]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Not applicable

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the feature request

We would like to have the possibility to set a session in the Amplify SDK by passing AccessToken and RefreshToken, in the same way as it is possible in the JS library. (ref: https://stackoverflow.com/a/67872625/18770645 )

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Duplicate of https://github.com/aws-amplify/amplify-android/issues/1486
