### ISSUE TITLE
App Close on Storage Upload causes Zombie Process

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-android#2324]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

implementation 'com.amplifyframework:aws-storage-s3:1.38.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.38.0'

### Environment information

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          18 (Oracle Corporation 18+36-2087)
OS:           Mac OS X 13.2 x86_64

### Describe the bug

If the user closes the app (by swiping up) while a Storage Upload operation is in progress, the upload finishes but the app is never closed.  

This issue is on the v1 version of Amplify Android and was caught by a customer using Amplify Flutter.  We tested if the issue was on our side but when creating a native Android app we encountered the same problem.

https://github.com/aws-amplify/amplify-flutter/issues/2736

### Reproduction steps (if applicable)

I upload an image, wait for it to upload, then close the app by swiping up.
I go to settings -> Amplify Storage Example App -> App Info
I see that Force stop is not possible as the app is closed.

I upload a large image, I immediately close the app by swiping up.
I go to settings -> Amplify Storage Example App -> App Info
I see that Force stop is possible because the app is not closed.

### Code Snippet

Amplify.Storage.uploadFile

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sdhuka** [comment]
@fjnoyp Amplify starts a foreground service for S3 upload, so when the user swipe close while the upload is in progress, the foreground service is still running. Amplify monitors the uploads and when all the S3 transfers are completed, it will stop the foreground service(you can confirm this by following logs). Once the foreground service is stopped, it is up to the OS to decide on when to close the app and beyond our control.

```
amplify:aws-s3                      com.example.sampleappv1                        I  Stopping AmplifyTransferService unbind check
amplify:aws-s3                      com.example.sampleappv1                        I  De-registering the network receiver.
```

**Comment by fjnoyp** [comment]
@sdhuka thanks for the followup here. 

How long should that process take and have you observed the OS closing the app by itself? 

For uploads that take 1-2 seconds to complete, I wait 5-10 minutes but the app still runs in the background.  I haven't observed the app close by itself.  

From a functional point of view, it seems weird that if the users waits 1-2 seconds for upload and closes app, the app closes immediately, but if they don't and close the app, for the same upload operation, that app will remain in background for an unknown period of time. 

Furthermore, I noticed another issue - if the user opens a basic storage example app and does nothing, and then closes the app, the app will also be stuck in background as well.  


This might not seem like an issue at first, since the Android OS will automatically shut down apps that are running in background.  For our customer, this difference in behavior appears to be breaking their user engagement statistics because the app keeps running =>

![image](https://user-images.githubusercontent.com/11478656/224541555-a35f7b66-b0ef-42c4-b416-7120cbb08d6f.png)

**Comment by sdhuka** [comment]
Issue was discussed offline and concluded that no change is required on the Android SDK.

**Comment by kamilklyta** [comment]
Hi @sdhuka,
I don't know if the process is not shut down because of the android SDK or flutter integration, since you didn't provide any explanation here.

However, I can confirm that my process was last running in the background for almost 3 days after closing the app, so I think this is not Android's default behavior.
