### ISSUE TITLE
 Amplify.API.mutate

### ISSUE THREAD

**Issue by k3nnet** [aws-amplify/amplify-android#234]
This is not really an issue on the API but more of a call for help. `MutationType.CREATE` is giving me an error of  `"Could not retrieve the response body from the returned JSON"`   in the `onError` callback. Can anyone help me debug this ?
```
Amplify.API.mutate(
    user,
    MutationType.CREATE,
    new ResultListener<GraphQLResponse<User>>() {
        @Override
        public void onResult(GraphQLResponse<User> response) {
            Log.i("ApiQuickStart", "Added Blog with id: " + response.getData().getId());
        }

        @Override
        public void onError(Throwable throwable) {
            // The error occurs here
            Log.e("ApiQuickStart", throwable.getLocalizedMessage());
        }
    }
);
```

**Comment by jamesonwilliams** [comment]
Hi @k3nnet, thanks for checking out the preview version of AWS Amplify for Android.

The error message you are getting is generated [here](https://github.com/aws-amplify/amplify-android/blob/release_v0.9.0/aws-api/src/main/java/com/amplifyframework/api/aws/SingleItemResultOperation.java#L136), and [here](https://github.com/aws-amplify/amplify-android/blob/6ea11e0a06ecdd2a2971bc59113f36735ba24af5/aws-api/src/main/java/com/amplifyframework/api/aws/SingleItemResultOperation.java#L158).

So, either you are getting a malformed response back from the endpoint (line 135), or the request to the endpoint is failing (line 156). Most likely, is is the second situation.

To help confirm this, can you please provide some additional information?
1. The GraphQL model schema you are using for the `user` object;
2. Details on how you configured your remote endpoint, via the `amplify` CLI;
3. The contents of your `amplifyconfiguration.json` (_without_ your exact endpoint url, and without any of your credentials);
4. The full stack trace of the error you are receiving, as described below.

The request to the endpoint could fail for a number of reasons. I suggest to simply print out the full stack trace, to show it:
```
    @Override
    public void onError(Throwable error) {
        Log.e("ApiQuickStart", "Failed to mutate.", error);
    }
```
Or by using Android's [`Log#getStackTraceString(Throwable)`](https://developer.android.com/reference/android/util/Log.html#getStackTraceString(java.lang.Throwable)):
```
    @Override
    public void onError(Throwable error) {
        Log.e("ApiQuickStart", Log.getStackTraceString(error));
    }
```

The error cause _is_ also directly available via [`getCause()`](https://developer.android.com/reference/java/lang/Throwable.html#getCause()) on the `error` in your callback. So, you could just print it directly, too:
```
    @Override
    public void onError(Throwable error) {
        String causeString = Log.getStackTraceString(error.getCause());
        Log.e("ApiQuickStart", "Error, with underlying cause: " + causeString);
    }
```

**Comment by k3nnet** [comment]
Hi @jamesonwilliams  . Thanks  for the quick response i've managed to get a more useful error message thanks to the error cause . The error i am getting is " Error, with underlying cause: java.io.IOException: Failed to retrieve Cognito User Pools token." 

i've configured my remote end point using amplify CLI  and i'll post my stacktrace ,schema and amplifyconfig file once i get a chance .

**Comment by jpignata** [comment]
@k3nnet This issue has been idle a bit - let us know if we can still help by reopening. Thanks!
