### ISSUE TITLE
wrong amplify version in storage documentation

### ISSUE THREAD

**Issue by UrielFrankel** [aws-amplify/amplify-android#2358]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
2.2.2

```

</details>

### Environment information

<details>

```
# Put output below this line
asdfasdf

```

</details>

### Describe the bug

in the docs the amplify version is 2.2.2 and there is setUseAccelerateEndpoint that do not exist there i had to look for the latest version to make it work

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Thank you for the heads up. The documentation has been updated to reflect the latest amplify version.
