### ISSUE TITLE
Not support for appsync service in China

### ISSUE THREAD

**Issue by ByiProX** [aws-amplify/amplify-android#2374]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line
.

```

</details>

### Describe the feature request

https://github.com/aws-amplify/amplify-android/blob/main/aws-api/src/main/java/com/amplifyframework/api/aws/DomainType.java

```
private static final String STANDARD_ENDPOINT_REGEX =
            "^https:\\/\\/\\w{26}\\.appsync\\-api\\.\\w{2}(?:(?:\\-\\w{2,})+)\\-\\d\\.amazonaws.com\\/graphql$";
```
the regex is not available for appsunc endpoint in China region.
Could this feature been fixed? 

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by thisisabhash** [comment]
Thank you for posting this. Our team will take a look and post updates here.

**Comment by mattcreaser** [comment]
Another user opened this issue in #2945. We'll use that issue to address this problem, please follow there for details.
