### ISSUE TITLE
Nested id field null on real-time subscription

### ISSUE THREAD

**Issue by PS-MS** [aws-amplify/amplify-android#2379]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    def amplify_version = "1.37.11"
    def amplify_kotlin_version = "0.21.11"
    implementation "com.amplifyframework:core-kotlin:$amplify_kotlin_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-datastore:$amplify_version"

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

We are building a questionnaire and initially we had a schema structure similar to below:
```
type Post @model {
  id: ID!
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

type Comment @model {
  id: ID!
  postID: ID! @index(name: "byPost")
  post: Post! @belongsTo(fields: ["postID"])
  content: String!
}
```
We found that, along with iOS and Android selection sets being incompatible, syncing was taking a while and a way to cut this down would be to nest the comments which brought us to a schema structure like so:
```
type Post @model {
  id: ID!
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
  commentsNested: [CommentNested]
}
```
# Old model
```
type Comment @model {
  id: ID!
  postID: ID! @index(name: "byPost")
  post: Post! @belongsTo(fields: ["postID"])
  content: String!
}
```
# New model
```
type CommentNested {
  id: ID!
  content: String!
}
```
If the app is closed and Post is updated with a new list of commentsNested then the app's delta sync will fill in the data correctly. However, if the app is open and subscribed then all of the commentsNested id fields will be null.

### Reproduction steps (if applicable)

1. Set up a schema structure similar to the above.
3. Run a mutation on the parent model with the nested data filled in
4. Full/Delta sync an Android app with syncing enabled (data should be correct)
5. Run a mutation on the parent model while the app is running and subscribed
6. Check the local database (nested data 'id' is null)

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by yuhengshs** [comment]
Hi @PS-MS ,

Thanks for reporting the issue, please upgrade to the latest Amplify Android versions and let us know if you are still encountering the same issues.

**Comment by lawmicha** [comment]
I'll close this due to inactivity since @yuhengshs couldn't reproduce it, and there have been no updates since then. If the issue persists, please open a new issue with the complete schema and include logs of the mutation request/response or subscription events. Let us know if you need further assistance.
