### ISSUE TITLE
Does amplify currently support KotlinMultiModule

### ISSUE THREAD

**Issue by kingcali3** [aws-amplify/amplify-android#2382]
I am implementing amplify for my kotlinmultimodule application and I am separating my modules from android library modules and java library modules. I am placing the my generated models into a domain module but since these generated models require android dependencies (specifically com.amplifyframework:core:2.2.2 and com.amplifyframework:aws-api:2.2.2 requiring android navigation dependencies), I am forced to make my domain module as an android library. Since java libraries can't have android dependencies is there any way to properly use the generated models in the java library for kmm? If there is something that I am fundamentally missing please excuse me as I am still getting familiar with kmm.

**Comment by tylerjroach** [comment]
At this time, Amplify for Android is built only for Android. We do not support Kotlin Multiplatform at this time. The lower level apis in the Developer Preview Kotlin SDK (https://github.com/awslabs/aws-sdk-kotlin) do not depend on Android. However, Amplify for Android is build with use cases to specifically enable the best experience for Android developers.

**Comment by kingcali3** [comment]
Ok thank you.
