### ISSUE TITLE
com.amplifyframework.kotlin.auth.fetchAuthSession(options: AuthFetchSessionOptions) : option paramter is not used

### ISSUE THREAD

**Issue by hskim-works** [aws-amplify/amplify-android#2383]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

com.amplifyframework.kotlin.auth.KotlinAuthFacade.kt
https://github.com/aws-amplify/amplify-android/blob/release_v2.6.0/core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt

fetchAuthSession's options parameter is not used

override suspend fun fetchAuthSession(options: AuthFetchSessionOptions): AuthSession {
        return suspendCoroutine { continuation ->
            delegate.fetchAuthSession(
                AuthFetchSessionOptions.defaults(),
                { continuation.resume(it) },
                { continuation.resumeWithException(it) }
            )
        }
    }

-> i think it changes to 

override suspend fun fetchAuthSession(options: AuthFetchSessionOptions): AuthSession {
        return suspendCoroutine { continuation ->
            delegate.fetchAuthSession(
                options,
                { continuation.resume(it) },
                { continuation.resumeWithException(it) }
            )
        }
    }

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Thank you for the report. I'm working on a fix now.
