### ISSUE TITLE
Improve documentation arround AndroidManifest.xml required settings

### ISSUE THREAD

**Issue by doronbl** [aws-amplify/amplify-android#2397]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Amplify core dependency
    implementation 'com.amplifyframework:core:2.5.0'
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    // Add the below line in `dependencies`
    implementation 'com.amplifyframework:core-kotlin:2.5.0'
    // API Gateway
    implementation 'com.amplifyframework:aws-api:2.5.0'
    // Cognito
    implementation 'com.amplifyframework:aws-auth-cognito:2.5.0'
    // Lifecycle built-in coroutine scopes
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.4.0'


```

</details>

### Environment information

<details>

```

Welcome to Gradle 7.5!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5/release-notes.html


------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_361 (Oracle Corporation 25.361-b09)
OS:           Windows 10 10.0 amd64




```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/

### Describe the feature request

I was struggeling to configure end to end flow of user registration using Cognito & Google as Idp federation.
The flow was handing on error page during redirect 
![Screenshot_20230416_025816](https://user-images.githubusercontent.com/1909792/232711947-b1d95960-9198-4909-8554-30fead507e88.png)
Walking through the documentation didn't ended with working code, at least for me..
It was very hard to find any similar references for what might be wrong in the net. I've finally was able to find [this](https://github.com/aws-amplify/amplify-android/issues/1648) GitHub issue which was discussing on something similar.
Only then I've found a viable instructions of how to properly set the queries part in the AndroidManifest.xml file.
I do not understand why the documentation does not include a code snipped for the queries tag, and instead [uses](https://docs.amplify.aws/lib/auth/social/q/platform/android/#update-androidmanifestxml) very general guidance of ```Add the following activity and queries tag to your app's```. The queries tag addition seems to be very generic in nature, so I see no reason why not being more explicit in the docs and not showing a configuration snippt of it.

The ask:
Add clearer guide on how proper AndroidManifest.xml should look like, by adding the queries part

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
@doronbl Can you clarify what you added? 

FYI, the queries tag shouldn't need to be added to the documentation because we add it for the customer.
See https://github.com/aws-amplify/amplify-android/blob/main/aws-auth-cognito/src/main/AndroidManifest.xml#L19

Older versions of Amplify required this to be added manually.

`Add the following activity and queries tag to your app's` should actually just read `Add the following activity tag to your app's`.
