### ISSUE TITLE
No option to get the URL of item in S3 bucket using key.

### ISSUE THREAD

**Issue by zubairzahoor** [aws-amplify/amplify-android#240]
I have files(pictures) in my S3 bucket and I am displaying them on screen. I don't want to use the `Amplify.Storage.downloadFile(...)`
as it takes a lot of time to download and then render. I want to use a picture loading library like glide and to do that I need to get the URL of the picture (probably by using the key). 
Currently there is no such option in android.

**Comment by zubairzahoor** [comment]
I guess AmazonS3 SDK has something like this.
```
AmazonS3 s3 = AmazonUtil.getS3Client(this);
URI uri = s3.generatePresignedUrl(bucket, key, expiry);
```

**Comment by zubairzahoor** [comment]
In JS you can easily get the publically accessible URL by using
```
Storage.get('test.txt')
    .then(result => console.log(result))
    .catch(err => console.log(err));
```
Any workaround for doing the same in android?

**Comment by raphkim** [comment]
This is a feature that currently isn't included yet in preview release, but we certainly hope to include it in our upcoming releases. 

Temporary workaround for this usecase would be to utilize `getEscapeHatch()` method to obtain a s3 client with which you can call [`generatePresignedUrl()`](https://github.com/aws-amplify/aws-sdk-android/blob/7e04c0269e59f8eb1db9c98b59a0197b63501aba/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3401).

**Comment by zubairzahoor** [comment]
@raphkim Thanks for the response but is it really applicable in my case. I have to access a 'PROTECTED' resource in s3 and there is no configurable option for AmazonS3Client for achieving that. S3ClientOptions does not let me change the access level like StorageDownloadFileOptions does.
How do I call generatePresignedUrl() for a protected image(resource)?

**Comment by raphkim** [comment]
Amplify Storage internally constructs a "service key", which is a combination of `StorageDownloadFileOptions`, `AWSMobileClient#getIdentityId()`, and S3 key. This service key can be constructed using [`S3RequestUtils`](https://github.com/aws-amplify/amplify-android/blob/master/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/utils/S3RequestUtils.java) and be passed directly as a key along with the bucket name to `generatePresignedUrl()`. I imagine the sample code for temporary workaround would look like the following:

```
StorageDownloadFileOptions options = StorageDownloadFileOptions.defaultInstance(); // This is your download file options
String identityId = AWSMobileClient.getInstance().getIdentityId();
String serviceKey = S3RequestUtils.getServiceKey(
    options.getAccessLevel(),
    identityId,
    key,
    options.getTargetIdentityId()
);

AmazonS3Client s3 = Amplify.Storage.getEscapeHatch();
URL url = s3.generatePresignedUrl(
    bucketName, 
    serviceKey, 
    null
);
```

**Comment by zubairzahoor** [comment]
@raphkim Thanks for the workaround. It works perfectly. 
But I think there should be a simpler way to do it in near future.

**Comment by raphkim** [comment]
> But I think there should be a simpler way to do it in near future.

There will be! Please continue to follow our project for the upcoming changes and thank you for using Amplify :)

**Comment by ireshdudeja** [comment]
> In JS you can easily get the publically accessible URL by using
> 
> ```
> Storage.get('test.txt')
>     .then(result => console.log(result))
>     .catch(err => console.log(err));
> ```
> 
> Any workaround for doing the same in android?

For how long this URL will be valid ?

**Comment by frankdu** [comment]
@ireshdudeja Not sure about JS. In Android, you can set the expiration in seconds:

`StorageGetUrlOptions.Builder getUrlOptionsBuilder = StorageGetUrlOptions.builder().expires(7 * 24 * 3600)`
