### ISSUE TITLE
DataStore delete does not cascade on Android

### ISSUE THREAD

**Issue by dengdan154** [aws-amplify/amplify-android#2403]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

This ticket is to track the issue where customer reported that DataStore delete does not cascade. I have attached reproduction steps below for further investigation. As the customer has reported, using the @hasOne directive prevents anything subsequent @hasMany entities from being deleted.

### Reproduction steps (if applicable)

Use the schema and code snipped attached below.

### Code Snippet

```kotlin
// Put your code below this line.
        val blog = Blog.builder()
            .name("blog")
            .build()

        val post = Post.builder()
            .title("My Post with comments")
            .rating(10)
            .blog(blog)
            .build()

        val comment = Comment.builder()
            .content("hi")
            .post(post)
            .build()

        // Save
        Amplify.DataStore.save(blog,
            {
                Log.i("MyAmplifyApp", "blog saved")
                Amplify.DataStore.save(post,
                    {
                        Log.i("MyAmplifyApp", "Post saved")
                        Amplify.DataStore.save(comment,
                            { Log.i("MyAmplifyApp", "Comment saved") },
                            { Log.e("MyAmplifyApp", "Comment not saved", it) }
                        )
                    },
                    { Log.e("MyAmplifyApp", "Post not saved", it) }
                )
            },
            { Log.e("MyAmplifyApp", "Blog not saved", it) }
        )
        Thread.sleep(500)

        // Check if comment exist
        Amplify.DataStore.query(Comment::class.java,
            { matches ->
                if (matches.hasNext()) {
                    val comment = matches.next()
                    Log.i("MyAmplifyApp", "Content: ${comment.content}")
                } else {
                    Log.i("MyAmplifyApp", "Succesful query, but no comments")
                }
            },
            { Log.e("MyAmplifyApp", "Query failed", it) }
        )

        // Delete
        Amplify.DataStore.query(Blog::class.java,
            {
                if (it.hasNext()) {
                    val blog = it.next()
                    Amplify.DataStore.delete(blog,
                        { Log.i("MyAmplifyApp", "Post deleted") },
                        { Log.e("MyAmplifyApp", "Delete failed") }
                    )
                }
            },
            { Log.e("MyAmplifyApp", "Query failed", it) }
        )
        Thread.sleep(500)

        // Verify comment deleted
        Amplify.DataStore.query(Comment::class.java,
            { matches ->
                if (matches.hasNext()) {
                    val comment = matches.next()
                    Log.i("MyAmplifyApp", "Content: ${comment.content}")
                } else {
                    Log.i("MyAmplifyApp", "Succesful query, but no comments")
                }
            },
            { Log.e("MyAmplifyApp", "Query failed", it) }
        )
    }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
type Blog @model @auth(rules: [{ allow: public }]) {
  id: ID!
  name: String!
  posts: [Post] @hasOne(indexName: "byBlog", fields: ["id"])
}

type Post @model @auth(rules: [{ allow: public }]) {
  id: ID!
  title: String!
  rating: Int!
  blogID: ID @index(name: "byBlog")
  blog: Blog @belongsTo(fields: ["blogID"])
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

type Comment @model @auth(rules: [{ allow: public }]) {
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post @belongsTo(fields: ["postID"])
  content: String!
}

```

</details>

**Comment by ankpshah** [comment]
Hello @dengdan154, 
   I was not able to reproduce this issue. Please find my observations below:
1. The GraphQL schema has following validation errors:
     a.  @hasOne cannot be used with lists. Use @hasMany instead.
     b.  Unknown argument "indexName" on directive "@hasOne"

2. Looking at GraphQL Schema, there might be conflicting detail. Assuming Blog has one to one relation to Post (indicated by hasOne directive), the field post should not be a list but rather a single Post Object.

In that case schema for Blog object should look like following:
           

> type Blog @model @auth(rules: [{ allow: public }]) {
>                 id: ID!
>                 name: String!
>                 posts: Post @hasOne(fields: ["id"])
>             }

3. Now with changes in model mentioned in point 1 and using code snippet provided by you, I was not able to reproduce the issue. The comment gets deleted upon deleting Blog as expected.

 I verified that comment was deleted by querying listComments in AppSync and also I could see "Succesful query, but no comments" in the logs which shows delete casscades from Blog to Post (with hasOne relation) and from Post to comments (with hasMany relation).

Follow Up questions:
  1. Could you confirm if you are still facing same issue? 
  2. Also could you provide details of the amplify-android library version you are using?
  3. Also could you try using latest version of the amplify-android library and check if you are still facing same issue?
