### ISSUE TITLE
[API] The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by alebret** [aws-amplify/amplify-android#241]
I use the master branch on [the commit on Jan 15, 2020](https://github.com/aws-amplify/amplify-android/commit/c8eca08bef99c78f7ff99ebc5ec3780763662429).

I used IAM authorization and Kotlin.

1. I have `amplifyconfiguration.json` and I initialize Amplify with:

```kotlin
fun initAwsAmplify() {
    try {
        Amplify.addPlugin(AWSApiPlugin())
        Amplify.configure(applicationContext)
        Log.i("AmplifyGetStarted", "Amplify is all setup and ready to go!")
    } catch (exception: AmplifyException) {
        Log.e("AmplifyGetStarted", exception.message)
    }
}
```
2. And call API with `get()`:
```kotlin
fun getRequestWithIAM() {
    val options = RestOptions("mypath/next") 
    Amplify.API.get(
        "dev",
         options,
         Consumer<RestResponse> {
             Timber.d("SUCCESS: " + it.data.asJSONObject())
         },
         Consumer {
             Timber.e("REST ERROR : " + it.printStackTrace())
         }
    )
}
```
3. Response
> SUCCESS: {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n\/dev\/mypath%252Fnext\n\nhost:myhost.execute-api.eu-west-1.amazonaws.com\nx-amz-date:20200120T132539Z\nx-amz-security-token:*******\n\nhost;x-amz-date;x-amz-security-token\*******'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20200120T132539Z\n20200120\/eu-west-1\/execute-api\/aws4_request\********'\n"}

So, I have a success but no real data response because I think there is a problem with the signature.
My request is `https://myhost.execute-api.eu-west-1.amazonaws.com/mypath/next`
With the encoding I have `https://myhost.execute-api.eu-west-1.amazonaws.com/mypath%2Fnext` but the Canonical String for this request should have `https://myhost.execute-api.eu-west-1.amazonaws.com/mypath%252Fnext` like the above message. 

Have you an idea or fix for this problem?

**Comment by alebret** [comment]
I found a solution : 
In aws-api, go to RestOperationRequestUtils.java class, in constructURL() function and change `return builder.build().url();` by :
```
try {
    return new URL(URLDecoder.decode(builder.build().url().toString(), "UTF-8"));
} catch (UnsupportedEncodingException e) {
    throw new MalformedURLException(e.getMessage());
}
```

**Comment by jamesonwilliams** [comment]
Possibly related:
 - https://github.com/aws-amplify/amplify-android/issues/537
 - https://stackoverflow.com/questions/60263497/authenticating-a-rest-api-with-cognito-using-aws-amplify-android/60270118#60270118

**Comment by jamesonwilliams** [comment]
Closing as this this deals with pre-release version of Amplify, and a workaround was found. Please re-open if this recurs in Amplify 1.0+.

**Comment by cliffordfajardo** [comment]
I was running into this issue for my NodeJS project. I was able to resolve my issue with the hints of this stackoverflow post:
- [Stackoverflow.com -- `amplify init` fails constantly](https://stackoverflow.com/questions/65830910/amplify-init-fails-constantly/66735741#66735741)
