### ISSUE TITLE
Amplify crashes after downloading an image and immediately starting a new Activity on Android

### ISSUE THREAD

**Issue by avinashrgudipati** [aws-amplify/amplify-android#2413]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line

</details>
implementation 'com.amplifyframework:aws-storage-s3:1.37.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.37.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    implementation 'com.amplifyframework:aws-api:1.37.0'
    implementation 'com.amazonaws:aws-android-sdk-appsync:3.3.1'
```

### Environment information

<details>

```
# Put output below this line

7.3.3
```

</details>

### Describe the bug

I am downloading an image using the S3 API and once the download is complete, Im calling startActivity and this crashes the application with the below logs

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.environmental360.ehstracks_android.dev, PID: 30844
    android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{99bcf41 u0 com.environmental360.ehstracks_android.dev/com.amazonaws.mobileconnectors.s3.transferutility.TransferService}
        at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

### Code Snippet

```Kotlin
// Put your code below this line.

Amplify.Storage.list(path,
            {storageList ->
                val latch = CountDownLatch(storageList.items.size)
                storageList.items.forEach { downloadFile(it.key, latch) }
                latch.await()
                listener.onComplete(path)
            },
            { error ->
                Toast.makeText(activity, error.localizedMessage, Toast.LENGTH_SHORT).show()
                listener.onComplete(path)
            }
        )
        
        private fun downloadFile(key: String, latch: CountDownLatch) {
        val localFile = File("${activity.filesDir}/$key")
        if (localFile.exists()) {
            latch.countDown()
            return
        }
        val parentDir = localFile.parentFile

        if (parentDir != null && !parentDir.exists()) {
            parentDir.mkdirs()
        }

        Amplify.Storage.downloadFile(
            key,
            localFile,
            StorageDownloadFileOptions.defaultInstance(),
            {
                latch.countDown()
            },
            {
                latch.countDown()
            }
        )
    }
    
    
```
in Listener.onComplete(), Im opening a new Activity using StartActivity()

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Hi @avinashrgudipati Please post a stacktrace of the crash to help us further debug.

**Comment by gpanshu** [comment]
Thank you for reporting this bug. Someone from our team will investigate and respond soon.

**Comment by avinashrgudipati** [comment]
> Hi @avinashrgudipati Please post a stacktrace of the crash to help us further debug.

Hi Tyler, the logs have some of the IDs. Is there a way to provide the logs securely?

**Comment by avinashrgudipati** [comment]
And FYI, if I do not wait until the S3 download to finish and launch the next activity, I do not see the crash which is what I am doing.

**Comment by tylerjroach** [comment]
@avinashrgudipati Thank you for the stacktrace. Please update to the newest v1 Amplify version. 1.37.0 contained a bug causing a crash when attempting to display a foreground notification for the transfer.

**Comment by avinashrgudipati** [comment]
I believe I've tried with 1.38.3 and 2.5.0 and both have failed but I will try again and close if that works
