### ISSUE TITLE
`UserNotConfirmedException` regardless of correct password being submitted 

### ISSUE THREAD

**Issue by poliver** [aws-amplify/amplify-android#2427]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
2.8.2

```

</details>

### Environment information

<details>

```
# Put output below this line
8.1.1

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/android/

### Describe the bug

If a user signs up, but fails to confirm the sign up, all subsequent attempts to sign in yield a `UserNotConfirmedException`, regardless of whether the correct password was entered or not. This appears to go against the [current documentation](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/android/), which suggests that I should be seeing a success response with `nextStep.signInStep == AuthSignInStep.CONFIRM_SIGN_UP`. The behavior implied by the docs is preferable because it allows me to distinguish between a user that has authenticated using the correct password and one that hasn't. Is extra config needed to get the behavior found in the linked docs?

### Reproduction steps (if applicable)

1. Call `Amplify.Auth.signUp(email, password)`
2. DO NOT call `Amplify.Auth.confirmSignUp()` (simulates a user quitting the app without confirming)
3. Call `Amplify.Auth.signIn(email, incorrectPassword)` (email from step 1 and an incorrect password)
4. Observe `UserNotConfirmedException` error response
5. Call `Amplify.Auth.signIn(email, correctPassword)` (email from step 1 and the correct password)
6. Observe the same `UserNotConfirmedException` error response

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

<img width="1273" alt="Screenshot 2023-05-01 at 11 11 54 PM" src="https://user-images.githubusercontent.com/3497406/235572002-e4028c7d-3bef-48b1-b112-05c800396305.png">

**Comment by poliver** [comment]
Interestingly, just found this in the Amplify UI repo: https://github.com/aws-amplify/amplify-ui-android/blob/6eeeb6910e0de7521e37bd1ac2ddf93c5aadacbd/authenticator/src/main/java/com/amplifyframework/ui/authenticator/AuthenticatorViewModel.kt#LL334C22-L336C22

**Comment by gpanshu** [comment]
Hi @poliver you are right. It is indeed mentioned in the documentation and that was a miss on our side. However since this is a breaking change for anyone that may have defensively coded against the exception and not the signin step we have to wait till the next major version update. This is already logged as a bug in our backlog. 

In the meantime you can add a check for BOTH the signinstep and the UserNotConfirmedException indicating that the user has not confirmed their account and need to do a confirm sign in before they can proceed to sign in. That way when the update is made your code will still work and will need just a tiny refactor to remove the check for the exception. 

I hope this helps.

**Comment by poliver** [comment]
The linked "fix" just updates the documentation to match the current behavior. It does not leverage, or even remove, the unused values of `AuthSignInStep`. The root issue of this ticket remains unchanged, making it difficult to distinguish a sign in attempt from a user with knowledge of the email vs a user with knowledge of both email and password.

@gpanshu is the root issue the bug you're referring to in your backlog? If so, why was this ticket closed?
