### ISSUE TITLE
 InvalidOauthConfigurationException{message=The Oauth configuration is missing or invalid., cause=null, recoverySuggestion=HostedUI Oauth section not configured or unable to parse from amplifyconfiguration.json file.

### ISSUE THREAD

**Issue by smithton7330** [aws-amplify/amplify-android#2439]
### Which Specific Feature is your question related to?

AWS Amlify

### Question

I am building my application with AWS Amplify service and I am facing several issues.
I used Kotlin language with Android.

```
class AuthActivity : AppCompatActivity() {
    private val TAG = AuthActivity::class.simpleName

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_auth)

        Amplify.addPlugin(AWSCognitoAuthPlugin())
        try {
            Amplify.configure(applicationContext)
            Log.i("MyAmplifyApp", "Initialized Amplify")
        } catch (error: AmplifyException) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
        }

        Amplify.Auth.fetchAuthSession(
            { Log.i("AmplifyQuickstart", "Auth session = $it") },
            { error -> Log.e("AmplifyQuickstart", "Failed to fetch auth session", error) }
        )

        Amplify.Auth.signInWithWebUI(
            this@AuthActivity,
            { Log.i("AuthQuickStart", "Signin OK = $it") },
            { Log.e("AuthQuickStart", "Signin failed", it) }
        )


    }


}
```

The above code is my custom activity.
I would like to build a Login page with Amplify.Auth.signInWithWebUI, however,
when I run this code, Logcat shows an error message:
 InvalidOauthConfigurationException{message=The Oauth configuration is missing or invalid., cause=null, recoverySuggestion=HostedUI Oauth section not configured or unable to parse from amplifyconfiguration.json file.

How can I fix it up and what should I do for this?
The following is the amplifyconfiguration.json file.

![image](https://user-images.githubusercontent.com/69702680/236615461-415d9a4f-77bf-4664-9bd8-068dc9a71278.png)

**Comment by tylerjroach** [comment]
@smithton7330 Are you still having issues? Please advise if my previous comment helped.

**Comment by tjleing** [comment]
Closing since there's been no response, please open a new issue if you still face difficulties using Amplify Android.
