### ISSUE TITLE
Calling activity is getting destroyed, when opening custom tab browser for signInWithWebUI and showing user cancelled authorization flow; but selecting account signs in successfully.

### ISSUE THREAD

**Issue by SomnathS09** [aws-amplify/amplify-android#2475]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5                                                  
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (JetBrains s.r.o. 17.0.6+0-b2043.56-9586694)
OS:           Windows 10 10.0 amd64
```
</details>

### Describe the bug

I'm using amplify [social sign-in](https://docs.amplify.aws/lib-v1/auth/social/q/platform/android/#configure-auth-category), and experiencing these 2 behaviours:

1. When Launching Amplify.Auth.signInWithSocialWebUI(), the calling activity is getting destroyed and new activity instance is created, so I'm not able to get success result callback available in the same activity. What to do about it?
`Amplify.Auth.signInWithSocialWebUI(AuthProvider.googlek(), this,
{ Log.i("AuthQuickstart", "Sign in OK: $it") },
{ Log.e("AuthQuickstart", "Sign in failed", it) })`
and also it's showing : **AuthClient: Authorization flow canceled by user, I/AuthQuickStart: User canceled sign in**, but signing in is going throgh and successful. What could cause this?
2. If user had selected a google account in custom tab of web browser first time, Amplify.Auth.signInWithSocialWebUI() call directly logs in to same account without opening custom tab browser and showing all google accounts

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by div5yesh** [comment]
1. Can you provide code snippets showing how are you calling `signInWithSocialWebUI`?
2. Cognito hostedUI authorize and login [endpoints](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html) does not support prompt request param. Due to this [limitation](https://stackoverflow.com/questions/58154256/aws-cognito-how-to-force-select-account-when-signing-in-with-google/59580105#59580105) the library cannot make the IdP to prompt account chooser. Alternatively, launching the login endpoint in Private/Incognito Custom Tab Session is not yet supported by Android Custom Tabs.

**Comment by SomnathS09** [comment]
I am using the [code snippet provided in the doc](https://docs.amplify.aws/lib-v1/auth/social/q/platform/android/#launch-social-web-ui-sign-in), here mentioned below : 
```
Amplify.Auth.signInWithSocialWebUI(AuthProvider.google(), this,
    { Log.i("AuthQuickstart", "Sign in OK: $it") },
    { Log.e("AuthQuickstart", "Sign in failed", it) }
)
```
`this` is current activity

**Comment by gpanshu** [comment]
@SomnathS09 in your AndroidManifest.xml for your activity is `noHistory` set to `true` ?

**Comment by SomnathS09** [comment]
No, actually my mainactivity is landscape, and amplify opens customTab in Portrait. So, config change causes activity to destroy.

**Comment by gpanshu** [comment]
@SomnathS09 Your mainactivity is forced to be in landscape and then when the customTab opens it still destoys mainactivity ? Or your mainactivity is adaptable to both and then when the customTab opens it opens in portrait and when the user orients their phone for authentication it recreates the underlying activity too? 
Note: setting the browser orientation is not in scope of Amplify as we can not control behavior or other apps.

**Comment by SomnathS09** [comment]
@[gpanshu](https://github.com/gpanshu) My App is landscape, user does not orient. In any case Amplify doesn't provide API to suggest about orientation for customTab.

**Comment by SomnathS09** [comment]
Those facing the problem similar to me can use `android:configChanges="screenSize|smallestScreenSize|orientation|screenLayout"` for their activity in `AndroidManifest.xml`.
