### ISSUE TITLE
Amplify and federateToIdentityPool problem, NotAuthorizedException(message=Invalid login token. Can't pass in a Cognito token.), recoverySuggestion=Please sign in and reattempt the operation.}

### ISSUE THREAD

**Issue by alex-ivantsov** [aws-amplify/amplify-android#2476]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Authentication, DataStore

### Gradle script dependencies

<details>

```groovy

    implementation "com.amplifyframework:core:2.8.5"
    implementation "com.amplifyframework:aws-storage-s3:2.8.5"
    implementation "com.amplifyframework:aws-auth-cognito:2.8.5"

```

</details>

### Environment information

<details>

```
gradle-7.6
JAVA11
```
</details>

### Describe the bug

I've been trying to integrate Amplify into the Android application but I can't seem to figure out how to initialize the Cognito Auth plugin using a developer authenticated identity and token. User authentication occurs at our server. Once a user has successfully authenticated with the server the client is returned:

Cognitio identityPoolId
region
OpenIdToken identityId
OpenIdToken Token

And I always get the same error

`UnknownException{message=Federation could not be completed., cause=SessionError(exception=NotAuthorizedException{message=Failed since user is not authorized., cause=NotAuthorizedException(message=Invalid login token. Can't pass in a Cognito token.), recoverySuggestion=Please sign in and reattempt the operation.}, amplifyCredential=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@f193e4f), recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}`

### Code Snippet

```kotlin
    Amplify.addPlugin(AWSCognitoAuthPlugin())
    Amplify.addPlugin(AWSS3StoragePlugin())
    val amplifyConfiguration: JsonObject = buildJsonObject {
        putJsonObject("auth") {
            putJsonObject("plugins") {
                putJsonObject("awsCognitoAuthPlugin") {
                    putJsonObject("IdentityManager") {
                        putJsonObject("Default") {}
                    }
                    putJsonObject("CredentialsProvider") {
                        putJsonObject("CognitoIdentity") {
                            putJsonObject("Default") {
                                put("PoolId", cognitoAWS.cognitoConfig.identityPoolId)
                                put("Region", cognitoAWS.cognitoConfig.region)
                            }
                        }
                    }
                }
            }
        }
        putJsonObject("storage") {
            putJsonObject("plugins") {
                putJsonObject("awsS3StoragePlugin") {
                    put(bucket, detailsForAWS.getValueOrException(bucket))
                    put(region, detailsForAWS.getValueOrException(region))
                }
            }
        }
    }

    Amplify.configure( AmplifyConfiguration.fromJson(JSONObject(amplifyConfiguration.toString())), context )

val options = FederateToIdentityPoolOptions.builder().developerProvidedIdentityId(cognitoAWS.openIdToken.identityId).build()
            (Amplify.Auth.getPlugin("awsCognitoAuthPlugin") as? AWSCognitoAuthPlugin)?.let { plugin ->
            plugin.federateToIdentityPool(
                cognitoAWS.openIdToken.token,
                AuthProvider.custom("developer"),
                options,
                {
                    //SUCCESS
                },
                {
                    //ERROR  <- **I am always here!!!**
                }
            )
        } ?: cor.resume(false)

```

### Log output

<details>

```
Auth State Change: ConfiguringAuth(id=)
InitAuthConfig Starting execution
Credential Store State Change: NotConfigured(id=)
Credential Store State Change: MigratingLegacyStore(id=)
MigrateLegacyCredentials Starting execution
MigrateLegacyCredentials Sending event LoadCredentialStore
Credential Store State Change: LoadingStoredCredentials(id=)
LoadCredentialStore Starting execution
Initialized Amplify
Provider GmsCore_OpenSSL not available
LoadCredentialStore Sending event CompletedOperation
Credential Store State Change: Success(storedCredentials=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@e118e9e)
MoveToIdleState Starting execution
MoveToIdleState Sending event MoveToIdleState
Credential Store State Change: Idle(id=)
InitAuthConfig Sending event ConfigureAuthorization
Auth State Change: ConfiguringAuthorization(authNState=NotConfigured(id=), authZState=NotConfigured(id=))
InitAuthZConfig Starting execution
InitAuthZConfig Sending event Configure
Auth State Change: ConfiguringAuthorization(authNState=NotConfigured(id=), authZState=Configured(id=))
ConfigureAuthZ Starting execution
ConfigureAuthZ Sending event ConfiguredAuthorization
Auth State Change: Configured(authNState=NotConfigured(id=), authZState=Configured(id=))
Auth State Change: Configured(authNState=FederatingToIdentityPool(id=), authZState=FederatingToIdentityPool(federatedToken=FederatedToken(token = eyJra***, providerName = developer), fetchAuthSessionState=NotStarted(id=), existingCredential=null))
InitializeFederationToIdentityPool Starting execution
InitializeFederationToIdentityPool Sending event FetchAwsCredentials
Auth State Change: Configured(authNState=FederatingToIdentityPool(id=), authZState=FederatingToIdentityPool(federatedToken=FederatedToken(token = eyJra***, providerName = developer), fetchAuthSessionState=FetchingAWSCredentials(identityId=us-east-1:xxx, logins=AuthProviderLogins(federatedToken=FederatedToken(token = eyJra***, providerName = developer))), existingCredential=null))
FetchAWSCredentials Starting execution
FetchAWSCredentials Sending event ThrowError
Auth State Change: Configured(authNState=Error(exception=NotAuthorizedException{message=Failed since user is not authorized., cause=NotAuthorizedException(message=Invalid login token. Can't pass in a Cognito token.), recoverySuggestion=Please sign in and reattempt the operation.}), authZState=Error(exception=SessionError(exception=NotAuthorizedException{message=Failed since user is not authorized., cause=NotAuthorizedException(message=Invalid login token. Can't pass in a Cognito token.), recoverySuggestion=Please sign in and reattempt the operation.}, amplifyCredential=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@e118e9e)))


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by dkimvvt** [comment]
More details:

There is an identity pool with a custom identity provider (nodejs backend) that returns an identity id and openId token. We don't use user pool as custom identity provider is enough for our solution. In short, we trying to implement [https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html](developer authenticated identities).

Algorithm that we want to implement looks like this:
1. User logs in to the our nodejs backend
2. User make a request to nodejs backend to get an identity id and OpenId token
3. User make a request to the Cognito to receive OpenId token
4. User uses OpenId token to access AWS services.

This algorithm worked just fine for Javascript Amplify, but we struggle to implement this on the Android and iOS sides. On the mobile side, we set up the config using [https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/#set-up-backend-resources](existing resources) (You can see more details in the github issue itself) and then calling `plugin.federateToIdentityPool` method as described in the [Advanced workflows](https://docs.amplify.aws/lib/auth/advanced/q/platform/android/#provide-custom-identity-id). But we get an `UnknownException` error on the Android

Please let us know if you need more details. Thank you

**Comment by gpanshu** [comment]
Hi @dkimvvt it seems getting AWS credentials is whats failing from the log output that you have provided. What method on javascript as you using to get credentials?

**Comment by dkimvvt** [comment]
Hi @gpanshu,
Credentials were correct. We solved the problem by replacing
`AuthProvider.custom("developer"),`
with
`AuthProvider.custom("cognito-identity.amazonaws.com"),`

It worked for some reason. Is there any reason why it worked? Can we reflect this in the documentation?

**Comment by gpanshu** [comment]
Hi @dkimvvt 
This is really good information, thank you for providing that.
Let me address your concerns:
1. We assume everyone uses CLI to generate [resources](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/#set-up-backend-resources) and CLI creates both of these files and hence we did not think we need to additionally mention that both files need to present. We do mention in our [getting started](https://docs.amplify.aws/lib/project-setup/use-existing-resources/q/platform/android/) guide that amplifyconfiguration.json must be present.
2. Since the Custom provider name is a cognito specific information we do not mention it in our docs. But I noticed that it is actually mentioned in the [developer authenticated identities](https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html) page from AWS that you linked which is the right place for this information.

Hope this helps and thank you for providing the solution that worked for you.

**Comment by dkimvvt** [comment]
1. Since we have multiple environments we use AWS CDK instead to manage our infrastructure. Because of this, I used "Existing resources" tab to manually create configuration file.
2. I guess differences between Android and Javascript Amplify libraries created a confusion here. In JS version of Amplify, "custom" worked fine, but it didn't work in the Android

Anyway, the problem is solved. Thank you for help @gpanshu
