### ISSUE TITLE
SESSION_EXPIRED event not called after refresh token expires

### ISSUE THREAD

**Issue by KamilSucharski** [aws-amplify/amplify-android#2481]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, RxJava

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:core:2.8.5'
implementation 'com.amplifyframework:aws-auth-cognito:2.8.5'
implementation 'com.amplifyframework:rxbindings:2.8.5'
```

</details>

### Environment information

<details>

```
------------------------------------------------------------ 
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (JetBrains s.r.o. 17.0.6+0-b2043.56-9586694)
OS:           Windows 10 10.0 amd64
```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/auth-events/q/platform/android/#subscribing-events

### Describe the bug

When the refresh token expires, the SESSION_EXPIRED Hub Event is not sent out. I traced the reason to `RealAWSCognitoPlugin.kt::_fetchAuthSession`:
```
private fun _fetchAuthSession(
	onSuccess: Consumer<AuthSession>,
	onError: Consumer<AuthException>
) {
	val token = StateChangeListenerToken()
	authStateMachine.listen(
		token,
		{ authState ->
			when (val authZState = authState.authZState) {
				is AuthorizationState.SessionEstablished -> {
					authStateMachine.cancel(token)
					onSuccess.accept(authZState.amplifyCredential.getCognitoSession())
				}
				is AuthorizationState.Error -> {
					authStateMachine.cancel(token)
					when (val error = authZState.exception) {
						is SessionError -> {
							when (error.exception) {
								is SignedOutException -> {
									onSuccess.accept(error.amplifyCredential.getCognitoSession(error.exception))
								}
								is SessionExpiredException -> {
									onSuccess.accept(AmplifyCredential.Empty.getCognitoSession(error.exception))
									sendHubEvent(AuthChannelEventName.SESSION_EXPIRED.toString())
								}
								else -> {
									val errorResult = UnknownException("Fetch auth session failed.", error)
									onSuccess.accept(error.amplifyCredential.getCognitoSession(errorResult))
								}
							}
						}
						is ConfigurationException -> {
							val errorResult = InvalidAccountTypeException(error)
							onSuccess.accept(AmplifyCredential.Empty.getCognitoSession(errorResult))
						}
						else -> {
							val errorResult = UnknownException("Fetch auth session failed.", error)
							onSuccess.accept(AmplifyCredential.Empty.getCognitoSession(errorResult))
						}
					}
				}
				else -> Unit
			}
		},
		null
	)
}
```

authState.authZState is AuthorizationState.Error = OK
authZState.exception is SessionError = OK
error.exception is `SessionError(exception=ServiceException{message=invalid_grant, cause=InvalidGrantException{message=invalid_grant, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, amplifyCredential=UserPool(signedInData=SignedInData(userId=fe607f33-1cc6-4414-bad2-8a208512d781, username=google_117104039535815043765, signedInDate=Thu Jun 15 11:05:17 GMT+02:00 2023, signInMethod=HostedUI(browserPackage=null), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***))))` = NOT OK!

If the error.exception was SessionExpiredException, then the event would be sent out as expected.

### Reproduction steps (if applicable)

1. Set the token lifetime to shortest possible (refresh token = 60 minutes)
2. Log in
3. Turn off app
4. Go back after 60 minutes
5. No SESSION_EXPIRED is sent

**Comment by KamilSucharski** [comment]
@gpanshu 
1. Client-side authentication flow, email+password or google. Unauthenticated access is not allowed.
2. fetchUserAttributes returns an NotAuthorizedException in the onError callback:
```
10:05:35.282  W  NotAuthorizedException{message=Failed since user is not authorized., cause=NotAuthorizedException(message=Access Token has expired), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
10:05:35.282  W  	at com.amplifyframework.auth.cognito.CognitoAuthExceptionConverter$Companion.lookup(CognitoAuthExceptionConverter.kt:80)
10:05:35.283  W  	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$fetchUserAttributes$1$1.invokeSuspend(RealAWSCognitoAuthPlugin.kt:1353)
10:05:35.283  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10:05:35.283  W  	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
10:05:35.283  W  	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
10:05:35.283  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
10:05:35.283  W  	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
10:05:35.284  W  	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
10:05:35.284  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
10:05:35.284  W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10:05:35.284  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
10:05:35.284  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
10:05:35.284  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
10:05:35.285  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
10:05:35.285  W  Caused by: NotAuthorizedException(message=Access Token has expired)
10:05:35.285  W  	at aws.sdk.kotlin.services.cognitoidentityprovider.model.NotAuthorizedException$Builder.build(NotAuthorizedException.kt:63)
10:05:35.286  W  	at aws.sdk.kotlin.services.cognitoidentityprovider.transform.NotAuthorizedExceptionDeserializer.deserialize(NotAuthorizedExceptionDeserializer.kt:34)
10:05:35.286  W  	at aws.sdk.kotlin.services.cognitoidentityprovider.transform.GetUserOperationDeserializerKt.throwGetUserError(GetUserOperationDeserializer.kt:65)
10:05:35.286  W  	at aws.sdk.kotlin.services.cognitoidentityprovider.transform.GetUserOperationDeserializerKt.access$throwGetUserError(GetUserOperationDeserializer.kt:1)
10:05:35.286  W  	at aws.sdk.kotlin.services.cognitoidentityprovider.transform.GetUserOperationDeserializerKt$throwGetUserError$1.invokeSuspend(Unknown Source:13)
10:05:35.286  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10:05:35.286  W  	... 5 more
```

> Once your refreshToken expires the only way forward is to resign-in as you can not refresh a refreshToken.

Exactly! But the SDK does not send out the event, so I don't know that the refresh token has expired.

**Comment by gpanshu** [comment]
@KamilSucharski after looking into the code I have identified that when we get a NotAuthorizedException in fetchAuthSession we will get the hub event sent out as you have defined in your first message. However the response you get for the invalid grant seems to be related to how you are getting credentials. 
Lets try to do some basic troubleshooting:

1. Can you confirm if your pool ID in your configuration is correct and there are no typos(please check both awsconfiguration and amplifyconfiguration)
2. Can you also try [fetchAuthSession with forceRefresh](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android/#force-refreshing-session) and paste the response here ?

Also are you able to reproduce this locally or is it just in production?

**Comment by KamilSucharski** [comment]
@gpanshu
I have an update: I was wrong, this does NOT happen on email+password auth, but ONLY on Google auth.
We now tried on iOS with Google login and got the same issue (invalid_grant)!
I think this might be related to things described in this article I found: https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35#.eqa5iwbkt
The RFC 6749 OAuth 2.0 specification (https://datatracker.ietf.org/doc/html/rfc6749#section-5.2) is quoted:
```
invalid_grant
	The provided authorization grant (e.g., authorization
	code, resource owner credentials) or refresh token is
	invalid, expired, revoked, does not match the redirection
	URI used in the authorization request, or was issued to
	another client.
```

The "refresh token is expired" part fits. Can you look into that?

As for your questions:
1. Yes they must be correct, as we didn't have other issues.
2. Didn't do that given the circumstances, let me know if you still want me to.
3. I'm testing on a deployed DEV environment.

**Comment by gpanshu** [comment]
@gpanshu that is indeed helpful information. 

Before we dig further can you attach your amplifyconfiguration.json and ensure you have scope field populated correctly.

**Comment by KamilSucharski** [comment]
@gpanshu Here it is, but I had to censor it:
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "APPNAME-dev",
        "region": "us-east-1"
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "ID",
            "AppClientId": "ID",
            "AppClientSecret": "SECRET",
            "Region": "us-east-1"
          }
        },
        "Auth": {
          "Default": {
            "OAuth": {
              "WebDomain": "DOMAIN",
              "AppClientId": "ID",
              "AppClientSecret": "SECRET",
              "SignInRedirectURI": "APPNAME://",
              "SignOutRedirectURI": "APPNAME://",
              "Scopes": [
                "aws.cognito.signin.user.admin",
                "email",
                "openid",
                "phone",
                "profile"
              ]
            },
            "authenticationFlowType": "USER_SRP_AUTH",
            "loginMechanisms": [
              "PREFERRED_USERNAME"
            ],
            "signupAttributes": [
            ],
            "passwordProtectionSettings": {
              "passwordPolicyCharacters": [
              ]
            },
            "mfaTypes": [
            ],
            "verificationMechanisms": [
            ]
          }
        }
      }
    }
  }
}
```
