### ISSUE TITLE
Android Amplify 2.8.4 (Java) - Logout social did not clear the saved token

### ISSUE THREAD

**Issue by tuancuong009** [aws-amplify/amplify-android#2486]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
2.8.4
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5                                                  
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM)
 version 1.10.11 compiled on July 10 2021
JVM:          18.0.2 (Oracle Corporation 18.0.2+9-61)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

In my app I use this method to login with Google:
`Amplify.Auth.signInWithSocialWebUI(
    AuthProvider.google(), 
    this,
    result -> Log.i("AuthQuickstart", result.toString()),
    error -> Log.e("AuthQuickstart", error.toString())
);`

it works fine, I have a token and process the app features, but if I click Logout button and I use this code:
`Amplify.Auth.signOut(
                        signOutResult -> {
                            Log.i("signOutResult ", signOutResult .toString());
                        }
                );`

the app will log out but if I click button Google login again it will open the home page without asking me to select or input google account to login, I think this case the token is still active, right? how can I log out and when I login again it will ask me to input a Google email? 

Thank you!

### Code Snippet

```java
// Put your code below this line.
`Amplify.Auth.signOut(
                        signOutResult -> {
                            Log.i("signOutResult ", signOutResult .toString());
                        }
                );`
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Hi @tuancuong009 once your sign out succeeds can you try a fetchDevices or any other api call that requires your user to be authenticated and paste the result here? If you are able to perform that action (after a successful signout) then there is a bug however if it says you are not signed in then whats happening is that you are signed out from your app and the user can not perform any action that requires authentication without signing in. Your browser however has you signed in and upon re-signIn it does not ask you for credentials again which is common as browsers cache your session unless you specifically go in and sign out from your browser.

**Comment by tuancuong009** [comment]
@gpanshu thanks for your response, I appreciate it.
And after I signed out successfully, I tried to call the fetchDevices and it shows this error:
`AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=us-west-2:52953373-cba5-47c2-9ad6-4e5de9db7263, error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@1c9e83c, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})`

This means I signed out.

And the issue is if I click login with google again -> it will not ask me to pick an account or input google account -> it logged in automatically with the previous google account. How can we log out the previous google account within the app?

**Comment by gpanshu** [comment]
Yes so that is actually expected behaviour. 

You must go to the google website and log yourself out on your browser or clear all cookies and data from your browser app for you to be able to authenticate again. Please note that these are manual steps and not automated through Amplify if you wish to do that.

If this satisfies your query please feel free to close this issue or respond if you have additional questions regarding this.

**Comment by tuancuong009** [comment]
I got it @gpanshu and thanks for your help, I will close the issue.
