### ISSUE TITLE
Amplify Auth Cognito exception: No native plugin registered

### ISSUE THREAD

**Issue by ThunderLi** [aws-amplify/amplify-android#2492]
I have been already sign in with Amplify.Auth.signIn(username: userName, password: pwd); When the app returns from the background to the foreground, I called  Amplify.Auth.fetchAuthSession,sometimes it throw a exception: No native plugin registered.
And i jump to source code find out :
<img width="712" alt="image" src="https://github.com/aws-amplify/aws-sdk-android/assets/21216049/2b7b943e-2c87-4f68-a620-bcde16557ac8">
in init i already  configure AWSCognitoAuthPlugin(), but i don't know how to cause it and how to solve.

here is my code:
<img width="673" alt="image" src="https://github.com/aws-amplify/aws-sdk-android/assets/21216049/6cc6de51-be39-4977-b158-3a3dc85d1848">

**Environment(please complete the following information):**
 - SDK Version: implementation ('com.amplifyframework:aws-auth-cognito:2.6.0')

**Device Information (please complete the following information):**
 - Device: Galaxy A52

**Comment by eeatonaws** [comment]
Transferring this issue to the Amplify Android repository.

**Comment by ThunderLi** [comment]
Hi @gpanshu I didn't create my own plugin, I already add this line in Application class
`Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.configure(applicationContext)`

And I didn't add NativePluginsCode in my project, Just i found it through  the 'No native plugin registered '  error when i call Amplify.Auth.fetchAuthSession;  But sometime it happen when the app returns from the background to the foreground.

**Comment by gpanshu** [comment]
Hi @ThunderLi where in your code do you have the fetchAuthSession call and when is it run? 
Perhaps the auth plugin has not fully configured yet.
Did you also try to update your core to match your auth library version ?

**Comment by ThunderLi** [comment]
Hi @gpanshu, I updated the latest version of auth library. And call fetchAuthSession when click a button action.

**Comment by gpanshu** [comment]
@ThunderLi can you add `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.DEBUG))` above the cognito plugin in your application class and attach the logs here? I would like to see the sequence of events to help unblock you.

**Comment by gpanshu** [comment]
Hi @ThunderLi following up on this. Can you advise a little more on your setup since you have attached an error from flutter but your code seems to be in Android. More info on your setup will help us troubleshoot your problem and unblock you faster.

**Comment by ThunderLi** [comment]
Hi @gpanshu, This is the Android code of a flutter plugin that I developed myself. In the flutter side, I initialized Amplify and logged in. In the Android side, I invoked some methods of Amplify.

**Comment by gpanshu** [comment]
@ThunderLi I am not entirely sure what you are trying to accomplish but I would love to unblock you asap. Please feel free to schedule a timeslot in my calendar and lets debug in person to figure out what might the issue be : https://prelude.amazon.com/s/3S7KTe9A/TSQMUT
