### ISSUE TITLE
Hidden Link for Android Push Notifications Token Registration

### ISSUE THREAD

**Issue by Etep15** [aws-amplify/amplify-android#2495]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Notifications

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/android/#set-up-backend-resources

### Describe the bug

We have a native android app and are attempting send a push notification to it. We are getting a 410 Permanent Failure from pinpoint. "Unregistered or expired token".

I assume it's because the token is unregistered. But we followed the steps in the Amplify v2 docs for Android. The only issue we had is that the notifications section in the amplifyconfiguration.json file was not present. Even after doing an amplify update notifications. So we added the section manually as per what was show in 

https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/android/#set-up-backend-resources

Under the "Existing Resources" tab. 

This then allowed the Android app to build and run. But we are still getting the error when trying to send a notification to that device.

HOWEVER, through googling, we seemed to have found a hidden page in the docs here...

https://docs.amplify.aws/lib/push-notifications/register-device/q/platform/android/#register-with-amazon-pinpoint

Once we used that code to register the device token. Everything worked. However we can't seem to find a way to get to that documentation through the links in docs in the first link. Seems like a critical piece of documentation. 

It does say however it is not needed if we are using PinPoint (which we are) to send the notifications. But in our case we did need it as we kept getting the not registered error. 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
[[
{
    "$metadata": {
        "httpStatusCode": 200,
        "requestId": "77df6b87-7800-48aa-928b-7a1da52090cf",
        "cfId": "[REDACTED],
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "MessageResponse": {
        "ApplicationId": "[REDACTED]",
        "RequestId": "77df6b87-7800-48aa-928b-7a1da52090cf",
        "Result": {
            "fF7kdZpRRHWUD1oCeUuuiW:APA91bGSih-RziXL8JBCgtOeBZYghLrZ3KHugG7NoZj39cZVC4pV1Ix6cS52-ssK6umYj06r5XfIaM4orwn9ASwy3EdIr8_bR4z7wZSPyrX8vaU_dYhY868yVavmqFNy3NsgvoS9L_s6": {
                "DeliveryStatus": "PERMANENT_FAILURE",
                "StatusCode": 410,
                "StatusMessage": "{\"errorMessage\":\"Unregistered or expired token\",\"channelType\":\"GCM\",\"pushProviderStatusCode\":\"200\",\"pushProviderError\":\"NotRegistered\",\"pushProviderResponse\":\"{\\\"multicast_id\\\":\\\"[REDACTED]\\\",\\\"success\\\":0,\\\"failure\\\":1,\\\"canonical_ids\\\":0,\\\"results\\\":[{\\\"error\\\":\\\"NotRegistered\\\"}]}\"}"
            }
        }
    }
}
]]

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by div5yesh** [comment]
@Etep15 Thank you for pointing this out. We have noted this documentation discoverability issue around notification's custom handling.

Device token registration is handled automatically if you are using Amplify's default service class `FCMPushNotificationService`. We recommend using the default service if you don't plan to make customization to notification handling behavior.

If you want to use a custom service class, use device registration API `Amplify.Notifications.Push.registerDevice(token)` as mentioned in the non-indexed docs page.

**Comment by div5yesh** [comment]
It would helpful to understand your use case and how/why do you plan to customize the notification handling so that we can improve our documentation?

**Comment by Etep15** [comment]
@div5yesh We are using this just to register the device through PinPoint (and then with FCM I'm assuming). I agree that this should register with FCM automatically. 

But we are NOT sending push notifications through the Android App. We are sending them from our backend in our lambdas. Here is the code we are using to send the push notification (works for both iOS and FCM).

`let addresses = {};

		for (let token of tokens)
		{
			addresses[token.toString()] = { "ChannelType": service };
		}

		let message = {
			"Action": action,
			"Body": body,
			"Priority": priority,
			"SilentPush": silent,
			"Title": title,
			"APNSPushType": type, // or alert, background
			"Badge": badge,
			"Sound": sound,
			"Data": data
		}

		let messageRequest = {
			"Addresses": addresses,
			"MessageConfiguration": getMessageConfigurationForService (service, message)
		}
		
		// Using V3 method

		const client = new PinpointClient({ region })
	
		const params = {
			ApplicationId: applicationId,
			MessageRequest: messageRequest,
		}
		const command = new SendMessagesCommand(params)
	
		try 
		{
			const response = await client.send(command)

			return ({err:null, res:response});
		} 
		catch (err) 
		{
			console.log('Send notification err : ', err)
			return ({err:err, res:null});
		}`

Note in this case ChannelType is being set to "GCM" as per PinPoint documentation as this supports both legacy and FCM. There's other functions here creating the objects needed but hopefully this gives you the gist of what we are doing. I can provide that source if needed. But unless we use that RegisterDevice code in the second link in the original question above, we will get a device not registered error.

**Comment by Etep15** [comment]
This shouldn't be closed. Reply above didn't give me an option to keep it open.

**Comment by div5yesh** [comment]
Reopening on @Etep15 behalf.

**Comment by div5yesh** [comment]
Thanks for clarifying your use case. Can you also provide code snippets of the following from your android application?

1. Amplify plugin configuration
2. FCM service class
3. Any other Amplify Notifications APIs called in your activity
