### ISSUE TITLE
Getting java.net.UnknownHostException: Unable to resolve host "cognito-idp.us-east-1.amazonaws.com": No address associated with hostname in various Auth results

### ISSUE THREAD

**Issue by Gesraha101** [aws-amplify/amplify-android#2542]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication, REST API

### Gradle script dependencies

<details>

```groovy
    implementation("com.amplifyframework:aws-api:2.8.7")
    implementation("com.amplifyframework:aws-auth-cognito:2.8.7")
    implementation("com.amplifyframework:core-kotlin:2.8.7")
    implementation("com.auth0.android:jwtdecode:2.0.2")
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18 (Oracle Corporation 18+36-2087)
OS:           Windows 11 10.0 amd64
```

</details>

### Describe the bug

**Describe the bug**
I have been getting `java.net.UnknownHostException: Unable to resolve host "cognito-idp.us-east-1.amazonaws.com": No address associated with hostname` exception in some Auth methods results (mainly Auth.fetchAuthSession since it is the most used one) in live reports. I could not reproduce this myself unfortunately. I even tried to do it by slowing down the network on an emulator, but it worked fine (with a delay of course but it did work). The recovery suggestion is "Sorry, we don't have a suggested fix for this error yet."

It is worth mentioning that I am using proguard with no rules made for amplify. I think I saw someone mentioning there should be some rules for it in an earlier search, but I cannot remember where.

### Code Snippet

```kotlin
try {
    Amplify.Auth.fetchAuthSession()
} catch(e: Exception) {
   println(e.toString())
} 

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "fantoken": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxxxxxxxxxxxxxx",
                    "region": "us-east-1",
                    "authorizationType": "NONE"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxxxxxxxxxxxxxxxxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxxxx",
                        "AppClientId": "xxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "PHONE_NUMBER"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "PHONE_NUMBER"
                        ]
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "xxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "xxxxxxxxxx",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    },
    "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "cloudFrontURL": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

### GraphQL Schema

N/A

**Comment by mattcreaser** [comment]
Hi @Gesraha101 this most often occurs because the clock on the device is different from local time. If your users do not have their time set correctly then they will not be able to use Auth APIs.

**Comment by Gesraha101** [comment]
Hello @mattcreaser thanks for the quick reply. I have tried to mess with the time on my device using the build on store but did not have any luck reproducing the behavior. I have been trying for an hour now.

I remember that the time messing resulted in a similar behavior in an old version (v1.33.4 to be exact). I used to get an exception out of the box when trying to even call Auth.signIn but cannot remember what it was exactly, hence why I upgraded to latest version back then (might have been the same one users are currently having).

Is there something different I need to do in order to reproduce it?

**Comment by Gesraha101** [comment]
Hello @mattcreaser following up on this. any news?
We have been getting many crashes and would appreciate fixing the issue ASAP

**Comment by mattcreaser** [comment]
@Gesraha101 I don't have any updates on this yet. I have also been unable to reproduce this issue so far. I'm still trying.

Do you have any data on whether the crashes are coming from a specific geographic region?

**Comment by mattcreaser** [comment]
@Gesraha101 that tracks with similar errors we've been seeing recently from users in Egypt. This is due to the change to DST this summer and a lack of corresponding device updates from Android manufacturers to correctly account for this change.

In this particular case, my current understanding is that the DNS lookup fails because of a DNSSEC signature validation error due to the incorrect device time falling outside of the signature's valid period. I am trying to learn more about this and will update this comment if my understanding changes.

Unfortunately DNS lookups occur at a much lower level than Amplify, so we don't currently have any solution to address this issue.

**Comment by Gesraha101** [comment]
Okay, that explains why errors from Egypt occur but why elsewhere? AFAIK, the DST situation should only be in Egypt this summer, right?

**Comment by tjleing** [comment]
@Gesraha101 because it's device/manufacturer-specific it's very reasonable that you could have never ran into this issue, especially if you are up-to-date with your device updates.  To reiterate, this is only an issue for users whose devices are either not updated or whose manufacturers have not provided updates that allow for the possibility of DST occurring in Egypt, as this is a new change in that region.

Alternately, you might see errors in other regions if their device times are not set correctly -- to reproduce this, you can set your device time to a value > 5 minutes from the correct one and observe whether or not the request goes through successfully.  If it does work or if it returns a different issue from the one you're currently getting, we can proceed to test a different hypothesis.

**Comment by Gesraha101** [comment]
@tjleing when I tampered with the device time (emulator this time), I got an issue that might be related to the current one at hand. I noticed that after logging in, just after the Id token expires, the Auth client returns the same expired token and is unable to refresh it anymore.

It wasn't instantaneous though. I had to wait for a couple of days for the issue to emerge.

**Comment by gpanshu** [comment]
Hi @Gesraha101 did you do fetchAuthSession with forceRefresh true? essentially if your device time is in the future and you sign in the current token will be deemed invalid if the current time > expiry time  and each refresh might fail at that point or return the same access token if the token is valid from a server perspective.
