### ISSUE TITLE
Service Not available FCM crash from Pinpoint

### ISSUE THREAD

**Issue by jeffville** [aws-amplify/amplify-android#2559]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Notifications

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:aws-api:2.11.1"
implementation "com.amplifyframework:aws-auth-cognito:2.11.1"
implementation "com.amplifyframework:aws-push-notifications-pinpoint:2.11.1"
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------
Kotlin:       1.6.21
Groovy:       3.0.10

```

</details>

### Describe the bug

We are getting a crash FCM: SERVICE_NOT_AVAILABLE on Pinpoint SDK (AWSPinpointPushNotificationsPlugin.kt:167) 
during initialisation. 

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
com.google.android.gms.tasks.zzw.getResult (com.google.android.gms:play-services-tasks@@18.0.2:3)
com.amplifyframework.pushnotifications.pinpoint.AWSPinpointPushNotificationsPlugin.fetchFCMDeviceToken$lambda-4 (AWSPinpointPushNotificationsPlugin.kt:167)
androidx.navigation.ui.NavigationUI$$ExternalSyntheticLambda0.b (R8$$SyntheticClass:11)
com.google.android.gms.tasks.zzi.run (zzi.java:1)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:268)
android.app.ActivityThread.main (ActivityThread.java:8016)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:627)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:997)

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tjleing** [comment]
Closing as #2555 is also closed for the same reason.  Please upgrade to v2.12.0 or higher.
