### ISSUE TITLE
Cant use PinpointProperties.builder().add()

### ISSUE THREAD

**Issue by HaitianZhuu** [aws-amplify/amplify-android#256]
I follow this guide:
https://aws-amplify.github.io/docs/android/analytics
```
BasicAnalyticsEvent event = new BasicAnalyticsEvent("Amplify-event" + UUID.randomUUID().toString(),
            PinpointProperties.builder()
            .add("DemoProperty1", "DemoValue1")
            .add("DemoProperty2", 2.0)
            .build());
```
![image](https://user-images.githubusercontent.com/47531353/73808584-6b48e180-480b-11ea-9e78-29db36c3cbe1.png)

Cant access PinpointProperties.builder().add()

**Comment by raphkim** [comment]
Hi @HaitianZhuu ,

Thank you for reporting this issue to us. This is indeed a bug that we will deploy a fix for in our next releases.

**Comment by jamesonwilliams** [comment]
Fixed in master ^
