### ISSUE TITLE
Unable to use existing appsync api without models

### ISSUE THREAD

**Issue by SeyiKayode** [aws-amplify/amplify-android#2574]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```
implementation("com.amplifyframework:core:2.12.0")
</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I followed the amplify android docs on using existing graphql api. After following this process, i wasn't able to use the appsync graphql api beacuse it doesn't have models. I couldn't find any part in the docs where an existing appsync graphql api was used and up till now i am unable to call any mutation or query because there i have not generated models to use. In the existing appsync api, model was not used.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by ankpshah** [comment]
Hi could you check if following Amplify documentation helps you to add existing AppSync endpoint for your usecase: https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/android/

**Comment by SeyiKayode** [comment]
I followed that but still wasn’t able to call the appsync api. I had to use custom request with the amplify GraphQLRequest where I parsed the schema as string and sent the request. So it works now.

**Comment by SeyiKayode** [comment]
> Hi could you check if following Amplify documentation helps you to add existing AppSync endpoint for your usecase: https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/android/

I followed that but still wasn’t able to call the appsync api. I had to use custom request with the amplify GraphQLRequest where I parsed the schema as string and sent the request. So it works now.

**Comment by ankpshah** [comment]
Have you tried using `amplify codegen models` as given in docs [here](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android/#configure-api:~:text=setup%20walkthrough.-,Generate%20Todo%20Model%20class,-To%20generate%20the):

**Comment by SeyiKayode** [comment]
> Have you tried using `amplify codegen models` as given in docs [here](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android/#configure-api:~:text=setup%20walkthrough.-,Generate%20Todo%20Model%20class,-To%20generate%20the)
> This will create model for the schema.

I have gotten it to work using the custom GraphQLRequest, the existing appsync api didn’t have model

**Comment by ankpshah** [comment]
Ok is there any open question that needs to be addressed?

**Comment by SeyiKayode** [comment]
> Ok is there any open question that needs to be addressed?

Not at all, thank you

**Comment by ndeka28** [comment]
@SeyiKayode  Can you please paste an example how the custom query works, I am trying the same from the documentation, but gives me a null response. Your great will highly be appreciated, as I am completely blocked

**Comment by SeyiKayode** [comment]
> @SeyiKayode Can you please paste an example how the custom query works, I am trying the same from the documentation, but gives me a null response. Your help will highly be appreciated, as I am completely blocked


for android kotlin, i generated the queries with the schema.graphql file using amplify codegen. Below is an example of a generated query after running "amplify codegen add"

query GetUserDetails($id: String) {
  getUserDetails(id: $id) {
    userDetails {
      id
      name
      address
      contact
      email
      city
      country
      userId
      createdAt
      updatedAt
    }
    error
  }
}

This generated query above, make it a string variable and it becomes...

val getUserDetailsQuery = "query GetUserDetails(\$id: String) {\n" +
            "  getUserDetails(id: \$id) {\n" +
            "    userDetails {\n" +
            "      id\n" +
            "      name\n" +
            "      address\n" +
            "      contact\n" +
            "      email\n" +
            "      city\n" +
            "      country\n" +
            "      userId\n" +
            "      createdAt\n" +
            "      updatedAt\n" +
            "    }\n" +
            "    error\n" +
            "  }\n" +
            "}"
            
 
After making it a string, write another function that contains the graphqlRequest which maps the id parameter and also makes use of the getUserDetailsQuery variable above (assuming it's kotlin)...

fun getUserDetailsRequest(id: String): GraphQLRequest<String> {
    return SimpleGraphQLRequest(
        Queries.getUserDetailsQuery,
        mapOf("id" to id),
        String::class.java,
        GsonVariablesSerializer()
    )
}


To finally make the api request, use the Amplify.API.query together with getUserDetailsRequest above. example below...

suspend fun getUserDetails(id: String): GetUserDetailsResult {
        return try {
            val response = Amplify.API.query(getUserDetailsRequest(id))
            val gson = Gson()
            val graphqlResponse = gson.fromJson(response.data, GetUserDetailsGraphQLResponse::class.java)
            GetUserDetailsResult.Success(graphqlResponse)
        } catch (error: ApiException) {
            GetUserDetailsResult.Failure(error)
        }
    }
    
from here, you will be able to get your result. I used Gson() to deserialize the data here and also used GetUserDetailsResult to declare the result type. You can customize yours.

**Comment by ndeka28** [comment]
Thanks a lot @SeyiKayode  I will have a try now, probably i have done something wrong with Gson desrialization

**Comment by ndeka28** [comment]
@SeyiKayode I Get below error while trying the same

```
getUserDetails: NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
2024-01-23 10:30:58.124 30207-30249 ProfileInstaller        com.nila.carwithcustomquery          D  
```

My code here:
```

suspend fun getUserDetails(id: String){
     try {
        val response = Amplify.API.query(getCar(id))
        val gson = Gson()
        val graphqlResponse = gson.fromJson(response.data, CarNew::class.java)

    } catch (error: ApiException) {
       
         Log.e("Nila", "getUserDetails: $error")
    }
}

private fun getCar(id: String) : GraphQLRequest<String> {
    val document = "query GetCarNew($id: String!) {\n" +
            "  getCarNew(id: $id) {\n" +
            "    id\n" +
            "    name\n" +
            "    __typename\n" +
            "  }\n" +
            "}"

    return SimpleGraphQLRequest(
        document,
        mapOf("id" to id),
        String::class.java,
        GsonVariablesSerializer()
    )
}
```
```


    // Amplify API and Datastore dependencies
    implementation("com.amplifyframework:core:2.14.6")
    implementation("com.amplifyframework:aws-api:2.14.6")
    implementation("com.amplifyframework:core-kotlin:2.14.6")

    // Support for Java 8 features
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:1.1.5")
```

Do you know any reason for this ?

Thanks,
Nila

**Comment by SeyiKayode** [comment]
> @SeyiKayode I Get below error while trying the same
> 
> ```
> getUserDetails: NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
> 2024-01-23 10:30:58.124 30207-30249 ProfileInstaller        com.nila.carwithcustomquery          D  
> ```
> 
> My code here:
> 
> ```
> 
> suspend fun getUserDetails(id: String){
>      try {
>         val response = Amplify.API.query(getCar(id))
>         val gson = Gson()
>         val graphqlResponse = gson.fromJson(response.data, CarNew::class.java)
> 
>     } catch (error: ApiException) {
>        
>          Log.e("Nila", "getUserDetails: $error")
>     }
> }
> 
> private fun getCar(id: String) : GraphQLRequest<String> {
>     val document = "query GetCarNew($id: String!) {\n" +
>             "  getCarNew(id: $id) {\n" +
>             "    id\n" +
>             "    name\n" +
>             "    __typename\n" +
>             "  }\n" +
>             "}"
> 
>     return SimpleGraphQLRequest(
>         document,
>         mapOf("id" to id),
>         String::class.java,
>         GsonVariablesSerializer()
>     )
> }
> ```
> 
> ```
> 
> 
>     // Amplify API and Datastore dependencies
>     implementation("com.amplifyframework:core:2.14.6")
>     implementation("com.amplifyframework:aws-api:2.14.6")
>     implementation("com.amplifyframework:core-kotlin:2.14.6")
> 
>     // Support for Java 8 features
>     coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:1.1.5")
> ```
> 
> Do you know any reason for this ?
> 
> Thanks, Nila


remove __type name from the document, add a slash before $id like I did in the example

**Comment by ndeka28** [comment]
@SeyiKayode  That helps resolve the error, I can query and mutate now. Thanks a lot for your help

Another note, since Aws App sync [sdk](https://github.com/awslabs/aws-mobile-appsync-sdk-android) , already generates all queries nad mutations already and much easier to use. Is there any particular reason to use Amplify SDK ? Looks doing through Amplify is much complex than Aws App Sync SDK.

Thanks
Nilanjana

**Comment by SeyiKayode** [comment]
> @SeyiKayode That helps resolve the error, I can query and mutate now. Thanks a lot for your help
> 
> Another note, since Aws App sync [sdk](https://github.com/awslabs/aws-mobile-appsync-sdk-android) , already generates all queries nad mutations already and much easier to use. Is there any particular reason to use Amplify SDK ? Looks doing through Amplify is much complex than Aws App Sync SDK.
> 
> Thanks Nilanjana

Amplify is used for authentication with aws cognito, its also used for mobile development on aws. So its just better to call endpoints with it too instead of using another new library to make requests. Amplify can also be used to create the api, depends on the requirements.
