### ISSUE TITLE
Could not receive token from additionalInfo{} when calling `signInWithWebUi` method after migrated to amplify v2

### ISSUE THREAD

**Issue by arvelalanaidn** [aws-amplify/amplify-android#2581]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
  implementation("com.amplifyframework:core:2.13.0")
  implementation("com.amplifyframework:aws-auth-cognito:2.13.0")
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.20 (Amazon.com Inc. 11.0.20+8-LTS)
OS:           Mac OS X 13.0.1 aarch64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/#configure-auth-category

### Describe the bug

Hi, 
After I migrated to amplify v2 from v1, I could not receive token from `additionalInfo{}` response when calling `signInWithWebUi` method, this is my response before and after migrating to v2.

My `signInWithWebUi` Implementation 

```
Amplify.Auth.signInWithWebUI(
  activity,
  { result ->
    onSuccess.invoke(println(result.toString))
  },

  { ex ->
    onFailure.invoke(ex)
  },
)
```
amplify version 2.13.0  response:
`signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null`

amplify version 1.37.3 response:
`signInStep=DONE, additionalInfo={provider=cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_60Qu63nZM, token=eyJraWQiOiJ4R3lqTmdNK3JBZlRQc2VwczVhe....}, codeDeliveryDetails=null`

**Any instructions on how to get token from Amplify v2?**

### Reproduction steps (if applicable)

1. Implement SignInWithWebUI
2. Login into existing webview
3. Print the result

### Code Snippet

```kotlin
// Put your code below this line.

Amplify.Auth.signInWithWebUI(
  activity,
  { result ->
    onSuccess.invoke(println(result.toString))
  },

  { ex ->
    onFailure.invoke(ex)
  },
)
```

### Log output

<details>

```
// Put your logs below this line
amplify version 2.13.0 response:
signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null

amplify version 1.37.3 response:
signInStep=DONE, additionalInfo={provider=cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_60Qu63nZM, token=eyJraWQiOiJ4R3lqTmdNK3JBZlRQc2VwczVhe....}, codeDeliveryDetails=null

```

</details>

### amplifyconfiguration.json

```json
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-southeast-1",
                            "Region": "ap-southeast-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-1",
                        "AppClientId": "xxxxx",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "account.satekxxx.com",
                            "AppClientId": "xxxxx",
                            "SignInRedirectURI": "idnapp://profile/me/",
                            "SignOutRedirectURI":  "idnapp://home/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        }
                    }
                }
            }
        }
    }
}

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
Hi @arvelalanaidn we'll take a look and get back to you soon.

**Comment by mattcreaser** [comment]
@arvelalanaidn This is the intended behaviour in V2. Please see [this document](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android/) for information about how to access the user's token. The code you want will look something like:

```kotlin
// Using coroutines
val session = Amplify.Auth.fetchAuthSession() as AWSCognitoAuthSession
val token = session.accessToken
```

Please let us know if you have any other questions.

**Comment by arvelalanaidn** [comment]
@mattcreaser Hi, I have used that code for accessToken, but my `idToken` is still null after I log out and log in again then fetchAuthSession using this code

```
       Amplify.Auth.fetchAuthSession(
        {
          val session = it as AWSCognitoAuthSession
          when (session.identityIdResult.type) {
            AuthSessionResult.Type.SUCCESS ->
              session.userPoolTokensResult.value?.let { awsUserPoolTokens -> println(awsUserPoolTokens.idToken)}
          }
        })
```

Any instructions on how to properly log out and get an IdToken after logging out and logging in again? Because my IdToken is always null after trying to log out then immediately log in using this code.

```
    Amplify.Auth.signOut { signOutResult ->
      when (signOutResult) {
        is AWSCognitoAuthSignOutResult.CompleteSignOut -> {
          // Call sign In function and fetchAuthSession
          toSignIn()
        }
```

**Comment by tylerjroach** [comment]
@arvelalanaidn 

Just to confirm, your  `PoolId` under the Default block of CognitoUserPool is something like  `"PoolId": "ap-southeast-1_xxxx"` right?

I created a clean `signInWithWebUi` sample app and am receiving a value for `idToken` in the AWSCognitoUserPoolTokens type.

**Comment by arvelalanaidn** [comment]
@tylerjroach yes

```
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-1",
                        "AppClientId": "xxxxx",
                        "Region": "ap-southeast-1"
                    }
                },
```

did you try logging in immediately after logging out?
I get a completeResult after logout, but when I try to log in again, my idToken is null
This is my code for logout and login

SignOut
```
    Amplify.Auth.signOut { signOutResult ->
      when (signOutResult) {
        is AWSCognitoAuthSignOutResult.CompleteSignOut -> {
          // Call sign In function and fetchAuthSession
          toSignIn()
        }
```

SignIn
```
    Amplify.Auth.signInWithWebUI(
      activity,
      { result ->
        onSuccess.invoke(
          fetchAuthSession()
        )
      },
```

Fetch
```
       Amplify.Auth.fetchAuthSession(
        {
          val session = it as AWSCognitoAuthSession
          when (session.identityIdResult.type) {
            AuthSessionResult.Type.SUCCESS ->
              session.userPoolTokensResult.value?.let { awsUserPoolTokens -> println(awsUserPoolTokens.idToken)}
          }
        })
```

**Comment by tylerjroach** [comment]
Hi @arvelalanaidn 

I see that you said yes, but in the latest post, your PoolId still just shows the region. A PoolId contains more than just a region.

I understand that you may have just removed the additional characters to obfuscate the PoolId, but just to make sure it is understood, your user pool config should look more like this.

```
"CognitoUserPool": {
  "Default": {
    "PoolId": "ap-southeast-1_xxxxxxxxx",
    "AppClientId": "xxxxx",
    "Region": "ap-southeast-1"
  }
}
```

**Comment by mattcreaser** [comment]
Hey there! We haven't heard back on this so we'll close this issue. Please feel free to open a new issue if needed.
