### ISSUE TITLE
Auth rememberDevice — InvalidParameterException, value null at 'deviceKey'

### ISSUE THREAD

**Issue by JPUF** [aws-amplify/amplify-android#2585]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
    def amplifyVersion = '2.11.2'
    implementation "com.amplifyframework:core:$amplifyVersion"
    implementation "com.amplifyframework:aws-auth-cognito:$amplifyVersion"
    implementation "com.amplifyframework:aws-api:$amplifyVersion"
    implementation "com.amplifyframework:aws-storage-s3:$amplifyVersion"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Eclipse Adoptium 17.0.7+7)
OS:           Mac OS X 13.4 x86_64
```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/device_features/q/platform/android/#configure-auth-category

### Describe the bug

I'm trying to block users from signing-in on multiple devices concurrently. My attempted solution is to block the user's progress if Auth.fetchDevices() returns multiple devices, or call Auth.rememberDevice() if there are no tracked devices. This works on a fresh install, first pass. Then when the user signs-out, I call Auth.forgetDevice(). After which, calling Auth.rememberDevice() when signing-in again returns the InvalidParameterException. 

I've seen a [similar thread for Amplify JS](https://github.com/aws-amplify/amplify-js/issues/3040). The proposed solution there is to call a `cognitoUser.getCachedDeviceKeyAndPassword()` method, which I can't find for Android.

### Reproduction steps (if applicable)

1. Auth.signIn() -> Auth.rememberDevice()
2. Auth.forgetDevice() -> Auth.signOut()
3. Auth.signIn() -> Auth.rememberDevice()
4. Exception thrown by rememberDevice()

### Code Snippet

```kotlin
override suspend fun rememberDevice(): Result<Unit> = suspendCoroutine { continuation ->
    auth.rememberDevice(
        /* onSuccess = */ {
            continuation.resume(Result.success(Unit))
        },
        /* onError = */ { error ->
            logger.logError(error)
            continuation.resume(Result.failure(error))
        }
    )
}

```

### Log output

<details>

```
InvalidParameterException{message=One or more parameters are incorrect., cause=InvalidParameterException(message=1 validation error detected: Value null at 'deviceKey' failed to satisfy constraint: Member must not be null), recoverySuggestion=Enter correct parameters.}
	at com.amplifyframework.auth.cognito.CognitoAuthExceptionConverter$Companion.lookup(CognitoAuthExceptionConverter.kt:70)
	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$updateDevice$1.invokeSuspend(RealAWSCognitoAuthPlugin.kt:1132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by JPUF** [comment]
I also forgot to mention that my AWS Cognito user pool Device Tracking setting is set to User Opt-In.

**Comment by tylerjroach** [comment]
Thank you for the details. One of the members will attempt to replicate your scenario and reply back.

**Comment by tylerjroach** [comment]
@JPUF I was able to replicate the issue.

I believe we have a bug that `DeviceMetadata`, which contains `deviceKey` is not accessible immediately after sign in (It should be!). It is correctly loaded once the app is closed and reopened.

In your replication scenario, if you closed the app after signIn and before rememberDevice, I believe your use case would work as expected.

We will label this as a bug and someone on our team will take on the fix. Thank you for your report.
