### ISSUE TITLE
Getting same auth session from Amplify Sdk

### ISSUE THREAD

**Issue by rajanroushan-snnventure** [aws-amplify/amplify-android#2590]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>
val option = AuthFetchSessionOptions.builder().forceRefresh(true).build()
        Amplify.Auth.fetchAuthSession(option,
            { result ->
                val cognitoAuthSession = result as AWSCognitoAuthSession
                when (cognitoAuthSession.userPoolTokensResult.type) {
                    AuthSessionResult.Type.SUCCESS -> Log.e("Tag","IdentityId: " + cognitoAuthSession.userPoolTokensResult.value)
                    AuthSessionResult.Type.FAILURE -> showMessage("IdentityId not present because: " + cognitoAuthSession.userPoolTokensResult.error.toString())
                }
            },
            { error -> showMessage(error.toString()) }
        )
I used this to get the update session for the loged in  user. 
When i installed 1st time application and login it's successfully getting all info but when Id token got expire the i try to update session id and the need to find user info but i got Jwt Expired Exception because token got expire. so when i hit again and again getting same token.
I used kotlin version 1.8.0
Java - 11
Amplify - 2.13.0
Apollo - 2.5.11
gradle version - 7.0.4
target sdk - 33
Even after this integration i am getting Apollo Parse Exception 

### Environment information

<details>

```
# Put output below this line


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/#update-androidmanifestxml

### Describe the bug

1. Newly installed
2. login with username and password
3. token id expire time 30 min after this time i try to login but getting token got expired because token it didn't expire

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Can you add `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE)` as the first configured Amplify plugin and provide the logs when a refresh is attempted.

What is the refresh token validity set at in Cognito?

**Comment by rajanroushan-snnventure** [comment]
refresh token - 30 days
Id token - 15min

**Comment by rajanroushan-snnventure** [comment]
In IOS Native it's working

**Comment by rajanroushan-snnventure** [comment]
Hi @tylerjroach is anything missing?. I am using login for  Amplify.Auth and for graphql i am using apollo. so when i am using Amplify.Auth version 2 then apollo not working else it's working but as i can see in documentation that need to upgrade to v2.

**Comment by rajanroushan-snnventure** [comment]
WSCognitoAuthSession(isSignedIn=true, identityIdResult=AuthSessionResult{value=null, error=ConfigurationException{message=Could not retrieve Identity ID, cause=null, recoverySuggestion=Cognito Identity not configured. Please check amplifyconfiguration.json file.}, type=FAILURE}
When we try to fetch session when user signed in then i got above error because token got expired

**Comment by rajanroushan-snnventure** [comment]
Hi @tylerjroach can you please check the log for me i have added the Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE)) can you please check and let me know the problem

**Comment by rajanroushan-snnventure** [comment]
"CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "[COGNITO IDENTITY POOL ID]",
              "Region": "[REGION]"
            }
          }
        }
is this required ? as i m getting identity id is not properly set. @tylerjroach @ericclemmons @calavera @jpignata

**Comment by tylerjroach** [comment]
@rajanroushan-snnventure Yes, that block is required, with the proper poolId and Region entered. Did you already have that in your `amplifyconfiguration.json` file? If not, please make sure it is added.

**Comment by tylerjroach** [comment]
I believe the issue was the missing block discussed above. If your issue is not resolved, please reach back out.
