### ISSUE TITLE
Android and ios behave differently in Aws Amplify

### ISSUE THREAD

**Issue by rajanroushan-snnventure** [aws-amplify/amplify-android#2595]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:aws-auth-cognito:2.13.2'

```

</details>
I have Signed in into one device after 5 min i want to login in another device so in Android i m getting SignedInException in Android but in IOS i am able log in successfully there is not exception we found. can any one let me know why this two have different behaviour.  

### Environment information

<details>

```
# Put output below this line

Android
I m using Aws Amplify -2.13.2
Kotlin - 1.8
Java - 11
IOS
Aws Amplify - 2.15.2
```

</details>

### Describe the bug

I have Signed in into one device after 5 min i want to login in another device so in Android i m getting SignedInException in Android but in IOS i am able log in successfully there is not exception we found

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

Nothing

**Comment by tylerjroach** [comment]
You should be able to sign in as a user on as many devices as you want, with no time limits between. If you are getting a SignedInException on the second device, it is likely because you were already signed in on that device. Please ensure the device is in a Signed Out state before trying to Sign In.
