### ISSUE TITLE
ApiClientException: Failed to get credentials from Cognito Identity

### ISSUE THREAD

**Issue by uvinodh** [aws-amplify/amplify-android#2600]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
ext {
    amplifyVersion = '1.36.3'
}

   implementation 'com.amplifyframework:core-kotlin:0.2.0'
   
    implementation "com.amplifyframework:aws-analytics-pinpoint:$amplifyVersion"
    implementation "com.amplifyframework:aws-api:$amplifyVersion"
    implementation "com.amplifyframework:aws-auth-cognito:$amplifyVersion"
    implementation "com.amplifyframework:aws-datastore:$amplifyVersion"
    implementation "com.amplifyframework:aws-predictions:$amplifyVersion"
    implementation "com.amplifyframework:aws-storage-s3:$amplifyVersion"
     implementation 'com.amplifyframework:core:1.36.3'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

We are getting the following error when we call an aws-sdk api just after login:
`ApiClientException: Failed to get credentials from Cognito Identity`

This is happening only on one device, Pixel 5.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
Hi @uvinodh, could you please provide a more complete description of the issue? A snippet showing what call(s) you are trying to make and a full log output would be a good start. 

I'm particularly interested in what you mean by "just after login" - does this mean after getting a response to the signIn API, or after receiving a Hub event, or something else? Also, is this a single device that you use for development testing?

**Comment by uvinodh** [comment]
@mattcreaser  

Hey, Thanks for the response. 

"just after login" => We use Amplify kotlin-coroutines signIn API for login.

`Amplify.Auth.signIn(email, password)`

 After we get login response as success, we proceed to call one of our backend API using AWS SDK. This API responds with error "ApiClientException: Failed to get credentials from Cognito Identity"

This is happening on one of the customers device, which is Pixel 5. 
Since, it's happening on the customer's phone, we are unable to provide the log output.

Thanks,

**Comment by gpanshu** [comment]
I have tested calling other Amplify APIs right after sign in and it seems to work. Can you please try the following: 

1. Update your Amplify to the latest versions of either the AWS SDK for Android (which is what you are currently using) or the V2 version (Amplify Android). I would recommend the [V2 version](https://github.com/aws-amplify/amplify-android/). 
2. Add the logging plugin if you can debug this locally by adding `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))` as the very first line in your plugins list on your app. 
Once you have done the above please comment back with the results and we can dive deeper together.
