### ISSUE TITLE
ConfirmSignIn to set a new password with user attribute doesn't work during first access 

### ISSUE THREAD

**Issue by gianluigi-bresaola** [aws-amplify/amplify-android#2622]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:core:2.14.2' 
implementation 'com.amplifyframework:aws-auth-cognito:2.14.2'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.4                                                  
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (JetBrains s.r.o. 17.0.6+0-b2043.56-10027231)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

After first sign in with a temporary password I receive CONFIRM_SIGN_IN_WITH_NEW_PASSWORD step, then I confirm with a new password and phone number but I get the follow error:
InvalidParameterException{message=One or more parameters are incorrect., cause=InvalidParameterException(message=Invalid attributes given, phone_number is missing), recoverySuggestion=Enter correct parameters.}
Phone number is in format "+ country code number" like as amplify documentation descibes and is provided as attribute to confirmSignIn function.

### Code Snippet

```java
// Put your code below this line.
val options = AWSCognitoAuthConfirmSignInOptions.builder()
            .userAttributes(
                listOf(
                    AuthUserAttribute(
                        AuthUserAttributeKey.phoneNumber(),
                        "+XXYYYYYYY"
                    )
                )
            )
            .build()

        Amplify.Auth.confirmSignIn(
            newPassword,
            options,
            { 
                onSuccess()
            },
            {
                onError()
               
            }
        )
```

### Log output

<details>

```
// Put your logs below this line
InvalidParameterException{message=One or more parameters are incorrect., cause=InvalidParameterException(message=Invalid attributes given, phone_number is missing), recoverySuggestion=Enter correct parameters.}

```

</details>

### amplifyconfiguration.json

{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "poolid",
            "AppClientId": "clientid",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "socialProviders": [],
            "usernameAttributes": [],
            "signupAttributes": [
              "EMAIL"
            ],
            "passwordProtectionSettings": {
              "passwordPolicyMinLength": 8,
              "passwordPolicyCharacters": []
            },
            "mfaConfiguration": "ON",
            "mfaTypes": [
              "SMS"
            ],
            "verificationMechanisms": [
              "EMAIL"
            ]
          }
        }
      }
    }
  }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by ankpshah** [comment]
Hello,
   The placeholder "+XXYYYYYYY" does not seem to follow the E.164 format.

**Comment by gianluigi-bresaola** [comment]
Hello,
thank you for the reply.
That's a fake placeholder to hide my personal number.
The number I send with attributes is "+39349411XXXX" , I tried with another number but I get the same error.
I tried with same code but Ios amplify version  and I can reach the end of first access flow with same account.

**Comment by gianluigi-bresaola** [comment]
Hello,
inside the library source code, I found that property "userAttributes"  of the class AWSCognitoAuthConfirmSignInOptions is not used inside function "_confirmSignIn" in the class RealAWSCognitoAutjPlugin, so the phone number attribute never reach the backend.

**Comment by tylerjroach** [comment]
Thank you for digging into this. Will take a further look.

**Comment by tylerjroach** [comment]
@gianluigi-bresaola Just wanted to provide an update that I've worked on a fix and we will work on getting this into a release. https://github.com/aws-amplify/amplify-android/pull/2640

**Comment by marcozabo** [comment]
Same problem here, @tylerjroach do you know when the fix will be released?
