### ISSUE TITLE
Android AWS Pinpoint -User Does Not Match Cognito

### ISSUE THREAD

**Issue by berdano** [aws-amplify/amplify-android#2636]
### Amplify CLI Version

2.45

### Question

Using AWS Pinpoint, I want to connect and send remote notifications when the application is logged in.

I made the necessary connections for this and created my awsconfiguration.json file.

My project includes Cognito, the connection must be established automatically and the user information, sub id, etc. must reach the server. It reaches the server, but the user information does not arrive.

Can you help me ?

awsconfiguration.json file:

```

"CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "eu-cenxxxxxxXXXXX1cfea",
        "Region": "eu-XXXXX-1",
        "AppClientId": "1rbXXXXXXXXXXg2"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PinpointAppId": "aXXXXXXXXXXbe40",
      "PoolId": "eu-central-XXXXXG0",
      "AppClientId": "1XXXXXXXXXXcg2",
      "Region": "eu-central-1",
      "AppClientSecret": "1X6XXXXXXXXXXXXXXXXXXXqm"
    }
  },
  "Auth": {
    "Default": {
      "OAuth": {
        "WebDomain": "login-brand-customer-dev.auth.eu-central-1.amazoncognito.com",
        "AppClientId": "1rbeXXXXXXXXXg2",
        "AppClientSecret": "1XXXXXXXXXXXXXXXXXXXX7qm",
        "SignInRedirectURI": "XXX://callback",
        "SignOutRedirectURI": "XXX://signout",
        "Scopes": ["profile", "openid", "email", "aws.cognito.signin.user.admin"]
      }
    }
  },
  "PinpointAnalytics": {
    "Default": {
      "AppId": "abXXXXXXXXXXXX40",
      "Region": "eu-cXXX-1"
    }
  },
  "PinpointTargeting": {
    "Default": {
      "Region": "eXXXral-1"
    }
  }
```
    (I added the X's for privacy.)

and my init code:

```
override fun initializePinpoint() {
        AWSMobileClient.getInstance().initialize(
            appContext,
            object : Callback<UserStateDetails> {
                override fun onResult(result: UserStateDetails) {
                    test(appContext)
                }
                override fun onError(e: Exception) {
                    logger.e(e) { "Error initializing AWS mobile client" }
                }
            }
        )

private fun test(context: Context) {
        val pinpointManager: PinpointManager
        val firebaseMessaging = FirebaseMessaging.getInstance()
        val id = AWSMobileClient.getInstance().tokens.idToken.getClaim("sub")

        val pinpointConfiguration = PinpointConfiguration(
            context,
            AWSMobileClient.getInstance(),
            AWSMobileClient.getInstance().configuration
        )
        pinpointManager = PinpointManager(pinpointConfiguration)
        pinpointManager.sessionClient.startSession()
        pinpointManager.analyticsClient.submitEvents()

        if (pinpointManager.targetingClient.currentEndpoint().user.userId.isNullOrEmpty()) {
            pinpointManager.targetingClient.currentEndpoint().user.userId = id
        }

        firebaseMessaging.token.addOnCompleteListener { task ->
            if (task.isSuccessful) {
                val fcmToken = task.result
                pinpointManager.notificationClient.registerDeviceToken(fcmToken)
            }
        }
        pinpointManager.targetingClient.updateEndpointProfile()
     
    }
`
```
I had to give the id automatically, but it still creates a new endpoint every time, which was not a good solution. Can you please point out my mistake for me? What do I need to know for Cognito and Pinpoint to work together?

**Comment by tylerjroach** [comment]
@berdano Thanks for the report. Someone on our team will be taking a look.

**Comment by tjleing** [comment]
@berdano can you provide which versions of the Android libraries you're using?  We made a [bug fix](https://github.com/aws-amplify/aws-sdk-android/pull/3060) to the Cognito + Pinpoint flow in the AWS SDK for Android around December of last year, which would also potentially be used in 1.x versions of Amplify Android.

**Comment by berdano** [comment]
Hello @tjleing , the library I use: com.amazonaws:aws-android-sdk-pinpoint , version : 2.73.0

**Comment by tjleing** [comment]
@berdano just a few clarification questions while we investigate:
1. The flow I was mentioning above which connects Cognito to Pinpoint is described [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html).  Is this what you're trying to implement?  It looks like you're manually updating the endpoint profile with the user id when the app starts.
2. Just making sure, you're experiencing that the ID of the endpoint profile (`profile.getEndpointId()`) changes when rerunning the app?  Deleting the app will clear the shared preferences and thus generate a new profile, but just reopening it is supposed to preserve the endpoint ID.
