### ISSUE TITLE
HostedUIRedirectActivity internal?

### ISSUE THREAD

**Issue by pm-nchain** [aws-amplify/amplify-android#2642]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

Authentication

### Gradle script dependencies

com.amplifyframework:aws-auth-cognito:2.14.4
com.amplifyframework:core-kotlin:2.14.4

### Environment information

NA

### Describe the bug

The [documentation](https://docs.amplify.aws/android/build-a-backend/auth/add-social-provider/#update-androidmanifestxml) says that you need to define `HostedUIRedirectActivity`, for social signs-in to work. But the `HostedUIRedirectActivity` is `internal`.

I think `HostedUIRedirectActivity` should be made public or documentation should describe, how to create activity on your own.

**Comment by tylerjroach** [comment]
Hi @pm-nchain, HostedUIRedirectActivity is intended to be internal and left unmodified. The only thing required on your part is providing it with an Intent Filter that will allow it to capture the sign-in/sign-out redirect intents that will come from the browser. See the code snippet from the documentation, where you must replace `scheme="insert-my-app-scheme-here"` with your own redirect scheme.

```
<application ...>
  ...
  <activity
      android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
      android:exported="true">
      <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="myapp" />
      </intent-filter>
  </activity>
  ...
</application>
```

**Comment by pm-nchain** [comment]
I see. So the correct approach here is to suppress lint error?

![image](https://github.com/aws-amplify/amplify-android/assets/147817488/af497039-05f7-40ff-8f57-4a6fe33da15a)

**Comment by tylerjroach** [comment]
@pm-nchain if you hover over it, what is the lint error saying? It almost looks like your project is unable to find the activity and that `com.amplifyframework:aws-auth-cognito:2.14.4` is not being found.

**Comment by tylerjroach** [comment]
Happens to everyone! Glad you got it working!

**Comment by mobstranil** [comment]
> Hi @pm-nchain, HostedUIRedirectActivity is intended to be internal and left unmodified. The only thing required on your part is providing it with an Intent Filter that will allow it to capture the sign-in/sign-out redirect intents that will come from the browser. See the code snippet from the documentation, where you must replace `scheme="insert-my-app-scheme-here"` with your own redirect scheme.
> 
> ```
> <application ...>
>   ...
>   <activity
>       android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
>       android:exported="true">
>       <intent-filter>
>           <action android:name="android.intent.action.VIEW" />
>           <category android:name="android.intent.category.DEFAULT" />
>           <category android:name="android.intent.category.BROWSABLE" />
>           <data android:scheme="myapp" />
>       </intent-filter>
>   </activity>
>   ...
> </application>
> ```

@tylerjroach  keeping android:exported="true" for hostedRedirectactivity is raising a security vulnerablity in sonarqube. Have you fixed it before ?
