### ISSUE TITLE
_HeadersCommonKt.headersCheckValue caused by IllegalArgumentException - Unexpected char <address> at 45 in x-amz-meta-text

### ISSUE THREAD

**Issue by yaroslav-v** [aws-amplify/amplify-android#2657]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:core:2.14.5"
implementation "com.amplifyframework:aws-storage-s3:2.14.5"
implementation "com.amplifyframework:aws-auth-cognito:2.14.5"

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Describe the bug

Hi there!

A part of our users experience issues with uploading images to AWS. The issue appears on all Android version from 10 to 14, affected devices include Samsung, Motorola, Oneplus, Google.

As far as I can see, the file name might contain some emoji symbols. For example:
_Caused by java.lang.IllegalArgumentException
Unexpected char 0xd83d at 0 in x-amz-meta-text value: 😏_

or
_Caused by java.lang.IllegalArgumentException
Unexpected char 0xd83e at 6 in x-amz-meta-name value: hayden🩷_

etc.

You can find a crashlog from Firebase in the attachment.

**Previously, we've used AWS Amplify v1.x and there were no such issues. So, I'm not sure what's correct way to handle this issue. Should it be handled by Amplify SDK or you have some recommendations for the data?**

### Code Snippet

```java
// Put your code below this line.
// Initialization in Application class

Amplify.Logging.disable();

Amplify.addPlugin(new AWSCognitoAuthPlugin());
Amplify.addPlugin(new AWSS3StoragePlugin());

AmplifyConfiguration amplifyConfig = AmplifyConfiguration.builder(context)
		.devMenuEnabled(false)
		.build();
Amplify.configure(amplifyConfig, context);


// Uploading, somewhere in the app

DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ", Locale.US);
dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

Map<String, String> metadata = new ArrayMap<>(4);
metadata.put("date", dateFormat.format(date));
metadata.put("session_uuid", uid);
metadata.put("token", authToken);
metadata.put("service", serviceName);

StorageUploadFileOptions options =
		StorageUploadFileOptions.builder()
				.accessLevel(StorageAccessLevel.PUBLIC)
				.contentType(mimeType)
				.metadata(metadata)
				.build();

final File file = new File(path);
if (file.canRead()) {
	Amplify.Storage.uploadFile(
			file.getName(),
			file,
			options,
			result -> {
				// write success logs
			},
			failure -> {
				// write failure logs
			}
	);
}

```

### Log output

<details>

```
// Put your logs below this line
Non-fatal Exception: com.amplifyframework.storage.StorageException
Something went wrong with your AWS S3 Storage upload file operation
	com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError (AWSS3StorageUploadFileOperation.kt:228)
	com.amplifyframework.storage.s3.transfer.TransferStatusUpdater.updateOnError$lambda$11$lambda$10 (TransferStatusUpdater.kt:160)
	android.os.Handler.handleCallback (Handler.java:984)
	android.os.Handler.dispatchMessage (Handler.java:104)
	android.os.Looper.loopOnce (Looper.java:238)
	android.os.Looper.loop (Looper.java:357)
	android.app.ActivityThread.main (ActivityThread.java:8101)
	java.lang.reflect.Method.invoke (Method.java)
	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
	com.android.internal.os.ZygoteInit.main (ZygoteInit.java:957)

Caused by java.lang.Exception
java.lang.IllegalArgumentException: Unexpected char 0xd83d at 0 in x-amz-meta-text value: 😏
	com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker.doWork$suspendImpl (BaseTransferWorker.kt:121)
	com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker$doWork$1.invokeSuspend (BaseTransferWorker.kt:11)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
	kotlinx.coroutines.UndispatchedCoroutine.afterResume (CoroutineContext.kt:270)
	kotlinx.coroutines.AbstractCoroutine.resumeWith (AbstractCoroutine.kt:102)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:46)
	kotlinx.coroutines.UndispatchedCoroutine.afterResume (CoroutineContext.kt:270)
	kotlinx.coroutines.AbstractCoroutine.resumeWith (AbstractCoroutine.kt:102)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:46)
	kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:584)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:793)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:697)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:684)

Caused by java.lang.IllegalArgumentException
Unexpected char 0xd83d at 0 in x-amz-meta-text value: 😏
	okhttp3.internal._HeadersCommonKt.headersCheckValue (-HeadersCommon.kt:140)
	okhttp3.internal._HeadersCommonKt.commonAdd (-HeadersCommon.kt:77)
	okhttp3.Headers$Builder.add (Headers.kt:166)
	okhttp3.internal._RequestCommonKt.commonAddHeader (-RequestCommon.kt:60)
	okhttp3.Request$Builder.addHeader (Request.kt:221)
	aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpUtilsKt$toOkHttpRequest$1.invoke (OkHttpUtils.kt:54)
	aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpUtilsKt$toOkHttpRequest$1.invoke (OkHttpUtils.kt:52)
	aws.smithy.kotlin.runtime.util.ValuesMap$DefaultImpls.forEach (ValuesMap.kt:54)
	aws.smithy.kotlin.runtime.util.ValuesMapImpl.forEach (ValuesMap.kt:69)
	aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpUtilsKt.toOkHttpRequest (OkHttpUtils.kt:52)
	aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.roundTrip (OkHttpEngine.kt:49)
	aws.smithy.kotlin.runtime.http.engine.internal.ManagedHttpClientEngine.roundTrip (ManagedHttpClientEngine.kt:1)
	aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invokeSuspend (SdkHttpClient.kt:44)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:108)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:584)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:793)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:697)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:684)

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by yaroslav-v** [comment]
Another causes for statistics:
_Caused by java.lang.IllegalArgumentException
Unexpected char 0x3042 at 0 in x-amz-meta-name value: あいする(ﾉ≧▽≦)ﾉ_

**Comment by tylerjroach** [comment]
@yaroslav-v Thank you for the detailed explanation. One of the members on our team will be taking a look.

**Comment by tylerjroach** [comment]
@yaroslav-v This is coming from OkHttp. OkHttp does not allow non ASCII characters in headers by default. See (https://github.com/square/okhttp/issues/2016) and the workaround while generating OkHttp requests (https://square.github.io/okhttp/5.x/okhttp/okhttp3/-headers/-builder/add-unsafe-non-ascii.html).

I'll have to look at our V1 dependencies to see why v1 would possibly be working here.

However, I do not believe the issue here is with the "key" being provided, but additional headers you may be passing that are not shown in the snippet?

Are you adding "x-amz-meta-text" and "x-amz-meta-name" headers yourself? I do not see us adding these. If possible, using only ASCII characters would allow the upload to suceed. I'll continue to look into how this was working in v1.

**Comment by tylerjroach** [comment]
@yaroslav-v I just confirmed the same exception occurs in Amplify v1 as well. Sending non-ASCII characters does not seem to be allowed in v1 or v2 due to OkHttp's default restriction.

**Comment by yaroslav-v** [comment]
> @yaroslav-v This is coming from OkHttp. OkHttp does not allow non ASCII characters in headers by default. See ([square/okhttp#2016](https://github.com/square/okhttp/issues/2016)) and the workaround while generating OkHttp requests (https://square.github.io/okhttp/5.x/okhttp/okhttp3/-headers/-builder/add-unsafe-non-ascii.html).
> 
> I'll have to look at our V1 dependencies to see why v1 would possibly be working here.
> 
> However, I do not believe the issue here is with the "key" being provided, but additional headers you may be passing that are not shown in the snippet?
> 
> Are you adding "x-amz-meta-text" and "x-amz-meta-name" headers yourself? I do not see us adding these. If possible, using only ASCII characters would allow the upload to suceed. I'll continue to look into how this was working in v1.

 Hi! Thx for the answer.

Well, in some cases we add a couple of additional values from users to the metadata array (check the code snippet):
**metadata.put("name", name);
metadata.put("text", text);**

So, probably, this is the source of the data, but we don't add any headers directly.

**Comment by tylerjroach** [comment]
@yaroslav-v We believe Amplify v2.14.10 fixes this issue, as the underlying AWS Kotlin SDK was updated to include the fix.

**Comment by yaroslav-v** [comment]
Thx, will test
