### ISSUE TITLE
amplify kotlin sdk failed only on fetchAuthSession

### ISSUE THREAD

**Issue by amiravisar89** [aws-amplify/amplify-android#2687]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

com.amplifyframework:core:1.36.0
com.amplifyframework:aws-auth-cognito:1.36.0

</details>

### Environment information

<details>

------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.13 (JetBrains s.r.o. 11.0.13+0-b1751.21-8125866)
OS:           Mac OS X 14.2.1 aarch64

</details>

### Describe the bug

I have used Amplify cli to import current auth. added the kotlin sdk into my project.
followed all steps and indeed **signIn** call and **userAttributes** call are successfull.
after i use **signIn** succesfully i get this warning:
""Failed to federate tokens during sign-in" "

and then when using fetchAuthSession function and getting this error:
"The account type you have configured doesn't support this operation."

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
Hi @amiravisar89, looks like you're using an old release of Amplify. Could you please upgrade to a recent version (latest is 2.14.9) and let us know if your issue persists? Thanks!

**Comment by amiravisar89** [comment]
@mattcreaser 
i have updated into 2.13.0 and now i am getting this error:
"Cognito Identity not configured. Please check amplifyconfiguration.json file."
I already pulled an auth. (did the same in iOS and it work perfectly)

**Comment by tylerjroach** [comment]
@amiravisar89 please post your apmlifyconfiguration.json with some values obfuscated, so we can see how your identity pool is configured.

**Comment by amiravisar89** [comment]
@tylerjroach 
`{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxxx",
                        "AppClientId": "xxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "PHONE_NUMBER"
                        ]
                    }
                }
            }
        }
    }
}`

**Comment by tylerjroach** [comment]
@amiravisar89 You don't have an IdentityPool configured in your configuration. If you are only using a User Pool, this is ok. Are you seeing that message in fetchAuthSession? If so, this would also be ok if it is returned from `authSession.identityIdResult` or `authSession.awsCredentialsResult`. Both of those values require an Identity Pool. That doesn't mean that your `authSession.userPoolTokensResult` can't still be successful.

**Comment by amiravisar89** [comment]
Hey thanks! after update i can now see the access token in a different member -> 
`session.accessToken`
i am good
