### ISSUE TITLE
fetchAuthSession returns isSignedIn=false when login is performed via external app

### ISSUE THREAD

**Issue by arctop-sk** [aws-amplify/amplify-android#2773]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
// Amplify core dependency
    implementation 'com.amplifyframework:core-kotlin:2.15.1'
    // Amplify cognito auth
    implementation 'com.amplifyframework:aws-auth-cognito:2.15.1'
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
    // Authenticator dependency
    implementation 'com.amplifyframework.ui:authenticator:1.1.0'

```

</details>

### Environment information

<details>

```
# Put output below this line

8.0
```

</details>

### Describe the bug

We have the ability for another app to call our login screen to allow the user to access our backend.
This works via a service that access our backend, and an activity that launches the Authenticator UI.
Our app uses the same service. 
When a user logs in via the activity from another app, although I can see in the hooks that the user is signed in, and if I close the 3rd party app the user is logged in our app, fetchAuthSession returns a signedIn = false
This means the actual signIn is working, but the authSession request returns false information.
I've also tried using the option to force refresh to no avail.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
Hi @arctop-sk, thanks for filing this issue.

I am wondering if you can expand on your use case a little bit. Here's how I am understanding your description, please let me know if I am interpreting anything incorrectly.

1. External app invokes your App's exported login Activity via an Intent. This Activity uses Authenticator to allow user to sign in with Amplify.
2. External app then uses an exported Service from your App to interact with your backend, using the credentials from Amplify.
3. User closes the external app.
4. Back in your application, you try to call `fetchAuthSession`, but it returns `isSignedIn = false`.

Is that an accurate description? Does the user need to log in again in your application?

**Comment by mattcreaser** [comment]
Thanks for the clarifications, that should be enough to reproduce this issue. We'll need to investigate. Please keep this issue updated if you find any additional information!

**Comment by arctop-sk** [comment]
I just did a quick check looking for workarounds.
If in the External app I unbind and rebind to the service after signIn, the status correctly updates.

**Comment by arctop-sk** [comment]
so one last comment and this is probably the issue. Our service is running in its own process, so the context in which the AWS session runs in is different between the app itself and the service, hence the discrepancies.

I wouldn't know what would be a solution for this, but I believe this is the problem

**Comment by arctop-sk** [comment]
final update. Moving our service to the app's process solves the issue.
I'm not sure if there is anyway to handle Auth cross process. I'll leave the issue open for now if you wish to investigate solutions. If not, you can close it.

**Comment by joon-won** [comment]
Hi @arctop-sk, glad your issue has been resolved! Thank you for providing your steps and findings, we believe it will be beneficial once we work on the issue in the future. Please re-open the issue should you wish to revisit it.
