### ISSUE TITLE
confirmSignUp returns userId = null  when isSignUpComplete is true

### ISSUE THREAD

**Issue by VadymKuriyDev** [aws-amplify/amplify-android#2775]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
2.14.12
```

</details>

### Environment information

<details>

```
Gradle 8.7
```

</details>

### Please include any relevant guides or documentation you're referencing

According  
```
/**
     * If {@link #isSignUpComplete} is true, this returns the newly registered user's id. Otherwise, null.
     * @return the newly registered user's id if {@link #isSignUpComplete} is true. Otherwise, null.
     */
```
in [AuthSignUpResult](https://github.com/aws-amplify/amplify-android/blob/e85e3bb9f28089bd70d5775fab1229f0645e0270/core/src/main/java/com/amplifyframework/auth/result/AuthSignUpResult.java#L72)

### Describe the bug

After calling `confirmSignUp` when `isSignUpComplete` is `true` userId is `null`. Expected - receive newly registered user's id

### Code Snippet

```kotlin
val authSignUp = Amplify.Auth.confirmSignUp(name, code)
```

### Log output

<details>

```
Response = AuthSignUpResult{isSignUpComplete=true, nextStep=AuthNextSignUpStep{signUpStep=DONE, additionalInfo={}, codeDeliveryDetails=null}, userId=null}

```

</details>

**Comment by joon-won** [comment]
Thank you for the report @VadymKuriyDev, our team member will look into the issue

**Comment by joon-won** [comment]
Hey @VadymKuriyDev, thank you for your patience. This definitely is a bug on our end, we'll try to fix it, and let you know once it goes live

**Comment by tylerjroach** [comment]
Hi @VadymKuriyDev,

Sorry for the confusion. We need to correct the documentation on that method. The Cognito service does not return `userSub` (userId) in the `confirmSignUp `call.

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmSignUp.html

userSub is only returned from `signUp` calls. 
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html

`AuthSignUpResult` is re-used for both signUp and confirmSignUp, so we will need to adjust the message on the `getUserId` method.

**Comment by VadymKuriyDev** [comment]
Hi @tylerjroach  thx for the explanation.

**Comment by VadymKuriyDev** [comment]
Hi @tylerjroach, thx for the explanation.
