### ISSUE TITLE
SDK v2.14.13 prevented events from being sent with the error “The security token included in the request is invalid” 

### ISSUE THREAD

**Issue by jin-jobs** [aws-amplify/amplify-android#2789]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Analytics

### Gradle script dependencies

<details>

```groovy
    api ("com.amplifyframework:aws-analytics-pinpoint:2.14.13") {
        exclude( group = "androidx.lifecycle", module = "lifecycle-viewmodel-ktx")
    }
    api ("com.amplifyframework:aws-auth-cognito:2.14.13") {
        exclude( group = "androidx.lifecycle", module = "lifecycle-viewmodel-ktx")
    }


```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.1 (Oracle Corporation 19.0.1+10-21)
OS:           Mac OS X 12.0.1 aarch64


```

</details>

### Describe the bug

In SDK v2.14.13, Events could not be sent with the error “The security token included in the request is invalid”.
Our app was previously using SDK v1.37.3, but we upgraded to SDK v2.14.13 in early April and applied it to our app.

During the internal testing process after applying the SDK, amplify event was intermittently not sent, and the following logs were generated in logcat at that time. 

```javascript
Failed to submit events aws.sdk.kotlin.services.pinpoint.model.PinpointException: The security token included in the request is expired
```
<img width="868" alt="스크린샷 2024-04-24 오전 9 19 03" src="https://github.com/aws-amplify/amplify-android/assets/17607205/3a9f0a0a-705f-4ec4-81cc-86142b1b9b2f">

Our team tried to reproduce the error, but it was difficult to get an easy reproduction path. 
We deployed the app with v2.14.13 to the market and checked the Amplify Event data about two weeks later, and found that events were being collected at a very low volume compared to before. 
We recognized this as a very big issue and are urgently investigating and analyzing the issue. 

Question:
1. I am wondering why this error is occurring? Is there anything we can do about it?
2. The release page of the current repository shows that the latest version of the SDK is v2.15.1. Is this v2.15.1 a fix for the issue we are experiencing?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

<img width="868" alt="스크린샷 2024-04-24 오전 9 19 03" src="https://github.com/aws-amplify/amplify-android/assets/17607205/b389c6fc-34e2-400c-b60e-0af8faf09c80">

**Comment by tylerjroach** [comment]
Hi @jin-jobs Can you show how Amplify is configured, and include any additional Amplify/AWS libraries you may be using in build.gradle. Specifically wanting to make sure you have no dependencies on AWSMobileClient. Please also provide information on the amplifyconfiguration.json being used.

**Comment by jin-jobs** [comment]
@tylerjroach 

We are not using the AWSMobileClient dependency. 
We are also not referencing any libraries other than “com.amplifyframework:aws-analytics-pinpoint” and “com.amplifyframework:aws-auth-cognito”.

Currently, our app is working fine within our internal development team and events are being delivered to amplify, but after launching to the market, end users are not receiving events.
Roughly 90% of all events are not being sent.
Our service is very dependent on amplify events and the current situation where events are not being collected is very damaging to our service.

Below is the contents of our amplifyconfiguration.json file.

We hope you will consider our issue as important.

<img width="874" alt="image" src="https://github.com/aws-amplify/amplify-android/assets/17607205/5aad7503-8582-4c9e-93a3-a235f5cdb697">

**Comment by jin-jobs** [comment]
@tylerjroach 
Sorry about that. I captured the contents of the wrong file.
I've recaptured the contents of the amplifyconfiguration.json currently applied to our app and attached it here.

Our app is experiencing issues with events not being collected when migrating the Amplify SDK from v1 to v2. Do we need to remove the awsconfiguration.json file from the app project when migrating from v1 to v2?

<img width="817" alt="image" src="https://github.com/aws-amplify/amplify-android/assets/17607205/724e3ab2-00a2-440f-9f30-bdd2043ebebc">

**Comment by tylerjroach** [comment]
@jin-jobs Just to confirm, the CognitoIdentity PoolId's match between the two different config files, as well as the Pinpoint AppId's correct?

You do not need to remove awsconfiguration.json (although it doesn't hurt to do so, awsconfiguration.json is not used by Amplify v2).

**Comment by jin-jobs** [comment]
@tylerjroach 
- CognitoIdentity PoolId and Pinpoint AppId's match
  - Yes, it's a perfect match, and these two config json files are still the same ones we used in the v1 sdk.
Also, the same config json files are being used in the v2 sdk based iOS app and events are being collected without any issues.
- The captured image below shows the logcat log on the first run of the app with debug build after declaring AndroidLoggingPlugin(LogLevel.VERBOSE).
  - launched on Android OS 14(Galaxy S24)
<img width="2127" alt="image" src="https://github.com/aws-amplify/amplify-android/assets/17607205/3bf12a61-6c06-4929-8b25-78eed31f4c73">

**Comment by jin-jobs** [comment]
@tylerjroach 
- We are not using amplify authentication for user login. I believe this means that we are only using guest authentication.
We use “Amplify.addPlugin(AWSCognitoAuthPlugin())” for auth code and no other code at all. 
- On the client side (Our Android App source code), we don't have any value related to access token. we don't have any information related to refresh token. it is not declared in our java/kotlin code either.

**Comment by mattcreaser** [comment]
Hi @jin-jobs we have identified what we believe to be the root cause of this issue. We will make a fix in a future version of Amplify, but in the meantime there is a workaround you can use to resolve the issue.

There is a conversion error when migrating user credentials from v1 to v2 that causes Amplify to continue to use guest credentials past their actual expiration date. This will affect users that initially received credentials while using an older version of your application prior to the upgrade.

To workaround this, you can force refresh the tokens. This will fetch and store new guest credentials which will have the proper expiry date set. Here is some sample code to use, this can be put in your `Application.onCreate` **after** calling `Amplify.configure`.

```kotlin
Amplify.Auth.fetchAuthSession(
    { authSession ->
        // Get the temporary guest credentials
        val cognitoSession = authSession as? AWSCognitoAuthSession
        val credentials = cognitoSession?.awsCredentialsResult?.value as? AWSTemporaryCredentials ?: return@fetchAuthSession

        // Guest credentials should expire within one hour. In the migration scenario from v1 this
        // expiry can incorrectly get set to a value very far in the future. This results in Amplify believing
        // the credentials are still valid when they have actually expired. If the expiry date for guest
        // credentials is more than one year in the future we are sure they are invalid and should be refreshed.
        // A future version of Amplify will resolve this issue automatically, but you can manually force a
        // refresh to work around the problem pending that fix being released.
        if (credentials.expiresAt > Instant.now().plus(1, ChronoUnit.YEARS)) {
            // Force-refresh the tokens. This will give the user valid tokens and resolve the issue. The
            // expiry date will be correctly set on these new credentials.
            Amplify.Auth.fetchAuthSession(
                AuthFetchSessionOptions.builder().forceRefresh(true).build(),
                { session ->
                    // Success callback
                    // Can check this value but valid token should be available with proper expiration
                },
                { exception ->
                    // Error callback
                    // Failure can be tracked here
                },
            )
        }
    },
    { exception ->
        // Error callback
        // Failure can be tracked here
    },
)
```

Once we release a fix for this you will be able to remove this code. We'll keep this issue open until then, but this should resolve the issue in the meantime.

**Comment by jin-jobs** [comment]
@mattcreaser 
Thank you so much for your in-depth review of the issue and suggestions for alternatives.🙇  I would like to express my very great appreciation to you and your team.
I will review your suggestion today and apply it to our app immediately and deploy it as a hotfix.
It will take some time to collect enough data from end-users in production, but I will share it here as a comment as soon as I have data validation.

**Comment by jin-jobs** [comment]
The Instant.now() function is requiring API Level 26 or higher. The min api level for our app and the Amplify Android SDK is 24. For now, the version we deploy as a hotfix will only apply the force refresh logic to API level 26 or higher.
In the future, if you make any modifications on the SDK side, please make it compatible with API level 24. 🙇

**Comment by vincetran** [comment]
Hi @jin-jobs, `Instant.now()` is coming from `java.time.Instant` which comes from Java 1.8 (aka Java 8). Android has a way to enable Java 8 functionality without increasing your API level with a [feature called desugaring](https://developer.android.com/studio/write/java8-support-table). 

In your `build.gradle.kts` (assuming you're using kotlin -- translate to Groovy if using that) you just need to add these configurations:

```
dependencies {
    ...
    // Support for Java 8 features. 
    // Note: We know we support this specific version but the latest version is 2+.
    // We can't guarantee full support if you use newer versions.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:1.1.5")
}

compileOptions {
        // Support for Java 8 features
        isCoreLibraryDesugaringEnabled = true

        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
}
```

**Comment by vincetran** [comment]
Sorry for the miss of calling that out earlier! Some of our other libraries (e.g. Datastore and the Authenticator UI component) require desugaring so some of our workspaces already have that configured 🙇‍♂️

**Comment by jin-jobs** [comment]
@vincetran 
Thank you for your confirmation. Until the next SDK is released, we'll take your suggestions into consideration for our app and incorporate them into our next market release.
Thank you so much!

**Comment by jin-jobs** [comment]
@mattcreaser @vincetran 

I did a hotfix release on Saturday and checked the data collected so far, but the event total volume is still not enough (-90%, same as before).
I was wondering if it is possible to modify the expireAt check conditional statement to be 1 hour back instead of 1 year back and force refresh when the exipre time is 1 hour back.

I'm worried that frequent force refresh may cause other side effects.

**Comment by jin-jobs** [comment]
Also, I'm wondering if the expire time is based on 1 year as a condition to force refresh in the code you suggested.

**Comment by tylerjroach** [comment]
Hi @jin-jobs We are deeply sorry for the mistake in the snippet that we provided to you.

```
Amplify.Auth.fetchAuthSession(
    { authSession ->
        // Get the temporary guest credentials
        val cognitoSession = authSession as? AWSCognitoAuthSession
        val credentials = cognitoSession?.awsCredentialsResult?.value as? AWSTemporaryCredentials ?: return@fetchAuthSession

        // Guest credentials should expire within one hour. In the migration scenario from v1 this
        // expiry can incorrectly get set to a value very far in the future. This results in Amplify believing
        // the credentials are still valid when they have actually expired. If the expiry date for guest
        // credentials is more than one year in the future we are sure they are invalid and should be refreshed.
        // A future version of Amplify will resolve this issue automatically, but you can manually force a
        // refresh to work around the problem pending that fix being released.
        if (credentials.expiresAt > Instant.now().plus(365, ChronoUnit.DAYS)) {
            // Force-refresh the tokens. This will give the user valid tokens and resolve the issue. The
            // expiry date will be correctly set on these new credentials.
            Amplify.Auth.fetchAuthSession(
                AuthFetchSessionOptions.builder().forceRefresh(true).build(),
                { session ->
                    // Success callback
                    // Can check this value but valid token should be available with proper expiration
                },
                { exception ->
                    // Error callback
                    // Failure can be tracked here
                },
            )
        }
    },
    { exception ->
        // Error callback
        // Failure can be tracked here
    }
)
```

In double checking the snippet above, we discovered the implementation of Instant.plus method used above does not support `ChronoUnit.YEARS`. The highest value it supports is `ChronoUnit.DAYS`. I have double checked this implementation and it is now working as expected. The onError block on the inner fetchAuthSession call was getting triggered with `UnknownException{message=An unclassified error prevented this operation., cause=java.time.temporal.UnsupportedTemporalTypeException: Unsupported unit: Years, recoverySuggestion=Sorry, we don’t have a recovery suggestion for this error.}`, failing to initiate the fetch for the new token.

Here is what I can tell you about AWS token expirations.
* The default expiration time is 1 hr, however, I believe it may be configurable up to 12 hours. 

> I was wondering if it is possible to modify the expireAt check conditional statement to be 1 hour back instead of 1 year back and force refresh when the exipre time is 1 hour back.

You are free to reduce the 365 days used in the token to a lower amount. We were attempting to be cautious in this implementation by setting a higher value. The bug in the v1 implementation was causing the expiration date to be 100+ years ahead of time, so setting it to be 1 year will easily capture this bug scenario, and nothing else. We intend this code block to only be triggered once. If you do lower it, I would probably set it to 1hr and 1 minute as a safety.

> Also, I'm wondering if the expire time is based on 1 year as a condition to force refresh in the code you suggested.

Yes, it was based on 1 year to force a refresh when we clearly have the wrong date. The new token have the configured expiration time (likely 1 hour).

**Comment by tylerjroach** [comment]
I wanted to provide additional context into how we tested the fix, so that you can verify/understand the bug and how the fix works.

1. Uninstall any existing version of app.
1. Install app with Amplify v1.
2. Call fetchAuthSession
3. Upgrade app to Amplify v2 version
4. Call fetchAuthSession
  * _Its at this point you likely had trouble reproducing. Any Amplify calls will succeed at this point because the token from v1 is still valid for the next hour. Once that hour expires, this is when failures will start to occur._
  * You can call fetchAuthSession (without forceRefresh) and check the expiration returned `((session as? AWSCognitoAuthSession)?.awsCredentialsResult?.value as? AWSTemporaryCredentials)?.expiresAt`. You will see the clearly wrong expiration date here.
5. Call fetchAuthSession with forceRefresh=true. Checking the expiration of the session returned again will show that the new token is set to expire in 1 hr.

For testing, it is also helpful to add `AndroidLoggingPlugin(LogLevel.VERBOSE)`, as the first configured Amplify plugin.

**Comment by mattcreaser** [comment]
Please note an addition to the above: if your `expiresAt` check is lower than the expiry value in your guest credentials then you will be force refreshing tokens when they don't need to be refreshed. This is why we recommended using a large value here.

> I'm worried that frequent force refresh may cause other side effects.

This code will be triggered at most once for each user, afterwards they will have valid expiry times and will not re-trigger the force refresh. Guest users also already refresh tokens on an hourly basis, so this overhead will be quite minimal.

**Comment by jin-jobs** [comment]
I am so grateful for your kind and quick confirmation and alternative suggestions.

@tylerjroach  
You don't have to apologize. I should have debugged the code you suggested a bit more, reviewed it, and applied it, but I didn't, so it was my fault for applying it right away. Thank you for your revised suggestions.

@mattcreaser  
Thanks for the detailed explanation and the list of things to watch out for. I changed the logic to check for 365 days based on DAYS as you guys first suggested and released a hotfix earlier today.
I will double check the event volume and share it here.

**Comment by jin-jobs** [comment]
I deployed the app with the modified code on Monday, and while not a lot of time has passed, the data collected seems to indicate that events are being collected normally.

@vincetran @mattcreaser @tylerjroach 
I am very grateful to you for your enthusiastic help in resolving the issue.

I would like to ask you one more question.
- app version v3.1, v1 > v2 migrated app : has issue
- app version v3.2, 1st code fix in v2 : has issue
- app version v3.3, 2nd code fix in v2 : fixed
In the above situation, events would have failed to be sent to pinpoint in app versions v3.1 and v3.2, but since the events are cached in the Amplify SDK internal DB, are these cached events being sent in v3.3? Or are events from v3.1 and v3.2 lost forever?

**Comment by tylerjroach** [comment]
@jin-jobs Let me test this and I will get back to you.

**Comment by tylerjroach** [comment]
@jin-jobs I tested this and the events are not lost. Your version 3.3 should be able to push events that were not being sent in 3.1 and 3.2. Upon failure, events are re-attempted (not dropped from local storage).

**Comment by jin-jobs** [comment]
@tylerjroach Thank you for checking ! 🙇

**Comment by tylerjroach** [comment]
No problem! I'm going to go ahead and close this issue since it appears the problem has been resolved. Please reach back out if you experience any other issues!

**Comment by tylerjroach** [comment]
2.16.1 has been released with the internal fix for the issue.
