### ISSUE TITLE
StoragePath Android not found

### ISSUE THREAD

**Issue by mbahmani90** [aws-amplify/amplify-android#2800]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'com.amplifyframework:aws-api:2.14.11'
    implementation 'com.amplifyframework:aws-datastore:2.14.11'

    implementation 'com.amplifyframework:core:2.14.11'
    implementation 'com.amplifyframework:aws-auth-cognito:2.14.11'
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.8.0'
    implementation("io.github.jan-tennert.supabase:postgrest-kt:0.7.6")
    implementation("io.ktor:ktor-client-cio:2.3.3")

    implementation 'com.amplifyframework:aws-storage-s3:2.14.11'

    implementation "androidx.navigation:navigation-compose:2.7.7"

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'

```

</details>

### Environment information

<details>

```
# Put output below this line
-

```

</details>
-

### Describe the bug

Hi,

I want to use StoragePath in kotlin android to upload my file in s3 storage. According to https://docs.amplify.aws/android/build-a-backend/storage/storagepath/#create-a-storagepath-from-string I should use the following command. 
StoragePath.fromString("public/exampleFile.txt")

But StoragePath is not found!

I can store file in s3 without any issue. However, I need StoragePath to store files in specific directory.

Thanks

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
@mbahmani90 You need to update the latest version of Amplify (2.16.0) to use StoragePath. The version you have reported does not have it. Instead, you would use the other methods that take a `key: String` which are marked in documentation as deprecated.

**Comment by mbahmani90** [comment]
I update amplify to 2.16.0 and it is now found. However, when I run:
```
Amplify.Storage.uploadInputStream(StoragePath.fromIdentityId { identityId ->
            "test/${fileName}"
        }, stream, { onComplete() },
            {
                app.l("$it")
                onError() })
```
I am receiving the following error:
```
StorageException{message=Something went wrong with your AWS S3 Storage upload InputStream operation, cause=java.lang.Exception: aws.sdk.kotlin.services.s3.model.S3Exception: Access Denied, recoverySuggestion=See attached exception for more information and suggestions}
```
It is just work fine when I replace:
```
"test/${fileName}"
```
with
```
"private/${identityId}/test/${fileName}"
```

**Comment by mbahmani90** [comment]
I had to write
```
"public/test/${fileName}"
```
Now it works. :) 
Many thanks.

**Comment by tylerjroach** [comment]
@mbahmani90 Thats great! Make sure to follow access control (public/private/protected) guidelines here: https://docs.amplify.aws/android/build-a-backend/storage/storagepath/.
