### ISSUE TITLE
We can't sign out the user which is signInWithSocialWebUI

### ISSUE THREAD

**Issue by ScottLu77** [aws-amplify/amplify-android#2839]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
dependencies {
    implementation 'com.amplifyframework:aws-api:2.18.0'
    implementation 'com.amplifyframework:aws-auth-cognito:2.18.0'
    ....
}

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (JetBrains s.r.o. 17.0.6+0-17.0.6b829.9-10027231)
OS:           Linux 6.5.0-35-generic amd64

```

</details>

### Describe the bug

We can't sign out the user which is signInWithSocialWebUI.
When I call signout and it will popup a webview instead redirect back to my app.

### Reproduction steps (if applicable)

1. Call Amplify.Auth.signInWithSocialWebUI(AuthProvider.custom(provider),...)
2. Call Amplify.Auth.signOut()
3. Web view opens
4. Web view does signout through the url set
5. Never redirect to app later unless I manually close it.

### Code Snippet

```java
// Put your code below this line.
Amplify.Auth.signOut { signOutResult ->
            when(signOutResult) {
                is AWSCognitoAuthSignOutResult.CompleteSignOut -> {
                    continuation.resume(true)
                }
                is AWSCognitoAuthSignOutResult.FailedSignOut -> {
                    continuation.resume(false)
                }
            }
        }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```json 
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxx",
                            "AppClientId": "xxx",
                            "SignInRedirectURI": "xxx",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "aws.cognito.signin.user.admin",
                                "email",
                                "openid",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

We are using AWS SAML provider(Azure), and enable "Sign-out flow" of the custom provider

![Screenshot from 2024-06-04 12-28-39](https://github.com/aws-amplify/amplify-android/assets/22672129/93bc1b1a-dbf3-48b4-930d-78f3933bf27e)

**Comment by tylerjroach** [comment]
Do you have your signout redirect url configured correctly through Cognito and your SAML provider? 

Please post how `HostedUIRedirectActivity` is configured in your manifest. The redirect comes from the browser. If the app is correctly configured to receive the redirect, then there is a misconfiguration on the service side in failing to provide the redirect.

**Comment by ScottLu77** [comment]
Hi tyler,
Thanks for your reply and here are my configurations

1. we declare SignOutActivity in AndroidManifest.xml as follows
<activity
    android:name=".SignOutActivity"
    android:exported="true"
    android:screenOrientation="portrait">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="**androidvortex**" />
    </intent-filter>
</activity>

2. Here is my amplifyconfiguration.json
"Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "xxxx",
                "AppClientId": "xxx",
                "SignInRedirectURI": "vortex://",
                "SignOutRedirectURI": "**androidvortex://**",
                "Scopes": [
                    "aws.cognito.signin.user.admin",
                    "email",
                    "openid",
                    "profile"
                ]
            },

3. Here is settings in AWS Cognito App integration
![Screenshot from 2024-06-05 09-41-45](https://github.com/aws-amplify/amplify-android/assets/22672129/36cb0a5e-4453-43f5-9904-238157bb7a78)

**Comment by ScottLu77** [comment]
Besides, we have turned on "Sign-out flow" to log out Microsoft Entra which is our identity provider when calling Amplify.Auth.signout()

![Screenshot from 2024-06-05 10-04-22](https://github.com/aws-amplify/amplify-android/assets/22672129/7d904c99-d5a6-4ea6-9af3-1f3177daa0df)

In this case, we found that during sign out, it will popup 2 WebView.
The first one mention Microsoft account has been logged out.
The second one mention your AWS account has been logged out.
![Screenshot from 2024-06-05 10-39-26](https://github.com/aws-amplify/amplify-android/assets/22672129/691bfce1-ed25-4c57-b135-aa6cedcbe93d)
![Screenshot from 2024-06-05 10-39-47](https://github.com/aws-amplify/amplify-android/assets/22672129/67cf44bc-1e0a-4dae-b74f-b5d6b0daa311)

By the way, I found that the second WebView Uri is abnormal as follows
**"https://login.microsoftonline.com/87d9efc2-1ebc-4845-a670-4356471354cb/oauth2/logoutredirect?lc=1028"**
instead of
**"xxxxx/logout_uri=androidvortex%3A%2F%2F"**
I guess that's why it can't redirect to our app.

**Comment by tylerjroach** [comment]
I've had another report in the past on issues with receiving the signout redirect with a Microsoft SAML and I'm not sure I ever received a final response from the customer as to what the issue was. Let me see if I can ask around some of our teams to see if they are familiar with what may be happening.

**Comment by ScottLu77** [comment]
Hi tyler, thanks for your quick response. we look forward to have a solution in the future.

**Comment by AzureLiao** [comment]
Same issue here, anything update? Thanks.

**Comment by tylerjroach** [comment]
I believe there's a likely misconfiguration on the Entra side. I was able to test with an Entra account and both `signIn` and `signOut` worked without issue.

Here is how the logout redirect is configured on the Entra side.


<img width="878" alt="Screenshot 2024-06-10 at 4 38 33 PM" src="https://github.com/aws-amplify/amplify-android/assets/634763/2761e888-2cad-43d9-9908-9d3d2f19e868">

**Comment by tylerjroach** [comment]
Hi @ScottLu77 I think we'e gotten the issue narrowed down.

I had not enabled the Sign Out Flow on the Cognito side. Once I did this, I was able to observe the same issue you were running into.

The [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp-sign-out.html#:~:text=Your%20user%20then%20returns%20to%20your%20saml2/logout%20endpoint%20with%20a%20LogoutResponse%20from%20their%20IdP.%20Your%20IdP%20must%20send%20the%20LogoutResponse%20in%20an%20HTTP%20POST%20request.%20Amazon%20Cognito%20then%20redirects%20them%20to%20the%20redirect%20destination%20from%20their%20initial%20sign%2Dout%20request) states: "Your IdP must send the LogoutResponse in an HTTP POST request."

I've found a post on a Microsoft support site that shows Entra does not support HTTP Post binding for sign out.

**Comment by ScottLu77** [comment]
Hi Tyler, thanks for your feedback.
We enabled the Sign Out Flow on the Cognito for letting user able to sso login with different social login from the same provider.
Since we had the same problem like this [1287](https://github.com/aws-amplify/amplify-android/issues/1287).
If there is any alternative solution, and it would be much appreciated.

**Comment by tylerjroach** [comment]
I'm sorry, without support from Entra on providing the LogoutResponse as an HTTP POST request, there are no alternatives I can provide.

The other issue we face is that Chrome Custom Tabs do not allow us to clear browser session/cookie information. This is the reason the signOut method is only able to clear credentials on the Cognito side, and not third party social provider.

**Comment by ScottLu77** [comment]
So you mean it's not possible letting user sso login to a different account?
However enabling Sign Out Flow on Cognito will run into my problem and it's unsolvable either?

**Comment by tylerjroach** [comment]
The user could log into a different account if they open a web browser and log out of Microsoft Entra manually. I understand this is not a great experience but there are no API's that allow us to control web session/cookies from Microsoft in the browser. That is not something we have permission to do. Unfortunately due to Entra's limitation in providing the LogoutResponse, Cognito is not getting the required information it needs to complete the sign out and redirect the user back into the application.

**Comment by ScottLu77** [comment]
But why is that everything works well when I switch back to android-amplify v1 (1.38.8)?

**Comment by tylerjroach** [comment]
Hi @ScottLu77,

Amplify v1 had a 10 second wait on receiving the redirect. If the 10 second timeout was hit, the rest of the sign out (ex: clearing the local tokens) would succeed.

This behavior was modified in v2 to ensure that the browser signout succeeded. This decision was made because calling signInWithHostedUi after a failed browser sign out would automatically re-sign the user in as the cached user, even in the non-social sign in flow.

Can you please confirm how Amplify v1 appears on signOut. I would expect it to hang in the browser on the "An error was encountered with the requested page" screen. Then once 10 seconds is hit, or the user cancels, the local sign out proceeds.

If you are not seeing this behavior, please let me know. It would be helpful to provide logs of the v1 sign out and possibly provide a video where we can see the redirects happening.

**Comment by ScottLu77** [comment]
Hi Tyler, update Amplify v1 behavior for your reference.
**After sign out, it will popup WebView and open two pages
The first one shows Microsoft account has been logged out.
The second one shows your AWS account has been logged out.**

![Screenshot_20240617_154452](https://github.com/aws-amplify/amplify-android/assets/22672129/619c6762-c409-4b7c-98e1-0cec1427e0b2)
![Screenshot_20240617_154503](https://github.com/aws-amplify/amplify-android/assets/22672129/db32eeb3-3612-4ff4-97bd-81f7ecf3977f)

**It seems that with Amplify V1, our app receive the redirect and sign out successfully without waiting for 10 second timeout.
attach logcat for your reference**

[signout_v1.txt](https://github.com/user-attachments/files/15863964/signout_v1.txt)

this is signout timestamp 06-17 16:18:39.893

**Comment by tylerjroach** [comment]
> The second one shows your AWS account has been logged out.

I'm not sure that is showing AWS. That link is still a Microsoft link, not a Cognito link.

Do you have to close each of the windows, or does the redirect happen and automatically close the windows?

**Comment by ScottLu77** [comment]
> > The second one shows your AWS account has been logged out.
> 
> I'm not sure that is showing AWS. That link is still a Microsoft link, not a Cognito link.
> 
> Do you have to close each of the windows, or does the redirect happen and automatically close the windows?
> 
> We can take a look on v1 behavior on our end and update the ticket.

Yes, we need to programmatically close all windows and restart our app's welcome activity as follows.
`val intent = Intent(context, WelcomeActivity::class.java)
intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
context.startActivity(intent)`

But at least the amplify v1 can be signed out successfully.

**Comment by tylerjroach** [comment]
Closing this ticket as we have a FR ticket.
