### ISSUE TITLE
Lookup idp based on user email

### ISSUE THREAD

**Issue by tfreeman82** [aws-amplify/amplify-android#2843]
Is there any way to lookup which idp is needed for a user based on the domain of their email address without using the hosted web UI? 

We currently use the hosted web UI with a field for the corporate id. The user enters their email in this field and, when they press the sign in button, their idp is found and they're redirected to it for final authentication.

We would like to adjust our existing native login screen to handle this same behavior but I've scoured the documentation and can't find any clear way to handle this. Is it possible at all and, if so, can you point me in the right direction?

**Comment by mattcreaser** [comment]
Hi @tfreeman82. Amplify does not provide this functionality and I'm not sure if it is possible, but if so then it would be via the underlying [AWS Kotlin SDK](https://github.com/awslabs/aws-sdk-kotlin).

You can [get an instance of the CognitoIdentityProviderClient from Amplify](https://docs.amplify.aws/gen1/android/build-a-backend/auth/sdk/) using the following code:

```kotlin
val cognitoAuthService = Amplify.Auth.getPlugin("awsCognitoAuthPlugin").escapeHatch as AWSCognitoAuthService
val cognitoIdentityProviderClient = cognitoAuthService.cognitoIdentityProviderClient
```

I'll transfer this issue to the Kotlin SDK repo for better support there.

**Comment by tfreeman82** [comment]
Thanks for the direction. That's exactly what I tried but I could only find a way to get a list of all idp's but not a way to get one based on the email. I've been trying to understand how the hosted web ui is able to handle this logic but don't have access to the data on the Chome custom tabs.

I don't have a great understanding of how our api side developer setup the hosted ui and lambda.

I'll open an issue on the Kotlin repo and see if they can provide more insight.

**Comment by mattcreaser** [comment]
Hosted UI is able to do this via returning an HTTP redirect from Cognito - so the logic is entirely server-side, and the client isn't directly involved. I'm not sure if equivalent information is available somewhere in the Cognito API.

I'll close this issue for now but please always free to open a new one if needed.
