### ISSUE TITLE
Amplify Kotlin Android feature for AWS IoT Core

### ISSUE THREAD

**Issue by datasciencemachine** [aws-amplify/amplify-android#2852]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Not applicable

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the feature request

In the Amplify v2 docuementation for Kotlin or Android, I am not able to see any implementation for AWS IoT Core in it. Basically, I need the support to create an android app to control my IoT Core Things. 

### Code Snippet

```java
// Put your code below this line.

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by datasciencemachine** [comment]
Thanks for your help Tyler. I can use sdk for my use case as well. However, on the sdk repo readme, it was mentioned to use amplify instead of  sdk directly, like in the screenshot below:
![Screenshot_20240619_113052_Chrome](https://github.com/aws-amplify/amplify-android/assets/63748020/bd519c9a-33e8-4e00-8220-420ffbf23669)

This the repo where i am planning to use the sdk from, can you please guide me if this is the correct repository to get iot core mqtt connection.
https://github.com/aws-amplify/aws-sdk-android

**Comment by vincetran** [comment]
@datasciencemachine As Tyler suggested, Amplify is not a complete 1:1 replacement for aws-sdk-android. So you can use the two other repos as he suggested.

For the MQTT connection, it actually looks like there's a v2 of that library: https://github.com/aws/aws-iot-device-sdk-java-v2 

For the AWS SDK Kotlin, here is the docs page with code examples for doing IoT things with it: https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/kotlin/services/iot#code-examples
