### ISSUE TITLE
Google.android.play:core has added this note for core:1.9.1

### ISSUE THREAD

**Issue by khambhaytajaydip** [aws-amplify/amplify-android#2853]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
com.amplifyframework:aws-storage-s3:1.37.6

```

</details>

### Environment information

<details>

```
# Put output below this line
Gradle 7.4                                                           
------------------------------------------------------------         
                                                                        
Kotlin:       1.5.31                                                 
Groovy:       3.0.9   

```

</details>

### Describe the bug

I am using the dependency **com.amplifyframework:aws-storage-s3:1.37.6** in my project, 
which has a transitive dependency on **com.google.android.play:core:1.9.1**.

![error in play_core](https://github.com/aws-amplify/amplify-android/assets/17040639/88563fcd-d2c7-4572-9529-8bc4674d6e8b)

I recently received the following email from the Play Store:

> Google.android.play has added this note for core:1.9.1:
> 
> Update your Play Core Maven dependency to an Android 14-compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backward-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: Overview of the Google Play Core libraries | Android Developers.
> 
> You may not be able to release future versions of your app with this SDK version to production or open testing."

![google play store message](https://github.com/aws-amplify/amplify-android/assets/17040639/7e7b0d1e-487d-415c-bcbf-99cf9a56a1be)

Given this information, how should I handle its transitive dependency on com.google.android.play:core?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by lawmicha** [comment]
Hi @khambhaytajaydip, thanks for letting us know. We will investigate upgrading this dependency before August 31st and provide updates here.

**Comment by lawmicha** [comment]
Hi @khambhaytajaydip, this was fixed in https://github.com/aws-amplify/amplify-android/pull/2131 which was released in https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.37.10 and https://github.com/aws-amplify/amplify-android/releases/tag/release_v2.1.0

Please upgrade your dependency on Amplify to 1.37.10 or higher. We also recommend migrating to Amplify v2.x.x if possible. Our development is focused on V2 and 2.19.0 is the latest released version https://github.com/aws-amplify/amplify-android/releases . If you have issues moving to V2, please reach out.

**Comment by khambhaytajaydip** [comment]
Thanks you @lawmicha for the update !!!
