### ISSUE TITLE
"validateObjectExistence" Support needed for AWSStorageGetURLOptions

### ISSUE THREAD

**Issue by wezside** [aws-amplify/amplify-android#2874]
**Which AWS Services is the feature request for?**
Please allow `StorageDownloadFileOptions` to support the validateObjectExistence

**Is your feature request related to a problem? Please describe.**
This is a feature which should be implemented in the Android SDK to avoid unnecessary download request which fails until object is available.

**Describe the solution you'd like**
Just add the setting to the AWSStorageGetURLOptions 

**Describe alternatives you've considered**
Only alternative is to try to Download the file repeatedly until it becomes available. Not a great workaround.

Currently using: 

```
implementation 'com.amplifyframework:core:2.13.0'
implementation 'com.amplifyframework:aws-storage-s3:2.13.0'
```

**Comment by lawmicha** [comment]
Hi @wezside, I've transferred this over to the Amplify Android repo. This feature request has been completed by https://github.com/aws-amplify/amplify-android/pull/2848 and released in https://github.com/aws-amplify/amplify-android/releases/tag/release_v2.20.0 Feel free to open another issue in this repo if you are seeing any problems
