### ISSUE TITLE
Update your com.google.android.play:core:1.10.3 on  1.38.8

### ISSUE THREAD

**Issue by NANAIPRM** [aws-amplify/amplify-android#2889]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

implementation 'com.amplifyframework:core:1.38.8'
    implementation 'com.amplifyframework:aws-auth-cognito:1.38.8'
    implementation 'com.amplifyframework:rxbindings:1.38.8'

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Update your com.google.android.play:core:1.10.3 Maven dependency to an Android 14 compatible version! Your current com.google.android.play:core:1.10.3 library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers. As a reminder, from August 31, 2024, Google Play requires all new app releases to target Android 14. Update to the latest library version dependency to avoid app crashes.

---

 
    
    how to fix on it

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
@NANAIPRM

Amplify Android v1 is deprecated as of June 1st, 2024. No new features or bug fixes will be added. Dependencies may become outdated and potentially introduce compatibility issues.

Please use the latest version (v2) of [Amplify Library for Android](https://docs.amplify.aws/android/) to get started. Refer to [the upgrade guide](https://docs.amplify.aws/gen1/android/start/project-setup/upgrade-guide/) for instructions on upgrading your application to the latest version.

**Comment by pauledwardtang** [comment]
@NANAIPRM I had a similar issue, but for `com.google.android.play:core:1.9.1`. After updating (yes updating) to 1.37.10, that made the problem go away.

The problematic transitive dependency was removed in https://github.com/aws-amplify/amplify-android/pull/2131.

I ran this command to find it:
```shell
./gradlew app:dependencyInsight --configuration [VARIANT]RuntimeClasspath --dependency com.google.android.play:core

```

```
com.google.android.play:core:1.9.1
\--- androidx.navigation:navigation-dynamic-features-runtime:2.3.4
     \--- androidx.navigation:navigation-dynamic-features-fragment:2.3.4
          \--- com.amplifyframework:core:1.35.1

```

We aren't using the rxbindings dependency, so maybe there is another dependency in that library (doubtful) or a release after 1.37.10 reintroduced the play core dependency. Have you tried the dependencyInsight gradle command?

**Comment by tylerjroach** [comment]
Please feel free to continue community discussions. I will be closing this ticket, however, since Amplify v1 is no longer supported.
