### ISSUE TITLE
Amplify.API.Mutate Update and Delete functions just change version and update time -- not actual content

### ISSUE THREAD

**Issue by ramyakandasamy7** [aws-amplify/amplify-android#289]
Describe the bug
When I followed the Android getting started guide for AWS Amplify located [here,](https://aws-amplify.github.io/docs/android/start?ref=amplify-android-btn) I am able to create and query my DynamoDB database. However, when I try to update the object with the following code below, the version number and time last updated changes but the content of the object does not change. I am also not able to delete objects from the database.
```
Amplify.API.mutate(
            Store.builder().content("howdy").id("c29cd2ab-87cf-4dcb-a488-5c049fc0a3e4").build() ,
            MutationType.UPDATE,
            new ResultListener<GraphQLResponse<Store>>() {
                @Override
                public void onResult(GraphQLResponse<Store> response) {
                    Log.i("ApiQuickStart", "Deleted: " + response.getData().getContent());
                }
                @Override
                public void onError(Throwable throwable) {
                    Log.e("ApiQuickStart", throwable.getMessage());
                }
            }
    );
```
To Reproduce

Follow the tutorial located here except for the change in step 2

For graphql schema, I changed mine to reflect the following:
```
type Product @model {
id: ID!
title: String!
quantity: String
}
type Store @model {
id: ID!
content: String!
products: [Product]
}
```
Add code to update a store object after creating an object and check the contents of the DynamoDB database after.
```
Amplify.API.mutate(
Store.builder().content("howdy").id("c29cd2ab-87cf-4dcb-a488-5c049fc0a3e4").build() ,
MutationType.UPDATE,
new ResultListener<GraphQLResponse>() {
@override
public void onResult(GraphQLResponse response) {
Log.i("ApiQuickStart", "Deleted: " + response.getData().getContent());
}
@override
public void onError(Throwable throwable) {
Log.e("ApiQuickStart", throwable.getMessage());
}
}
);
```
Expected behavior
I expect that when I update a store content from "Luckys" to "howdy" as shown above, the content should change to howdy. Instead, just the version and last updated time changes.

Device: Android Studio Pixel 3 emulator
OS: 10.14.6

**Comment by TrekSoft** [comment]
Hey, this sounds like you have sync enabled on your table. If you have it enabled, you have to make sure to send the current version of each record when you perform a mutate, otherwise the mutation won't go through and it just updates the last update time (and possibly also the version number like you mentioned). Is there a reason you want to have sync enabled on the table? That was designed for use with DataStore not raw API.

**Comment by TrekSoft** [comment]
The way you get sync enabled on a table is if you answer the following question "yes" during the CLI setup:

- Configure conflict detection?

You should say No to "configure conflict detection" unless you're wanting to use DataStore.

**Comment by ramyakandasamy7** [comment]
Apologies for the lack of response -- I tried it again and this time did not configure conflict detection. It still is only updating the version number.

Is there any way I can disable "sync" if that is the issue here?

**Comment by TrekSoft** [comment]
This sounds like it may be a caching issue - if you start a new project with N for conflict detection I think it should work just fine.

**Comment by jamesonwilliams** [comment]
@ramyakandasamy7 The issue with the CLI-generated file(s) may be worth filing in the [amplify-cli issues](https://github.com/aws-amplify/amplify-cli/issues).
