### ISSUE TITLE
Run Query

### ISSUE THREAD

**Issue by mithleshjs** [aws-amplify/amplify-android#300]
I want to run GraphQL queries but nowhere in the docs it is specified how to do that.

**Comment by jamesonwilliams** [comment]
Hi @mithleshjs, thanks for your question.

Here are some links to the documentation around using the Amplify API category to do queries:
 1. [Listing all items that match some conditions](https://aws-amplify.github.io/docs/android/api#list-query);
- [Querying for a particular item by its ID](https://aws-amplify.github.io/docs/android/api#query-by-id).

The Framework provides [a number of different methods](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/api/GraphQlBehavior.java#L37-L241) for querying a GraphQL endpoint.

It is possible, but more complex, to use these APIs without AppSync. Please let me know if this is your case and we will try to guide you. Let me know if the docs still aren't helping.

**Comment by mithleshjs** [comment]
I am using Hasura as a GraphQL endpoint. So these docs are not helping in my case.
