### ISSUE TITLE
Using Custom GraphQL Endpoint

### ISSUE THREAD

**Issue by mithleshjs** [aws-amplify/amplify-android#303]
It is not mentioned in the docs how to use your own custom endpoint. Can anybody help with that?

**Comment by jpignata** [comment]
This isn't yet supported in Amplify Android, but is on our list. Please add +1's to this Feature Request to help us prioritize.

**Comment by jamesonwilliams** [comment]
It could be interesting to implement this as a new plugin, around Apollo. Something like:

```kotlin
Amplify.addPlugin(ApolloApiPlugin())
```

The plugin implementation could include a factory to create Amplify API category `GraphQlRequest` objects, from Apollo `Operation` objects.

**Comment by sktimalsina** [comment]
@mithleshjs you can use custom domains in your configuration now. Please refer to [this doc](https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/android/) on how to use custom domains.
