### ISSUE TITLE
DataStoreException: Bad subscription data

### ISSUE THREAD

**Issue by atomicalsoftwares** [aws-amplify/amplify-android#343]
Hello,

Learning to use Amplify and I'm running onto the following crash when using sync:

Crashlog:

> https://pastebin.com/iiUZD1i3

Schema:

> type MyModel@model {
>     data: AWSJSON
>     merchantId: ID!
>     model: AWSJSON
>     name: String
>     price: String
>     priceRangeStart: Int
>     priceRangeEnd: Int
>     type_id: String!
>     status: Boolean
> }

Using Android Studio, 4.1 Canary 4.

I've tried cleaning project and cleaning app data but now the error crashes the app.

Update: This is happening when I call "Amplify.DataStore.query". The request is succesful and calls: "public void onResult(Iterator<MyModel> result) ".

But taking a closer look while debugging, this is the result:

![image](https://user-images.githubusercontent.com/35309955/78266621-46c36a00-751b-11ea-9529-ee579220eb3a.png)

This happens *after* I've saved a single object.

**Comment by raphkim** [comment]
Hi @atomicalsoftwares ,

Thank you for trying AWS Amplify and for reaching out to us!

AWS Amplify requires that every model contain `id: ID!` field to uniquely identify itself. 

I see that your `MyModel` model already contains what appears to be an ID (`merchantId`). If that ID is a reference to self, then a solution here would be to rename that variable to simply `id`. Otherwise, you would need to add another field of that name to your model.

**Comment by atomicalsoftwares** [comment]
Hello,

I did this last night, but I believe the same error came up, I've tried deleting the project through the cli and re-creatign it, but I'm still getting the same error.

Crashlog:

> https://pastebin.com/ZnkVb3D3

Model:

> 
> type MyModel @model {
>     id:ID!
>     data: AWSJSON
>     merchantId: ID!
>     model: AWSJSON
>     name: String
>     price: String
>     priceRangeStart: Int
>     priceRangeEnd: Int
>     type_id: String!
>     status: Boolean
>     notes: String
> }

**Comment by atomicalsoftwares** [comment]
Off the topic,

Is the ID needs to be UUID or can it be any ID? Because when I try to do my own ID, it says it's not a proper UUID format.

**Comment by jamesonwilliams** [comment]
> Is the ID needs to be UUID or can it be any ID? Because when I try to do my own ID, it says it's not a proper UUID format.

In the code right now, there are a lot of assumptions around it being a UUID. I'd stick with that, for the time-being. I can see it being useful to use a non-UUID, too, however.

**Comment by jamesonwilliams** [comment]
> I did this last night, but I believe the same error came up, I've tried deleting the project through the cli and re-creating it, but I'm still getting the same error.
> 
> Crash-log:
> 
> > https://pastebin.com/ZnkVb3D3
> 
> Model:
> 
> > type MyModel @model {
> > id:ID!
> > data: AWSJSON
> > merchantId: ID!
> > model: AWSJSON
> > name: String
> > price: String
> > priceRangeStart: Int
> > priceRangeEnd: Int
> > type_id: String!
> > status: Boolean
> > notes: String
> > }

From the error log, it looks like AppSync doesn't think your model has an `id`. Can you make sure that the endpoint actually got updated? Are your client configs pointing to the new endpoint? Can you validate your new endpoint by issuing queries against it in the AWS AppSync console?

**Comment by atomicalsoftwares** [comment]
> From the error log, it looks like AppSync doesn't think your model has an `id`. Can you make sure that the endpoint actually got updated? Are your client configs pointing to the new endpoint? Can you validate your new endpoint by issuing queries against it in the AWS AppSync console?

Is this done by issuing amplify push?

**Comment by jamesonwilliams** [comment]
Hi @atomicalsoftwares, based on that stack trace, it looks like you're using the `0.9.1` or `0.9.1` releases. (The message ["Failed to publish item to network"](https://github.com/aws-amplify/amplify-android/blob/release_v0.9.1/aws-datastore/src/main/java/com/amplifyframework/datastore/network/SyncEngine.java#L219) was only present in these releases.)

The network synchronization stuff basically didn't work in the 0.9.x preview releases.

The 0.10.0 release includes significant updates _specifically_ to the network synchronization logic in the DataStore. A good next step would be to update your `build.gradle` to point to this latest release.

We have been iterating on the [Android DataStore Getting Started](https://docs.amplify.aws/lib/datastore/getting-started?platform=android) documentation over the last couple of weeks, and it should now refer to the 0.10.0 release, as well.

Feel free to re-open if you are seeing this issue in 0.10.0.
