### ISSUE TITLE
Cannot resolve symbol 'AmplifyModelProvider'

### ISSUE THREAD

**Issue by bakeano** [aws-amplify/amplify-android#370]
Good day all,

I am implementing AWS Amplify DataStore for android following the docs, and basically i get this error when i try to initialize the data store plugin on amplify:

**Cannot resolve symbol 'AmplifyModelProvider'**

You can find code from my gradle files and my application class below.

I try to search on java files and i cant find reference of that symbol on the dependencies provided on the  [docs](https://docs.amplify.aws/lib/datastore/getting-started?platform=android)

Thanks in advance for your help.

Steps to reproduce:

1. Create new android project
2. Install Amplify CLI, using npm, `npm install -g @aws-amplify/cli`
3. Configure amplify, `amplify configure`
4. On new android project root folder, run amplify init, `amplify init`
5. On new android project root folder, `amplify add auth`, adding authentication
6. Create android application class
7. Add android application class to AndroidManifest.xml
8. Try to add data store plugin to amplify on onCreate method of the application class

I already try the following solutions:

1. Clean project
2. Rebuild project
3. Run Make Project
4. Close and open again Android Studio

AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.bakeano.htejobs">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```

MyApplication.java
```
package com.bakeano.htejobs;

import android.app.Application;
import android.util.Log;

import com.amazonaws.mobile.client.AWSMobileClient;
import com.amazonaws.mobile.client.Callback;
import com.amazonaws.mobile.client.UserStateDetails;
import com.amplifyframework.api.aws.AWSApiPlugin;
import com.amplifyframework.core.Amplify;
import com.amplifyframework.core.model.ModelProvider;
import com.amplifyframework.datastore.AWSDataStorePlugin;

public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        // AWSMobileClient initialization
        AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                try {
                    ModelProvider modelProvider = AmplifyModelProvider.getInstance(); // Error on this line !!!
                    Amplify.addPlugin(AWSDataStorePlugin.forModels(modelProvider));
                    Amplify.addPlugin(new AWSApiPlugin());
                    Amplify.configure(getApplicationContext());
                } catch (Exception e) {
                    Log.e("bakeanoMessage", "Amplify adding plugins Exception: " + e.getMessage(), e);
                }
            }

            @Override
            public void onError(Exception e) {
                Log.e("bakeanoMessage", "AWSMobileClient init Exception: " + e.getMessage(), e);
            }
        });
    }
}
```

Module Gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "com.bakeano.htejobs"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    // androidx constraint layout
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta4'

    // aws amplify framework core
    implementation 'com.amplifyframework:core:0.10.0'

    // AWSMobileClient
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.16.11'

    // aws amplify for the drop-in ui
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.16.11'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.16.11'

    // aws amplify api
    implementation 'com.amplifyframework:aws-api:0.10.0'

    // aws amplify data store
    implementation 'com.amplifyframework:aws-datastore:0.10.0'

}
```

Project Gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'

        // amplify tools gradle plugin
        classpath 'com.amplifyframework:amplify-tools-gradle-plugin:0.2.1'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

// applying the amplify tools plugin
apply plugin: 'com.amplifyframework.amplifytools'

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by jamesonwilliams** [comment]
Hi @bakeano! Firstly, thank you for the detailed and well-formatted report.

`AmplifyModelProvider` is a _[code-generated](https://docs.amplify.aws/lib/datastore/getting-started?platform=android#generate-models)_ file. _After_ you generate models per the docs, you'll end up with a file at `src/main/java/com/amplifyframework/datastore/generated/model/AmplifyModelProvider.java`.

In your example, you don't import this class, so you'd need to add:
```
import com.amplifyframework.datastore.generated.model.AmplifyModelProvider;
```
So that the symbol can be resolved when you call `AmplifyModelProvider.getInstance()`, later.

Aside from this, looking through your code, looks like you're more or less on the right track.

**Comment by bakeano** [comment]
Hi @jamesonwilliams thanks for your quick reply!!!,

using your directions i was able to generate the file and import it, thanks !!, but a note:

i need it to run `amplify codegen models` on the terminal on the root folder of the project, and just after that the files where generated, i use the "modelgen" directive on android studio before with no results, maybe i did not understand the docs correctly, but i was in the assumption that running that on the console was optional, and the normal procedure was running modelgen from android studio.

Thanks !!!

**Comment by jamesonwilliams** [comment]
@bakeano Correct! The `amplify-tools-gradle-plugin` provides that `modelgen` task in Android Studio. And that is _for sure_ supposed to generate models, when you run it.

The `amplify-tools-gradle-plugin` is basically a thin wrapper around the same stuff that `amplify codegen models` does. Both are part of the `amplify-cli` project. You shouldn't have to do both.

Both of those artifacts are part of the `amplify-cli`. We could look at [raising an issue in that project](https://github.com/aws-amplify/amplify-cli/issues), if you've got repro steps.
