### ISSUE TITLE
com.amplifyframework.AmplifyException: Unknown/bad category type: dataStore

### ISSUE THREAD

**Issue by bakeano** [aws-amplify/amplify-android#384]
Good day All,

I have this error during data store plugin adding on amplify initialization.

`com.amplifyframework.AmplifyException: Unknown/bad category type: dataStore`

I have added the code i believe is pertinent, please ask for more if need it, have follow documentation as good as possible, if i am making a begginer mistake please be gentle :-)

Thanks !!

Android logs
```
2020-04-17 18:58:55.797 30894-30928/com.bakeano.htejobs E/bakeanoMessage: Amplify adding plugins Exception: Unknown/bad category type: dataStore
    com.amplifyframework.AmplifyException: Unknown/bad category type: dataStore
        at com.amplifyframework.core.AmplifyConfiguration.forCategoryType(AmplifyConfiguration.java:4)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:16)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1)
        at com.bakeano.htejobs.MyApplication$1.onResult(MyApplication.java:36)
        at com.bakeano.htejobs.MyApplication$1.onResult(MyApplication.java:23)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
        at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:596)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:762)
```

Android Application Class (**MyApplication.java**)
```
package com.bakeano.htejobs;

import android.app.Application;
import android.util.Log;

import com.amazonaws.mobile.client.AWSMobileClient;
import com.amazonaws.mobile.client.Callback;
import com.amazonaws.mobile.client.UserStateDetails;
import com.amplifyframework.api.aws.AWSApiPlugin;
import com.amplifyframework.core.Amplify;
import com.amplifyframework.core.model.ModelProvider;
import com.amplifyframework.datastore.AWSDataStorePlugin;
import com.amplifyframework.datastore.generated.model.AmplifyModelProvider;

public class MyApplication extends Application {


    @Override
    public void onCreate() {
        super.onCreate();

        // AWSMobileClient initialization
        AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                try {
                    // AWS Amplify datastore plugin
                    ModelProvider modelProvider = AmplifyModelProvider.getInstance();
                    Amplify.addPlugin(AWSDataStorePlugin.forModels(modelProvider)); <--- Error line

                    // AWS Amplify api plugin
                    Amplify.addPlugin(new AWSApiPlugin());

                    // AWS Amplify configure
                    Amplify.configure(getApplicationContext()); <--- Exception line
                } catch (Exception e) {
                    Log.e("bakeanoMessage", "Amplify adding plugins Exception: " + e.getMessage(), e);
                }
            }

            @Override
            public void onError(Exception e) {
                Log.e("bakeanoMessage", "AWSMobileClient init Exception: " + e.getMessage(), e);
            }
        });
    }
}
```

**Amplify status from amplify-cli** `amplify status`
Current Environment: dev

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Api      | amplifyDatasource | No Change | awscloudformation |
| Auth     | ~resourceName~   | No Change | awscloudformation |

GraphQL endpoint: https://~somekey~.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: ~someotherkey~

**Comment by bakeano** [comment]
I was trying to work arround this issue and find this error on amplify cli, maybe is related:

```
amplify api update
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Enable DataStore for entire API
Cannot read property 'output' of undefined
TypeError: Cannot read property 'output' of undefined
    at transformGraphQLSchema (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/transform-graphql-schema.js:397:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by jamesonwilliams** [comment]
Hey @bakeano!

When you add a backend via the Amplify CLI, it's supposed to spit out a file called `amplifyconfiguration.json`, into your project directory (under `app/src/main/res/raw/amplifyconfiguration.json `.)

When I go through the DataStore docs to setup a new project, I end up with an `amplifyconfiguration.json` file that looks like this:
```
{
    "dataStore": {
        "plugins": {
            "awsDataStorePlugin": {
                "syncMode": "api",
                "apiName": "amplifyDatasource"
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://MY_REDACTED_ENDPOINT_ID.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "MY_REDACTED_API_KEY"
                }
            }
        }
    }
}
```

Based on the message you're seeing, it sounds like your `amplifyconfiguration.json` doesn't have any `"dataStore"` in it, like the one above does.

If the CLI is _crashing_ while operating on your schema, before it properly write out this file, that could be one explanation?

Couple questions for you --
1. What is the _current_ contents of your `amplifyconfiguration.json` (please don't share your endpoint ID or API key!)
2. What is the contents of your GraphQL schema -- the one that the CLI didn't like?
3. Which CLI version do you use?

We can either cut a new issue in the [`amplify-cli` project](https://github.com/aws-amplify/amplify-cli/issues/new?template=bug_report.md), or maybe @yuth can help us transfer this current #384 over into it?

**Comment by bakeano** [comment]
Hello @jamesonwilliams,

i got the file `amplifyconfiguration.json` located on the path you mention, as you predicted the file does not have the "dataStore" section, find below the content.

i send the GraphQL schema too, find below.

CLI version `amplify -v`: 4.18.0

I have already made a post on [amplify-cli project](https://github.com/aws-amplify/amplify-cli), here is the issue: [TypeError: Cannot read property 'output' of undefined at transformGraphQLSchema](https://github.com/aws-amplify/amplify-cli/issues/4058) #4058

If you want me to do further steps please list them ill do them gladly.

**amplifyconfiguration.json (full content)**
```
{
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://$endpointID$.appsync-api.$region$.amazonaws.com/graphql",
                    "region": "$region$",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    }
}
```
**graphQL schema**
```
type PhotoReport @model
  @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  name: String!
  uploadButtonText: String!
  definition: AWSJSON!
  job: AWSJSON!
  templateId: Int!
  status: AWSJSON!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  deletedAt: AWSDateTime
  photoReportObjects: [PhotoReportObject] @connection
}

type PhotoReportObject @model
  @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  type: String!
  name: String!
  precedence: Int!
  photoReportID: ID!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  deletedAt: AWSDateTime
  photoGroups: [PhotoGroup] @connection
}

type PhotoGroup @model
@auth(rules: [{allow: private, provider: iam}]) {
    id: ID!
    name: String!
    precedence: Int!
    photoReportObjectID: ID!
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    deletedAt: AWSDateTime
    photos: [Photo] @connection
}

type Photo @model
@auth(rules: [{allow: private, provider: iam}]) {
    id: ID!
    name: String!
    pictureURI: String!
    photoGroupID: ID!
    userId: Int!
    statusName: String!
    details: AWSJSON
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    deletedAt: AWSDateTime
}
```

Thanks !!

**Comment by bakeano** [comment]
Hi all,

amplify cli has updated to 4.18.1, the same issues still persist.

Thanks !!

**Comment by jamesonwilliams** [comment]
@yuth Is this a CLI issue?

**Comment by lambda0xff** [comment]
@jamesonwilliams 
I have a web app set up with amplify.
From Android studio, after I do an `amplify pull`, the `dataStore` section is missing from `amplifyconfiguration.json`

**Comment by bakeano** [comment]
hi @lambda0xff, i can hardly help you with this as i never found a solution, neither here or in android-cli project, the only conclusion i got is that the software is still in preview and under heavy development, so results are unpredictable.

Neither way try to run ... `add datastore to entiry api` in amplify cli, when you update the api category, that action suppose to create the datastore section on `amplifyconfiguration.json`, in my case it does not work, but maybe in your case it does.

Regards !!

**Comment by jamesonwilliams** [comment]
@bakeano @lambda0xff Hey guys, yea this was broken in the 0.10 release. It has been fixed in master.

You can either:
1. Manually patch the config file.
```
{
    "dataStore": {
        "plugins": {
            "awsDataStorePlugin": {
                "syncMode": "api",
                "apiName": "amplifyDatasource"
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://MY_REDACTED_ENDPOINT_ID.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "MY_REDACTED_API_KEY"
                }
            }
        }
    }
}
```
2. Use master [see notes](https://github.com/aws-amplify/amplify-android/blob/master/CONTRIBUTING.md#consuming-development-versions-of-the-framework)
3. Wait for the next release which should be coming shortly, and will include the fix.
