### ISSUE TITLE
AWS Amplify XR (AR/VR) with android

### ISSUE THREAD

**Issue by p3420a1** [aws-amplify/amplify-android#410]
Any pointers on how to implement AR/VR category in Android Application

AWS Amplify XR

SDK Version: [e.g. 2.6.25]
Device Information

Device: [e.g. Pixel XL, Simulator]
Android Version: [e.g. Pie 9]

**Comment by jpignata** [comment]
This is not on our near term roadmap and hasn't seen much activity. Closing for now but please reopen or comment if you'd like us to consider this feature.

**Comment by AlexisHolyoak** [comment]
@jpignata Is there any chance of an update here in the near future?
