### ISSUE TITLE
Make it easier to debug Amplify library code

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-android#443]
Currently when you step into Amplify from application code, you get the decompiled source. Android Studio should be able to step right into the published source code from Maven. This would help debug issues when building applications.

**Comment by jessica-mulein** [comment]
+1 from the peanut gallery!
try setting fields: ["blah"] to a scalar like fields: "blah" :)

**Comment by jpignata** [comment]
This was addressed in https://github.com/aws-amplify/amplify-android/pull/546 and will go out with 1.0.1.
