### ISSUE TITLE
Possible race condition with publishSubject 

### ISSUE THREAD

**Issue by michalisAsp** [aws-amplify/amplify-android#451]
Facing issues with master branch latest version with DataStore sync enabled.
Didn't have a chance to debug yet and identify the exact issue, but I came across this.
https://github.com/aws-amplify/amplify-android/blob/72fd6f1a0f51123d7df4dfe61bbbaf77cfa8aaa0/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java#L102

`PublishSubject` is not thread safe. Not sure what are your plans on refactoring here, but a temporary "fix" is to make it serialized.
http://reactivex.io/RxJava/javadoc/io/reactivex/subjects/Subject.html#toSerialized--

**Comment by jamesonwilliams** [comment]
@michalisAsp Good catch! Appreciate the close eye, here. I will put up a PR to address this briefly and would appreciate your review.
