### ISSUE TITLE
[Storage] Support uploading an InputStream or URI instead of File

### ISSUE THREAD

**Issue by Shakezulla57** [aws-amplify/amplify-android#469]
Linking to this issue from current SDK for brevity.

https://github.com/aws-amplify/aws-sdk-android/issues/1436

Basically Android is moving away from the file scheme. Most if not all "files" will be coming from the MediaStore using the Storage Access Framework.  Without the ability to use InputStreams an app would have to copy every file it wants to upload into its cache directory in order to have a reliable `File()` to use. This would be detrimental to users because of storage limitations and overall confusion about why a file cannot be uploaded because your device is out of storage.

**Comment by shiv71** [comment]
@jpignata Is this fix [(targetSdkVersion to 29 SAF issue)](https://github.com/awslabs/aws-sdk-android-samples/pull/336) merged in the s3 library?

**Comment by richardmcclellan** [comment]
@shiv71, https://github.com/awslabs/aws-sdk-android-samples/pull/336 is not part of the library, it is part of a sample app which uses the library.

Currently, Amplify `Storage` only supports `File` as an input type.  This is not ideal given the recent to the Storage Access Framework in Android 10.  

The current workaround is to write your `InputStream` or `URI` to a temporary `File` on disc first, and then pass that File to the Storage API.   Take a look at our sample app for an example: https://github.com/awslabs/aws-sdk-android-samples/blob/604fd21e214b5a6fab85a07d613f374963eafe8e/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/UploadActivity.java#L429-L522

In the meantime, please add comments or reactions here if you'd like to see this issue prioritized, thanks!

**Comment by rahulvyas** [comment]
@richardmcclellan Would you guys update the amplify Storage SDK to support URI directly instead of copying into cache directory ?

**Comment by joseOlivares** [comment]
Please, work on it!  We need that feature.

**Comment by TrekSoft** [comment]
Yep, this is definitely on our radar. Got a lot on our plates right now but will prioritize based on ticket activity.

**Comment by changxu0306** [comment]
Hello! Now we support uploading InputStream using `TransferUtility` in AWS Android SDK v2.19.2. You can just call `upload()` and pass your InputStream as a parameter to the method. The corresponding API in Amplify framework will be released in the next version. I'll close this issue for now. Feel free to reopen it if you have further problems. Thank you!
