### ISSUE TITLE
DataStore observe should trigger also for dependencies

### ISSUE THREAD

**Issue by michalisAsp** [aws-amplify/amplify-android#527]
For schema below, I think that the current behaviour of the observable `dataStore.observe(Blog::class.java)` is that we receive updates only if there is a change to a `Blog` item. For updates to `Post` we will have to use a separate observable.

```
type Blog @model
{
    id: ID!
    posts: Post @connection
}
type Post @model
{
    id: ID!
    text: String
}
```

It would be useful to add options(or default behaviour) to `dataStore.observe(Blog::class)` so that we receive updates for both Blog & Post. I think other libs are using triggers on all tables referenced in a query.

Anyway, in my case It's particularly difficult to implement also due to lack of support for one to one bi-directional relations.

**Comment by jamesonwilliams** [comment]
Hey @michalisAsp thanks for suggesting this! I can definitely see why this would be useful. Sounds like there is an easy enough workaround available for the interim.

You could do something like:
```
// Instead of just observing a single class, observe multiple classes.
Observable.fromIterable(AmplifyModelProvider.getInstance().models())
    .flatMap(clazz -> RxAmplify.DataStore.observe(clazz))
    .filter(anyChange -> {
        // add your custom matching logic,
        // so that you'll only process changes that interest you
    })
    .subscribe(changeOfInterest -> {
        // When one shows up .... profit!
    });
```

**Comment by jamesonwilliams** [comment]
We take up features based in part on number of GitHub reactions. If you would like to see this feature implemented, please add a 👍 or similar reaction to the original post here: https://github.com/aws-amplify/amplify-android/issues/527#issue-625034082. Closing for now.
