### ISSUE TITLE
REST API converts PUT and POST with no body into GET request in-flight

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-android#538]
OkHttp seems to convert in-flight POST and PUT requests to GET requests if the body provided is null. This is surprising.

In order to address this, `RestOptions` should be changed to:

1. Ensure that the constructor cannot be called directly, rather we should prefer `RestOptions.Builder`
1. In the constructor, if provided `data` is `null`, pass an empty `byte[]`

**Comment by c0rdeiro** [comment]
when will this bug be addressed?

**Comment by jpignata** [comment]
@c0rdeiro Soon. :) For now, you can work around it by providing an empty body. A better fix is forthcoming.

**Comment by c0rdeiro** [comment]
Thank you so much, this was driving me insane in the last 2 days

**Comment by jpignata** [comment]
Same here! Sorry for the trouble.

**Comment by TrekSoft** [comment]
Got a PR for it right here @c0rdeiro : https://github.com/aws-amplify/amplify-android/pull/539
