### ISSUE TITLE
Amplify.Storage.uploadFile() function is not working

### ISSUE THREAD

**Issue by srikamalteja** [aws-amplify/amplify-android#550]
**Describe the bug**
Hi,

I integrated amplify storage library and configured everything by following the documentation.

https://docs.amplify.aws/lib/storage/getting-started/q/platform/android#uploading-data-to-your-bucket

The issue is, Amplify.Storage.uploadFile() is not giving either success or failure response.

Note : In MyApplication extends Application class, first configure and then add plugins like below otherwise application is crashing. So please update document.

            Amplify.configure(getApplicationContext());
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());

File file = new File(picturePath);

Amplify.Storage.uploadFile(
            "UserKey",
            file,
            result -> Log.i("MyAmplifyApp", "Successfully uploaded: " + result.getKey()),
            storageFailure -> Log.e("MyAmplifyApp", "Upload failed", storageFailure)
    );

Amplify storage library 

This is what i'm using in build.gradle (:app)

    implementation 'com.amplifyframework:core:0.10.0'
    implementation 'com.amplifyframework:aws-api:0.10.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.0.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.0.0'

In build.gradle (project)

classpath 'com.amplifyframework:amplify-tools-gradle-plugin:1.0.0'

**Comment by raphkim** [comment]
Hi @srikamalteja !

Thank you for using Amplify! I understand that you are frustrated because the storage plugin is not behaving as you expected.

From your description, I am noticing that you are configuring Amplify before adding the plugins. `Amplify.configure()` is a once in a life-cycle operation that configures all of its added plugins; the plugins would have to be registered *before* this function is invoked.

However, you are mentioning that your application crashes when you add the plugins beforehand. Would you be able to show us a log and stacktrace of this occurrence? This may be a result of not having the configuration file. Did you follow the steps described [here](https://docs.amplify.aws/lib/storage/getting-started/q/platform/android#provision-backend-storage) via Amplify CLI to set up the backend?

**Comment by srikamalteja** [comment]
Hi @raphkim ,

Yes I followed same steps mentioned in the document and when I add plugins before `Amplify.configure()` I got below error.

`AmplifyException {message=Failed to instantiate AWSMobileClient, cause=java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient., recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:87)
        at com.amplifyframework.core.category.Category.configure(Category.java:13)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:17)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1)
        at packag.nnk.com.fk.base.BaseApplicationClass.onCreate(BaseApplicationClass.java:33)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6479)
        at android.app.ActivityThread.access$1300(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient.
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:587)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by jpignata** [comment]
Heya @srikamalteja! Out of curiosity, does your `amplifyconfiguration.json` have Auth configured within it? Can you let us know what version of the CLI you're using? (`amplify version`)

**Comment by raphkim** [comment]
Hi @srikamalteja 

Would you be able to try using this [solution](https://github.com/aws-amplify/amplify-android/issues/549#issuecomment-637100313)?

**Comment by srikamalteja** [comment]
Hello @jpignata 

There is no Auth configured in the `amplifyconfiguration.json` 

`{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "*********",
                "region": "**********",
                "defaultAccessLevel": "guest"
            }
        }
    }
}`

**Comment by srikamalteja** [comment]
Hey @raphkim , I tried your solution but didn't work, application is still throwing the same exception.

After adding all the contents from `awsconfiguration.json` to `amplifyconfiguration.json`,

`amplifyconfiguration.json` looking like

`{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "storage": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "us-east-1:5b1ed651-1322-4f44-916f-20187c78048e",
              "Region": "us-east-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "us-east-1_xZFXjq6HX",
            "AppClientId": "mi2gvj1ri4qbs******",
            "AppClientSecret": "9nq5ulsc9q7h2psrfvj0agdbn6gvfl5cv9*******",
            "Region": "us-east-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        },
        "S3TransferUtility": {
          "Default": {
            "Bucket": "******",
            "Region": "*****"
          }
        }
      }
    }
  }
}`

**Comment by raphkim** [comment]
Hi @srikamalteja ,

Please add the content of `awsconfiguration.json` under "auth" -> "plugins" -> "awsCognitoAuthPlugin"

**Comment by srikamalteja** [comment]
Hey! It didn't throw any exception :D,  also `Amplify.Storage.uploadFile();`  worked.

Thank guys :)

I'm posting the final answer for others who got confused,

Initially your awsconfiguration file looks like,

`{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "u*****-1:5b****-1322-4f44-916f-201***",
                "Region": "region"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1_x*****",
            "AppClientId": "mi2gvj1ri4qbs*****",
            "AppClientSecret": "9nq5ulsc9q7h2p*******",
            "Region": "region"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "your bucketname",
            "Region": "your region"
        }
    }
}`

and your amplifyconfiguration.json looks like,

`{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "your bucket",
        "region": "region",
        "defaultAccessLevel": "guest"
      }
    }
  }
}`

after copying all the content (just press ctrl +a and ctrl + c) from `awsconfiguration.json` file and insert the copied content under "auth" -> "plugins" -> "awsCognitoAuthPlugin".

So the final `amplifyconfiguration.json` looks like

`{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "your bucket name",
        "region": "your region",
        "defaultAccessLevel": "guest"
      }
    }
  },
  
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "*****-1:5b*****-13**-4f44-916f-201***",
              "Region": "region"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "u_xZFXjq6HX",
            "AppClientId": "mi2gvj1ri4q******",
            "AppClientSecret": "9nq5ulsc9q7h2psrfvj0a******",
            "Region": "region"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        },
        "S3TransferUtility": {
          "Default": {
            "Bucket": "your bucket name",
            "Region": "region"
          }
        }
      }
    }
  }
}`
