### ISSUE TITLE
[API GraphQL] API query and mutations

### ISSUE THREAD

**Issue by jtphe** [aws-amplify/amplify-android#558]
I tried to make query and also mutations but every time I get this message :

> AmplifyException {message=There is more than one API configured for this plugin with matching endpoint type., cause=null, recoverySuggestion=Please specify the name of API to invoke in the API method.}

I don't know if I had to add something in the config file or if it's about my code? 

This is an mutation example that I made : 
```
val folderDB = Folder.builder()
    .owner(owner)
    .parent(parent)
    .name(folderName)
    .build()

Amplify.API.mutate(ModelMutation.create(folderDB),
    { response -> Log.i("MyAmplifyApp", "Updated Todo with id: " + response.data.id) },
    { error -> Log.e("MyAmplifyApp", "Update failed", error) }
)
```

**Comment by jamesonwilliams** [comment]
Hi @jtphe! Do you have multiple endpoints configured in your `app/src/main/res/raw/amplifyconfiguration.json`?

If you have multiple endpoints defined, but you only intend to use one, then simply remove the one you don't need.

If you have multiple endpoints defined, _and_ intend to use more than just one of them, then, you need to specify the name of the API when you perform the `mutate` call:

```
Amplify.API.mutate(
    "apiNameInConfigFile",
    ModelMutation.create(folderDB),
    { response -> Log.i("MyAmplifyApp", "Updated Todo with id: " + response.data.id) },
    { error -> Log.e("MyAmplifyApp", "Update failed", error) }
);
```

If you only have a single endpoint configured in `amplifyconfiguration.json`, and still get this message, it sounds like a bug. If this is the case, please do include a copy of your `amplifyconfiguration.json`, with all unique identifiers _XXXX_'d out (hostname, API key, auth details, etc.)

**Comment by jtphe** [comment]
Ok I see, I had 2 APIs but I only use one, so I removed the unused ! Thank you :)
