### ISSUE TITLE
Not getting all schema attributes in my model definitions

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-android#564]
I have as simple schema for an app I'm building:
```
type Recipe @model {
  id: ID!
  name: String!
  description: String
  counter: Int!
  rating: Rating
}

enum Rating {
  YUCK
  MEH
  TASTY
  AMAZING
}
```
When I run the modelgen I expect to be able to write the following code:

```java
Recipe item = Recipe.builder()
       .name("Build Android application")
       .description("Build an Android application using Amplify")
       .counter(1)
       .rating(MEH)
       .build();
```

However, the `Recipe` class does not have the `description` and `rating` attributes as part of it's definition. What do I do next?

**Comment by jpignata** [comment]
Debugged over Chime. Essentially, `Builder` requires that properties are specified in such a way that all required parameters are defined first. This works with the above schema:

```java
 Recipe item = Recipe.builder()
            .name("Build Android application")
            .counter(1)
            .rating(MEH)
            .description("Build an Android application using Amplify")
            .build();
```
