### ISSUE TITLE
Amplify adding plugins Exception: Failed to instantiate AWSMobileClient within 10 seconds

### ISSUE THREAD

**Issue by planasmultimedia** [aws-amplify/amplify-android#565]
If i execute in CLI: amplify status i got the following settings:
 Category | Resource name      | Operation | Provider plugin   |
| -------- | ------------------ | --------- | ----------------- |
| Function | Music2AllLambdas   | No Change | awscloudformation |
| Auth     | cognito6dd11ce5    | No Change | awscloudformation |
| Api      | ApiRest            | No Change | awscloudformation |
| Api      | Music2AllAPI       | No Change | awscloudformation |
| Storage  | musicallsongimages | No Change | awscloudformation |

Error: E/bakeanoMessage: Amplify adding plugins Exception: Failed to instantiate AWSMobileClient within 10 seconds
    AmplifyException {message=Failed to instantiate AWSMobileClient within 10 seconds, cause=null, recoverySuggestion=Check network connectivity}
 at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:93)
 at com.amplifyframework.core.category.Category.configure(Category.java:13)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:17)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1)
        at com.example.music2all.MyApplication$1.onResult(MyApplication.java:30)
        at com.example.music2all.MyApplication$1.onResult(MyApplication.java:24)

app/build dependencies: 
implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.16.12') { transitive = true; }
    implementation 'com.amplifyframework:core:1.0.0'
    //implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.16.11' // For AWSMobileClient

    implementation 'com.amplifyframework:aws-storage-s3:1.0.0' // For S3 storage

    implementation 'com.amplifyframework:aws-auth-cognito:1.0.0'
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.16.12' //For UserPoolsSignIn
    //implementation 'com.amazonaws:aws-android-sdk-lambda:2.2.+' // For Lambda Functions
    //implementation 'com.amplifyframework:aws-api:1.0.0' //For API

    implementation 'com.amazonaws:aws-android-sdk-core:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.12'

    implementation 'com.amazonaws:aws-android-sdk-apigateway-core:2.16.12'

MyApplication:
@Override
    public void onCreate() {
        super.onCreate();

        // AWSMobileClient initialization
        AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                try {
                    Amplify.addPlugin(new AWSCognitoAuthPlugin());
                    Amplify.addPlugin(new AWSS3StoragePlugin());
                    Amplify.configure(getApplicationContext());
                    Log.d("My Application", "AMPLIFY INITIALIZED ----------------");
                } catch (Exception e) {
                    Log.e("bakeanoMessage", "Amplify adding plugins Exception: " + e.getMessage(), e);
                }
            }

            @Override
            public void onError(Exception e) {
                Log.e("bakeanoMessage", "AWSMobileClient init Exception: " + e.getMessage(), e);
            }
        });
    }

I don't know what i'm missing here, everything is configured following the tutorials and i spend so many hours trying to fix this. Please help

**Comment by arifNislam** [comment]
@planasmultimedia How did you solve this?
