### ISSUE TITLE
Support for Google One Tap sign-in and sign-up

### ISSUE THREAD

**Issue by i-haz-teh-codez** [aws-amplify/amplify-android#567]
I have my app set up for Google One Tap authentication, which returns a token when the user successfully authenticates. Now I'd like to integrate that with Amplify Auth but I'm not seeing how I can go about it — not only is email confirmation unnecessary in this case, `signIn` and `signUp` methods on the Auth object take a username and password (which are not required), and `signInWithSocialWebUI` will defeat the whole point of One Tap. Is there a quick fix that I'm unaware of to use a token from a social identity provider to sign up and confirm an account with the Cognito User Pool used by Amplify Auth?

**Comment by jpignata** [comment]
Let us know if we can help further.
