### ISSUE TITLE
Amplify Core's aar proguard is keeping all public/protect class

### ISSUE THREAD

**Issue by richardissuperman** [aws-amplify/amplify-android#571]
i just tried import amplify-core today, and I ran into a ProGuard issue. I believe this rule in amplify-core’ `aar` is the problem: 

```
-keep public class * {
    public protected *;
}
``` 

We have some legacy issue on some of our client side data model dependencies (which contains duplicate classes) and we rely on ProGuard to delete the duplicates for us before packaging. 

One of the duplicated classes is:

> Warning: Exception while processing task java.io.IOException: Can't write [...REDACTED...build/private/gradle/intermediates/transforms/proguard/marketProd/debug/0.jar] (Can't read [...REDACTED.../build/lib/commons-logging-adapters-1.1.1.jar(;;;;;;;**.class)] (Duplicate jar entry [org/apache/commons/logging/impl/Jdk14Logger.class]))
Thread(Tasks limiter_3): destruction

I manually unzip the `aar` and remove that line of ProGuard rule and use `jar -cvf` to zip the `aar` and import into our app and, I can confirm it is working again. (This is a temp workaround to unlock our development work)

I saw a PR here : https://github.com/aws-amplify/amplify-android/pull/546

Do we have any plan to release this soon? Anyway, I can use my workaround for now.

**Comment by TrekSoft** [comment]
Hey @richardissuperman,

We actually have PR out right now to remove ProGuard running from our library so once that's out you can upgrade to the new version and it should address this issue.

https://github.com/aws-amplify/amplify-android/pull/546

**Comment by jpignata** [comment]
This will be included in our next release. Please re-open if you have any questions -- thanks!
