### ISSUE TITLE
Is it possible to customize the path/folder of generated code for modelgen gradle task

### ISSUE THREAD

**Issue by richardissuperman** [aws-amplify/amplify-android#572]
1. It seems like **modelgen** gradle task from plugin **com.amplifyframework.amplifytools** will automatically generate code under ```app/src/main/java``` , however our project doesn't have an app module , are we able to customize it ? 

2. It also seems like we need the ```/amplify``` folder to be existed at the root folder of a project, otherwise the **modelgen** gradle task won't recognize this project as an amplify project hence codegen will fail. Can we also set a different path for where amplify folder can be ? 

Our general goal is to put everything related to Amplify to a independent app module (which is a library module but inside the same repository as our main app )

<img width="326" alt="Screen Shot 2020-06-11 at 5 34 27 PM" src="https://user-images.githubusercontent.com/5363585/84452189-01ea3c80-ac0a-11ea-9706-47adbfaf208e.png">

**Comment by richardmcclellan** [comment]
Closing, as we will track this request via https://github.com/aws-amplify/amplify-codegen/issues/55
