### ISSUE TITLE
Allow configurable "walk depth" for Amplify Generated GraphQL Query

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#577]
Right now, the "walk depth" for a generated GraphQL query is hard-coded to [1 level for DataStore](https://github.com/aws-amplify/amplify-android/blob/master/aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java#L61), and [2 levels for API](https://github.com/aws-amplify/amplify-android/blob/master/aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java#L63).

Seems like this would be a nice thing to be user-configurable, instead. I believe the CLI asks about how many levels to traverse, no? The client could honor that same value, as a configuration item.

**Comment by watanabethais** [comment]
I'm trying to migrate from mobile SDK and came into this.
There's any progress with this feature request?

**Comment by tylerjroach** [comment]
Hi, happy to share that we have released LazyLoading and the use of custom selection sets on Android API category. The API category will now have a depth of 0 by default for relational models. However, you can easily add an `includes` block to optimistically load additional data at whatever depth is needed.

See the documentation here for more details!
https://docs.amplify.aws/lib/graphqlapi/relational/q/platform/android/
