### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by sganeshkanna** [aws-amplify/amplify-android#604]
Unable to pass access key and secret key for authentication. No method available. If you are removing this issue. Please let me know the reason or suggestion. My email- mail2sgk@gmail.com

**Comment by jpignata** [comment]
Thanks for the report. Can you provide some additional details of what you're trying to do, and what error you are seeing?

**Comment by sganeshkanna** [comment]
I need to upload/download file without login (user name and password). Instead i have access key and secret key. There is no method inside Amplify.Auth class.

**Comment by sganeshkanna** [comment]
Here is the way we are creating AWSs3 client earlier AmazonS3Client sS3Client = new AmazonS3Client(new BasicAWSCredentials(ACCESS_KEY,SECRET_KEY));

What is the equivalent in Amplify

**Comment by jamesonwilliams** [comment]
Hi @sganeshkanna --

At the moment, the `AWSS3StoragePlugin` is hard-coded to work only with an Amazon Cognito User Pool. If you are using a different authentication mechanism, I recommend to continue using the S3 SDK, for the time-being. The S3 SDK is still supported.

We can consider adding support for additional authentication mechanisms into the Amplify Storage category. If you would like to see this happen, please vote on this comment with a 👍.
