### ISSUE TITLE
Unable to upload and list file 

### ISSUE THREAD

**Issue by rddewan** [aws-amplify/amplify-android#607]
Always getting this error. Tried wit so many project some project work for upload but cant get list some project works nothing . This i really crazy no document to look up for auth process  

//upload
```console
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9D1BE1089D79AB7A), S3 Extended Request ID: 28TFushvH3idMyoAcFgiAFkNuxV0PPHtSiQg3DSioE1oTm4PTy+AY5sDNvbvWJb2jKFGIKwqODs=
```

//storage list
```console
AmplifyException {message=Something went wrong with your AWS S3 Storage list operation, cause=com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 7DFAE42FB3DD9C02), S3 Extended Request ID: djdqWiGsMY96ifmb2Ku+oc/IL9yKaGpP6ZDYip9PyOUYQCNq4B7KymixH+t914HTxkIxDnTNGe4=, recoverySuggestion=See attached exception for more information and suggestions}
```

**Comment by jamesonwilliams** [comment]
Hi @rddewan, can you include the code you're using to setup/configure Amplify and its plugins? Are using the Cognito auth plugin, as well as the `AWSS3StoragePlugin`? What is the contents of your `ampilfyconfiguration.json` (please block out any credentials/authorization values)? How are your S3 buckets configured? Did you follow the [Getting Started guide for Amplify Storage](https://docs.amplify.aws/lib/storage/getting-started/q/platform/android)?

**Comment by tendynewbies** [comment]
Hi @jamesonwilliams ,

I am getting the same error.
I'm using Cognito auth to authenticate user and then also logging user in via Amplify.Auth.signIn(...)
I followed guide to use amplify storage for android, but no-luck :(

**Comment by jamesonwilliams** [comment]
Please include the code you are using, as well as the contents of your `build.gradle` and `amplifyconfiguration.json` files. Be sure to scrub any credentials out of the `amplifyconfiguration.json` before posting them here.
