### ISSUE TITLE
How to unsusbcribe to an Datastore observation

### ISSUE THREAD

**Issue by richardissuperman** [aws-amplify/amplify-android#611]
In current Amplify DataStore API I only found ```observe``` API 

```
Amplify.DataStore.observe()
```

Is there a way to stop observing data models in case of memory leak?

**Comment by jamesonwilliams** [comment]
Hi @richardissuperman! The first value returned by the `observe(...)` methods is a `Cancelable`. You can use this object to cancel the observation:
```java
final AtomicReference<Cancelable> cancelable = new AtomicReference<>();
Amplify.DataStore.observe(
    cancelable::set,
    change -> {},
    failure -> {},
    /* completion */ () -> {}
);

Cancelable c = cancelable.get();
if (c != null) c.cancel();
```

The version available through the Rx facade is a better developer experience, in my opinion.

```
Disposable disposable = RxAmplify.DataStore.observe();
disposable.dispose();
```

**Comment by richardissuperman** [comment]
@jamesonwilliams thanks, the RxAmplify looks cool
