### ISSUE TITLE
Feature Request: Allow adding extra variables to models' Subscription in DataStore

### ISSUE THREAD

**Issue by richardissuperman** [aws-amplify/amplify-android#619]
I noticed that Amplify DataStore will setup all Model classes' CRUD Subscription during initialisation (models which are defined in ```ModelProvider``` ), however it force to pass an empty set of variables to the generated GraphQLRequest

https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncClient.java#L101

Can we provide an api for dev to be able to pass variables for these sync Susbcription. ? 

I was thinking if we can change the ```ModelProvider``` interface and expose a method like ```Map<Class<T>, Map<String,String>> getModelVariables```, so we can pass this model provider all the way down to ```AppSyncClient```.

**Comment by richardissuperman** [comment]
then the code will be like:

```

        final GraphQLRequest<String> request =
            new GraphQLRequest<>(document, Collections.emptyMap(), String.class, variablesSerializer);

        Map<String,String> variables = modelProvider.getModelVariables().getOrDefault(clazz, new HashMap<>());
        
        for(Map.Entry<String,String> entry : variables.entrySet()){
            request.putVariable(entry.getKey(), entry.getValue());
        }



```

**Comment by jamesonwilliams** [comment]
Hey @richardissuperman -- what's the motivation for this change? If you could pass variables to the DataStore subscription, what would that achieve? What's the use case?

**Comment by richardissuperman** [comment]
Hi @jamesonwilliams , for certain types of Model classes, we want to subscribe/sync to the updates of it with certain IDs. For example customer A create a model with ID "abc" , and we want customer A only receive updates of the model with ID "abc" only.

**Comment by jamesonwilliams** [comment]
Hey @richardissuperman -- got it!

For DataStore, this would lead to _considerable_ complexity. The design of the system is to synchronize all states of a type of model. We need to consider model relationships. If a different type of model later tries to make reference to one that has not been sync'd, that would prevent it from being stored.

In short, I do not think we should change the DataStore's sync engine to accomodate this request.

_However_, we did have a feature request for the API category, to filter on subscriptions.

If we had that, you could perform a filter on an API subscription, and perhaps achieve the result you're looking for.

https://github.com/aws-amplify/amplify-android/issues/580

If that will meet your needs, can you 👍 #580?

**Comment by richardissuperman** [comment]
@jamesonwilliams yeah i think its mostly the same request as #580 , i understand probably there are some limitation on DataStore, which makes sense. 
But using a RxJava filter operator doesn't sound right to me as it means that the websocket Amplify setup will still keep receiving those subscription right? Won't that consume more data for one customer/device ?
Is there any reason that the ```putVariables()``` doesnt work for the GraphQLRequest class ? I noticed that the variables will be attached already to the bottom of the document inside GraphQLRequest instance。

Or the worst case, is there any we we can hack the GraphQLRequest instance or its document to subscribe with arguments?

**Comment by richardissuperman** [comment]
@jamesonwilliams 
after some deep dive i found the only difference on building the GraphQL document with Amplify and AppSyncClient is that Amplify's document doesnt include customised argument inside the query string:

<img width="604" alt="Screen Shot 2020-07-02 at 3 32 57 PM" src="https://user-images.githubusercontent.com/5363585/86415156-076ffb00-bc7b-11ea-8cdd-896e143047c2.png">

I guess it would be an easy feature request to add them into the document in : https://github.com/aws-amplify/amplify-android/blob/main/aws-api/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequestFactory.java#L343 ?
