### ISSUE TITLE
Amplify.signInWithWebUI not prompting login page for new user after calling Amplify.signOut

### ISSUE THREAD

**Issue by Flori1428** [aws-amplify/amplify-android#634]
**Describe the bug**
The first time I call `Amplify.signInWithWebUI`, the login screen shows up.

However, it doesn't show up again if I call sign-out, and then call sign-in for a second time, to prepare for a new user.

**Steps to reproduce the behavior:**
1. Call `Amplify.signInWithWebUI`.
2. Enter user credentials (login succeeds, and navigates back to the app).
3. Call `Amplify.signOut` (The callback is retrieved)
```java
Amplify.Auth.signOut(
    () -> Log.d("AuthQuickstart", "signedout"),
    error -> Log.d("AuthQuickstart", error.toString())
);
```
4. Call `Amplify.signInWithWebUI`. This time, the user will _not_ be prompted with a login screen, but instead retrieves the callback with `isSignInComplete=true`.

**Expected behavior**
1. Call` Amplify.signInWithWebUI`
2. Enter user credentials (login succeeds, navigates back to the app)
3. Call `Amplify.signOut` (callback retrieved)
4. Call `Amplify.signInWithWebUI`
5. User will be prompted with login screen

**Note** - Also tried doing a **global sign-out**, i.e.:

```java
Amplify.Auth.signOut(
    AuthSignOutOptions.builder().globalSignOut(true).build(),
    () -> Log.i("AuthQuickstart", "Signed out globally"),
    error -> Log.e("AuthQuickstart", error.toString())
);
```

**but this produces an error**:
> getTokens does not support retrieving tokens while signed-out

**Additional context**
While calling `Amplify.signInWithWebUI`, user is not prompted with login screen but result is retrieved indicating **isSignInComplete=true**. But after that, if a call is made to:

```java
Amplify.Auth.fetchAuthSession(
    result -> Log.i("AmplifyQuickstart", result.toString()),
    error -> Log.e("AmplifyQuickstart", error.toString())
);
```

I see `isSignedIn=false`. If it returned true for `isSignInComplete` in the first step, then why it is returning false while retrieving tokens?

See below for full response from both the calls.

** Amplify.signInWithWebUI response**

```console
AuthSignInResult {
  isSignInComplete = true, nextStep = AuthNextSignInStep {
    signInStep = DONE, additionalInfo = {
      provider = cognito - idp.us - east - 2. amazonaws.com / us - east - 2 _jxxxxxxxx,
      token = <token value>
    }, codeDeliveryDetails = null
  }
}
```

** Amplify.Auth.fetchAuthSession response **
```console
AWSCognitoAuthSession {
  isSignedIn = false, awsCredentials = AuthSessionResult {
    value = null, error = AmplifyException {
      message = You are currently signed out., cause = null, recoverySuggestion = Please sign in and reattempt the operation.
    }, type = FAILURE
  }, userSub = 'AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId = 'AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', userPoolTokens = 'AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'
}
```

**Comment by janejjshen** [comment]
This one uses the same backend as mentioned in https://github.com/aws-amplify/amplify-ios/issues/630#issuecomment-656662644... not sure if issue is specific to signing out for a federated sign in.

**Comment by jamesonwilliams** [comment]
Hi @janejjshen, do you mind cleaning up the formatting a bit? https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by TrekSoft** [comment]
Hey, sorry about this - it is a bug with the current sign out which we have addressed in #570 and will be out in the next release shortly.

**Comment by TrekSoft** [comment]
Just released the fix to this so if you update to v1.1.0 it should resolve it!

**Comment by Flori1428** [comment]
I updated my sdk to 
```    implementation 'com.amplifyframework:core:1.1.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.0.0' 
```
my login logout working fine.But  my issue is still there **" User in not prompted with login screen after log out ,instead user will be logged in  automatically using old username and password (happening bcoz of cookies) every-time we have to wipe the cookies to get login screen."**

**Comment by TrekSoft** [comment]
Could you post your relevant code snippets?

**Comment by jamesonwilliams** [comment]
> I updated my SDK to
> 
> ```groovy
>  implementation 'com.amplifyframework:core:1.1.0'
>  implementation 'com.amplifyframework:aws-auth-cognito:1.0.0' 
> ```

It looks like you updated `core`, but not `aws-auth-cognito`? David's fix is in 1.1.0 of the auth lib, not of the core lib.

Let us know, either way. Please re-open if this is still an issue with 1.1.x.

**Comment by akshayshankarek** [comment]
After signing out using Amplify.Auth.signout() , I got success callback but when I try to signIn again with Amplify.Auth.signInWithWebUI() it gets automatically signed in with previous user without prompting login screen.
Also when I tried to sign out I got an error log saying "CustomTabsManagerActivity was created with a null state. This should never happen. Please file an issue with us on GitHub" 
But after signing out , if I open and close the chrome app and try to sign in again then the login page gets prompted.

**Comment by rohitmahajan-ap** [comment]
I have same issue with  implementation "com.amplifyframework:aws-auth-cognito:1.37.5" version
