### ISSUE TITLE
Issue with delete Mutation in Datastore

### ISSUE THREAD

**Issue by parthsoni42** [aws-amplify/amplify-android#637]
Hello Team,

We are following the [DataStore documentation](https://docs.amplify.aws/lib/datastore/data-access/q/platform/android#delete-data), but are encountering an error when we calling the DataStore's `delete(...)` method:

> AmplifyException {message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}

Thanks

**Comment by TrekSoft** [comment]
Hi, we need a lot more information in order to troubleshoot this. Could you provide the steps to reproduce this and the specific code snippet you're calling that results in this error?

**Comment by parthsoni42** [comment]
> Hi, we need a lot more information in order to troubleshoot this. Could you provide the steps to reproduce this and the specific code snippet you're calling that results in this error?

Hello @TrekSoft 

we are using following snippet for delete mutation. please check

Amplify.DataStore.query(UsersAndOrgs.class,UsersAndOrgs.ID.eq("84db64dc-8b2b-4734-9574-a77ecc5ce902"),
matches -> {
if (matches.hasNext()) {
UsersAndOrgs post = matches.next();
Amplify.DataStore.delete(post,
deleted -> Log.i("MyAmplifyApp", "Deleted a post."),
failure -> Log.e("MyAmplifyApp", "Delete failed.", failure)
);
}
},
failure -> Log.e("MyAmplifyApp", "Query failed.", failure)
);

**Comment by TrekSoft** [comment]
Have you tried logging out the post object before calling delete to make sure it's what you expect it is?

**Comment by richardmcclellan** [comment]
@parthsoni42 I'm not sure why you are getting that error, but you can probably simplify your code to avoid doing a `query`, and just call `delete` like this:

```
Amplify.DataStore.delete(UsersAndOrgs.justId("84db64dc-8b2b-4734-9574-a77ecc5ce902"),
        deleted -> Log.i("MyAmplifyApp", "Deleted a post."),
        failure -> Log.e("MyAmplifyApp", "Delete failed.", failure)
);
```

**Comment by jpignata** [comment]
@parthsoni42 Can you let us know if that object exists and if this is a delete bug? Thanks!
