### ISSUE TITLE
Issue with Amplify.Auth.fetchAuthSession, FAILURE occures

### ISSUE THREAD

**Issue by karmaobserver** [aws-amplify/amplify-android#645]
Hello,

I am using the new Amplify Framework. I can successfully initialize the SDK, sign in a user and then fetch the user's auth session. I can extract their token ID, and set it as the bearer for calls to server side. Amplify refreshes my token id few times.

But after a few hours, when the token ID expires and I try to get new one with `Amplify.Auth.fetchAuthSession`, I get this error:

> AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}"

I do not understand why this occurs, since our refresh token is set for a very long time (more then one year). As I understand, the SDK should always automatically refresh my token ID when it expires, by calling `fetchAuthSession(...)`. The _current_ behavior forces the user to sign in again, which I need to avoid.

Some additional notes:

1. We use 3 applications on the same device, with the same user pool id.
2. At one point, we have a scenario where our backend does a global sign-out on that user pool. The backend sends an Android push notification. When the client receives it, it will delete everything from device and then re-authenticate the user with same username and password, and re-fetch the token via `fetchAuthSession(...)`.

**Comment by karmaobserver** [comment]
As additional notes. We use 3 applications on same device with same user pood id. At one point, we have case that our backend do globalSignout on that user pool and send Android push notification where we delete everything from device and then again authetificate user with same username and password at some user interaction and then fetchAuthSession to get token.

**Comment by karmaobserver** [comment]
Hello guys,

Can I get any help with this one what could be the problem?

**Comment by rjuliano** [comment]
Is there any evidence at all that the backend global sign out process you mentioned took place? If that happened, the [Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-identity-user-pools-revoking-all-tokens-for-user) state that it would certainly invalidate any refresh tokens

**Comment by meenakshi-bharduwaj** [comment]
Hello,

I am using the Amplify Framework. I can successfully initialize the SDK, sign in a user and then fetch the user's auth session. I can extract their token ID, and set it as the bearer for calls to server side. Amplify refreshes my token id few times.

But after a few hours, when the token ID expires and I try to get new one with Amplify.Auth.fetchAuthSession, I get this error:

AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}"

**Comment by MohsinJamadar09** [comment]
Hi @meenakshi-bharduwaj ,
I am facing the same issue.

would you like to share if this issue resolved? or any workaround for this

@rjuliano @karmaobserver
