### ISSUE TITLE
Request for Auth.getPreferredMFA(...) for JavaScript parity

### ISSUE THREAD

**Issue by saravhari** [aws-amplify/amplify-android#671]
AWS Cognito Android SDK "GET MFA API" (getUserMfaSettingsInBackground) needed from CognitoUserPool class

**Need to get the current user MFA setting as an API**

In Amplify JavaScript library this get method is available.

![image](https://user-images.githubusercontent.com/16345716/87518578-1359b500-c69e-11ea-94ef-7efc34079a55.png)

But in Android sdk only option available is "setUserMfaSettingsInBackground".

```java
public void setUserMfaSettingsInBackground(final List<CognitoMfaSettings> mfaSettings,
                                            final GenericHandler callback) {
        if (callback == null) {
            throw new CognitoParameterInvalidException("callback is null");
        }
        final CognitoUserSession session = this.getCachedSession();

        new Thread(new Runnable() {
            @Override
            public void run() {
                final Handler handler = new Handler(context.getMainLooper());
                Runnable returnCallback;
                try {
                    setUserMfaSettingsInternal(mfaSettings, session);
                    returnCallback = new Runnable() {
                        @Override
                        public void run() {
                            callback.onSuccess();
                        }
                    };
                } catch (final Exception e) {
                    returnCallback = new Runnable() {
                        @Override
                        public void run() {
                            callback.onFailure(e);
                        }
                    };
                }
                handler.post(returnCallback);
            }
        }).start();
    }
```

We want to perform the SMS_MFA enable and disable provision in mobile as well as web app. I'm able to update the preferred MFA type in web and can able to get the current state on load. Same thing need to be done on android, While landing to a screen initially I need to check the current Preferred MFA type and then I will update the type.

Kindly help on this to get the get API in android SDK.

**Comment by tylerjroach** [comment]
https://docs.amplify.aws/lib/auth/mfa/q/platform/android/#fetch-the-current-users-mfa-preferences

Amplify Android v2 now has the capability to fetch current MFA preferences, in addition to updating preferences!
