### ISSUE TITLE
Allow custom queryField in Amplify DataStore or API

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#674]
It will be extremely useful to be able to allow Amplify take in custom query Field.  This way one can tailor the query to get the required data in the right filter. At the moment all the sorting is done on the Android side which could be very time consuming.

```graphql
type HealthCentreConsultant @model @searchable
@key(fields:["consultantID", "longitude", "latitude", "id"])
@key(name: "byConsultantByLongitudeByLatitude", fields: ["consultantID", "longitude", "latitude"], queryField: "consultantByLongitudeByLatitude")
@key(name: "byHealthCentreByConsultant", fields:["healthCentreID", "consultantID"], queryField: "healthCentreByConsultant")
@key(name: "byConsultantBySearch", fields: ["consultantID", "search"], queryField: "consultantBySearch")
@key(name: "byConsultantByLongitudeByLatitudeBySearch", fields: ["consultantID", "longitude", "latitude", "search"], queryField: "consultantByLongitudeByLatitudeBySearch")
```

**Comment by jamesonwilliams** [comment]
Hi @KayIlory, the API category does support a custom query field. Please see [the Fetching Data section of the AP (GraphQL) docs](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/android#list-items).

In the example, `Todo.NAME.contains("first")` is a "query predicate". There is some additional information around forming query predicates [in the DataStore Guide](https://docs.amplify.aws/lib/datastore/data-access/q/platform/android#predicates). (Both API and DataStore use query predicates.)

**Comment by KayIlory** [comment]
@jamesonwilliams  - this above mentioned doesnt return the data if one uses a different sort key with the custom queryField.
For example if I wanted this sort
@key(name: "byConsultantBySearch", fields: ["consultantID", "name"], queryField: "consultantBySearch")
I wont be able to get it with the above mentioned above.

The different keys allows for different sorts.

Does this

**Comment by KayIlory** [comment]
I could not find anywhere that one could utilise different keys with different sorts when querying the data from Amplify. @jamesonwilliams  keen on any direction with regards to that

**Comment by eeatonaws** [comment]
The release of [GraphQL Transformer v2](https://docs.amplify.aws/cli/migration/transformer-migration/) and [custom primary key support](https://docs.amplify.aws/lib/datastore/advanced-workflows/q/platform/android/#customize-primary-keys) as well as support for [sort keys](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key) should enable your use case. Please let us know if you have any additional questions.
