### ISSUE TITLE
RFC: Align Android Storage APIs to iOS

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-android#679]
- [Current Gaps](#current-gaps)
- [Proposed Changes](#proposed-changes)
  * [Add new `uploadFile` and `downloadFile` overloads to Android.](#add-new--uploadfile--and--downloadfile--overloads-to-android)
  * [Add new `uploadData` and `downloadData` methods to Android.](#add-new--uploaddata--and--downloaddata--methods-to-android)
- [Side-by-side comparison](#side-by-side-comparison)
  * [Get URL of a remote resource ✅](#get-url-of-a-remote-resource--)
  * [Download `Data` from a remote resource ❌](#download--data--from-a-remote-resource--)
  * [Download remote resource into local `File` ❌](#download-remote-resource-into-local--file---)
  * [Upload `Data` to a remote resource ❌](#upload--data--to-a-remote-resource--)
  * [Upload `File` to remote resource ❌](#upload--file--to-remote-resource--)
  * [Remove a remote resource ✅](#remove-a-remote-resource--)
  * [List remote resources ✅](#list-remote-resources--)

## Current Gaps

Currently, there are two functional gaps between the [iOS Storage APIs](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L11) and the [Android Storage APIs](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L43):

1. Android’s [`uploadFile(...)`](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L118-L153) and [`downloadFile(...)`](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L79-L116) do not include a facility to listen for progress updates. This gap is noted in https://github.com/aws-amplify/amplify-android/issues/646.
2. Android does not include equivalents of iOS's [`uploadData(...)`](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L51-L64) or [`downloadData(...)`](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L23-L34) APIs. However, would accept a `byte[]` as data. These APIs should also include progress callbacks. Note: there is also https://github.com/aws-amplify/amplify-android/issues/469, which requests support for `InputStream` or `FileDescriptor` as an input type.

### Add new `uploadFile` and `downloadFile` overloads to Android.
These overloads include an additional `Consumer<StorageTransferProgress>` argument.
```java
@NonNull StorageUploadFileOperation<?> uploadFile(
    @NonNull String key,
    @NonNull File local,
    @NonNull StorageUploadFileOptions options,
    @NonNull Consumer<StorageTransferProgress> onProgress, // nota bien
    @NonNull Consumer<StorageUploadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
```java
@NonNull StorageDownloadFileOperation<?> downloadFile(
    @NonNull String key,
    @NonNull File local,
    @NonNull StorageDownloadFileOptions options,
    @NonNull Consumer<StorageTransferProgress> onProgress, // nota bien
    @NonNull Consumer<StorageDownloadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```

The `StorageTransferProgress` is an immutable state bundle:
```java
public final class StorageTransferProgress {
    private final long currentBytes;
    private final long totalBytes;

    public StorageTransferProgress(long currentBytes, long totalBytes) {
        this.currentBytes = currentBytes;
        this.totalBytes = totalBytes;
    }
   
    public long getCurrentBytes() {
        return currentBytes;
    }
 
    public long getTotalBytes() {
        return totalBytes;
    }

    public double getFractionCompleted() {
        return ((double) currentBytes) / totalBytes));
    }

    // equals(), hashCode(), toString()
}
```
### Add new `uploadData` and `downloadData` methods to Android.
These methods use an `byte[]` instead of a `File` as the local data type. These methods also do include a `Consumer<StorageTransferProgress>`, for tracking progress.

```java
@NonNull StorageUploadDataOperation<?> uploadData(
    @NonNull String key,
    @NonNull byte[] local, // nota bien
    @NonNull StorageUploadFileOptions options,
    @NonNull Consumer<StorageTransferProgress> onProgress,
    @NonNull Consumer<StorageUploadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
```java
@NonNull StorageDownloadDataOperation<?> downloadData(
    @NonNull String key,
    @NonNull byte[] local, // nota bien
    @NonNull StorageDownloadFileOptions options,
    @NonNull Consumer<StorageTransferProgress> onProgress,
    @NonNull Consumer<StorageDownloadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
## Side-by-side comparison

Capabilities below are marked with ✅ if they have cross-platform behavior parity, and ❌ if not.

### Get URL of a remote resource ✅
Ref: [Android](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L45-L77), [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L12-L21).

```swift
func getURL(
    key: String,
    options: StorageGetURLOperation.Request.Options?,
    resultListener: StorageGetURLOperation.ResultListener?
) -> StorageGetURLOperation
```
```java
@NonNull StorageGetUrlOperation<?> getUrl(
    @NonNull String key,
    @NonNull Consumer<StorageGetUrlResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
    
@NonNull StorageGetUrlOperation<?> getUrl(
    @NonNull String key,
    @NonNull StorageGetUrlOptions options,
    @NonNull Consumer<StorageGetUrlResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
### Download `Data` from a remote resource ❌
Ref: [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L23-L34).

```swift
func downloadData(
    key: String,
    options: StorageDownloadDataOperation.Request.Options?,
    progressListener: ProgressListener?,
    resultListener: StorageDownloadDataOperation.ResultListener?
) -> StorageDownloadDataOperation
```
**Note: Android has not equivalent API, currently.**

### Download remote resource into local `File` ❌
Ref: [Android](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L79-L116), [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L36-L49).

```swift
func downloadFile(
    key: String,
    local: URL,
    options: StorageDownloadFileOperation.Request.Options?,
    progressListener: ProgressListener?,
    resultListener: StorageDownloadFileOperation.ResultListener?
) -> StorageDownloadFileOperation
```
```java
@NonNull StorageDownloadFileOperation<?> downloadFile(
    @NonNull String key,
    @NonNull File local,
    @NonNull Consumer<StorageDownloadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);

@NonNull StorageDownloadFileOperation<?> downloadFile(
    @NonNull String key,
    @NonNull File local,
    @NonNull StorageDownloadFileOptions options,
    @NonNull Consumer<StorageDownloadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
### Upload `Data` to a remote resource ❌
Ref: [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L51-L64).

```swift
func uploadData(
    key: String,
    data: Data,
    options: StorageUploadDataOperation.Request.Options?,
    progressListener: ProgressListener?,
    resultListener: StorageUploadDataOperation.ResultListener?
) -> StorageUploadDataOperation
```
**Note: Android has no equivalent API, right now.**

### Upload `File` to remote resource ❌
Ref: [Android](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L118-L153), [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L66-L79).

```swift
func uploadFile(
    key: String,
    local: URL,
    options: StorageUploadFileOperation.Request.Options?,
    progressListener: ProgressListener?,
    resultListener: StorageUploadFileOperation.ResultListener?
) -> StorageUploadFileOperation
```
```java
@NonNull StorageUploadFileOperation<?> uploadFile(
    @NonNull String key,
    @NonNull File local,
    @NonNull Consumer<StorageUploadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);

@NonNull StorageUploadFileOperation<?> uploadFile(
    @NonNull String key,
    @NonNull File local,
    @NonNull StorageUploadFileOptions options,
    @NonNull Consumer<StorageUploadFileResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
### Remove a remote resource ✅ 
Ref: [Android](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L155-L184), [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L81-L90).

```swift
func remove(
    key: String,
    options: StorageRemoveOperation.Request.Options?,
    resultListener: StorageRemoveOperation.ResultListener?
) -> StorageRemoveOperation
```
```java
@NonNull StorageRemoveOperation<?> remove(
    @NonNull String key,
    @NonNull Consumer<StorageRemoveResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);

@NonNull StorageRemoveOperation<?> remove(
    @NonNull String key,
    @NonNull StorageRemoveOptions options,
    @NonNull Consumer<StorageRemoveResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```
### List remote resources ✅ 
Ref: [Android](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/storage/StorageCategoryBehavior.java#L186-L218), [iOS](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategoryBehavior.swift#L92-L99).

```swift
func list(
    options: StorageListOperation.Request.Options?,
    resultListener: StorageListOperation.ResultListener?
) -> StorageListOperation
```
```java
@NonNull StorageListOperation<?> list(
    @NonNull String path,
    @NonNull Consumer<StorageListResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);

@NonNull
StorageListOperation<?> list(
    @NonNull String path,
    @NonNull StorageListOptions options,
    @NonNull Consumer<StorageListResult> onSuccess,
    @NonNull Consumer<StorageException> onError
);
```

**Comment by palpatim** [comment]
Nittiest of the nits: 

>     public int getCompletionPercent() {
>        return (int) Math.round((100f * currentBytes) / totalBytes));
>    }

Is `int` the right return type for this? 

Slightly less nitty: In some cases, a service will not provide a "totalBytes", yet it might still be useful to be notified of progress with the total number of bytes downloaded "so far". iOS doesn't have a great model for this, either, but I believe it does protect against divide by zero errors in cases where we don't supply a non-zero denominator.

Other than that bikeshedding, I think the proposal makes sense. Using a stream rather than a `Data` type is reasonable and platform-friendly. I haven't spent enough time on Android to know whether raw byte arrays are in common use on the platform, but I've spent enough time to know that InputStreams are pretty common. That pattern will arguably match better with some hypothetical streaming API than any of the existing iOS patterns.

**Comment by rjuliano** [comment]
Overall it looks good to me. Using the stream should afford developers the necessary flexibility to handle the upload of data without having to rely on local storage. 

The only tricky scenario I can think of would be the use of unbounded input streams for example. I may be overthinking this, but do you think we need to account for that at all? Perhaps it's a detail we dive into during implementation.

As far as achieving parity with iOS, I think this is good to go.

**Comment by jamesonwilliams** [comment]
@rjuliano & @palpatim Thanks for the inputs! I agree, the `totalBytes` may not be available, and so `getCompletionPercent()` could return `NaN`.

@palpatim - instead of `int`, what return type did you have in mind for `totalBytes`?

The `InputStream` is a good idea, but it is not actually achieving _parity_, it is more like a new feature. I updated item (2) to add a `byte[]` input for `uploadData` and `downloadData`.

**Comment by jamesonwilliams** [comment]
iOS uses "Guest" as a permission class, as opposed to the word "Public." "Public" sounds like a writable bucket, but that's not what it is. JavaScript and Android should align naming to use "Guest."

**Comment by jamesonwilliams** [comment]
iOS uses "Guest" as a permission class, as opposed to the word "Public." "Public" sounds like a writable bucket, but that's not what it is. JavaScript and Android should align naming to use "Guest."
