### ISSUE TITLE
Is there a plan to stop supporting aws-sdk-android?

### ISSUE THREAD

**Issue by wcenGitHub** [aws-amplify/amplify-android#682]
I'm working on a project (Android side) and our backend is using Cognito to do user authentication. My needs are

1. User authentication
2. User sign up
3. User forgot password
4. Token management (such as storing and refreshing) feature 
5. Get the access token value for other usage

I haven't found a way to access the token value through **amplify-android** library (maybe I missed it). I'm using **aws-sdk-android** in my project which suits my need completely.

I wonder if AWS has a plan to stop supporting **aws-sdk-android** and I must use **amplify-android**?

Thanks

**Comment by jamesonwilliams** [comment]
@wcenGitHub We are recommending that new code be developed with the Amplify Android library.

Please see the section of the Amplify Auth documentation around "[accessing credentials](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android)."

In particular, you can retrieve a user access token via the [`AWSCognitoAuthSession`](https://github.com/aws-amplify/amplify-android/blob/main/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthSession.java#L31) which returned by `fetchAuthSession(...)`:
```kotlin
Amplify.Auth.fetchAuthSession(
    { result ->
        val cognitoAuthSession = result as AWSCognitoAuthSession
        val accessToken = cognitoAuthSession.userPoolTokens.value.accessToken
    },
    { error -> Log.e("AuthQuickStart", error.toString()) }
)
```

Another option is to access the underlying `AWSMobileClient`, via the escape hatch of the `Amplify.Auth` category. (Ref: [Auth escape hatch documentation](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android).) Then, you can [obtain the access token from the `AWSMobileClient`]https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android#token-fetch-and-refresh). 
```kotlin
val mobileClient = Amplify.Auth.getPlugin("awsCognitoAuthPlugin").escapeHatch as AWSMobileClient?
```

Between the two approaches, the first one is recommended.

**Comment by wcenGitHub** [comment]
Thanks @jamesonwilliams , it is very helpful. I wonder is it recommended to fetchAuthSession every time we need the access token? 

Thanks
