### ISSUE TITLE
Unable to login on user created from cognito console

### ISSUE THREAD

**Issue by Uma1r** [aws-amplify/amplify-android#683]
**Describe the bug**
When a user created from Cognito console (given name and family name required attributes) logs in for the first time with the temp password, it gets `CONFIRM_SIGN_IN_WITH_NEW_PASSWORD` as next signIn step. When `confirmSignIn` is done based on this, it returns the error that Missing required attribute.

**Steps to reproduce the behavior:**
1. Call `Amplify.Auth.signIn(...)` on a newly created user from Cognito console
2. Result will return `CONFIRM_SIGN_IN_WITH_NEW_PASSWORD`
3. Call `Amplify.Auth.confirmSignIn(...)`
4. Result will be an error:
> AmplifyException {message=Confirm sign in failed, cause=com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoParameterInvalidException: Missing required attribute: family_name, recoverySuggestion=See attached exception for more details}

How can I set new password and pass in the required attributes when a user (created from Cognito console) logs in for the first time? The  `Amplify.Auth.confirmSignIn(...)` method signature doesn't provide an option to do this and there isn't an alternative to this as well

**Comment by Uma1r** [comment]
Any info on this?

Amplify Auth doesn't seem to support passing user attributes in `confirmSignIn`, the method signature only takes in the confirmation code. 

```
@Override
    public void confirmSignIn(
            @NonNull String confirmationCode,
            @NonNull Consumer<AuthSignInResult> onSuccess,
            @NonNull Consumer<AuthException> onError
    ) {
        getSelectedPlugin().confirmSignIn(confirmationCode, onSuccess, onError);
}
```

I think the method should provide the ability to send in user attributes as well since a user created from Cognito console will be unable to sign in (or do anything for that matter) because the user will not be confirmed unless required user attributes are provided in `confirmSignIn`.

**Comment by jpignata** [comment]
@rjuliano Do we have work to surface [this fix](https://github.com/aws-amplify/aws-sdk-android/issues/1403) in Amplify?

**Comment by rjuliano** [comment]
@jpignata Looks like that's the case. We'll have to add a corresponding overloaded version of the `confirmSignIn` API that takes in a map of parameters.

**Comment by AntoEko** [comment]
Is there any workaround in meantime ?

**Comment by rjuliano** [comment]
A potential workaround would be to use the the `confirmSignIn` API via the escape hatch. The code would probably look something like this:

```java
AWSMobileClient mobileClient = (AWSMobileClient) Amplify.Auth.getPlugin("awsCognitoAuthPlugin").getEscapeHatch();
HashMap<String, String> inputAttributes = new HashMap<String, String>();
//Add attribute to set new password
inputAttributes.put(CHALLENGE_RESPONSE_NEW_PASSWORD_KEY, "<new password>");
//Set some extra attributes
inputAttributes.put(CHALLENGE_RESPONSE_USER_ATTRIBUTES_PREFIX_KEY + "name", "dummy-name");
inputAttributes.put(CHALLENGE_RESPONSE_USER_ATTRIBUTES_PREFIX_KEY + "nickname", "dummy-nickname");

//Confirm sign-in using the challenge response + attributes
SignInResult signInResultAfterConfirm = mobileClient.confirmSignIn(inputAttributes);
```

**Comment by richardmcclellan** [comment]
Resolved by https://github.com/aws-amplify/amplify-android/pull/1343
