### ISSUE TITLE
Amplify.Auth.signUp returns 'isSignUpComplete = true' when signUpStep is 'CONFIRM_SIGN_UP_STEP'

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-android#686]
When calling `Amplify.Auth.signUp(...)`, the response includes a `nextStep.signUpStep` value of `CONFIRM_SIGN_UP_STEP`, while at the same time an `isSignUpComplete` value of `true`.  

My expectation is that the `isSignUpComplete` value should only be `true` if `signUpStep` is `DONE`.

![image](https://user-images.githubusercontent.com/10621276/88990425-c7f4f880-d292-11ea-9518-fa7c635f00ba.png)

This code is being called from the Android platform code of a Flutter plugin, but I do not expect that this would make a difference.

**Comment by TrekSoft** [comment]
Hey, this is intended behavior. You are successfully signed up at this point - it's just that there is an additional step you can take of confirming your account which is needed to sign in.

**Comment by palpatim** [comment]
> Hey, this is intended behavior. You are successfully signed up at this point - it's just that there is an additional step you can take of confirming your account which is needed to sign in.

This is exactly the opposite of my recollection: I thought we interpreted that flag as a convenience to mean "there are no remaining steps." In our discussions, we even talked about implementing it in iOS as a computed property returning the results of `nextStep == .done`. The semantic meaning was "the flow is done; my expectation of a successful 'sign up' is that a user can now sign in."

**Comment by TrekSoft** [comment]
From what I remember, the reason we digressed from no next step equaling done in this case is that you are indeed completely signed up after the success callback comes back. If you got "isSignedUp = false" and then tried to sign up again, it would give you an error, "User is already signed up" which is contradictory.

The fact that there are additional next steps you can take (not necessary for completing sign up but necessary for being able to sign in) doesn't change the fact that you are signed up at that point.

**Comment by andreimcristof** [comment]
got this as well. went through the amplify tutorial for flutter, but used the latest amplify version, so it enterd this issue. It works with: 

```
if (result.isSignUpComplete) {
        if (result.nextStep is AuthNextSignUpStep) {
          //enter verify flow
        }
        // signup was ok. do login
        loginWithCredentials(credentials);
      }
```

**Comment by royjit** [comment]
Re-opening the issue, as per discussion we decided to fix this in Android. Since this is a breaking change, we might add this in the next major version update. Here are the different scenarios:

```

// SignUp needs to confirm using SMS
nextStep -> .confirmUser(SMS)
isSignupComplete -> false 

// SignUp needs to confirm, but not email/SMS provided
nextStep -> .confirmUser(nil)
isSignupComplete -> false 

// SignUp confirmed
nextStep -> .done
isSignupComplete -> false 

```

**Comment by gpanshu** [comment]
Hello @haverchuck we have addressed and fixed this in the V2 version of Amplify library for Android. If upgrading is an option for you please try that out.
