### ISSUE TITLE
Amplify.Storage.uploadFile corrupt video files

### ISSUE THREAD

**Issue by aguigon** [aws-amplify/amplify-android#692]
Hello,

We are recording videos with the Android camera and trying to upload those videos to S3 with:

```kotlin
suspend fun upload(key: String, file: File, accessLevel: StorageAccessLevel) =
    suspendCancellableCoroutine<StorageUploadFileResult> { cont ->
        val options = StorageUploadFileOptions.builder()
            .accessLevel(accessLevel)
            .build()
        Amplify.Storage.uploadFile(key, file, options,
            { result -> cont.resume(result) },
            { error -> cont.cancel(error) }
        )
    }
```

Our app will have multiple recorded files/uploads. Files are stored locally and are not sent concurrently.

It appears that randomly some uploads are corrupted. The size of the file uploaded to S3 seems coherent, but the content is corrupted and unreadable by MediaConvert for encoding purpose, but by "standard" players too. Apparently when we try to read the locally stored file everything is good.

We are working with little files for now (~5-20 Mb).

We have exactly the same issue with the iOS implementation (`amplify-ios`).

**Comment by jamesonwilliams** [comment]
@aguigon Can you verify the file size before and after the upload, as well as the MIME type and other metadata that is being set on the S3 object?

**Comment by aguigon** [comment]
Hi @jamesonwilliams I'll try to ask for it to my developpers.
For the Content-Type it comes as: "application/octet-stream" on S3. There are no other metadata.
