### ISSUE TITLE
SQL commands fail if models have words that correspond to sqlite reserved words

### ISSUE THREAD

**Issue by saltonmassally** [aws-amplify/amplify-android#707]
### Describe the bug

 Datastore SQL commands fail if your model has SQLite reserved words in them. take for example this create table query generated by the library:

```
CREATE TABLE IF NOT EXISTS Request (
  id TEXT PRIMARY KEY NOT NULL,
  state TEXT NOT NULL,
  groupId TEXT,
  FOREIGN KEY (groupId) REFERENCES Group(id) ON DELETE CASCADE,
);
```

or

```
CREATE TABLE IF NOT EXISTS Group (
  id TEXT PRIMARY KEY NOT NULL,
);
```

Both will fail because of the presence of `Group` which is a reserved word.

### Expected behavior
Model names and fields should be quoted

**Comment by raphkim** [comment]
Hi @saltonmassally ,

Thank you for reporting this issue. We will add this item to the backlog and provide an update here when a fix is implemented.
