### ISSUE TITLE
Cannot query based on AWSDateTime

### ISSUE THREAD

**Issue by btdo** [aws-amplify/amplify-android#723]
Hello, I'm trying to query for data that was updated after a certain time using the updatedAt attribute with "AWSDateTime" type in GraphQL API.  Here's my schema. 
```
 type TrackSyncItem @model {
    id: ID!
    trackId: String!
    userDescription: String
    type: TrackItemType
    source: TrackItemSource
    owner: String
    deleted: Boolean
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
    ttl: Int
} 
```
Here's my code 
```
val lastUpdatedItem = Temporal.DateTime(Date(), 0)
val queryPredicate = TrackSyncItem.UPDATED_AT.gt(lastUpdatedItem)
Amplify.API.query(
                ModelQuery.list(TrackSyncItem::class.java, queryPredicate),
                { response -> ...},{...}) 
```
Currently, I get a compile error on the query predicate saying  
```
Type parameter bound for T in 

fun <T : Comparable<T!>!> gt
(
value: T!
)
: QueryPredicateOperation<T!>!
is not satisfied: inferred type Temporal.DateTime! is not a subtype of Comparable<Temporal.DateTime!>!
```

**Comment by saltonmassally** [comment]
@btdo I believe this [commit](https://github.com/aws-amplify/amplify-android/commit/f1d8417880f7f59b1e42f5771a9197d4b6df3f87) should fix that for you.

**Comment by richardmcclellan** [comment]
Resolved by https://github.com/aws-amplify/amplify-android/pull/721.   This will be available after the next Amplify release.

**Comment by btdo** [comment]
hi @richardmcclellan , Yes I can pass the query predicate now.  However, when I running the query with the updated_at predicate, it still returns me all the records that were modified before the lastUpdatedTime

**Comment by btdo** [comment]
Actually @richardmcclellan , sorry, the filtering query works now.  Although, i've noticed that it seems to pull the entire result set and then filter out based on the predicate on the app. This makes it very slow.
