### ISSUE TITLE
Todo example fails sync with Validation error of type FieldUndefined: Field 'syncTodos' in type 'Query' 

### ISSUE THREAD

**Issue by Diederikjh** [aws-amplify/amplify-android#725]
I am getting a sync error when using a new amplify project using the Todo example schema.

I ran 

1. `amplify init`
2. `amplify add api` (Choosing example schema)
3. `amplify push`
4. `amplify pull` (Did this just to be sure publish didn't change anything that I might need. Getting same results.

My app's code is adding a new Todo. This seems to work locally, when looking at the `AmplifyDatastore.db` file.

Answers to the prompts on `push` was:
```
? Do you want to generate code for your newly created GraphQL API Yes
? Enter the file name pattern of graphql queries, mutations and subscriptions app/src/main/graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
```

When the app is online (and I have initialized Amplify) I get below error logs.

```
amplify:aws-datastore: Failed to sync down cloud state for model type = Todo
    AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'syncTodos' in type 'Query' is undefined @ 'syncTodos'', locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:107)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

The one thing that I did do that might have confused things is in the same project folder I had a completely different API connected.  Before I did above steps I delete the `/amplify` folder, and ensure `amplify status` returned 

> You are not working inside a valid Amplify project.

I also had to remove the old GraphQL endpoint from the `amplifyconfiguration.json` file.

**Comment by richardmcclellan** [comment]
Here's the important part of the error: `Field 'syncTodos' in type 'Query' is undefined`.

I believe this is because you don't have conflict resolution on your AppSync API, which needs to be *enabled* to using the DataStore category.    It should be *disabled* if you are using the API category.   To enable it, run `amplify update api`, choose "GraphQL", then choose "Enable DataStore for entire API", then run `amplify push`

I'm leaving this issue open as an improvement opportunity, so that we can look at making the error message more helpful, as this issue has been raised several times now.

**Comment by Diederikjh** [comment]
OK thanks.

I ran 

`amplify update api`

with answers

```
(re-do all configurations)  couldn't copy this one, and can't seem to bring this question back.
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Walkthrough all configurations
? Choose the default authorization type for the API API key
? Enter a description for the API key: test key
? After how many days from now the API key should expire (1-365): 7
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? No
? Configure conflict detection? Yes
? Select the default resolution strategy Auto Merge
? Do you want to override default per model settings? No
```

And and ran `amplify push` answering more things, and now it seems to work.

Another note about usability of the cli:  I find it a bit weird that I have to push things to make my local generated code work.  Thinking about it for a minute I guess there is code that needs to potentially run differently on the cloud that is affected by what `amplify update api` did.  What I'm saying is that a warning to say I need to still push before my work is complete would be nice.

**Comment by jamesonwilliams** [comment]
> What I'm saying is that a warning to say I need to still push before my work is complete would be nice.

This sounds like a worthwhile CLI improvement, thanks for the input.

**Comment by jamesonwilliams** [comment]
@aws-amplify/amplify-cli Please transfer to CLI repo
