### ISSUE TITLE
Social sign in crashes the browser without any error messages

### ISSUE THREAD

**Issue by Zablas** [aws-amplify/amplify-android#748]
I was trying to setup a Facebook login for my app. I followed this guide: https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android#amazon-cognito-user-pool-setup

However, I already had a cognito user pool setup so instead of running `amplify add auth` I ran `amplify update auth` and chose the complete walkthrough for all the options. The changes that I made were choosing Facebook as a social provider and setting up a OAuth flow. I gave my Facebook app ID and secret and added the redirect links. After that I updated my AndroidManifest.xml to look like this:

        <activity
            android:name=".LoginActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize"/>
        <activity android:name="com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="cheuwo" />
            </intent-filter>
        </activity>

LoginActivity is where the user can click the Facebook icon to run this code:

    fun facebookLogin(view: View)
    {
        Amplify.Auth.signInWithSocialWebUI(AuthProvider.facebook(), this,
            { result ->
                if(result.isSignInComplete)
                {
                    val intent = Intent(this, OfferListActivity::class.java)
                    startActivity(intent)
                    finish()
                }
            },
            { error ->
                println(error.message)
                println(error.localizedMessage)
                println(error.cause)
                println(error.recoverySuggestion)
            })
    }

And yes, I have `onActivityResult()` overloaded as shown in the guide. What happened was this: when I clicked on the icon the first time it took me to the login page where I put in my Facebook credentials. However, after signing in I was redirected back to LoginActivity. Now whenever I try to tap on the Facebook icon the browser starts loading a little bit and instantly redirects me back. Not even a complete reinstall of the app helped.

**Comment by Zablas** [comment]
Minor update. Everything seems to be setup correctly on the "Facebook developer account" side of things as I seem to be getting calls there:

![Screenshot_16](https://user-images.githubusercontent.com/22299325/91048407-4f305480-e624-11ea-8212-8ec540cc0212.jpg)

So I'm assuming there's somethings wrong with my `AndroidManifest.xml` and yet I can't figure out what.

**Comment by TrekSoft** [comment]
Hey, did you ever get log messages for the onSuccess or onError callbacks of signInWithSocialWebUI? If you're not sure, you can run the app on a new emulator and see. Also add logs to your onActivityResult method to make sure that's being called in either the case where you sign in successfully or where you exit the login flow by closing out of the window that pops up.

**Comment by Zablas** [comment]
@TrekSoft Managed to get some things logging. The request code returned is -1 and I finally got these errors:

Sign in with web UI failed
com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request

**Comment by Zablas** [comment]
I've also decided to analyze the "data" parameter in `onActivityResult()`. The uriString member of it looks like this:

cheuwo://callback/?error_description=attributes+required%3A+%5Bbirthdate%5D&state=GC1jj6x0lXHvaTooFV8L2_fMNgai6CvX2FhPArN7IJs&error=invalid_request#_=_

So it's complaining about a missing birthdate. Obviously I could just disable overall but in my app users are required to state their birthdate. How should I go around this?

**Comment by TrekSoft** [comment]
Hmm, this sounds like something on the Facebook side you would have to configure to ask the user permission for since your app is requiring that attribute.

**Comment by TrekSoft** [comment]
Yeah I think the easiest thing to do would be to remove birth date as a required attribute during sign up and instead just get it and add it to the user's record later (you could even do it immediately after sign up in the callback).

**Comment by Zablas** [comment]
@TrekSoft yeah after removing the birthdate recommendation it seems to be working. Before I close this I wanted to ask if there is a possibility in this framework to get the user's profile picture after a successful OAuth as that seems to be one of the default permissions on Facebook's side so we don't need a review for that.

**Comment by TrekSoft** [comment]
I see we have a "Picture" attribute you can select in the "What attributes are required for signing up?" step of the CLI (press the up and down arrows to scroll through the list when you get to that step) which I would assume would work for that.

**Comment by Zablas** [comment]
@TrekSoft Okay, I'll look into it. Thank You for the responsiveness!
