### ISSUE TITLE
Instances in which cognito identity defers from user login identity

### ISSUE THREAD

**Issue by saltonmassally** [aws-amplify/amplify-android#780]
`com.amplifyframework.api.aws.AWSApiPlugin#getUsername` appears to return the username used to log into device, however there are configurations for Cognito in which the user identity/username is the userSub attribute. 

An example is if user registers with a phone or email (in place of a username). Screenshots below illustrate this better 
<img width="731" alt="Screenshot 2020-09-01 at 02 36 40" src="https://user-images.githubusercontent.com/2057234/91768991-2697f400-ebfc-11ea-8186-9b482e5fc5be.png">

<img width="760" alt="Screenshot 2020-09-01 at 02 37 12" src="https://user-images.githubusercontent.com/2057234/91768983-23046d00-ebfc-11ea-8f8a-60d8de05d771.png">

Given that we use the referenced method above to build subscription requests, we are sending the phone number rather than the actual Cognito recognized username in this case.

Can we use userID rather than userName?

```
AuthUser currentUser = Amplify.Auth.getPlugin(AUTH_DEPENDENCY_PLUGIN_KEY).getCurrentUser();
return (currentUser != null) ? currentUser.getUserId() : null;
```

**Comment by TrekSoft** [comment]
Hey Salton, 

Thanks for the detailed issue and screenshot. Could you clarify what your ask is? I was following you up to the last couple sentences.

**Comment by saltonmassally** [comment]
Sorry for the ambiguity there. Given the configuration above, say I register with a phone number +122222222, Cognito uses my sub (userID)  as my username (basically the UUID in the screenshot).

However, calls to AwsMobileClient.username returns `+122222222` rather than the UUID username. This is problematic as subscriptions fail (i believe given that the username from the auth tokens does not match that passed as owner by the subscription document).

However, if I have `com.amplifyframework.api.aws.AWSApiPlugin#getUsername` call AwsMobileClient.userId (as shown in the example code snippet above), it returns the correct username in my case and subs work fine. 

I guess the question is how do we support both cases
1) where username is set by the user and is correctly returned by AwsMobileClient.userName (currently supported) 
2) where username is not set by the user and AwsMobileClient.userName rather returns the phone_number or email

**Comment by TrekSoft** [comment]
Ok gotcha - I believe we are actively working on fixing the issue with subscriptions as reported here: https://github.com/aws-amplify/amplify-android/issues/749

In general, we want the ability for users to getUsername and separately getUserId. Is there a reason beyond fixing the subscription issue you want getUsername to return the user id for phone and email?

**Comment by saltonmassally** [comment]
This is definitely a duplicate of #749, will close this in favor of that. No other reasons beyond the subscription issue. thanks David!
