### ISSUE TITLE
Amplify API and DataStore ValidationError when querying or mutating data

### ISSUE THREAD

**Issue by Scarlett13** [aws-amplify/amplify-android#781]
Hi!

I would like to ask a question regarding an error in my Amplify DataStore and GraphQL API, where there are more than one many-to-many relationships defined:

```graphql
type PersonalInfo
{
  id: ID!
  name: String!
  specialization: String!
  project: [PersonalProject] @connection(keyName: "byPerson", fields: ["id"])
}

type PersonalProject
@key(name: "byPerson", fields: ["personalId", "directorid"])
@key(name: "byProject", fields: ["departmentid", "personalId"])
{
  id: ID!
  personalId: ID
  personalInfo: PersonalInfo @connection(fields: ["personalId"])
  projectId: ID
  project: Project @connection(fields: ["projectId"])
}

type Project
{
  id: ID!
  projectName: String
  projectDeadline: String!
  person: [PersonalProject]  @connection(keyName: "byProject", fields: ["id"])
}
```

Everything was fine when I played with this in the Amplify Console. The problem arrises when I code in Android Studio and create a new `PersonalInfo` type without project. It gave me errors like:

```console
GraphQLResponse.Error
{
  message='Validation error of type FieldUndefined: Field 'projectPersonalProjectId' in type 'PersonalInfo' is undefined @ 'syncSelves/items/projectPersonalProjectId'', 
  locations='[GraphQLLocation{line='7', column='7'}]', 
  path='null', 
  extensions='null'
}
```

It happens when I try to mutate from client side both in API request or DataStore request. Please help me on this.

Thank you!

**Comment by Scarlett13** [comment]
Ive got this issue resolved by disabling the datastore for the project. But I have to work on that offline scenarios while using both services? Thanks.

**Comment by richardmcclellan** [comment]
HI @Scarlett13, apologies for the very late reply on this.

Based on your error message, `Field 'projectPersonalProjectId' in type 'PersonalInfo' is undefined @ 'syncSelves/items/projectPersonalProjectId'`, AppSync is saying that there is no `projectPersonalProjectId` field on a type named `Self`.   Can you share your entire `schema.graphql` file, including this `Self` type?

My guess is that your generated models are out of sync with your AppSync schema.  Make sure you are up to date by running `amplify push`.
