### ISSUE TITLE
Amplify.Auth UserAttributeKeys different from iOS

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-android#787]
On Android, [user attributes](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/auth/AuthUserAttributeKey.java) map exactly to cognito user attributes, while iOS's [user attributes](https://github.com/aws-amplify/amplify-ios/blob/eb5b7ff98ae9ac090dc8c71e374b8f3bcb0ee472/Amplify/Categories/Auth/Models/AuthUserAttribute.swift#L34) is missing a few, specifically `zoneinfo`, `website`, `updated_at`, `profile`.

Should iOS have these attributes for parity or are these too specific for the Amplify layer? the solution on iOS is to pass `.unknown("zoneinfo")`.
If Cognito introduces a new user attribute, is there a way to pass that attribute key name on Android?
I see there's a custom one on Android as well. On iOS cognito plugin there is [custom logic](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AuthUserAttributeKey+Extension.swift#L99) that prepends the `custom:` prefix to the passed in `.custom([value])` case so it is sent to cognito as `custom:[value]`. is this the same behavior on Android?

Related issue on iOS: https://github.com/aws-amplify/amplify-ios/issues/751
Cognito docs: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html

**Comment by raphkim** [comment]
@TrekSoft , can we have your input on this?

**Comment by TrekSoft** [comment]
None of those four attributes are specific to Cognito so I think it's worth keeping them. They could be named more clearly but given the benefit of using consistent terminology with what people expect from the past, I think it's worth keeping them named as is too. As far as what happens if Cognito introduces a new user attribute, I'm not sure, that may be worth investigating.

**Comment by raphkim** [comment]
Android currently doesn't appear to be appending any prefix to the custom attribute key. Will this disparity cause any issue? Does Cognito treat an attribute prepended with `custom:` differently than the others?

**Comment by Jordan-Nelson** [comment]
@lawmicha should this be transferred to amplify-ios?

**Comment by lawmicha** [comment]
> Android currently doesn't appear to be appending any prefix to the custom attribute key. Will this disparity cause any issue? Does Cognito treat an attribute prepended with `custom:` differently than the others?

yes this would cause an issue and cognito treats them differently: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes
custom attributes require "custom:" prefix to distinguish them from standard attributes

As @TrekSoft mentioned there is an API enum case disparity. iOS should probably add those missing cases and make sure it is an additive change to the developer's perspective

@raphkim described a plugin implementation disparity. Android should probably update plugin implementation to prepend "custom:" otherwise it wouldn't be possible to use Custom Attributes via Cognito

**Comment by lawmicha** [comment]
> @lawmicha should this be transferred to amplify-ios?

We should keep this issue to track Android's support for .custom and .unknown. 

iOS should be track adding the missing enum cases: https://github.com/aws-amplify/amplify-ios/issues/1248

Flutter should implement against the workaround using iOS's unknown case: https://github.com/aws-amplify/amplify-flutter/issues/598#issuecomment-849715738

**Comment by raphkim** [comment]
for now, the workaround would be to use `custom("custom:" + attribute)` for the custom attribute key usecase.

I imagine it will be a breaking change for the customers that are already using the method this way.

**Comment by GSala** [comment]
>For now, the workaround would be to use custom("custom:" + attribute) for the custom attribute key use-case and I suspect that there are already some customers who are doing this.

I'm going to have to do exactly that. Is there a better choice?

**Comment by div5yesh** [comment]
None as of now. Please use the workaround if that fits your use case.

**Comment by gpanshu** [comment]
If upgrading is an option for you to our V2 version of Amplify Android library I would recommend doing so as we are now using AWSCognitoAuthUpdateUserAttributesOptions.metadata where you can store your userattributes in a map. Thank you.
