### ISSUE TITLE
Bug in Generated Amplify GraphQL Object - NullPointer for DateTime Object

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#793]
The version > 1.2.0 has these errors where the Object for created Time is throwing a NullPointerException. It is confirmed the date does exist in the back end and this was working fine prior to the latest version. It seems the data conversion is having issues with the latest release.

The DEBUG steps images
![image](https://user-images.githubusercontent.com/51476926/92104193-e9d52400-edd8-11ea-953b-cc2be9577bd7.png)
![image](https://user-images.githubusercontent.com/51476926/92104289-01aca800-edd9-11ea-8329-364b6b2acd4f.png)
![image](https://user-images.githubusercontent.com/51476926/92104320-0d986a00-edd9-11ea-885d-2e468381a6e6.png)

The GraphQL
![image](https://user-images.githubusercontent.com/51476926/92104436-37ea2780-edd9-11ea-8a15-3ad9cd99e4e3.png)

The create date does exist with value
![image](https://user-images.githubusercontent.com/51476926/92104985-0cb40800-edda-11ea-814b-0f6302ef17f4.png)

Using the below AWS Date Time Formatter based on scalar acceptable types
![image](https://user-images.githubusercontent.com/51476926/92105175-5997de80-edda-11ea-8f31-970620b3b2a1.png)

**Comment by KayIlory** [comment]
Sames issues for Date as well. Object showing as 0000-00-00 for date of birth in image above as well

**Comment by KayIlory** [comment]
@richardmcclellan I made the changes to the build.gradle and error still exist.
![image](https://user-images.githubusercontent.com/51476926/92226207-48170b00-ee9c-11ea-9188-9149b8380d18.png)
![image](https://user-images.githubusercontent.com/51476926/92226260-5ebd6200-ee9c-11ea-83f9-02e3147a803b.png)

**Comment by KayIlory** [comment]
![image](https://user-images.githubusercontent.com/51476926/92226945-6df0df80-ee9d-11ea-904c-5941ccc40cd8.png)

**Comment by KayIlory** [comment]
![image](https://user-images.githubusercontent.com/51476926/92227232-e35cb000-ee9d-11ea-8388-c35a3aa7177e.png)
![image](https://user-images.githubusercontent.com/51476926/92227297-fa030700-ee9d-11ea-8c7e-a39bf1c071f1.png)

**Comment by KayIlory** [comment]
I found out this issue exist if the objects when received gets serialized for transmission and  deserialized, it looses all the dates. Something to do with the toString. @richardmcclellan

**Comment by richardmcclellan** [comment]
I believe the issue here is that a `Temporal.DateTime` gets constructed from `String` in an invalid format.  That would result in the `NullPointerException` when calling `toString()`.    https://github.com/aws-amplify/amplify-android/pull/825 should make it easier to debug this, because an exception will be thrown that actually contains the invalid String.

**Comment by richardmcclellan** [comment]
The `NullPointerException` when calling `toString()` should be fixed by https://github.com/aws-amplify/amplify-android/pull/825/, which will be in the next release, 1.3.2.
