### ISSUE TITLE
Disable Amplify Developer Menu

### ISSUE THREAD

**Issue by shanmugpriyan306** [aws-amplify/amplify-android#794]
I am trying to integrate **'com.amplifyframework:aws-auth-cognito:1.3.0'** into android application. When I do debug/release build, I can see **two application** with same app name. 1st application is my development app & 2nd application is _**Amplify Developer Menu.**_

How to avoid or stop installing 2nd application[i.e Amplify Developer Menu] as attached on screenshot below.
**Note:** I am not facing this issue on **release_v1.2.0** 
![device-2020-09-03-162743](https://user-images.githubusercontent.com/1314621/92107740-e2774000-ee03-11ea-97bc-c9a1f0bfb144.png)

**Comment by jpignata** [comment]
Thanks @shanmugpriyan306! We're looking at this right now.

**Comment by TrekSoft** [comment]
Sorry for the trouble - we found the issue and are deploying a patch release now to address it. Will update this ticket when it's live.

**Comment by TrekSoft** [comment]
Patch is released - please update to 1.3.1. Thanks again for alerting us about this and sorry for the inconvenience.

**Comment by shanmugpriyan306** [comment]
This issue again coming on 1.4.1 version. @TrekSoft

**Comment by TrekSoft** [comment]
I just tested on 1.4.1 and am not seeing it. Could you try on a fresh project just to see if it's something specific with your current project? If you can't figure it out from there post the contents of your AndroidManifest.xml and build.gradle and I'll take a look.

**Comment by mihirap** [comment]
I am also having this issue with 1.4.1

**Comment by mihirap** [comment]
Use this in the Application class, Kotlin code

val config = AmplifyConfiguration.builder(applicationContext).devMenuEnabled(false).build()
Amplify.configure(config, applicationContext)

**Comment by TrekSoft** [comment]
@mihirap are you responding to me as far as how to replicate the behavior @shanmugpriyan306 is reporting or are you replying to him with what he should do?

**Comment by mihirap** [comment]
@TrekSoft I replying to @shanmugpriyan306 that he can use the above code to avoid the issue 👍
