### ISSUE TITLE
How to get new access token by exchanging Refresh token

### ISSUE THREAD

**Issue by shanmugpriyan306** [aws-amplify/amplify-android#795]
Integrated com.amplifyframework:aws-auth-cognito:1.2.0 & able to get accessToken, idToken, refreshToken.

If current accessToken is expired, then how to use refreshToken to get new accessToken using this library.

**Comment by raphkim** [comment]
Hi @shanmugpriyan306,
The Cognito Auth plugin will automatically refresh its access token and id token (if the refresh token is not expired) when you make any call to the AWS service. Please refer to this [documentation](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android#token-fetch-and-refresh) for more details on the behavior.
