### ISSUE TITLE
Amplify Framework 1.2/1.3 breaks run of instrumented tests in the AWS DeviceFarm

### ISSUE THREAD

**Issue by ivpdev** [aws-amplify/amplify-android#799]
I tried to upgrade the Amplify Framework ("com.amplifyframework:core") from 1.0.0 to 1.2.0 or 1.3.0, but this breaks the run of all the instrumented tests in the DeviceFarm due to class loader problems (the log of failed test is attached to the issue).
It works for the Amplify Framework v1.0.0.
 The used device: Google Pixel 3

Sample of the errors log:
<img width="1199" alt="Screenshot 2020-09-04 at 14 45 51" src="https://user-images.githubusercontent.com/6624536/92240800-79540300-eebd-11ea-8b91-73840c3a1161.png">

Full logs:
[log.txt](https://github.com/aws-amplify/amplify-android/files/5174834/log.txt)

**Comment by richardmcclellan** [comment]
Here is the main error I see in your attached log.  I'm not sure why it would be related to the Amplify version.   

```
java.lang.RuntimeException: Unable to instantiate instrumentation ComponentInfo{de.hcsg.hedy_copd.test/de.hcsg.hedy_copd.HedyCOPDInstrumentationTestRunner}: java.lang.ClassNotFoundException: Didn't find class \"de.hcsg.hedy_copd.HedyCOPDInstrumentationTestRunner\" on path: DexPathList[[zip file \"/system/framework/android.test.runner.jar\", zip file \"/system/framework/android.test.mock.jar\", zip file \"/data/app/de.hcsg.hedy_copd.test-urvDCdRIteSsT2f4Utxu3A==/base.apk\", zip file \"/data/app/de.hcsg.hedy_copd-BBjwQRdOP743PXRy9N-TAQ==/base.apk\"],nativeLibraryDirectories=[/system/lib64, /product/lib64]]
```

Perhaps this might solve your issue?  https://stackoverflow.com/a/53029942/282279

**Comment by ivpdev** [comment]
@richardmcclellan unfortunately the problem occurs only on when upgrading Amplify to 1.2/1.3 completely identical project with Amplify 1.0 runs just find on the Device Farm, so it must be some tweak of the class loader or something similar on the newer versions of Amplify.
