### ISSUE TITLE
Developer Menu can't be disabled in Debug Mode

### ISSUE THREAD

**Issue by estiukamobi** [aws-amplify/amplify-android#800]
When integrating '**_com.amplifyframework:aws-auth-cognito:1.3.1_**' I have noticed that a Developer Menu Screen has been introduced when the application is in Debug mode. It appears if the device is shaken.

However, the developer Menu is enabled by default and cannot be disabled, also the shake detector is way too sensitive
https://github.com/aws-amplify/amplify-android/blob/f345bda690eec84d5e83fecb4efba7e50bcf8c11/core/src/main/java/com/amplifyframework/core/Amplify.java#L145

**Comment by KayIlory** [comment]
I am also facing the same issues. Anyway to disable this 
![image](https://user-images.githubusercontent.com/51476926/92325755-f3fb5a80-f044-11ea-9350-b4bfc35bb90f.png)

**Comment by jpignata** [comment]
Howdy! That will only show up in debug mode. We'll circle back next week on an option to disable and tweaks to the shake sensitivity.

**Comment by 24Lathiya** [comment]
@estiukamobi Android application generating two app shortcuts with same icon and name. One is opening app were another open menu like [KayIlory's Issue](https://github.com/aws-amplify/amplify-android/issues/800#issuecomment-687777020)

Please help @jamesonwilliams

**Comment by jpignata** [comment]
Heya @24Lathiya -- are you seeing this behavior with our 1.3.1 release?

**Comment by 24Lathiya** [comment]
@jpignata OMG this issue gone with 1.3.1 thanks.

**Comment by jamesonwilliams** [comment]
Resolving as per https://github.com/aws-amplify/amplify-android/issues/800#issuecomment-688847165

**Comment by jpignata** [comment]
I think we should discuss two items:

1) Do we have an option to disable this functionality in debug?
2) Should we tweak the sensitivity?

**Comment by richardmcclellan** [comment]
Here is the [ReactNative ShakeDetector implementation](https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/ReactAndroid/src/main/java/com/facebook/react/common/ShakeDetector.java), that is used for showing the ReactNative debug menu.  Copying the sensitivity values would probably make sense.  The comments indicate they only trigger on detecting a "rage shake". 😂

**Comment by kwatkins** [comment]
This is still in 1.3.1... And bad form adding without a disable flag, it's super annoying.

**Comment by jpignata** [comment]
@kwatkins Got it. We'll make a fix right away for the next release to reduce the sensitivity and add a flag to disable.

**Comment by jamesonwilliams** [comment]
#821 went out in [the 1.3.2 release](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.3.2).

**Comment by mihirap** [comment]
1.3.1, 1.3.2, 1.4.1 I checked with these versions. But can't disable it.

**Comment by richardmcclellan** [comment]
Hi @mihirap,

You should be able to disable the debug menu in 1.3.2 and above by passing a custom `AmplifyConfiguration` to `Amplify.configure()` like this:

```
val config = AmplifyConfiguration.builder(applicationContext)
    .devMenuEnabled(false)
    .build()
Amplify.configure(config)
```

**Comment by simondorociak** [comment]
> Hi @mihirap,
> 
> You should be able to disable the debug menu in 1.3.2 and above by passing a custom `AmplifyConfiguration` to `Amplify.configure()` like this:
> 
> ```
> val config = AmplifyConfiguration.builder(applicationContext)
>     .devMenuEnabled(false)
>     .build()
> Amplify.configure(config)
> ```

It works. Thanks.

**Comment by indiamaster** [comment]
I'm facing same issue in my flutter application. Is there any solution for that?

**Comment by jamesonwilliams** [comment]
> Hi @richardmcclellan I'm facing same issue in my flutter application. Is there any solution for that?

Please add an issue in the [Amplify Flutter repo](https://github.com/aws-amplify/amplify-flutter/issues/new/choose). Flutter will need to expose the developer menu option themselves. Or, they may just want to hardcode `devMenuEnabled(false)` for the time being.

**Comment by photizzo** [comment]
To follow up on @mihirap comment. In the most recent version you need to supply the `application context` as one of its arguments
```
Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            val config = AmplifyConfiguration.builder(applicationContext)
                .devMenuEnabled(false)
                .build()
            Amplify.configure(config, applicationContext

**Comment by richardmcclellan** [comment]
FYI, we recently changed (https://github.com/aws-amplify/amplify-android/pull/1167) the developer menu to be disabled by default, so if you don't want to use the developer menu, you no longer need to explicitly disable it, as mentioned above.   


To use Amplify without the developer menu:

```
Amplify.configure(applicationContext)
```

To enable the developer menu:

```
val config = AmplifyConfiguration.builder(applicationContext)
    .devMenuEnabled(true)
    .build()
Amplify.configure(config, applicationContext)
```

**Comment by mertoenjosh** [comment]
How do I disable it if I am amplifyconfiguration.json. Is there a block I need in the file.  This is how I am initializing it. 

```kt
Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.addPlugin(AWSS3StoragePlugin())
Amplify.configure(
    AmplifyConfiguration
        .fromConfigFile(
            applicationContext,
             R.raw.amplifyconfiguration
         ), applicationContext
)
```

**Comment by tylerjroach** [comment]
@mertoenjosh The dev menu does not get enabled/disabled from the json configuration file. However, with the example shown, it should not be enabled by default. You would have to explicitly add `.devMenuEnabled(true)` to enable it.

**Comment by mertoenjosh** [comment]
I haven't enabled it explicitly in my code. Amplify version 1.6.4.

**Comment by eeatonaws** [comment]
As of Amplify Android 1.16.13, the developer menu is disabled by default. Prior to version 1.16.13, the developer menu is enabled by default and `.devMenuEnabled(false)` can be added to disable the developer menu.

**Comment by mertoenjosh** [comment]
The function `.fromConfigFile(appCxt, R.raw.amplifyconfiguration.json)` returns the configuration not a builder hence adding `.devMenuEnabled(false)` is not possible. Using a builder allows me to call 'devMenuEnabled(false)`. Thanks for your responses @tylerjroach and @eeatonaws.

This is how I am initializing it now. It works. 

```kt
val config = AmplifyConfiguration
                .builder(applicationContext, R.raw.amplifyconfiguration)
                .devMenuEnabled(false)
                .build()

            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            Amplify.configure(config, applicationContext)
```
