### ISSUE TITLE
Cannot receive SESSION_EXPIRED event 

### ISSUE THREAD

**Issue by abogatov** [aws-amplify/amplify-android#803]
After I upgrade from 1.1.0 to 1.3.1 version, I am no longer seeing the `SESSION_EXPIRED` event on the `HubChannel.AUTH` Hub channel.
```kotlin
Amplify.Hub.subscribe(HubChannel.AUTH) { hubEvent: HubEvent<*> ->
    when (hubEvent.name) {
        InitializationStatus.SUCCEEDED.toString() -> {
            Log.i("App", "Auth successfully initialized")
        }
        InitializationStatus.FAILED.toString() -> {
            Log.i("App", "Auth failed to succeed")
        }
        else -> {
            when (AuthChannelEventName.valueOf(hubEvent.name)) {
                AuthChannelEventName.SIGNED_IN -> {
                    Log.i("App", "Auth just became signed in.")
                }
                AuthChannelEventName.SIGNED_OUT -> {
                    Log.i("App", "Auth just became signed out.")
                }
                AuthChannelEventName.SESSION_EXPIRED -> { //This event won't be generated after the token expires
                    Log.i("App", "Auth session just expired.")
                    // logout
                }
                else -> {
                    Log.i("App", "Auth event: ${hubEvent.name}.")
                }
            }
        }
    }
}
```
I use this event to detect the expiration of the refresh token and log out to re-authorize the user. Otherwise, there will be an error when accessing the `Amplify.API`.

**Comment by abogatov** [comment]
Hi guys, how about this issue? 
Maybe there is a workaround how I can determine that the session is expired to ask user to re-login.

**Comment by changxu0306** [comment]
Hello @abogatov ,
By default, the refresh token expires 30 days after your application user signs into your user pool. When you
create an application for your user pool, you can set the application's refresh token expiration to any value between 60 minutes and 10 years. 
Are you sure that you are not seeing `AuthChannelEventName.SESSION_EXPIRED` event after the refresh token expires? I suggest you setting the refresh token expiration to 60 minutes and call `Amplify.Hub.subscribe()` after it expired. If it does happen, please reply to this issue and we'll take care on it.

**Comment by div5yesh** [comment]
Hi @abogatov, were you able to fix this problem?

We will be closing this issue soon. 
Please let us know if you are still experiencing this issue.
