### ISSUE TITLE
Amplify.Auth.fetchAuthSession returns "You are currrently signed out." immediately after successful Amplify.Auth.signIn call

### ISSUE THREAD

**Issue by benvaun** [aws-amplify/amplify-android#826]
I'm trying to get a basic Android app setup with Amplify Auth, using existing user and application pools that are already working on our iOS side. But I'm seeing an issue after a user is successfully authenticated with `USER_PASSWORD_AUTH`. Subscribing to the Hub event, I'm able to see the `SIGNED_IN` event, and no `SIGNED_OUT` or `SESSION_EXPIRED` events occur. Amplify configuration succeeds, and logging in the (existing) user returns with the following:

> AuthSignInResult{isSignInComplete=true, nextStep=AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}}

Immediately afterwards, I attempt to fetch the Auth session, but get the following:

> AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}

Here's the code in question:

![image](https://user-images.githubusercontent.com/21106106/93122833-0b0cfe80-f67c-11ea-9468-252420c82d6f.png)
![image](https://user-images.githubusercontent.com/21106106/93122857-15c79380-f67c-11ea-9f28-e410b4ac27b9.png)

and my (edited for privacy) `amplifyconfiguration.json` file:

![image](https://user-images.githubusercontent.com/21106106/93122989-48718c00-f67c-11ea-8820-51b320d59695.png)

**Comment by TrekSoft** [comment]
Hey, this definitely sounds like a bug - what version of the library and plugin are you using?

**Comment by benvaun** [comment]
from my build.gradle:
implementation 'com.amplifyframework:core:1.3.1'
implementation 'com.amplifyframework:aws-auth-cognito:1.3.1'

**Comment by TrekSoft** [comment]
Hey, so yeah attempting to replicate it here it seems it has to do with your using USER_PASSWORD_AUTH instead of USER_SRP_AUTH. Did you set up USER_PASSWORD_AUTH through the CLI (if so, how?) or did you modify the configuration file manually? Is there a reason you wanted to do USER_PASSWORD_AUTH instead of USER_SRP_AUTH?

USER_PASSWORD_AUTH is handled through your own custom lambda so I'm wondering if you're wrongly returning a value that the user is signed in from that when they actually aren't hence the discrepancy.

**Comment by benvaun** [comment]
I created the configuration file manually, but in any case, I switched to USER_SRP_AUTH and I'm getting the exact same behavior.

**Comment by TrekSoft** [comment]
Are you sure you switched that value in `amplifyconfiguration.json` and not `awsconfiguration.json`? It's also possible there's a cached value remaining from the previous USER_PASSWORD_AUTH. Try running your program on a new emulator.

**Comment by benvaun** [comment]
Yes, definitely changed it in the amplifyconfiguration.json file, and I'm running the app on a physical phone with a full uninstall and clean install. I also went ahead and created a completely fresh project with the USER_SRP_AUTH amplifyconfiguration.json file, and I'm seeing the exact same behavior. 
That said, our iOS app is using the exact same app and user pool, with the exact same amplifyconfiguration.json file, and USER_PASSWORD_AUTH, and not seeing this issue.

**Comment by queden** [comment]
Hi, not sure if this is related, but I am using Amplify 1.3.1 on Android and am having issues with Sign in as well. When calling Sign in like this: 
```
Amplify.Auth.signIn(
            username,
            password,
            { result ->
                Log.d(LOGIN_TAG, if (result.isSignInComplete) "Sign in succeeded" else "Sign in not complete")
            },
            { error ->
                Log.e(LOGIN_TAG, error.toString())
            }
        )
```
The code never enters the result or error blocks (as confirmed by checking logcat), but logging immediately before and after the signIn call show that the code passes by it. When I later call Amplify.Auth.currentUser, my application crashes with a result that says 
``` Unable to start activity ComponentInfo{io.appatech.appa/io.appatech.appa.activities.MainActivity}: java.lang.IllegalStateException: Amplify.Auth.currentUser must not be null```

I've played around with a few other auth functions and was able to sign up a user in Cognito from the Android app. I can open up another issue if needed but this seemed related.

**Comment by queden** [comment]
I am also getting the same 
```
AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}
```
when fetching, but there is still no logging from the sign in.

**Comment by TrekSoft** [comment]
@queden - yeah this seems different so if you don't mind, could you open a separate issue with your redacted amplifyconfiguration.json file and surrounding code for where you're calling signIn and configuring Auth as well as the log output from Debug level and higher around the time you call signIn?

@benvaun - hmm - have you tried signing in and fetching auth session before modifying the amplify configuration.json file to put the iOS userpool?

**Comment by queden** [comment]
Some of the issues I had resolved themselves (almost without me doing anything), but I wanted to know: is Amplify.Auth.signIn async? It's results are logging after my success/error handling, which is making it difficult to process errors.

**Comment by queden** [comment]
Nevermind, all is good!

**Comment by queden** [comment]
Had resolved my other errors, but now am getting an error which seems more related to what benvaun had. I am attempting to access the current user and it's attributes after a successful sign-in, but I am continually getting a `java.lang.IllegalStateException: Amplify.Auth.currentUser must not be null` error. What's more, I call Amplify.Auth.fetchAuthSession right above calling Amplify.Auth.currentUser, and it returns 

```
AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=com.amazonaws.auth.BasicSessionCredentials@[id], error=null, type=SUCCESS}, userSub='AuthSessionResult{value=[id] error=null, type=SUCCESS}
```
etc. etc. 

Not sure why this is succesful but current user is null.

**Comment by queden** [comment]
Weird, this error is happening really inconsistently. It was continually crashing with the currentUser must not be null exception, and then I did not even change the code, and the next time I ran, it worked fine. It will work fine for a few runs, and then will start failing unpredictably. Logs show that nothing is happening between a successful sign on and fetching the current user.

**Comment by queden** [comment]
Tried this to see if it would ever connect, but basically it either connected on the first loop or went on infinitely until I ran out of memory. Just a hit or miss from run to run

```
        var currentUser: AuthUser? = null

        while (currentUser == null) {
            Log.d(TAG, "Attempting to fetch current user")
            currentUser = try {
                Amplify.Auth.currentUser
            } catch (e: java.lang.IllegalStateException) {
                null
            }

            if (currentUser == null) {
                Log.d(TAG, "Fetching current user failed")
            } else {
                Log.d(TAG, "Found current user")
            }
        }
```

**Comment by TrekSoft** [comment]
Hey, yeah this sounds different since fetchAuthSession is returning signed in for you. 

Could you open it as a new issue where you specify:

1. what your configuration is (specifically did you enable guest access, identity pools, and/or are you using Lambdas)
2. your redacted amplifyconfiguration.json file
3. surrounding code for where you're calling signIn and configuring Auth before calling getCurrentUser (specifically are you making sure not to call getCurrentUser until after Amplify is configured)?

**Comment by benvaun** [comment]
Found the cause- the Identify Pool that was being initialized with the App Client did not have the User Pool as an Authentication Provider. When we added the User Pool as an Authentication Provider to the Identity Pool, it works.

**Comment by TrekSoft** [comment]
Wonderful - thanks for that update @benvaun !

**Comment by mihirap** [comment]
Thank you @benvaun (hat off)

**Comment by mariuspena** [comment]
@benvaun how exactly did you fix it? I am having the same issue. 
Amplify.Auth.signIn(username, password) returns isSignInComplete true.
`AuthSignInResult{isSignInComplete=true, nextStep=AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}}`
Amplify.Auth.fetchAuthSession replies with 
`AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=If you have guest access enabled, please check that your device is online and try again. Otherwise if guest access is not enabled, you'll need to sign in and try again.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}',....`
ios app runs just fine.

my amplifyconfiguration.json is this
`{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-west-1_xxxxxxxxx",
              "Region": "eu-west-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-west-1_xxxxxxxxx",
            "AppClientId": "yyyyYYYyyyYYyyyYYyyyYY",
            "AppClientSecret": "zzzZZZzzzZZZzzzzzzZZZzZZzzzzzZZZzzzZZZ",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_PASSWORD_AUTH"
          }
        }
      }
    }
  }
}
`

**Comment by benvaun** [comment]
@mariuspena in the AWS Console, when you're looking at the App Clients, confirm that your User Pool is selected as the Authentication Provider for that Identity Pool. Specifically, on the left, under App Integration, select App Client Settings, then find your App Client. In the App Client, under Enabled Identity Providers, make sure that the checkbox next to your User Pool is checked.

**Comment by mariuspena** [comment]
@benvaun 
General Settings > App Clients - I can see the app client id and secret and flow configs
App integration > App Client Settings - found my client id > "select all" check is on, "Cognito User Pool" check is on

I think my problem is in the amplifyconfiguration.json

`json
"CredentialsProvider":{
               "CognitoIdentity":{
                  "Default":{
                     "PoolId":"eu-west-1_xxxxxxxxx",
                     "Region":"eu-west-1"
                  }
               }
            }
`
because "PoolId":"eu-west-1_xxxxxxxxx" should resemble "us-west-1:123e4567-e89b-12d3-a456-426614174000", right ?

**Comment by mariuspena** [comment]
so we added an identity pool linked to cognito and got the id for that and it works. thanks

**Comment by OrelsProjects** [comment]
> This was my issue. May be this will help someone.
> 
> ![2021-10-29_142117](https://user-images.githubusercontent.com/75514218/139426768-8c31df6e-51cd-48cb-affa-23eb93759204.png)

LIFE SAVER!
