### ISSUE TITLE
NullPointerException thrown on calling toString or hashCode of Temporal.DateTime

### ISSUE THREAD

**Issue by saltonmassally** [aws-amplify/amplify-android#848]
A model with Temporal.DateTime (AWSDatetime) field with null values results in the following:

```
  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.time.LocalDateTime.toString()' on a null object reference
        at java.time.OffsetDateTime.toString(OffsetDateTime.java:1906)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.core.model.temporal.Temporal$DateTime.toString(Temporal.java:277)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.generated.model.Group.hashCode(Group.java:340)
```

I think `this.offsetDateTime` below evaluates to null
```
return "Temporal.DateTime{offsetDateTime='" + this.offsetDateTime + "'" + '}';
```

**Comment by saltonmassally** [comment]
Got a few more details on this. Looks like either the datetime format i am using is wrong or some issue with the conversion to Temporal.Datetime.

Datetime stored in sqllite `2020-09-21T16:57:03.132Z`

<img width="1199" alt="Screenshot 2020-09-22 at 01 38 54" src="https://user-images.githubusercontent.com/2057234/93815962-77878f00-fc74-11ea-967e-c6b09bacd813.png">

**Comment by saltonmassally** [comment]
Furthering this. I suspect the issue might be the zone handling as if I use java.time.format.DateTimeFormatter#ISO_ZONED_DATE_TIME is works fine for my case above in which a zone rather than an offset is supplied. I haven;t tested for offset case though

**Comment by jamesonwilliams** [comment]
> Got a few more details on this. Looks like either the datetime format i am using is wrong or some issue with the conversion to Temporal.Datetime.

https://github.com/aws-amplify/amplify-android/pull/825 will make the `Temporal.DateTime` "fail fast" if it sees an input it doesn't like. If you are getting into this state due to a bad format, this might help, @saltonmassally?

I do also get your other point. [The `gson` instance being used in the deserialization method is just `gson = new Gson();`](https://github.com/aws-amplify/amplify-android/blob/7de77fe56dc79ab1c75a154821e3f1b04bb308d2/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java#L137).

Instead, it should be an instance of Gson that is configured with adapters for [the various temporal deserializers](https://github.com/aws-amplify/amplify-android/blob/7de77fe56dc79ab1c75a154821e3f1b04bb308d2/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/TemporalDeserializers.java#L28-L32).

**Comment by saltonmassally** [comment]
> I do also get your other point. The `gson` instance being used in that deserialization method is just from [`gson = new Gson();`](https://github.com/aws-amplify/amplify-android/blob/7de77fe56dc79ab1c75a154821e3f1b04bb308d2/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java#L137). That isn't "enough." Instead, it should be an instance of Gson that is configured with adapters for [the various temporal deserializers](https://github.com/aws-amplify/amplify-android/blob/7de77fe56dc79ab1c75a154821e3f1b04bb308d2/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/TemporalDeserializers.java#L28-L32).

Both serializer and deserializer given that both are done with that method. Something akin to 

```
new GsonBuilder()
            .registerTypeAdapter(Date.class, new GsonVariablesSerializer.DateSerializer())
            .registerTypeAdapter(Temporal.Timestamp.class, new GsonVariablesSerializer.TemporalTimestampSerializer())
            .registerTypeAdapter(Temporal.Date.class, new GsonVariablesSerializer.TemporalDateSerializer())
            .registerTypeAdapter(Temporal.DateTime.class, new GsonVariablesSerializer.TemporalDateTimeSerializer())
            .registerTypeAdapter(Temporal.Time.class, new GsonVariablesSerializer.TemporalTimeSerializer())
            .registerTypeAdapter(Temporal.Date.class, new TemporalDeserializers.DateDeserializer())
            .registerTypeAdapter(Temporal.Time.class, new TemporalDeserializers.TimeDeserializer())
            .registerTypeAdapter(Temporal.Timestamp.class, new TemporalDeserializers.TimestampDeserializer())
            .registerTypeAdapter(Temporal.DateTime.class, new TemporalDeserializers.DateTimeDeserializer())
            .create();
```

**Comment by kjones** [comment]
I did a small refactor a few days back where I extracted the serializers to a `TemporalSerializers` class to mirror the `TemporalDeserializers` [here](https://github.com/kjones/amplify-android/commit/47453f8fc640f9af0d0ae6c819c5537c7237dbd2) that might provide a starting point.

**Comment by jamesonwilliams** [comment]
@kjones That's awesome; great start! Thanks
