### ISSUE TITLE
Amplify auth login for Android, application must restart after login in other to access User information

### ISSUE THREAD

**Issue by kingchikason** [aws-amplify/amplify-android#852]
**Amplify**
**Amplify Authentication login**
**Android studio application**

After logining with the Amplify auth, I can't access the information of the user, meaning that it is still seen that their is no login until the application is restarted.

It is an Android application.
The login page is on a fragment inside navigation component.

I don't know if I needed to refresh the Amplify auth after logining and if so how?

**Comment by jamesonwilliams** [comment]
Hi @kingchikason! Unfortunately, we don't have enough information to help right now. Pease can you provide:
1. Your `amplifyconfiguration.json` (with credentials and IDs scrubbed out);
2. The code you use to configure/initialize Amplify
3. Your app and project-level `build.gradle`
4. The code you use to sign-in a user
5. What you expect to happen when you run that code
6. What actually happens
7. Logs that occur on your device, around the time of the Amplify interactions.
