### ISSUE TITLE
Prevent Orchestrator's startup sequence from being re-triggered while still in-flight

### ISSUE THREAD

**Issue by rjuliano** [aws-amplify/amplify-android#853]
## Background
The startup sequence for the orchestrator performs the following tasks:
- Start observing changes to local storage and push changes to the mutation outbox (Always)
- Set up subscriptions for all models (Only if API is present)
- Execute initial sync for all models (Only if API is present)
- Start processing mutation outbox items (Only if API is present)
- Start processing changes received via remote subscriptions (Only if API is present)

Currently we attempt to trigger this sequence from a couple of different places:
- During [DataStore startup](https://github.com/aws-amplify/amplify-android/blob/c612d56181ba4a686ff2da4fc8a8913050f9863f/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L226)
- When [DataStore.clear is called](https://github.com/aws-amplify/amplify-android/blob/c612d56181ba4a686ff2da4fc8a8913050f9863f/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L482)
- Before [any interaction with the DataStore](https://github.com/aws-amplify/amplify-android/blob/c612d56181ba4a686ff2da4fc8a8913050f9863f/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L495)(other than clear)

The 3rd scenario was implemented as a way for us to ensure that the sync engine is always running (or recovers from failure, specifically in offline scenarios). 99% of the time, this will be a no-op because the [orchestrator is already started](https://github.com/aws-amplify/amplify-android/blob/df70332ab7f6197fe5756a85196f8505fa05e95d/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java#L157). However...

## The problem
As it stands, there's a period of time between when the Orchestrator's start method is called and the internal state of the Orchestrator is updated, that leaves room for that method to be invoked multiple times. This happens typically when the app calls Amplify.configure and immediately tries to query or save something to the DataStore.

## The solution
We need to add some safeguards to ensure that there can only be one invocation of the start/stop methods in flight at any given point. 

Whatever solution is implemented needs to ensure it does not impact DataStore interactions when the device is offline. The problem we had in the past is that if we block for the entirety of the startup sequence (those 5 steps above), it introduces delays on every interaction with the DataStore (for offline cases). We truly only need to block until the storage observer starts.

**Comment by jamesonwilliams** [comment]
Thanks @rjuliano; you have described the problem well!

**Comment by jamesonwilliams** [comment]
Resolved by #876, closing.
