### ISSUE TITLE
Access Denied when uploading file to storage - Guest + Private

### ISSUE THREAD

**Issue by rahulraj64** [aws-amplify/amplify-android#857]
Hi,

I have a use case of uploading files from an Android SDK. Since this is an
SDK, I cannot implement a login mechanism to upload the file since the original
app may have one. Instead, I am looking for guest user authentication so that
the guest users can access their own files and nothing else. I have updated
auth & storage to allow unauthorized access. Still, I am getting this
exception:

> Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied;

My code for uploading a file:

```kotlin
private fun upload() {
    val fileFromUri = getFileFromUri(uri, uploadKey)
    Amplify.Auth.fetchAuthSession(
        { result ->
            val cognitoAuthSession = result as AWSCognitoAuthSession
            when (cognitoAuthSession.identityId.type) {
                AuthSessionResult.Type.SUCCESS -> {
                    Log.i("AuthQuickStart", "IdentityId: " + cognitoAuthSession.identityId.value)
                    val options = StorageUploadFileOptions.builder()
                        .accessLevel(StorageAccessLevel.PRIVATE)
                        //.targetIdentityId(cognitoAuthSession.identityId.value)
                        .build()
                    Amplify.Storage.uploadFile(
                        uploadKey,
                        fileFromUri,
                        options,
                        {
                            Log.i("MyAmplifyApp", "Successfully uploaded: $uploadKey")
                            setValue(Resource.success(uploadKey))
                        },
                        { error: StorageException ->
                            Log.e("MyAmplifyApp", "Upload failed", error)
                            setValue(Resource.error(error.message ?: "Upload error", null))
                        }
                    )
                }
                AuthSessionResult.Type.FAILURE -> Log.i("AuthQuickStart", "IdentityId not present because: " + cognitoAuthSession.identityId.error.toString())
            }
        },
        { error -> Log.e("AuthQuickStart", error.toString()) }
    )
}
```

My Config file:

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-south-1:53XX",
                            "Region": "ap-south-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-south-1_IXvTypLOO",
                        "AppClientId": "1vsXX",
                        "AppClientSecret": "1vXX",
                        "Region": "ap-south-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "docXX",
                        "Region": "ap-south-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "docXX",
                "region": "ap-south-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}

```
Also, I need one more confirmation that since the credential file is hardcoded,
Can someone can decompile app and use the credentials to access all the files?
If so, can StorageAccessLevel.PRIVATE prevent this?

**Comment by rjuliano** [comment]
Guest users can only upload to the public area of the bucket. This is controlled by the policies under for unauthRole IAM role (which is the role used for guest users).

The policies for protected and private make use of the `cognito-identity.amazonaws.com:sub` variable to restrict access to objects uploaded by the user. 

What authentication methods are available for the Android SDK you're referring to?

**Comment by rahulraj64** [comment]
Hi @rjuliano 
Thanks for your reply. I will detail my use case here. We are developing an android SDK (A custom camera app that only captures pictures of pet animals and uploads into a server, in this case, S3). So the SDK should be self-contained with all the Amplify configurations and capable of uploading images on its own, without depending on the hosting app. The hosting app does not use Aws/Amplify so the Cognito authentication (username, email, phone, etc) cannot be used to authorize a user to grant upload permission (Maybe the hosting app uses another provider like Firebase).  

Since this is an SDK, we cannot implement yet another auth mechanism since the user already logged in using another provider and we cannot prompt for yet another signup inside SDK. The only possibilities of implementing a login mechanism inside an SDK are:

1. **Guest login**. (Similar to Firebase Anonymous login): Since this is a guest, the users do not need to use another signup process. But according to your comments, they cannot upload files into a private folder. If I allow the guest users to upload files inside a public folder, this is a security issue since it is accessible by anyone else who decompiles app to get the credentials. In Firebase, anonymous login users can have private access to the storage depending on the security rules. I am seeking an alternative like this: (https://firebase.google.com/docs/auth/android/anonymous-auth)
2. **SignIn with Custom Token**: If the hosting app uses a different type of auth, they could be able to create a custom token against the user and send it to through the SDK. The SDK then sign in the user using the provided token so that we authorize the user inside SDK to access storage. Alternative to this (https://firebase.google.com/docs/auth/android/custom-auth)

I'm sorry that I am referring to Firebase here since I cam from this background & new to AWS, and they provide these types of systems to cover the SDK use cases. Please have a detailed look and provide me the solutions for the above-mentioned use cases. 

Thanks.
