### ISSUE TITLE
CUSTOM_AUTH user shows as not signed in, even though she is

### ISSUE THREAD

**Issue by edgar-zigis** [aws-amplify/amplify-android#870]
Hello, we are facing an issue when using Amplify Auth with a custom
authentication flow. We have some custom lambdas which allow us to authenticate
within Cognito without specifying a password. However, after successful sign
in, we can't access any user property. Instead we see the message:
> You are currently signed out.

**amplifyconfiguration.json**
```json
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-west-1_some_id",
              "Region": "eu-west-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-west-1_some_id",
            "AppClientId": "app_client_id_which_we_use",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "CUSTOM_AUTH"
          }
        }
      }
    }
  }
}
```
**build.gradle (app)**
```gradle
implementation 'com.amplifyframework:core:1.4.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.4.0'
```
**Application class**
```kotlin
// onCreate ->
Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.configure(this)
```
**Testing code**
```kotlin
Amplify.Auth.signIn("+3706XXXXXX", null, {
     val userEmail = AuthUserAttribute(AuthUserAttributeKey.email(), "xxxxx@gmail.com")
     Amplify.Auth.updateUserAttribute(userEmail, {
         Log.i("AuthDemo", "Updated user attribute = $it")
     }, {
         Log.e("AuthDemo", "Failed to update user attribute.")
     })
}, {
     printError()
})
```
**Response:**

After `signIn`:
> AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}

After _updateUserAttribute_:
> AmplifyException {message=Failed to fetch user attributes, cause=java.lang.Exception: Operation requires a signed-in state, recoverySuggestion=Ensure that you are logged in and online}

When testing the flow via aws console it works fine though.

If I try to call `Amplify.Auth.fetchAuthSession` after successful login, I get this:
> AWSCognitoAuthSession{ 
>    isSignedIn=false, 
>    awsCredentials=AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=If you have guest access enabled, please check that your device is online and try again. Otherwise if guest access is not enabled, you'll need to sign in and try again.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=If you have guest access enabled, please check that your device is online and try again. Otherwise if guest access is not enabled, you'll need to sign in and try again.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, 
>    type=FAILURE}'}

Please take a look on this as this does not looks right.

Same flow using AWS console which works fine:
```console
➜  authentication git:(master) ✗ aws cognito-idp initiate-auth --client-id some_client_id_we_use --auth-flow CUSTOM_AUTH --auth-parameters USERNAME=+3706XXXXXX 
{
    "ChallengeParameters": {
        "USERNAME": "+3706XXXXXX"
    },
    "AuthenticationResult": {
        "AccessToken": "some_access_token_we_get",
        "ExpiresIn": 3600,
        "TokenType": "Bearer",
        "RefreshToken": "some_refresh_token_we_get",
        "IdToken": "some_id_token_we_get"
    }
}
➜  authentication git:(master) ✗ aws cognito-idp update-user-attributes --user-attributes Name="email",Value="xxxxx@gmail.com" --access-token some_access_token_we_get
```

I did try working with AWSMobileClient directly too and I get same results.

```kotlin
AWSMobileClient.getInstance().signIn("+3706XXXXXX", null, null, object : Callback<SignInResult> {
    override fun onResult(result: SignInResult?) {
       // user is signed successfully and this block is always called
       AWSMobileClient.getInstance().getUserAttributes(object : Callback<Map<String, String>> {
           override fun onResult(result: Map<String, String>?) {
               ...
           }

           override fun onError(e: Exception?) {
			   // this block is always called with exception message telling
               // that user is not signed in
           }
       })
    }

    override fun onError(e: Exception?) {
        ...
    }
})
```
But I also have noticed some interesting behaviour with:
```kotlin
AWSMobileClient.getInstance().addUserStateListener {
    ...
}
```
First it outputs `logged in` state at the start of signIn call, but later on it
outputs `logged out` after signIn call is completed.

**Comment by edgar-zigis** [comment]
Same flow using AWS console which works fine:
```
➜  authentication git:(master) ✗ aws cognito-idp initiate-auth --client-id some_client_id_we_use --auth-flow CUSTOM_AUTH --auth-parameters USERNAME=+3706XXXXXX 
{
    "ChallengeParameters": {
        "USERNAME": "+3706XXXXXX "
    },
    "AuthenticationResult": {
        "AccessToken": "some_access_token_we_get",
        "ExpiresIn": 3600,
        "TokenType": "Bearer",
        "RefreshToken": "some_refresh_token_we_get",
        "IdToken": "some_id_token_we_get"
    }
}
➜  authentication git:(master) ✗ aws cognito-idp update-user-attributes --user-attributes Name="email",Value="xxxxx@gmail.com" --access-token some_access_token_we_get
```

**Comment by edgar-zigis** [comment]
I did try working with AWSMobileClient directly too and I get same results.

```
AWSMobileClient.getInstance().signIn("+37067551197", null, null, object : Callback<SignInResult> {
    override fun onResult(result: SignInResult?) {
       // user is signed successfully and this block is always called
       AWSMobileClient.getInstance().getUserAttributes(object : Callback<Map<String, String>> {
           override fun onResult(result: Map<String, String>?) {
               ...
           }

           override fun onError(e: Exception?) {
               // this block is always called with exception message telling that user is not signed in
           }
      })
   }

  override fun onError(e: Exception?) {
        ...
  }
})
```
But I also have noticed some interesting behaviour with:
```
AWSMobileClient.getInstance().addUserStateListener {
    ...
}
```
First when the app is launched it reports the logged in state (before any sign in code is executed), but later on it outputs logged out state immediately after signIn call is completed.

**Comment by edgar-zigis** [comment]
Ok, so apparently we have managed to resolve the issue. After further investigation we have encountered this error:
`'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+ (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: xxx)`
And then we found out, that in CognitoIdentity.PoolId we actually need to use Cognito Federated Identity pool id instead of the User Pool Id.

The documentation on how to use AWS Amplify in the app is very scarce and uninformative when it comes to the AWS configs. You should really provide step by step instruction on how the amplifyconfiguration.json should look like, when to use Cognito user pools and when federated identities.

**Comment by ypawar159** [comment]
@edgar-zigis I am trying to get a passwordless custom auth flow working with the android amplify client.
How did you manage to respond to the custom challenge? I couldn't find any substitute for this js call `Auth.sendCustomChallengeAnswer(user, OTP)` in android client.

**Comment by edgar-zigis** [comment]
@ypawar159 maybe this snippet will help you:
```
fun respondToDeviceChallenge(challenge: AWSDeviceChallenge, verificationCode: String) {
        val userPool = CognitoUserPool(context, AWSMobileClient.getInstance().configuration)
        val user = userPool.getUser(challenge.user.username)

        val challengeRequest = RespondToAuthChallengeRequest().also {
            it.session = challenge.session
            it.challengeName = "CUSTOM_CHALLENGE"
            it.clientId = userPool.clientId
            it.challengeResponses = hashMapOf(
                Pair(CognitoServiceConstants.AUTH_PARAM_USERNAME, challenge.user.username),
                Pair(CognitoServiceConstants.CHLG_RESP_ANSWER, verificationCode)
            )
        }
        user.respondToChallenge(challengeRequest, object : AuthenticationHandler {
            override fun onSuccess(
                userSession: CognitoUserSession?,
                newDevice: CognitoDevice?
            ) {
                GlobalScope.launch {
                    try {
                        authenticationApiClient.signIn(challenge.user.username)
                        _state.value = AuthenticationChallengeState(continuation = null, error = null)
                    } catch (exception: Throwable) {
                        _state.value = AuthenticationChallengeState(error = exception)
                    }
                }
            }
            override fun onFailure(exception: Exception?) {
                _state.value = AuthenticationChallengeState(error = exception)
            }
            override fun getAuthenticationDetails(
                authenticationContinuation: AuthenticationContinuation?,
                userId: String?
            ) {}
            override fun authenticationChallenge(continuation: ChallengeContinuation?) {
                _state.value = AuthenticationChallengeState(continuation = continuation)
            }
            override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {}
        }, true).run()
    }
```
where `AWSDeviceChallenge` is our custom object containing _username_ & _session_ returned from our lambdas.
We use only onSuccess, onError and continuation (because we use both email & phone for verification).

**Comment by ypawar159** [comment]
@edgar-zigis Thanks for the code snippet.

I was able to combine it with some info on the amplify docs to get the required behaviour.
Here is my simple code to get it done.
```
fun confirmSignIn(challgeneCode:String) {
        val res: MutableMap<String, String> =
            HashMap()
        res[CognitoServiceConstants.CHLG_RESP_ANSWER] = challgeneCode

        val mobileClient = Amplify.Auth.getPlugin("awsCognitoAuthPlugin").escapeHatch as AWSMobileClient
        mobileClient.confirmSignIn(res, object : Callback<SignInResult?> {
            override fun onError(e: Exception?) {
                Log.e(LogTag, "Confirm Custom auth Sign-in error", e)
            }

            override fun onResult(result: SignInResult?) {
                Log.d(LogTag, "Result signin state = ${result?.signInState}")
            }
        })
    }
```

**Comment by mariuspena** [comment]
@edgar-zigis how did you get the identity pool id ?

**Comment by edgar-zigis** [comment]
@mariuspena from AWS console.
