### ISSUE TITLE
Unable setup guest user when using web ui and using mGoogleSignInClient.getSignInIntent() throws NotAuthorizedException when getting temp credentials

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-android#887]
using amplify auth in android

here's a summary of the problems i am experiencing using auth in android app:

1) setting up auth following documentation for sign in with web ui and social sign in with web ui (the web ui works) but i cannot also enable unauthorised (guest) sign in
2) if i then sign in using mGoogleSignInClient.getSignInIntent() to sign in as a google user, calling mobileClient.federatedSignIn(IdentityProvider.GOOGLE.toString(), "google id token", new Callback<UserStateDetails>() {} to get temporary credentials throws NotAuthorizedException: Token is not from a supported provider of this identity pool
3) then if i update auth to allow guest login and google federation, i get an update failed error when running amplify push. the remedy is to remove auth and then add again, selecting manual configuration to allow guest login and google federation. the result is that i can sign in as a google user using mGoogleSignInClient.getSignInIntent() but when trying to sign in using Amplify.Auth.signInWithWebUI() it returns signInWithWebUI error: AmplifyException {message=Sign in with web UI failed, cause=java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}

so i either have to set up auth to use web ui and no guest user login or set up with google federation (and i suppose facebook, etc too) and i use my own ui and then i can have guest login.

it would be nice to be able to use web ui and have guest login and also nice to be able to call mobileClient.federatedSignIn(IdentityProvider.GOOGLE.toString(), "google id token", new Callback<UserStateDetails>() {} to get temporary credentials once signed in using web ui as google user

below is a more detailed explanation of how i installed auth:

1)set up auth following documentation for sign in with web ui and social sign in with web ui.
  - everything works as expected
  - cannot enable unauthorised (guest) sign in
  - once signed in as google user, calling mobileClient.federatedSignIn(IdentityProvider.GOOGLE.toString(), "google id token", new Callback<UserStateDetails>() {} throws NotAuthorizedException: Token is not from a supported provider of this identity pool

2) trying to update auth, i select the following opttions:

	- What do you want to do? Walkthrough all the auth configurations
	-Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
	-Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
	-Do you want to enable 3rd party authentication providers in your identity pool? Yes
	-Select the third party identity providers you want to configure for your identity pool: Google
	
	Enter your Google Web Client ID for your identity pool:  xxxxxxxxx.apps.googleusercontent.com
  
 You've opted to allow users to authenticate via Google within an Android project.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an Android Client ID. 

	Enter your Google Android Client ID for your identity pool:  xxxxxxxxxx.apps.googleusercontent.com
	-Do you want to add User Pool Groups? No
	-Do you want to add an admin queries API? No
	-Multifactor authentication (MFA) user login options: OFF
	-Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
	-Please specify an email verification subject: Your verification code
	-Please specify an email verification message: Your verification code is {####}
	-Do you want to override the default password policy for this User Pool? No
	-Specify the app's refresh token expiration period (in days): 30
	-Do you want to specify the user attributes this app can read and write? No
	-Do you want to enable any of the following capabilities?
	-Do you want to use an OAuth flow? No
	-? Do you want to configure Lambda Triggers for Cognito? No
	
amplify push gives the following errors:

	UPDATE_FAILED      authamplify6a73ecb1        AWS::CloudFormation::Stack Wed Oct 07 2020 16:10:35 GMT+0200 (South Africa Standard Time) Parameters: [hostedUIProviderCreds] do not exist in the template
	Following resources failed

	× An error occurred when pushing the resources to the cloud

	Resource is not in the state stackUpdateComplete
	An error occurred during the push operation: Resource is not in the state stackUpdateComplete
	
	i then remove auth and add it again
	
	The current configured provider is Amazon Cognito. 

 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)
 Please provide a friendly name for your resource that will be used to label this category in the project: android
 Please enter a name for your identity pool. android_id_pool
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? Yes
 Select the third party identity providers you want to configure for your identity pool: Google
  
 You've opted to allow users to authenticate via Google.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an App ID. 

 Enter your Google Web Client ID for your identity pool:  xxxxxxxx.apps.googleusercontent.com
  
 You've opted to allow users to authenticate via Google within an Android project.  If you haven't already, you'll need to go to https://developers.google.com/identity and create an Android Client ID. 

 Enter your Google Android Client ID for your identity pool:  xxxxxxxxxx.apps.googleusercontent.com
 Please provide a name for your user pool: android_user_pool
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
Successfully added auth resource android locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

after amplify push:

	-sign in as google user:

  GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken("xxxxxxxxx.apps.googleusercontent.com")// web id 
                .requestEmail()
                .build();

        // Build a GoogleSignInClient with the options specified by gso.
        mGoogleSignInClient = com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(this, gso);
        Intent signInIntent = mGoogleSignInClient.getSignInIntent();
        startActivityForResult(signInIntent, RC_SIGN_IN);

then in handleSignInResult():

			- able to get Google ID token
			-able to call mobileClient.federatedSignIn(IdentityProvider.GOOGLE.toString(), "Google ID token, new Callback<UserStateDetails>() {} to get temp credentials
also:
	-able to sign in as guest (unauthenticated user) and get guest credentials
but
	-calling Amplify.Auth.signInWithWebUI() returns signInWithWebUI error: AmplifyException {message=Sign in with web UI failed, cause=java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}

**Comment by jamesonwilliams** [comment]
Hi @kannieWeesNie, sorry to hear you're having trouble. There is a lot of content here, and the formatting is difficult to work through. We'll be better able to help you if you can distill your issue into a more concise and focused report.

**Comment by kannieWeesNie** [comment]
hi @jamesonwilliams thanks for the speedy reply

here's the gist of my issues:

i'm using amplify in android.

if i set up auth to use the web ui
	-i cannot also enable guest login
	-if i then sign in using mGoogleSignInClient.getSignInIntent() and then call mobileClient.federatedSignIn(IdentityProvider.GOOGLE.toString(), "google id token", new Callback<UserStateDetails>() {} to get temporary credentials it throws NotAuthorizedException: Token is not from a supported provider of this identity pool
	
if i then try and update auth to allow guest login and google federation
	-i get an update failed error when running amplify push. the remedy is to remove auth and then add auth again, selecting manual configuration to allow guest login and google federation. the result is that i can sign in as a google user using mGoogleSignInClient.getSignInIntent() but when trying to sign in using Amplify.Auth.signInWithWebUI() it returns signInWithWebUI error: AmplifyException {message=Sign in with web UI failed, cause=java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}

it would be nice to be able to use web ui and have guest login and also nice to be able to call mobileClient.federatedSignIn(IdentityProvider.GOOGLE.toString(), "google id token", new Callback<UserStateDetails>() {} to get temporary credentials once signed in using web ui as google user

**Comment by TrekSoft** [comment]
Hey, so yeah there are some (unnecessary) limitations on which combinations of things you can have configured through the CLI at the same time (HostedUI and federated sign in is one such combination - not sure about Guest, hadn't tried it before but wouldn't be surprised). You can file a feature request with the CLI repo to support these combinations.

It is possible to have both HostedUI and Federated Sign In configured simultaneously by setting up Hosted UI through the CLI and then editing your identity pool on the AWS console website, expanding "Authentication Providers", and filling in the info on the Google+ tab.
