### ISSUE TITLE
Amplify Auth: using custom identity pool issues

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-android#894]
I have setup Auth in an Android app, using default configuration for username &
password sign-in. I then tick the box "Enable access to unauthenticated
identities" to allow guest users access to get credentials. Everything works.

If I create a new identity pool, using all the same settings as per the one
created by Amplify, and then replace the pool ID in the
`awsconfiguration.json` and `amplifyconfiguration.json` files with my new pool
ID, everything works.

However, if I run `amplify push --force`, the pool ID is replaced by the
original identity pool ID. 

Is it possible to use my custom identity pool, so that it is not overwritten by
the original? If so, how?

Also, what about using my custom user pool? If so, how?

Thanks.

**Comment by rjuliano** [comment]
Have you tried taking a look at [this recently released](https://docs.amplify.aws/cli/auth/import) CLI feature?

**Comment by kannieWeesNie** [comment]
thanks @rjuliano I will definitely look at it. Thanks for pointing it out to me!
