### ISSUE TITLE
Support for Scoped Storage

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-android#896]
When upgrading the Android Gradle Plugin to 4.1.0, the Android Lint now complains:
> /Users/jhwill/amplify-android/aws-storage-s3/src/main/AndroidManifest.xml:19: Error: WRITE_EXTERNAL_STORAGE no longer provides write access when targeting Android 11+, even when using requestLegacyExternalStorage [ScopedStorage]

To continue upgrading Amplify (and to properly support the latest versions of Android), we will need to add support for [Scoped Storage](https://developer.android.com/training/data-storage#scoped-storage):
> To give users more control over their files and to limit file clutter, apps that target Android 10 (API level 29) and higher are given scoped access into external storage, or scoped storage, by default. Such apps have access only to the app-specific directory on external storage, as well as specific types of media that the app has created.

**Comment by sdhuka** [comment]
@richardmcclellan Could we close this issue?

**Comment by richardmcclellan** [comment]
@sdhuka I've opened https://github.com/aws-amplify/amplify-android/pull/1377 which should resolve this issue.
