### ISSUE TITLE
List All Users From Congnito Using Amplify 

### ISSUE THREAD

**Issue by oras** [aws-amplify/amplify-android#898]
Hello,

I am using Android 9 / Pie. I tried to pull all users for the same IoT device from Cognito. Is there any way to do it using the Amplify Android library? Can I use the directive `@function`? What is the best approach?

Thanks

**Comment by oras** [comment]
Hi,

I build a sample  lambda function and pushed it to the server.

I added the function signature reference to the schema.graphql

```
type Query 
{
  echo(msg: String): String @function(name: "getUsers-${env}")
}
```

How can I call this function from android app using Amplify ?

**Comment by oras** [comment]
So as I understand the only option for now is using aws-appsync

**Comment by undefobj** [comment]
For listing all users in a Cognito User Pool we recommend using `listUsers` from the Admin Queries API: https://docs.amplify.aws/cli/auth/admin#admin-queries-api

You should then be able to call this using Android's REST client: https://docs.amplify.aws/lib/restapi/fetch/q/platform/android
