### ISSUE TITLE
Conflict Handler Always Coming Back

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#899]
The conflict resolver seems not to work with API. When the conflict resolver is enabled, it create an "AmplifyDataStore" table in Dynamo. 

However, when one removes the DataStore features, it doesn't permanently remove the entry in the `transform.conf.json`. Every time before I push I always have to remove:

```json
"ResolverConfig": {
    "project": {
        "ConflictHandler": "AUTOMERGE",
        "ConflictDetection": "VERSION"
    }
}
```

And then it reappears again and I don't know why. Would be good to permanently disable/enable conflict resolution as opposed to it having to do this every time.

**Comment by jamesonwilliams** [comment]
Hi @KayIlory, this looks like an issue with the Amplify CLI. The CLI configured the backend resources, and manages the `transform.conf.json` file that you mention. Can you please [create an issue there](https://github.com/aws-amplify/amplify-cli/issues/new)?

**Comment by KayIlory** [comment]
done @jamesonwilliams
