### ISSUE TITLE
Set custom prefix for Storage uploads, target root of the bucket instead-of folders namespaced by accessLevel?

### ISSUE THREAD

**Issue by naththeprince** [aws-amplify/amplify-android#910]
For all the uploads performed by the code below, my files are put in a `public/` folder. Are these prefixes hardcoded in the library based on access levels? If public is the default access level, is there any way I can set a custom prefix for these values, so that I can put my files in root of the bucket instead of `public/`?
 ```kotlin
Amplify.Storage.uploadFile(key, image, options,
    { progress -> uploadProgress(progress) },
    { result -> uploadSuccess(result)},
    { error -> uploadError(error) }
)
```

**Comment by richardmcclellan** [comment]
> Are these prefixes hardcoded in the library based on access levels?

Yes, these are currently hardcoded, and not configurable.  

Customizing these prefixes is [supported by amplify-js](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js#customize-object-key-path), so it is something we could consider adding for amplify-android as well.  

@naththeprince can you describe your use case a little further and explain why you'd like to remove the prefix?

**Comment by naththeprince** [comment]
Thanks for the info @richardissuperman 

Yes. The usecase is we have the web portal thats live and uploading the images to root of the folder, we have a rest API that sends the cloudfront url to the s3-key (like profile photo, thumbnails), the api is same for mobile and webportal. 

The webportal is live, now we are building mobile application on Flutter, we used native android/ios code earlier to upload to s3 using transferutility (cognito pool id) earlier, but the AWS docs seems to be suggesting us to use Amplify to upload to S3 even with the existing resources, so after integrating amplify and uploading images, our app was broken, the image urls doesn;t work on web/mobile app, so it took few hrs to find out that the reason is amplify adds a default prefix public/, I also found that amplify.js has customization way to do it. I even tried to add customPrefix to the amplifyconfiguration.json, then I checked the source code and found the public/ is hardcoded and can't be customised for android sdk as of now.

Thanks for confirming. Hope the usecase makesense. Let me know :) 

As of now, I have removed amplify integration and gone back to cognito+transferutility approach, to resolve our usecase issue.

**Comment by mordka** [comment]
Hi @richardmcclellan due to this limitation we have also reverted to transferutility. We have existing system, with no public uploads. We don't want to use your prefixes. Amplify library should be modular enough to fit any existing project without major architecture changes. 
On a side note, preceding the bucket key with a static string is affecting bucket read operations -https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html 
> [...] your application can achieve at least 3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per prefix in a bucket.

**Comment by SomnathS09** [comment]
> Thanks for the info @richardissuperman
> 
> Yes. The usecase is we have the web portal thats live and uploading the images to root of the folder, we have a rest API that sends the cloudfront url to the s3-key (like profile photo, thumbnails), the api is same for mobile and webportal.
> 
> The webportal is live, now we are building mobile application on Flutter, we used native android/ios code earlier to upload to s3 using transferutility (cognito pool id) earlier, but the AWS docs seems to be suggesting us to use Amplify to upload to S3 even with the existing resources, so after integrating amplify and uploading images, our app was broken, the image urls doesn;t work on web/mobile app, so it took few hrs to find out that the reason is amplify adds a default prefix public/, I also found that amplify.js has customization way to do it. I even tried to add customPrefix to the amplifyconfiguration.json, then I checked the source code and found the public/ is hardcoded and can't be customised for android sdk as of now.
> 
> Thanks for confirming. Hope the usecase makesense. Let me know :)
> 
> As of now, I have removed amplify integration and gone back to cognito+transferutility approach, to resolve our usecase issue.

How did you check that it was adding public/ prefix? (Sorry I'm new to this)

**Comment by hackrx** [comment]
any updates on this? I also want to upload images and files to specific bucket folders like `/profileImages` and `/classnotes`.

**Comment by cody1024d** [comment]
With this now being supported in IOS and JS, I think this is sorely lacking here in Android. Also, selfishly, because it prohibits the functionality from working correctly in Flutter as well (especially since the Flutter framework does not have access to the old TransferUtility classes).

**Comment by pcanas** [comment]
Since this feature is already implemented for other platforms, could you ship it in a future release for Android as well? It looks like many of us would appreciate such functionality.

**Comment by burak-pensa** [comment]
@richardmcclellan is there any progress on this issue?

**Comment by sktimalsina** [comment]
Hi, I agree that it is missing parity in Android. We are looking into porting this to Android as well. Although we don't have exact ETA, we will post updates here.
