### ISSUE TITLE
SQLiteLog:  (1) no such column: containedModelClassName

### ISSUE THREAD

**Issue by sunithapremjee** [aws-amplify/amplify-android#912]
**Issue Description**
I get this error:
> SQLiteLog: (1) No such column: containedModelClassName.

The `Amplify.DataStore.save(...)` function doesn't work and my application is not responding. 

`schema.graphql` has table name `Item` with columns `id`, `user`, `title`, `description` and `pdfdoc`. I haven't given any column name in the error log mentioned above. Stuck with this issue for long time.

**Environment Information**
*Amplify Plugins Information:*
AWSDataStorePlugin: 1.4.1
AWSApiPlugin: 1.4.1
AWSCognitoAuthPlugin: 1.4.1

**Device Information**
Device Manufacturer: Samsung
Device Model: SM-G975U
Android System Version: 10
SDK Version: 29
Device is an Emulator: No

**Comment by jamesonwilliams** [comment]
Please include your `schema.graphql` as well as the code you are using to invoke `.save(...)`. Is this a new problem with 1.4.1, or have you seen it before?

**Comment by jamesonwilliams** [comment]
Interesting, we haven't seen this one before. `containedModelClassName` is [a field in one of our internal system models, the `PendingMutation`](https://github.com/aws-amplify/amplify-android/blob/12ec8e9819228f63bd677a0431a5ab191f79d9e1/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/PendingMutation.java#L279). 

Please use the [Database Inspector](https://developer.android.com/studio/inspect/database) in Android Studio to inspect your `AmplifyDatabase.db`. Does it have a `PendingMutation` table? Does that table contain a column for `containedModelClassName`?

If not, please can you provide full logs of your DataStore startup, with [verbose logging enabled](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output)? I suspect the `PendingMutation` table is not being setup correctly. Please keep your eye out for that in the logs.
