### ISSUE TITLE
CLI Doesn't Fully Disable Conflict Handling When Updating API

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#916]
The conflict resolver seems not to work with API.

When the conflict resolver is enabled, it creates an `AmplifyDataStore` table in Dynamo.

However, when one removes the DataStore features, the below entry in the `transform.conf.json` is not permanently removed, too. Every time before I push, I always have to remove these lines:

```json
"ResolverConfig": {
    "project": {
        "ConflictHandler": "AUTOMERGE",
        "ConflictDetection": "VERSION"
    }
}
```

After pushing, these lines reappear again and I don't know why. It would be good to permanently disable/enable conflict resolution, as opposed to it having to do this every time.

**Comment by renebrandel** [comment]
@jpignata - this seems to be related to the Android Amplify Tools.

**Comment by jamesonwilliams** [comment]
@KayIlory -- did @nikhname's suggestion help?

**Comment by KayIlory** [comment]
@jamesonwilliams  yes I have been testing for a while now and can confirm the suggestion from @nikhname worked

**Comment by jamesonwilliams** [comment]
Awesome, glad to hear, @KayIlory. Thanks @nikhname!
