### ISSUE TITLE
How can I refresh id token manually?

### ISSUE THREAD

**Issue by AliakseiIvanou** [aws-amplify/amplify-android#919]
I want to update the user attribute and get a new token with updated params. I need it updated since our server takes some params from it.

How can I refresh the token so it will contain updated params? Also, I'm not sure should this token be refreshed automatically after parameter update?

Found similar issue in the AWS SDK: https://github.com/aws-amplify/aws-sdk-android/issues/696. It has a `SharedPreferences` workaround. Not sure if it will work with Amplify? What exact prefs do I need to clear? Thanks.

Amplify Auth version: 1.4.1

**Comment by TrekSoft** [comment]
Hey @AliakseiIvanou - currently the way to achieve this use case is to get an instance of the [AWSMobileClient escape hatch](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android) and call the `refresh()` method on it. The token cannot be refreshed automatically by us since we have no way of knowing when you update the params on the server side.

**Comment by baltekgajda** [comment]
I used the `refresh()` method and now i am getting "The security token included in the request is invalid" message with `AmazonServiceException`. It only happens when tokens have to be refreshed.

**Comment by edgar-zigis** [comment]
@TrekSoft your provided answer does not really work.
`(Amplify.Auth.getPlugin("awsCognitoAuthPlugin").escapeHatch as AWSMobileClient).refresh()`
returns same token values. I did try launching it on separate threads with delays, etc. I still get same results.

**Comment by TrekSoft** [comment]
Sorry guys, you're correct - that does not achieve what you're looking for and I see this is still a [pending feature request](https://github.com/aws-amplify/aws-sdk-android/issues/696) for AWSMobileClient which Amplify Auth is currently based on. You can add your +1s there as well to help get it prioritized and reopened this so others can add +1s to this.

**Comment by baltekgajda** [comment]
Meanwhile waiting for the official way to do this, is there a walkaround you are aware of? Cuz i have my app published and im struggling with this problem.

 I noticed that when 'Amplify' is initialized every time the app starts, it refreshes the tokens or does something that helps with the problem. So when it happen that tokens expire, relaunching the app fixes it, but this fix is far from ideal.

**Comment by TrekSoft** [comment]
Sorry no I'm not aware of a workaround other than signing out and back in which obviously probably doesn't work for your situation.

**Comment by edgar-zigis** [comment]
@baltekgajda there is a workaround, but it will require you using lambdas. We shoot a request to our lambda with active identity token and get a custom challenge answer and session in the response. 
Then we use `RespondToAuthChallengeRequest` from the `AWSMobileClient`, provide **session**, **challenge answer** there and call it on Cognito user. After that the next call to `Amplify.Auth.fetchAuthSession` will return new tokens.

**Comment by chinalwb** [comment]
How about using reflection?


```
//            AWSMobileClient.getInstance()
//                CognitoUserPool userpool
//                        getCurrentUser() returns CognitoUser
//                            refreshSession()
//
//                            --> com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser#refreshSession
//                            final CognitoUserSession cognitoUserSessionFromStore = readCachedTokens();
//                            cipSession = refreshSession(cognitoUserSessionFromStore);
//                            cacheTokens(cipSession);
```

**Comment by dobrowins** [comment]
To extend @chinalwb 's great answer, here's the code that works in 1.18.0:
```
val client = AWSMobileClient.getInstance()

val userPoolField: Field? = client::class.java.getDeclaredField("userpool")
userPoolField?.isAccessible = true
val userPool = userPoolField?.get(client) as? CognitoUserPool
val currentUser = userPool?.currentUser as CognitoUser

val readCachedTokensFun = CognitoUser::class.java.getDeclaredMethod("readCachedTokens")
readCachedTokensFun.isAccessible = true
val cachedSession = readCachedTokensFun.invoke(currentUser) as? CognitoUserSession

// async call! perform on background thread or exception would occur
val refreshSessionFun = CognitoUser::class.java.getDeclaredMethod("refreshSession", CognitoUserSession::class.java)
refreshSessionFun.isAccessible = true
val refreshedSession = refreshSessionFun.invoke(currentUser, cachedSession) as? CognitoUserSession

val cacheTokensFun = CognitoUser::class.java.getDeclaredMethod("cacheTokens", CognitoUserSession::class.java)
cacheTokensFun.isAccessible = true
cacheTokensFun.invoke(currentUser, refreshedSession)
```

But please for the sake of anything you cherish use it as last resort.

**Comment by div5yesh** [comment]
Please use this workaround: https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-1101894554 and let us know if it fits your use case.

**Comment by tjleing** [comment]
If the workaround does not work, please comment on this issue or open a new one.
