### ISSUE TITLE
Temporal 's java.time package usage causes NoClassDefFoundError in device below API 26.

### ISSUE THREAD

**Issue by richardissuperman** [aws-amplify/amplify-android#922]
We are trying to use Gson to serialise/deserialise Amplify generated model classes. However, when converting ```Temporal```, the app crash due to NoClassDefFound error for device below API 26:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneOffset;

        at com.amplifyframework.core.model.temporal.Temporal$DateTime.<init>(Temporal.java:211) 

```

It looks like this package only added to api 26 and above: https://developer.android.com/reference/java/time/package-summary

**Comment by richardmcclellan** [comment]
Hi @richardissuperman,by default, `java.time` is only supported in API 26 and above, but the Gradle Plugin 4.0.0 [backports the functionality to all API versions](https://developer.android.com/studio/write/java8-support#library-desugaring) by "desugaring" these APIs.

As described in the [Amplify Android Project Setup docs](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android#n2-install-amplify-libraries), make sure your app's build.gradle has desugaring enabled like this:

```
android {
    compileOptions {
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.10'
```

**Comment by richardissuperman** [comment]
thanks ! let me close this ticket !
