### ISSUE TITLE
DynamoDB Error: "Item size has exceeded the maximum allowed size"

### ISSUE THREAD

**Issue by Darthlatte** [aws-amplify/amplify-android#925]
Hi, I have an Android app which logs user data while the app is closed, using a foreground service.

I have it setup such that data is saved every X minutes using a timer and it works fine running for some time (couple of hours).

At some point I can see the new items are no longer pushed to DynamoDB, although I get a successful response from `Amplify.DataStore.save(...)`. I also noticed that at some point the "CreatedAt" timestamp starts to shift a couple of minutes for a new item.

Could this be because the local datastore get filled with data too fast, or maybe some timeout occurs?

I'm using the Amplify Stack for Android.

Please see snippet below for my implementation:

`foregroundService.java`:

```java
Amplify.DataStore.save(input, success -> {
    Log.d("Datastore", "Auto saved item: " + success.item().getId());
}, error -> {
    Log.e("Datastore", "Could not auto save item to datastore", error);
});
```

Thanks!

**Comment by jamesonwilliams** [comment]
Hi @Darthlatte, I like your user photo!

Your `save` call looks straight-forward and correct. I suggest to dig into your device's logs. You can [enable verbose logging in Amplify](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output) by following these instructions.

Please capture logs from around the time the synchronization stops, and share them here.

**Comment by Darthlatte** [comment]
Hi

I think I may have found the issue. 

I'm getting the output below. Seems like I have to limit my data chunks :-) I'll just run some more tests and report back. Thank you.

```
AppSync response contained errors = [GraphQLResponse.Error{message='Item size has exceeded the maximum allowed size (Service: DynamoDb, Status Code: 400, Request ID: SJGA6AJC2UU83U7SQM72JNLIH3VV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='createMyData'}]', extensions='{errorInfo=null, data=null, errorType=DynamoDB:DynamoDbException}'}], cause=null, recoverySuggestion=Verify that your AppSync endpoint is able to store createMyData models.}
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$null$12(MutationProcessor.java:261)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$-YifFJT2h6JRCO36L1QFfIa_E9w.accept(Unknown Source:8)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$4(AppSyncClient.java:317)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$lyeKjjQ4RZeJfT0qjSuLSlLLr_s.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
```
