### ISSUE TITLE
Google Hosted UI Login Fails with GraphQL Owner privileges

### ISSUE THREAD

**Issue by KayIlory** [aws-amplify/amplify-android#928]
![image](https://user-images.githubusercontent.com/51476926/97116202-96ee5d80-16f3-11eb-8b81-81bdecf1a48b.png)

Hi, when users login with federated google hosted UI, there is an issue where the user cannot interact with a table having owner privileges. 

I have:
```graphql
type User @model(timestamps:{createdAt: "createdOn", updatedAt: "updatedOn"})
@auth(rules: [
    {allow: owner,  operations: [create, read, update, delete]},
```

If the user signs in with Google auth, then they are not assigned owner entitlements. This seems to have occurred lately with the new Amplify release.

**Comment by TrekSoft** [comment]
Thanks for the good details on this @KayIlory  - a bunch of improvements have been made around this area in the past couple months. Would you mind trying this again with the latest version of Amplify and seeing if this issue has been addressed in it?
