### ISSUE TITLE
Amplify Api category added automatically - why?

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-android#929]
I have just built a new Android app. I ran `amplify init` and noticed that `amplifyconfiguration.json` file was updated to this:

```json
"api": {
    "plugins": {
        "awsAPIPlugin": {
            "amplifyDatasource": {
                "endpointType": "GraphQL",
                "endpoint": "https://xxxxxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
                "region": "eu-west-2",
                "authorizationType": "API_KEY",
                "apiKey": "xxxxxxx"
            }
        }
    }
}
```

Then when I run `amplify add auth`, I see this:

| Category | Resource name          | Operation | Provider plugin   |
| -------- | ---------------------- | --------- | ----------------- |
| Api      | amplifyDatasource      | Create    | awscloudformation |
| Auth     | amplifystarter75e86d9b | Create    | awscloudformation |

No where did I request to add an API. Why is this happening?

**Comment by jpignata** [comment]
Heya @kannieWeesNie -- did you perhaps run through the tutorial? `amplifyDatasource` is created by Amplify Tools automatically in this flow. If you do not want that API, you should initialize with only `amplify init`. Moving to a discussion to continue the conversation.
