### ISSUE TITLE
Access Token Doesn't Recognize by API Gateway Cognito User Pool Authorizer

### ISSUE THREAD

**Issue by oras** [aws-amplify/amplify-android#934]
Hi,

I can't use the resource using the Cognito User Pool Authorizer.
When I Copy the Access Token from my app using the AWSCognitoAuthSession.
To the Authorizer test it's response with "Unauthorized request..."

Also tried to use the following article with the same results:
https://aws.amazon.com/premiumsupport/knowledge-center/cognito-custom-scopes-api-gateway

Also tried to use postman with the following explanation include AWS Signature header: https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html 

Also with Curl 

```Batch
Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.


X:\>curl https://h1z7c2zen5.execute-api.eu-central-1.amazonaws.com/dev/items/ -H "Authorization: eyJraWQiOiJtamYxMnlKbFpxb053ZTlaZ2VFbnRBcFpJMVhtN1NrdzRsK0c3YVhwU0VjPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI1OTdlZ.......................... and so on ............"
{"message":"Unauthorized"}

```

**Comment by jamesonwilliams** [comment]
Hi @oras. Is this a question about the Amplify Android library? If so, please give us some details about how you are using that software.

**Comment by oras** [comment]
Hi @jamesonwilliams,

As I told you last time I succedd to use lambda function in order to fetch the users list from Cognito server.

Unfortunately I realized that it's not including token session. It's only work with open token  without security.

**Comment by oras** [comment]
What you are doing ?

**Comment by KannadukiAoi** [comment]
Any news so far? I just met same probelm now. Don't know how to make the access toekn extracted form Amplify to access my REST API. I set the Authorization of api call to Cognito pool and extract the access toekn from Amplify on mobile app but always got Unauthorize message back. I also try use the HostUI in Cognito to generate the access key and the key is correctly work. So I don't know why the access token from Amplify cannot pass the authorization.

By the wya, if I switch the Authorization from Cognito user pool to AWS IAM, then I can use the AccesKey and SecurityKey form Amplify to acces that api now. But still wonder to know how to generate a vaild access token on mobile app.

**Comment by NicolasPrr** [comment]
@KannadukiAoi  did u solved?
