### ISSUE TITLE
Amplify.signInWithWebUI not prompting login page for new user after calling Amplify.signOut

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-android#960]
This issue seems to be the same as #634

I call `Amplify.Auth.signInWithWebUI()` and Web Ui login form shows. I login successfully (either as Google user or Cognito user) and then log out using `Amplify.Auth.signOut()` (both for single device or globally). If I login again, no Web Ui login form is displayed and I am automatically logged in (as the previously logged in user). 

Tried again after about two hours then the Web Ui form displayed so it seems that there is a valid session (lurking somewhere). Is this the correct flow? If not, then how does one get the Web Ui login form to show after logging out if wanting to login in again as a different user?

My dependencies are: 
`implementation 'com.amplifyframework:aws-auth-cognito:1.4.1' and 
implementation 'com.amplifyframework:core:1.4.1' `

Appreciate some help here.

Thanks

**Comment by TrekSoft** [comment]
Can you post the code you are using for signOut? Are you passing in an options object? When signing in with web UI you should just be calling the default signOut method without passing in any options object. This is what leads to [calling the underlying AWSMobileClient instance](https://github.com/aws-amplify/amplify-android/blob/main/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java#L967) with invalidateTokens set to true which is needed to fully sign out of a Web UI type sign in.

**Comment by kannieWeesNie** [comment]
hi @TrekSoft thanks for your response. Unfortunately I have deleted the app and move on. I have the code on file and will rebuild the app when I have time to see what I actually did and get back with my findings. Thanks again for your assistance.
