### ISSUE TITLE
Tokens not refreshing

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-android#964]
See https://github.com/aws-amplify/aws-sdk-android/issues/2235.

Not sure which one this would belong to.

**Comment by jamesonwilliams** [comment]
Since https://github.com/aws-amplify/aws-sdk-android/issues/2235 deals with the Amplify library, I'll move that here, and close this current https://github.com/aws-amplify/amplify-android/issues/964 as a duplicate.
