### ISSUE TITLE
Amplify inaccessible after app sleeps in background.

### ISSUE THREAD

**Issue by naman23awasthi** [aws-amplify/amplify-android#973]
> The version of the Framework you are using: 

```gradle
com.amplifyframework:core:1.4.1
com.amplifyframework:aws-auth-cognito:1.4.1
com.amplifyframework:aws-api:1.4.1
```

> Details and configurations for any backend resources that are relevant: 

I use Auth and API. Add it in my MainActivity using

```kotlin
val config = AmplifyConfiguration.builder(applicationContext)
    .devMenuEnabled(false)
    .build()
Amplify.addPlugin(AWSApiPlugin())
Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.configure(config, applicationContext) 
```

Amplify API uses GraphQL endpoint. In the code, BroadcastReceiver calls mutate approximately every minute to send data to the dynamoDB. There is one table called "todo" in our DB where data is stored. The schema is of the type

```graphql
type Todo @model @auth(rules: [{ allow: owner }]){
	"""Some id variable for unique ID"""
        username: String!
	accelerationX: Float!
	accelerationY: Float!
        accelerationZ: Float!
}
```

When the app is in the background for longer than 20 minutes, the app goes to sleep. (BroadcastReceiver is still alive.) But, as the app is asleep, Amplify auth and API are no longer available which implies the BroadcastReceiver cannot access the API.mutate function and gives an error:

> {message=Could not retrieve the response body from the returned JSON, cause=java.io.IOException: Failed to retrieve Cognito User Pools token., recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}

I expected the data to be sent to the database even when the app is in the background. The app stops sending data to dynamoDB in around 20 minutes of inactivity

**Comment by richardmcclellan** [comment]
Hi @naman23awasthi,  it looks like this is the main issue:

```
Failed to retrieve Cognito User Pools token.
```

This could occur if you try to make an API call while signed out.  Is it possible you are signing out when your app is closed?  If you could share your code related to when you sign in, sign out and make the API call, that might help to debug further.

**Comment by naman23awasthi** [comment]
Hi @richardmcclellan , we only call Amplify.Auth.signOut() in the onClick method of the signout button in our UI. 

```
binding.signout.setOnClickListener{
            locationUpdateViewModel.stopLocationUpdates()
            try{
                Amplify.Auth.signOut(
                    {
                        var i = Intent(activity?.applicationContext, Login::class.java)
                        startActivityForResult(i,MainActivity.LOGINACTIVITY)
                    },
                    { error -> Log.e("AuthQuickstart", error.toString()) }
                )
            }
            catch (E: Exception){

            }
        }
```

**Comment by raphkim** [comment]
https://www.androidpolice.com/2020/05/30/how-to-prevent-apps-sleeping-in-the-background-on-android/
It seems that your mobile device is putting the app to sleep, which prevents your Auth category from retrieving your User Pools token. Please try disallowing app optimization to prevent this from happening.
