### ISSUE TITLE
Is there any documentation on how to use amplify without CLI?

### ISSUE THREAD

**Issue by AlexandrSalin** [aws-amplify/amplify-android#983]
Is there any documentation on how to use Amplify without the CLI?

Actually, I do no need to use CLI. All our services like buckets, identity
pools, storages, are already set up by DevOps and backend side.  All I need is
to be able to configure Amplify correctly on the Android side. But
documentation on how I can to do this is almost nonexistent.  Could you please
point where I can get enough description of how to setup all features over JSON
config? I think it's some thing like this:

```kotlin
val cfg = AmplifyConfiguration.builder(JSONObject(config))
    .devMenuEnabled(false)
    .build()

Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.addPlugin(AWSS3StoragePlugin())
Amplify.configure(cfg, context)
```

Where config is:
```json
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "us-east-1:bla_bla_bla",
              "Region": "us-east-1"
            }
          }
        }
      }
    }
  },
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket" : "arn:aws:s3:::bla_bla_bla",
        "region" : "us-east-1"
      }
    }
  }
}
```

and so on

**Comment by jamesonwilliams** [comment]
Hi @AlexandrSalin, please see the section on [using existing AWS resources](https://docs.amplify.aws/lib/storage/existing-resources/q/platform/android) in the Amplify Storage documentation.

As to your other question:
> Why does Amplify Android not provide the ability to change `access_level` name?

Please follow https://github.com/aws-amplify/amplify-android/issues/910.
