### ISSUE TITLE
Disable synchronization to specific models with selective sync

### ISSUE THREAD

**Issue by upachecog** [aws-amplify/amplify-android#987]
Hi @richardmcclellan as we discussed in #944 in this [comment](https://github.com/aws-amplify/amplify-android/issues/944#issuecomment-731855877) 

It would be useful for me to disable synchronization to specific models in my GraphQL schema because there are some use cases in which the user is just allowed to create data, so queries and subscriptions are not required.

Your suggestion was to do something like this:

```
.syncExpression(Location::class.java) { QueryPredicates.NONE }
```

**Comment by PS-MS** [comment]
Is there any update on this issue? I have just tried with the latest (amplify-android 1.26.0 and amplify-kotlin 0.10.0) but run into the logs mentioned in PR #1126

`Caused by: DataStoreException{message=Tried to parse an unsupported QueryPredicate, cause=null, recoverySuggestion=Try changing to one of the supported values: QueryPredicateOperation, QueryPredicateGroup.}
        at com.amplifyframework.datastore.appsync.AppSyncRequestFactory.parsePredicate(AppSyncRequestFactory.java:199)
        at com.amplifyframework.datastore.appsync.AppSyncRequestFactory.buildSyncRequest(AppSyncRequestFactory.java:110)
        	... 16 more`

**Comment by raphkim** [comment]
Hey @PS-MS @upachecog , 

This use-case is already supported via following sync expression:

```
.syncExpression(Location::class.java) { QueryPredicates.none() }
```

Please let me know if this is not working for your use-case.

**Comment by PS-MS** [comment]
Hi @raphkim ,

I no longer need this but tried just in case and still have the same DataStoreException as above
```
W/amplify:aws-datastore: Initial cloud sync failed.
    DataStoreException{message=Failed to get fields for model., cause=DataStoreException{message=Tried to parse an unsupported QueryPredicate, cause=null, recoverySuggestion=Try changing to one of the supported values: QueryPredicateOperation, QueryPredicateGroup.}, recoverySuggestion=Validate your model file.}
```
        
This is when using
`.syncExpression(Answer::class.java) { QueryPredicates.none() }`

**Comment by eeatonaws** [comment]
Hi @PS-MS, thank you for trying that sync expression and reporting the error you observed. We are looking into the cause of the error.

**Comment by raphkim** [comment]
Thank you for pointing that out! I have opened a PR to address this issue.

**Comment by eeatonaws** [comment]
The PR to fix this issue was included in the latest release, [Amplify Android 1.28.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.28.0).
