### ISSUE TITLE
[Flutter support] Remote delete mutations are not getting saved locally

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-android#994]
In a flutter app using `SerializedModel`. when a delete mutation is received by the app running in android, it is not currently saved/merged in the local store. No error/exceptions are observed when this happens. 

To reproduce this:

* Run a flutter app, or an android app with serialized models.
* Create a delete mutation outside of the android app.
* Observe that the delete mutation is not persisted in local storage and consequently no event is received through `observe()`

It looks like the issue could be with how library queries (See line 178 below) for an incoming delete mutation with the class SerializedModel rather with the actual String modelName. this results in onNotPresent to be called and so the library [doesn’t delete ](https://github.com/aws-amplify/amplify-android/blob/9db52862c3c7174877ce7247624999e67cb32a47/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java#L135-L146) anything from the localStorage

https://github.com/aws-amplify/amplify-android/blob/9db52862c3c7174877ce7247624999e67cb32a47/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Merger.java#L176-L185

**Comment by jamesonwilliams** [comment]
Thanks for doing the research, here, @Amplifiyer. It made it fast for me to resolve the issue.

https://github.com/aws-amplify/amplify-android/pull/1004
