### ISSUE TITLE
Class Cast Exception when Saving Enum

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-android#999]
As discussed before, we pass Enums as strings to the Amplify Android save method. 

targetType = String
javaClass = String::class.java

However when trying to save enums we get a class cast exception saying that strings cannot be cast to Java.enum type.  Since we pass targetType and javaClass as a string, we believe there is a glitch where the Android code is still trying to cast to an enum because the ModelField's isEnum boolean is true.

**Comment by jamesonwilliams** [comment]
Hi @fjnoyp, can you please include the data and schema you are using (in Kotlin), and the call you make to the Android library? I assume that this is a `ModelField` instance with these values?

| isEnum | targetType | javaClassForValue |
|-----------|----------|-----------------|
| true | `"String"` | `String::class.java` |

Can you include the tested data, schema, logs, and a full stack trace?

**Comment by fjnoyp** [comment]
Here's the schema: 
```

enum TestEnum { 
  yes,
  no,
  maybe
}

type AllTypeModel @model { 
  id: ID!
  stringType: String!
  intType: Int!
  floatType: Float!
  boolType: Boolean!
  dateType: AWSDate!
  dateTimeType: AWSDateTime!
  timeType: AWSTime!
  timestampType: AWSTimestamp!
  enumType: TestEnum 
}
```

**Comment by fjnoyp** [comment]
Here's the code in Android we make: 

```
  @VisibleForTesting
    fun onSave(flutterResult: Result, request: Map<String, Any>) {
        val modelName: String
        val serializedModelData:  Map<String, Any>

        try {
            modelName = request["modelName"] as String
            serializedModelData = deserializeNestedModels(request["serializedModel"].safeCastToMap()!!)
        } catch (e: Exception) {
            postFlutterError(
                    flutterResult,
                    FlutterDataStoreFailureMessage.AMPLIFY_REQUEST_MALFORMED.toString(),
                    createErrorMap(e))
            return
        }

        val plugin = Amplify.DataStore.getPlugin("awsDataStorePlugin") as AWSDataStorePlugin
        val schema = modelProvider.modelSchemas()[modelName];

        val serializedModel = SerializedModel.builder()
                .serializedData(serializedModelData)
                .modelSchema(schema)
                .build()

        val predicate = QueryPredicateBuilder.fromSerializedMap(
                request["queryPredicate"].safeCastToMap()) ?: QueryPredicates.all()

        plugin.save(
                serializedModel,
                predicate,
                Consumer{
                    LOG.info("Saved item: " + it.item().toString())
                    handler.post { flutterResult.success(null) }
                },
                Consumer {
                    LOG.error("Save operation failed", it)
                    postFlutterError(
                            flutterResult,
                            FlutterDataStoreFailureMessage.AMPLIFY_DATASTORE_SAVE_FAILED.toString(),
                            createErrorMap(it))
                }
        )
    }
```

**Comment by fjnoyp** [comment]
Yes it is a modelschema with those values that you listed above @jamesonwilliams

**Comment by fjnoyp** [comment]
Here's a full stack trace: 

`Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for sdk gphone x86 arm to report its views...
Debug service listening on ws://127.0.0.1:52849/EjrTcXO6eVE=/ws
Syncing files to device sdk gphone x86 arm...
I/flutter ( 6137):  DateTime: 2020-11-25T09:48:42-08:00
I/flutter ( 6137):  Date: 2020-11-25
I/flutter ( 6137):  Time: 09:48:42-08:00
I/amplify:aws-datastore( 6137): DataStore orchestrator transitioning states. Current mode = STOPPED, target mode = LOCAL_ONLY.
I/amplify:aws-datastore( 6137): Starting to observe local storage changes.
I/amplify:aws-datastore( 6137): Now observing local storage. Local changes will be enqueued to mutation outbox.
I/amplify:flutter:datastore( 6137): Established a new stream form flutter com.amplifyframework.datastore.storage.sqlite.-$$Lambda$0NKeZW6Mwf4F83r11OGUIWtYc5c@95eaab4
I/amplify:aws-datastore( 6137): Starting the orchestrator.
I/amplify:aws-datastore( 6137): Orchestrator completed a transition
E/amplify:flutter:datastore( 6137): Received an error
E/amplify:flutter:datastore( 6137): DataStoreException{message=Error in saving the model: AllTypeModel[id=a1743a53-f422-4b66-8eb3-007f6bbafd79], cause=java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum, recoverySuggestion=See attached exception for details.}
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
E/amplify:flutter:datastore( 6137): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:flutter:datastore( 6137): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:datastore( 6137): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore( 6137): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore( 6137): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:datastore( 6137): Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:103)
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
E/amplify:flutter:datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
E/amplify:flutter:datastore( 6137): 	... 6 more
W/amplify:aws-datastore( 6137): Storage adapter subscription ended in error
W/amplify:aws-datastore( 6137): DataStoreException{message=Error in saving the model: AllTypeModel[id=a1743a53-f422-4b66-8eb3-007f6bbafd79], cause=java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum, recoverySuggestion=See attached exception for details.}
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
W/amplify:aws-datastore( 6137): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/amplify:aws-datastore( 6137): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/amplify:aws-datastore( 6137): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore( 6137): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore( 6137): 	at java.lang.Thread.run(Thread.java:923)
W/amplify:aws-datastore( 6137): Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:103)
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
W/amplify:aws-datastore( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
W/amplify:aws-datastore( 6137): 	... 6 more
W/System.err( 6137): io.reactivex.rxjava3.exceptions.CompositeException: 2 exceptions occurred. 
W/System.err( 6137): 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
W/System.err( 6137): 	at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onError(PublishSubject.java:318)
W/System.err( 6137): 	at io.reactivex.rxjava3.subjects.PublishSubject.onError(PublishSubject.java:241)
W/System.err( 6137): 	at io.reactivex.rxjava3.subjects.SerializedSubject.onError(SerializedSubject.java:137)
W/System.err( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:323)
W/System.err( 6137): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
W/System.err( 6137): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err( 6137): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 6137): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 6137): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 6137): 	at java.lang.Thread.run(Thread.java:923)
W/System.err( 6137):   ComposedException 1 :
W/System.err( 6137): 	DataStoreException{message=Error in saving the model: AllTypeModel[id=a1743a53-f422-4b66-8eb3-007f6bbafd79], cause=java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum, recoverySuggestion=See attached exception for details.}
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
W/System.err( 6137): 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err( 6137): 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 6137): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 6137): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 6137): 		at java.lang.Thread.run(Thread.java:923)
W/System.err( 6137): 	Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:103)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
W/System.err( 6137): 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err( 6137): 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 6137): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 6137): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 6137): 		at java.lang.Thread.run(Thread.java:923)
W/System.err( 6137):   ComposedException 2 :
W/System.err( 6137): 	java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-7-thread-1
W/System.err( 6137): 		at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
W/System.err( 6137): 		at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
W/System.err( 6137): 		at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
W/System.err( 6137): 		at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:363)
W/System.err( 6137): 		at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:168)
W/System.err( 6137): 		at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.error(EventChannel.java:230)
W/System.err( 6137): 		at com.amazonaws.amplify.amplify_datastore.DataStoreObserveEventStreamHandler.error(DataStoreObserveEventStreamHandler.kt:39)
W/System.err( 6137): 		at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin$onSetupObserve$3.accept(AmplifyDataStorePlugin.kt:325)
W/System.err( 6137): 		at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin$onSetupObserve$3.accept(AmplifyDataStorePlugin.kt:48)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$observe$7(SQLiteStorageAdapter.java:562)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$QGNTOtWInIQ3mrbv5cf-iz0Xmow.accept(Unknown Source:4)
W/System.err( 6137): 		at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
W/System.err( 6137): 		at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onError(PublishSubject.java:318)
W/System.err( 6137): 		at io.reactivex.rxjava3.subjects.PublishSubject.onError(PublishSubject.java:241)
W/System.err( 6137): 		at io.reactivex.rxjava3.subjects.SerializedSubject.onError(SerializedSubject.java:137)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:323)
W/System.err( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
W/System.err( 6137): 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err( 6137): 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 6137): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 6137): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 6137): 		at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6137): FATAL EXCEPTION: pool-7-thread-1
E/AndroidRuntime( 6137): Process: com.amazonaws.amplify.amplify_datastore_example, PID: 6137
E/AndroidRuntime( 6137): io.reactivex.rxjava3.exceptions.CompositeException: 2 exceptions occurred. 
E/AndroidRuntime( 6137): 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
E/AndroidRuntime( 6137): 	at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onError(PublishSubject.java:318)
E/AndroidRuntime( 6137): 	at io.reactivex.rxjava3.subjects.PublishSubject.onError(PublishSubject.java:241)
E/AndroidRuntime( 6137): 	at io.reactivex.rxjava3.subjects.SerializedSubject.onError(SerializedSubject.java:137)
E/AndroidRuntime( 6137): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:323)
E/AndroidRuntime( 6137): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
E/AndroidRuntime( 6137): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime( 6137): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 6137): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6137): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6137): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6137):   ComposedException 1 :
E/AndroidRuntime( 6137): 	DataStoreException{message=Error in saving the model: AllTypeModel[id=a1743a53-f422-4b66-8eb3-007f6bbafd79], cause=java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum, recoverySuggestion=See attached exception for details.}
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
E/AndroidRuntime( 6137): 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime( 6137): 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 6137): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6137): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6137): 		at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6137): 	Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:103)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
E/AndroidRuntime( 6137): 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime( 6137): 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 6137): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6137): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6137): 		at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6137):   ComposedException 2 :
E/AndroidRuntime( 6137): 	java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-7-thread-1
E/AndroidRuntime( 6137): 		at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
E/AndroidRuntime( 6137): 		at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
E/AndroidRuntime( 6137): 		at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime( 6137): 		at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:363)
E/AndroidRuntime( 6137): 		at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:168)
E/AndroidRuntime( 6137): 		at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.error(EventChannel.java:230)
E/AndroidRuntime( 6137): 		at com.amazonaws.amplify.amplify_datastore.DataStoreObserveEventStreamHandler.error(DataStoreObserveEventStreamHandler.kt:39)
E/AndroidRuntime( 6137): 		at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin$onSetupObserve$3.accept(AmplifyDataStorePlugin.kt:325)
E/AndroidRuntime( 6137): 		at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin$onSetupObserve$3.accept(AmplifyDataStorePlugin.kt:48)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$observe$7(SQLiteStorageAdapter.java:562)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$QGNTOtWInIQ3mrbv5cf-iz0Xmow.accept(Unknown Source:4)
E/AndroidRuntime( 6137): 		at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
E/AndroidRuntime( 6137): 		at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onError(PublishSubject.java:318)
E/AndroidRuntime( 6137): 		at io.reactivex.rxjava3.subjects.PublishSubject.onError(PublishSubject.java:241)
E/AndroidRuntime( 6137): 		at io.reactivex.rxjava3.subjects.SerializedSubject.onError(SerializedSubject.java:137)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:323)
E/AndroidRuntime( 6137): 		at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
E/AndroidRuntime( 6137): 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime( 6137): 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 6137): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6137): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6137): 		at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6137): 
I/Process ( 6137): Sending signal. PID: 6137 SIG: 9
Lost connection to device.`

**Comment by jamesonwilliams** [comment]
@fjnoyp Can you try setting the `isEnum` to `false` in the Kotlin `ModelSchema` that you provide us? (It's an enum to Flutter, but not to our system.)

**Comment by fjnoyp** [comment]
Setting isEnum to false appears to have fixed the issue
